### ISSUE TITLE
Implement gramatically gendered versions of certain strings for female characters

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1000]
Most notably for `{playername} was defeated...` and `{playername} fled...` but I imagine there are other cases where the verb form depends on the noun gender.

Would also need to implement a way of denoting character gender in `characters.csv`.

**Comment by ncrecc** [comment]
What about characters like Jester and Robot with no gender?

**Comment by onetruepurple** [comment]
The Jester is male, the Robot's gender will depend on what the noun's gender is in each language.

**Comment by onetruepurple** [comment]
This is needed for a number of WIP translations to be gramatically correct.

**Comment by TerryCavanagh** [comment]
Uff, yes, several localisers have brought this up as a problem now. Will see what I can do before Switch.

**Comment by TerryCavanagh** [comment]
No longer planning to fix this - most of the translations have been delivered and the issue has been worked around as well as possible for those cases. It's something to learn from and do better about for the next game, at this point.
