### ISSUE TITLE
Infinite witch rat combo

### ISSUE THREAD

**Issue by woctezuma** [TerryCavanagh/diceydungeons.com#1001]
> Basically I found that while playing the Witch if you have the "Rat" ability (+1 poison, split the die) allocated to your n°1 spell slot and you put it into an upgraded spell slot you can just sit there turning one 1 die into two 1 dice which then make a new Rat to continue for infinite damage.

Referenc:e https://steamcommunity.com/app/861540/discussions/0/1651043320643514718/

**Comment by TerryCavanagh** [comment]
Fixed!
