### ISSUE TITLE
Upgrading a Flamethrower Upgraded both in inventory.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#1004]
Inevitability of Rust. Had 2 Flamethrowers equipped on Floor 5. Upgraded one of them and both got upgraded.

Flamethrower count also never went down on use, either.

**Comment by lcenine** [comment]
https://www.reddit.com/r/DiceyDungeons/comments/cupe7o/bug_upgrading_one_flamethrower_upgraded_both/

**Comment by TerryCavanagh** [comment]
Fixed in v2.1.
