### ISSUE TITLE
On game continue Bear reverted to Thief.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#1009]
![BearThief](https://user-images.githubusercontent.com/40739964/58262817-f69b4900-7d48-11e9-80a7-6d84e0605ab3.jpg)

Not sure if the Thief was defeated before I quit the game. It ended up with the Thief being equipped with Bear Maul and Bear Charge and a Spatula.

**Comment by mrcdk** [comment]
This should be fixed
