### ISSUE TITLE
elongated FURY? bar

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#1010]
Warrior Elimination Round. I saved my game, quit, continued, declined a deal, changed equipment, declined the same deal again, went downstairs, fought Snowman, and got this long FURY?.
<img width="960" alt="Screenshot 2019-05-23 19 06 01" src="https://user-images.githubusercontent.com/38589027/58297879-44867000-7d8e-11e9-965a-6e9aa1104036.png">

**Comment by pace212** [comment]
It went back to normal after that fight.

**Comment by lcenine** [comment]
Also seen it several times. I have only encountered it on a continued save game.

**Comment by TerryCavanagh** [comment]
Thanks! Looks like this one is due to a missing variable for fury in the save files!
