### ISSUE TITLE
Fighting Warlock as Warrior causes a crash with no error log

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1013]
![](https://i.frogbox.es/lpt)

**Comment by TerryCavanagh** [comment]
Ahh! Continue functionality is really good for reproducing bugs :D

Do you maybe still have this continue file?

**Comment by ncrecc** [comment]
I'm not sure where the continue file would be found!

**Comment by ncrecc** [comment]
Oh, here it is: https://i.frogbox.es/lpw

**Comment by TerryCavanagh** [comment]
Thanks!

**Comment by TerryCavanagh** [comment]
Fixed.
