### ISSUE TITLE
Upgraded form of Grappling Hook? is called "Grappling Hook? Upgraded+"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1014]

**Comment by TerryCavanagh** [comment]
This one is surprisingly tricky - it's to do with the confusing seperation of `displayname`, `rawname`, `name` and `namemodifier` mess in equipment right now. Kludged in a temporary fix for now, but I think it's gonna cause more problems later, so leaving this open.

![image](https://user-images.githubusercontent.com/2874150/58585284-31711580-8250-11e9-9d9c-a9e1e0b9d976.png)

**Comment by TerryCavanagh** [comment]
This one is properly fixed now, thankfully.
