### ISSUE TITLE
Confuse applies outside of battle

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1016]
![image](https://user-images.githubusercontent.com/2874150/58356018-095b6e00-7e6e-11e9-90df-b49c732ad8f6.png)

![image](https://user-images.githubusercontent.com/2874150/58356033-0e202200-7e6e-11e9-9c53-d37c8c04e2f1.png)

(editor specific, I think)

**Comment by findersjeepers** [comment]
This is not specific to the editor. Rather, if you leave a battle while you are affected by Confusion, whether by using the editor flee or by quitting to title, your items will continue to show as confused until the next time that you have a battle turn wherein you are _not_ Confused.

**Comment by TerryCavanagh** [comment]
This one was fixed last year!
