### ISSUE TITLE
Enemy moves button isn't working on Super Enemies

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1017]
On encounters with Super Enemies, the enemy moves button doesn't do anything.

**Comment by TerryCavanagh** [comment]
Ah! This one is tricky. Not gonna fix it for v0.17.2, but leaving notes for later:

The problem is `Combat.canpreviewmoves()`, which just returns `return !Actuate.isActive();`. This fails on Super Enemies, I assume because we're using Actuate to control the Super Enemy glow effect.

**Comment by mrcdk** [comment]
This should be fixed.
