### ISSUE TITLE
Continuing a game forgets which gadget you have when playing as inventor

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1027]
![image](https://user-images.githubusercontent.com/2874150/58357241-f21e7f80-7e71-11e9-84f3-df5da997057e.png)

(Worth checking a related issue: does continue remember the rust values in the inventor inevitability of Rust episode?)

**Comment by ncrecc** [comment]
Rust values are preserved, except on the forgotten gadget.

**Comment by mrcdk** [comment]
This should be fixed
