### ISSUE TITLE
Change the audience laugh to a gasp

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1033]
It's too much right off the bat. Keep the laugh effect for later in the game.

**Comment by ncrecc** [comment]
"Later in the game"? Does that refer to launch-exclusive stuff?

**Comment by TerryCavanagh** [comment]
Maybe! I'm thinking this make more sense for the final Lady Luck encounter, but possibly even just boss battles.

**Comment by TerryCavanagh** [comment]
Fixed.
