### ISSUE TITLE
Changing mods should probably invalidate saves

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1035]
![image](https://user-images.githubusercontent.com/2874150/58357558-2f374180-7e73-11e9-8f2d-434289d6bfb0.png)

**Comment by mrcdk** [comment]
The game already checks the mod list and each mod version but if a mod changes without updating the mod version it may break. I'm not sure if we can fix this.

**Comment by TerryCavanagh** [comment]
Oh - so this one is sort of fixed now - the game is pretty good about preserving the current floor when you load a game even if the current generator has been changed (thanks to a mod or version change). So, probably the game *shouldn't* be invalidating continue saves. Closing.
