### ISSUE TITLE
Silent crash - Windows 10 - Dicey v0.17

### ISSUE THREAD

**Issue by JakeH** [TerryCavanagh/diceydungeons.com#1038]
**What happens:**
When entering a battle, the game silently crashes at the end of the FIGHT intro animation.

No error dialog message appears. 

**PC:**
OS: Windows 10 Home
CPU: Intel Core i5 6600K
GPU: Nvidia 980Ti

**Game:**
v.017, 20-05-2019 64-bit, GL

**Steps to reproduce:**
Using this [continue.json](https://pastebin.com/J5hSH37z) file,
1. Open Dicey
2. Select English, Windowed
3. Select Continue
4. Click on the Warlock

**Comment by TerryCavanagh** [comment]
Thanks for this! Appreciate the continue file!

**Comment by TerryCavanagh** [comment]
Fixed! (this was due to a bug with Warlock that's been fixed in beta.)
