### ISSUE TITLE
Chocolate Cookie+ countdown permanently reverted to 12 after being weakened in an earlier fight

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1039]
![image](https://user-images.githubusercontent.com/2095534/58370861-c18b2400-7f0b-11e9-82a6-d0468151d220.png)

**Comment by triplegerms** [comment]
![image](https://user-images.githubusercontent.com/29346558/63050139-659bc000-bea8-11e9-916a-23aadfd99632.png)

Same issue with Bear Charge+ after being weakened in a previous fight. 
v1.0

**Comment by TerryCavanagh** [comment]
I just rewrote how countdowns are handled in cases where an upgraded piece of equipment reduces the countdown amount - so all cases of this should be fixed now!
