### ISSUE TITLE
infinite dagger dice against a cleric with a stolen silenced card

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#104]
![gif](https://user-images.githubusercontent.com/3826749/38454012-7e86df38-3a5f-11e8-96dc-739b1e8faf47.gif)
![infinite_dice](https://user-images.githubusercontent.com/3826749/38454017-9bd3db54-3a5f-11e8-915e-81a1e444d565.gif)

**Comment by TerryCavanagh** [comment]
Can't figure this one out right now - gonna have to leave it to v0.5 :/

**Comment by YinYin-Falcon** [comment]
So, it does not seem to occur when a small silenced card is stolen.

**Comment by YinYin-Falcon** [comment]
Got new footage of it (3:20):
[https://streamable.com/noy0p](url)
so far I only encountered it if you get silenced and in turn steal the silencing chant, as well as playing the dagger with a *highlighted* dice - if you click outside of the dagger to unhighlight it, the dice won't pop out for reuse

**Comment by TerryCavanagh** [comment]
Oh, whoa, nice catch. This helps a LOT, thank you!

**Comment by TerryCavanagh** [comment]
This one's fixed! I changed how reusable equipment's logic works a few versions ago, but forgot to close this issue!
