### ISSUE TITLE
Jester Snapping Shocked Countdown Items is Strange.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#1042]
Non-countdown items snap when shocked. Countdown items  just keeps adding a 6.

I just expected it to do something, I suppose mainly because shocked countdown items can be discarded but apparently cannot be snapped.

Seeing the dice get placed on the card could be be interpreted as unshocking the card.

https://drive.google.com/file/d/13ma6WKcgvUbifZ3kFBcsSBLV5w8TY18T/view

**Comment by TerryCavanagh** [comment]
This one has been fixed in recent versions!
