### ISSUE TITLE
Now that Auto Dagger isn't Robot exclusive, the name is slightly nonsensical

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1043]

**Comment by ncrecc** [comment]
Spitballing: Switchblade? Mace? Flail?

**Comment by onetruepurple** [comment]
I was thinking of Ray Gun (and ditching the existing MAX4 weapon, since it's already a carbon copy of Short Sword)

**Comment by ncrecc** [comment]
Ditching Ray Gun would require redesigning RoboBot once (if) it makes its way back in, though I guess that was already planned.

**Comment by ncrecc** [comment]
Added in June 4th(?) build:
![](https://i.frogbox.es/lrk)

**Comment by TerryCavanagh** [comment]
Yep, fixed!
