### ISSUE TITLE
Vampire hang (Jester, Snap, OSX)

### ISSUE THREAD

**Issue by ebugle** [TerryCavanagh/diceydungeons.com#1045]
Playing on version 0.17 on OSX as the Jester, the Vampire boss will stop responding after using the Jester's Snap ability. The vampire rolls dice but its equipment doesn't show up. I've had this happen twice after long Snap combos, and am uncertain if there may be any other factors contributing.

Possibly also relevant:

*The Vampire is Shocking me first.
*The Wooden Stake cards are getting snapped as well (one of which gets played and does nothing as the vampire isn't at 5 or less at that time, and the other doesn't for some reason)
*I am level 5, not 6 (despite killing everything on the way).

**Comment by ncrecc** [comment]
You killed all of the enemies on every floor up to the boss and you were still at Level 5? That sounds concerning. Did you skip any chests (possible Mimics)?

**Comment by TerryCavanagh** [comment]
Jester can no longer encounter Drake, so this never comes up.
