### ISSUE TITLE
Pips on character art are somewhat inconsistent

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1048]
(Apologies if this is too pedantic!)
The direction of the 2 on the characters' left-hand side is different on the character select screen than anywhere else. The picture below shows inventor, but this applies to all of them (except witch, which I'll get to in a moment)
![](https://i.frogbox.es/lpy)
Oddly enough, Witch is shown as having a 6 on her left-hand side on the character select screen and the title screen, but not on her icon or in-game:
![](https://i.frogbox.es/lpz)

**Comment by TerryCavanagh** [comment]
I'll pass this one on to Marlowe :D

**Comment by ncrecc** [comment]
Oh, and the two on the left-hand side is represented as a 3 in the diceydungeons.com banner art: ![](http://diceydungeons.com/assets/images/v015banner.jpg)

**Comment by TerryCavanagh** [comment]
Fixed!
