### ISSUE TITLE
ring of sacrifice is not once per battle as advertised

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#105]
It is also as expensive as dodge (20 count down), while being effectively worse (still taking damage down to 1 hp).

**Comment by TerryCavanagh** [comment]
Yeah, this is way off, I think. You wanna be able to use it without any resistance on any turn where you think you might die. I'm gonna try making it a require1 for v0.5. Have also fixed the single use thing.

Fixed for v0.5.

**Comment by YinYin-Falcon** [comment]
I've been *thinking*, not being single use actually made it somewhat decent, since it allows surviving a whole barrage of attacks for a turn, so you get to survive whatever. The dodge only does *one* attack (a bit like shield vs armor).

My expected behaviour would actually be single use/activation per battle, but remain active until health has been dropped to 0 and brought back to 1 (kind of like a zelda fairy/or FF phoenix down/etc - revives you exactly once).

**Comment by TerryCavanagh** [comment]
Oh, that makes sense. Hmm...
