### ISSUE TITLE
Crash when trying to access to equipement with Witch

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#1050]
I just had an upgrade with a second prepared slot, I tried to open the list of equipement, the app crashed (on Windows 8.1).

![Error](https://user-images.githubusercontent.com/8949232/58429744-2464f280-80a7-11e9-8f07-b2e9c4301b1d.png)

--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	0.17 / 0.7.0 (mod API)
sess. ID:	dicey_dungeons_2019-05-27_17'33'27
started:	2019-05-27 17:33:27
--------------------------------------
crashed:	2019-05-27 17:39:50
duration:	00:06:23
error:		ERROR in callscenemethod(ViewSpellbook,update) static : Error: There's no spell template for ""., stack = 
Called from Gamedata.getspelltemplate (Gamedata.hx line 719)
Called from elements.Spellbook.createspell (elements/Spellbook.hx line 42)
Called from states.ViewSpellbook.changeprecast (states/ViewSpellbook.hx line 135)
Called from states.ViewSpellbook.update (states/ViewSpellbook.hx line 374)
Called from Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 90)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 268)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

**Comment by TerryCavanagh** [comment]
Heya, thanks for this!

Which episode were you playing as when this happened? Do you remember what was in your spellbook (and on which numbers, ideally? I'm interested in whether this is the same as a bug that occurs if you're playing Countdown and haven't learnt a spell in slot 1).

(By the way! Are you active on discord as well? If so, what's your username? I really appreciate the bug reports you've been making this past year!)

**Comment by musicalentropy** [comment]
You're welcome !

The episode was the one with the dice always going out in the same order (6, 5, 4, 3 and so on). I was on level 2 or 3 I guess since it was my second prepared slot. I had 5 spells if I remember it well, covering the dice 2-6, I think it was the default one on the six, the shield, the fire spell on 4, the default one on the 5 too, and the yellow one which does 5 damage for even numbers. I had nothing on 1, but nothing called Countdown.

Yes I'm on Discord, my username is IvanC#9192. You're welcome for the help, your game is very very good and has been improved a lot too over this past year ;)

**Comment by TerryCavanagh** [comment]
Perfect, that's very helpful, thank you!

I don't seem to be able to contact you on discord for some reason, but I wanted to ask you: would you like to have access to the beta testing branch of the game? I'd really appreciate your feedback on the new episodes and final game content before it goes live for everyone! (If you're interested, just send me a DM on discord!)

**Comment by TerryCavanagh** [comment]
Fixed!
