### ISSUE TITLE
Inventory, while in upgrade dialog, is misaligned.

### ISSUE THREAD

**Issue by muizzsiddique** [TerryCavanagh/diceydungeons.com#1063]
When given the choice to upgrade as a Warrior from level-up and the Inventory is accesible, the Inventory graphic isn't aligned properly.

I'm running 0.17.2 on Windows 10 Home 64-bit.

![Screenshot (112)](https://user-images.githubusercontent.com/23620568/58706649-917bcf00-83aa-11e9-9194-127e1c1aea9a.png)

**Comment by TerryCavanagh** [comment]
This screen is long gone! (replaced by Ned since launch)
