### ISSUE TITLE
Suggestion: split special into two fields: "inaccessible from CfB Robot/Expect the Unexpected" and "inaccessible in editor" 

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1065]
For example: Heat Sink is "special" because Witch and Jester should never receive it... but that also means it's unobtainable in the editor, even though it's just a regular and common Robot card. (Maybe there are some other properties of special cards I'm missing.)

**Comment by ncrecc** [comment]
This is *sort of* fixed with the introduction of the PU field, but not for lunasa or BR CfB robot

**Comment by TerryCavanagh** [comment]
This is now fixed with equipment tags in v1.9.
