### ISSUE TITLE
The Storm and The Storm+ are identical

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1067]
The other Scathatch cards have damage upgrades, but The Storm does 6+6 damage and can't go up any higher (without introducing a 7 dice, anyways).

**Comment by TerryCavanagh** [comment]
Fixed! This was a random bug lottery. I made it so the un-upgraded version of The Storm no longer silences. This is a nice solution (suggested by Matz on discord!), because it doesn't change the balance of the game and also makes it possible for Scathach to appear as a boss in more episodes.
