### ISSUE TITLE
Finders Keepers skillcard isn't once per battle

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1069]
I thought I would have been able to steal multiple pieces of equipment if I used FK twice, but nope. :(

**Comment by lcenine** [comment]
Is there any reason why Finders Keepers reappears when it has already been activated? I don't see any benefit to it because you can keep more than 1 item.

**Comment by TerryCavanagh** [comment]
There's a slightly odd edge case issue here that's worth looking at, but I think I'll create a new issue for it. Closing this one.
