### ISSUE TITLE
HTML5 version on OSX Safari hammers CPU

### ISSUE THREAD

**Issue by rjp** [TerryCavanagh/diceydungeons.com#107]
Macbook Pro, 3.1GHz Core i5, OSX 10.13.4 beta, Safari 11.1.

Dicey Dungeons consistently uses 40-50% CPU according to Activity Monitor.

**Comment by TerryCavanagh** [comment]
Sorry about that - I've basically done no optimisation on the game at all in the past month.

After v0.5 I'm planning to take a little time to clean things up a little. I think there'll be a lot I can do about this.

**Comment by TerryCavanagh** [comment]
This should be hugely improved in v0.5 now. Closing!
