### ISSUE TITLE
Bear (enemy)'s name is misaligned

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1076]
![](https://i.frogbox.es/lqa)

**Comment by ncrecc** [comment]
![image](https://user-images.githubusercontent.com/11216597/64122732-6a011d80-cd70-11e9-80dd-99e8d841908c.png)
Still here. Super Bear's name is properly aligned, oddly enough

**Comment by TerryCavanagh** [comment]
related to https://github.com/TerryCavanagh/diceydungeons.com/issues/1978

**Comment by TerryCavanagh** [comment]
Fixed!
