### ISSUE TITLE
text didn't disappear in tutorial battle

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#1083]
<img width="1280" alt="Bildschirmfoto 2019-06-03 um 00 10 08" src="https://user-images.githubusercontent.com/465632/58767989-01997900-8594-11e9-9509-98eeed468728.png">

**Comment by increpare** [comment]
(i didn't do anything particularly interesting to cause this I don't think)

**Comment by increpare** [comment]
(I don't know if it's relevant, but I'm using HD sprite mode)

**Comment by increpare** [comment]
oh it's generally messy - i'll try restarting...
<img width="1280" alt="Bildschirmfoto 2019-06-03 um 00 11 42" src="https://user-images.githubusercontent.com/465632/58767997-34dc0800-8594-11e9-82b4-88bbecb2a2a1.png">

**Comment by increpare** [comment]
restarted and the tutorial fight works fine now

**Comment by ncrecc** [comment]
HD sprite mode is a mess in general right now (from what I'm aware).

**Comment by TerryCavanagh** [comment]
Oh, this appears to be a new one :( I might just disable HD sprite stuff for launch, I think.

**Comment by TerryCavanagh** [comment]
Fixed.
