### ISSUE TITLE
somehow lost an item?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#1085]
Not sure what caused it - I was playing as a thief, left the game, reloaded, noticed there was a chest, picked up the leather armour there, but when I went into battle I found I only had leather armour in my inventory

<img width="1280" alt="Bildschirmfoto 2019-06-03 um 01 46 17" src="https://user-images.githubusercontent.com/465632/58768874-8e96ff00-85a1-11e9-98ca-5e187e41a27c.png">

**Comment by TerryCavanagh** [comment]
Fixed in launch.
