### ISSUE TITLE
No animation for Counter Spell locking dice, whereas there is one for regular Lock

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1090]

**Comment by ncrecc** [comment]
No animation for Counter Spell (lock dice that roll x) kicking in either

**Comment by ncrecc** [comment]
This is probably intentional with pu lock

**Comment by TerryCavanagh** [comment]
Actually this one is a lot trickier than it might first appear: say you Counter a 6, and also freeze the enemy. When the dice appears, you expect it to lock before freeze is applied - i.e. the six locks before the freeze turns it into a 1. This interaction is a kind of a mess to pick apart, which makes this really difficult. It's probably best not to risk breaking it at this stage of development, honestly.
