### ISSUE TITLE
Lock? completely trivializes Aoife

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1092]
Aoife has a two-slot card and a "needs doubles" card... meaning with Lock?, which restricts her to one dice, she can't do anything and must skip any turn on which she's Lock?ed. Maybe placing a die in a two-slot card should further the unlocking process (and, if necessary, prevent the die from being taken out of the card).

**Comment by onetruepurple** [comment]
Something's gotta give:

1. Change Tower Shield into a single slot, 2 uses item (to make it more cohesive with the upgraded version), or:
2. Change Shield Grip into some sort of single slot, as was in the distant past, or:
3. Change the way Lock? works, or:
4. Redesign Aoife.

I strongly prefer option 1, would really dislike option 4, and the other two are gradually in between.

**Comment by TerryCavanagh** [comment]
I think doing a more powerful Tower Shield? is worth exploring here - Aoife is kinda broken in Parallel Universe anyway, so an episode specific buff seems like a good idea.

**Comment by TerryCavanagh** [comment]
(and a Shield Grip? too)

**Comment by onetruepurple** [comment]
That's not a bad idea, especially since it potentially opens the way into more PU-specific enemy designs, if you want to fall down that hole. ;-)

**Comment by TerryCavanagh** [comment]
Aoife's had a redesign since launch, so this issue is out of date. Closing!
