### ISSUE TITLE
Consider giving more variation to Jester's first chest

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1098]
Right now it's always Juggling Ball, which is a good item but it's the same situation as the Warrior always getting Wooden Shield back in the day.

**Comment by onetruepurple** [comment]
@TerryCavanagh Still valid in RC1

**Comment by onetruepurple** [comment]
With #1399 closed I have low hopes of this getting done, but keeping it open just in case.

**Comment by TerryCavanagh** [comment]
Yeah, not planning to do this one at this point 😞
