### ISSUE TITLE
Consider giving Copycat curse every turn if playing This'll Be Fine, perhaps?

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1101]
This would make fights with Copycat slightly more fair

**Comment by TerryCavanagh** [comment]
This was a decent suggestion, but I don't want to make an exception for Copycat's behaviour on this episode - the consistent thing to do is to have Copycat copy all of your *innate* status effects everywhere, but that potentially causes other problems in bonus round episodes. Not going to mess with this I think.
