### ISSUE TITLE
Weaken? adds damage to 0-damage attacks (e.g. battering ram with no shield)

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1104]
![](https://i.frogbox.es/lqs)
Probably also applies to Thorns?

**Comment by ncrecc** [comment]
This has been intentionally used in More Fluff for quite a while, with an item that does "0 damage, twice" with the purpose being that its damage is increased by alt Weaken

**Comment by TerryCavanagh** [comment]
Yep, I think this one can stay! Closing.
