### ISSUE TITLE
Battering Ram and Lightning Rod should probably be fury-able

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1106]
Right now if you fury them, it acts like you just used them once since you deplete the damage they'd do on the first turn.

**Comment by iestynne** [comment]
This happened to me (with Lightning Rod) and I had no idea what happened. I thought it was a bug - needs some kind of better communication that Fury cannot be used on Lightning Rod, it shouldn't just waste Fury to no effect.

**Comment by ncrecc** [comment]
Also Harvest Scythe

**Comment by TerryCavanagh** [comment]
Probably Lightning Rod just should be in Warrior episodes. 🤔 Battering Ram, I'm not sure about.

**Comment by TerryCavanagh** [comment]
Haven't fixed this for general cases, but I've specifically fixed this for Battering Ram, Lightning Rod, and Harvest Scythe in v2.1.
