### ISSUE TITLE
Button on re-equipped backup cards isn't reactivated

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1108]
![gif](https://giant.gfycat.com/OffensiveIcyClam.gif)
console not relevant, just fiddly to crop out :)

**Comment by TerryCavanagh** [comment]
Need to check if this still happens in v1.9, it's been a while since it was reported!

**Comment by TerryCavanagh** [comment]
Yep, this one's been fixed!
