### ISSUE TITLE
Feature Request: user provided csv files

### ISSUE THREAD

**Issue by FelixNemis** [TerryCavanagh/diceydungeons.com#111]
This would be really awesome to play around with equipment, enemies, starting gear, and shops.

**Comment by TerryCavanagh** [comment]
This is... potentially pretty cool. I'll see what I can do :D

**Comment by FelixNemis** [comment]
Awesome!

**Comment by TerryCavanagh** [comment]
I've decided to develop an in-game editor to give you access to stuff like this, so I probably won't be going the csv approach. Closing, thanks!
