### ISSUE TITLE
Define more gadgets for equipment

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1111]
Right now there are a lot of cards that default to the "Accelerate" gadget, even when there are obvious matching gadgets that could go with them. (e.g. Blowtorch for Burning Light, Refrigerator for Ice Shard)

This has been around for a while, and it wouldn't take too much effort just to skim through equipment.csv and fill in some matching gadgets for gadgetless equipment.

**Comment by TerryCavanagh** [comment]
This is now done - every single piece of equipment in the game has a gadget associated!
