### ISSUE TITLE
Consider redefining Silence so it works on enemies

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1117]
I'm thinking something like this: rightmost card (including skillcards) requires two dice to unshock, cannot use your limit break if you have one until that card is unshocked, does not stack

(Although that would require making Jester, Robot, and Bear silenceable for it to fully make sense)

**Comment by TerryCavanagh** [comment]
Not planning to make Silence work on enemies at this point - gonna close up all remaining cases where the player can potentially get cards which inflict it.
