### ISSUE TITLE
Rosewood Guardian boss

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#112]
New boss idea:

- Innate ability, poison heals it and weak against fire (double damage)
- uses rosepetal staff, shield, armor and charm
- armor and charm work the same as the staff, but put armor and poison on itself respectively
- has a relatively low health pool (~40, just enough to not succumb to alpha damage and recover from it)
- the level could have a fireball lying around/sell a staff in a shop and perhaps introduce antidote as well

Concept is a "softer" version of the Vampire. You can have a relatively normal nail biting experience using some fire damage and the antidote or an *incredibly* tough challenge without them.

Might be going a bit beyond what current bosses demand ... (shield, armor, healing *and* poison)

**Comment by TerryCavanagh** [comment]
There's some cool stuff here! I love the idea of poison as enemy healing, but I think there's too much going on with the addition of the rosewood stuff.

Having an item that removes poison on an enemy seems very specific; the existing antidote removes it on the *player*, but having that work for either side introduces the problem of a targetting mechanic. Though, I suppose an item that removed poison from BOTH sides could work... hmm.

I might try a variation of this without the rosewood complications. Thanks for the suggestion!

**Comment by YinYin-Falcon** [comment]
> Having an item that removes poison on an enemy seems very specific

While I do wish to have some equipment that can be played on both yourself and the enemy (curse or counter spell would be prime candidates), I only really meant this as a method to slow down your own poison death.

Flexible cards would be great, especially once this goes full mobile and you can possibly swipe/flick the cards up/down to play them rather than pressing a button. Giving the cards arrow shaped edges at top and bottom depending on where you can play them. Targeting problem solved.

And yeah as I guessed it's a bit much at once. But you can pick and choose! :D
(just a higher level rose with rosepetal armor would be cool already)

**Comment by TerryCavanagh** [comment]
Done! Thank you for the suggestion!
