### ISSUE TITLE
Downgraded Call for Backup Robot heals the enemy not the player

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1128]
![Screenshot 2019-06-24 at 19 52 19](https://user-images.githubusercontent.com/48322734/60044130-9c7c0380-96b9-11e9-96e6-daa26a9cdaf2.png)

```Call for Backup Robot_downgraded,Regenerate|Heal [heal]3 health,2,attack(-3);,,,,BACKUP,WHITE,,,,none,0,YES,NO,NO,NO,NO,NO,,,,,,,,,,```

I imagine it's meant to be `attackself(-3);` :)

**Comment by TerryCavanagh** [comment]
This one's been fixed a little while! Closing.
