### ISSUE TITLE
Cutscenes load very slowly and there's no way of knowing if they're loading or if the game is stuck

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1133]

**Comment by TerryCavanagh** [comment]
Has this improved any in beta? I've done some loading optimisations here and we've switched to ATF textures, but it's hard to tell on my machine what impact that's had.

**Comment by onetruepurple** [comment]
This is considerably better now, on my machine at least. Some sort of indication that the game is loading content would still be good for launch, though.
