### ISSUE TITLE
"die" vs "dice"?

### ISSUE THREAD

**Issue by Spacetchi** [TerryCavanagh/diceydungeons.com#1143]
I've noticed that on Steam, the description says "...if you weren't a walking dice" and one of the images says "...you're a giant dice...". Also there are many cards that say "freeze/burn/etc 1 dice". Is the word "dice" singular in this game by intention?

**Comment by TerryCavanagh** [comment]
Hey - yes, it's a deliberate choice I made early in development. In modern usage, using "die" as singular is considered a bit archaic, although obviously it's still widely used thanks to things like D&D manuals.

If people feel strongly enough about this, it is possible to mod the game to change any of the text to whatever you like! However, I'm not interested in making this change myself - I just personally find sentences like "You receive an extra die" or "return the die" a little awkward looking.
