### ISSUE TITLE
options menu on title screen broke

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#1144]
Not sure what happened, but after opening it and closing it a few times, clicking on "options" doesn't open the menu - it just makes everything a little darker.  Thankfully the title buttons all still respond (I can click options again to make the darkness go away).  

Wasn't able to repro after starting.

(release candidate 0.2)

**Comment by TerryCavanagh** [comment]
Ah, this'll be because my debug options were enabled in this build (pressing F1-F5 gives you different debug reouts depending on where you are in the game). Fixed anyway!
