### ISSUE TITLE
German Localization issues thread

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#1146]

**Comment by increpare** [comment]
Profile text outside of box bounds on left

<img width="1280" alt="Bildschirmfoto 2019-08-02 um 00 47 29" src="https://user-images.githubusercontent.com/465632/62402832-ff4e9d80-b589-11e9-92bc-7f11843c8ba1.png">

**Comment by increpare** [comment]
Would this better be "Zug beenden"?

(normally you get the first turn, then the other player, so you're not ending the round when you hit the button right?)

<img width="204" alt="Bildschirmfoto 2019-08-02 um 00 18 04" src="https://user-images.githubusercontent.com/465632/62402837-0aa1c900-b58a-11e9-9363-5bbba29b85b8.png">

**Comment by increpare** [comment]
Out-of-bounds text on buttons in in-game options menu

<img width="1280" alt="Bildschirmfoto 2019-08-02 um 00 15 14" src="https://user-images.githubusercontent.com/465632/62402853-2311e380-b58a-11e9-9636-8d19527f3d49.png">

**Comment by increpare** [comment]
It looks like "Schrecken" should be "Schreckens" - either the text is getting cropped or there's a missing s 

<img width="1280" alt="Bildschirmfoto 2019-08-02 um 00 06 53" src="https://user-images.githubusercontent.com/465632/62402864-391fa400-b58a-11e9-9422-6bd985e6826b.png">

**Comment by increpare** [comment]
Further about Zug vs Runde.  With the strahlenwaffe, it says "X pro Runde verwenden", but shouldn't it be "X pro Zug" because it's "X uses this turn" and not "X uses this round" (relevant for thieves).

<img width="1280" alt="Bildschirmfoto 2019-08-03 um 19 19 50" src="https://user-images.githubusercontent.com/465632/62415029-e692c600-b623-11e9-9944-d69d8b679c42.png">

**Comment by increpare** [comment]
Heilkristall+ text goes outside of box

<img width="1280" alt="Bildschirmfoto 2019-08-03 um 19 36 01" src="https://user-images.githubusercontent.com/465632/62415189-f90dff00-b625-11e9-8d1c-5d825d12ce3f.png">

**Comment by increpare** [comment]
überwältigen has out-of-bounds text

<img width="1280" alt="Bildschirmfoto 2019-08-03 um 20 00 04" src="https://user-images.githubusercontent.com/465632/62415389-58214300-b629-11e9-8654-2f003c222b24.png">

**Comment by increpare** [comment]
Auslöser- has oob text

<img width="1280" alt="Bildschirmfoto 2019-08-03 um 20 08 20" src="https://user-images.githubusercontent.com/465632/62415481-7e93ae00-b62a-11e9-927b-74b8ac7847d3.png">

**Comment by increpare** [comment]
out of bounds text

<img width="1280" alt="62418301-0b0f9200-b666-11e9-83a2-523a32da183c" src="https://user-images.githubusercontent.com/465632/62429598-cc82e180-b710-11e9-87a9-b3b1cad02495.png">

**Comment by increpare** [comment]
oob text

<img width="1280" alt="Bildschirmfoto 2019-08-05 um 01 19 24" src="https://user-images.githubusercontent.com/465632/62430636-884b0d80-b71f-11e9-8fd0-9432d71d7f37.png">

**Comment by increpare** [comment]
mechanical arm text oob
<img width="1280" alt="Bildschirmfoto 2019-08-07 um 21 49 38" src="https://user-images.githubusercontent.com/465632/62653202-5d4dfd00-b95d-11e9-95c3-78b39f3177e5.png">

**Comment by increpare** [comment]
man-eating plant oob text

<img width="1280" alt="Bildschirmfoto 2019-08-07 um 21 54 04" src="https://user-images.githubusercontent.com/465632/62653458-e9f8bb00-b95d-11e9-97a8-ffa8dc37d2f4.png">

**Comment by increpare** [comment]
character name overlaps with dice 

<img width="1280" alt="Bildschirmfoto 2019-08-07 um 22 13 22" src="https://user-images.githubusercontent.com/465632/62654689-a2276300-b960-11e9-807d-93e751c28a35.png">

**Comment by increpare** [comment]
text going out of screen area

<img width="1280" alt="Bildschirmfoto 2019-08-07 um 22 26 33" src="https://user-images.githubusercontent.com/465632/62655516-71e0c400-b962-11e9-98cb-4d4280859ae1.png">

**Comment by increpare** [comment]
show improvements checkbox goes offscreen

<img width="1280" alt="Bildschirmfoto 2019-08-08 um 00 52 33" src="https://user-images.githubusercontent.com/465632/62663198-e291db80-b976-11e9-8c76-21cb83a09d63.png">

**Comment by increpare** [comment]
text goes off edge of screen

<img width="1280" alt="Bildschirmfoto 2019-08-08 um 01 04 12" src="https://user-images.githubusercontent.com/465632/62663710-f6d6d800-b978-11e9-8fcf-94107e9d18ad.png">

**Comment by increpare** [comment]
text-box pushed off left off-screen

<img width="1280" alt="Bildschirmfoto 2019-08-08 um 01 37 58" src="https://user-images.githubusercontent.com/465632/62664831-50410600-b97d-11e9-9152-ba3de146e9c8.png">

**Comment by TerryCavanagh** [comment]
Have passed these on to Thomas! Thanks!

**Comment by TerryCavanagh** [comment]
(regarding text box positions: I'll write some code to push those back on screen for launch when they're clipped offscreen like that, so it shouldn't happen then)

**Comment by increpare** [comment]
slightly unhelpful text overlapping background items

<img width="1280" alt="Bildschirmfoto 2019-08-13 um 23 30 48" src="https://user-images.githubusercontent.com/465632/62978815-70ac0d00-be22-11e9-85ff-3940d5fa7f4d.png">

**Comment by increpare** [comment]
does this count as out of bounds?

<img width="317" alt="Bildschirmfoto 2019-08-13 um 23 54 39" src="https://user-images.githubusercontent.com/465632/62980072-cd5cf700-be25-11e9-9f01-4a5a427857fc.png">

**Comment by increpare** [comment]
"close options" button in options menu still a bit tight

![Bildschirmfoto 2019-08-14 um 00 19 05](https://user-images.githubusercontent.com/465632/62981313-32feb280-be29-11e9-9317-2e789916b5b6.png)

**Comment by increpare** [comment]
text overlapping

<img width="1280" alt="Bildschirmfoto 2019-08-14 um 01 39 33" src="https://user-images.githubusercontent.com/465632/62984869-1bc5c200-be35-11e9-95f0-52812e4ca09b.png">

**Comment by increpare** [comment]
challenges text goes outside button

<img width="1280" alt="Bildschirmfoto 2019-08-14 um 10 29 21" src="https://user-images.githubusercontent.com/465632/63006306-89e2a700-be7e-11e9-9f64-aed29c5b2428.png">

**Comment by increpare** [comment]
OOB text

<img width="383" alt="Bildschirmfoto 2019-08-14 um 22 35 08" src="https://user-images.githubusercontent.com/465632/63054283-db714d00-bee3-11e9-9cab-975ad5a6514d.png">

**Comment by increpare** [comment]
inventor's text goes outside the box

<img width="321" alt="Bildschirmfoto 2019-08-14 um 22 48 41" src="https://user-images.githubusercontent.com/465632/63055246-c1386e80-bee5-11e9-81e7-a3d69135bd99.png">

**Comment by increpare** [comment]
dog text going well out of screen bounds

<img width="1280" alt="Bildschirmfoto 2019-08-14 um 22 53 32" src="https://user-images.githubusercontent.com/465632/63055548-6a7f6480-bee6-11e9-9983-a62a0af13ec8.png">

**Comment by TerryCavanagh** [comment]
All of these issues have been fixed! Closing.
