### ISSUE TITLE
"To unlock EPISODES: Play a game with five contestants" unclear

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#1147]
It's not clear to me what that means. Doesn't that mean "Play five games?"  Do you mean "Play a game with each of the contestants"?  It's a bit mysterious to me.  Would it help to have progress indicated "(1/5 played)".  Or, what might alo

<img width="1280" alt="Bildschirmfoto 2019-08-03 um 19 14 04" src="https://user-images.githubusercontent.com/465632/62414973-e514ce00-b622-11e9-9c21-a863588f7545.png">

Oh ok, comparing at the labels for the other locked characters I understand now.  Huh.  Not sure what I'd suggest as better.

**Comment by TerryCavanagh** [comment]
I think the issue here is really that it appears before you have any context for it. I've changed it at launch to only appear after you unlock robot, and I've had nobody mention it since. Closing!
