### ISSUE TITLE
direwolf strong against poison but takes extra poison damage?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#1148]
<img width="1280" alt="Bildschirmfoto 2019-08-03 um 19 56 31" src="https://user-images.githubusercontent.com/465632/62415352-d7624700-b628-11e9-8b75-458148a79c52.png">

**Comment by TerryCavanagh** [comment]
There was an error with updating the tooltips on poison which is fixed now! Closing.
