### ISSUE TITLE
gog?

### ISSUE THREAD

**Issue by pdknsk** [TerryCavanagh/diceydungeons.com#1153]
As your previous games are on there, I had considered it a given, but the launch page makes no mention of it.

**Comment by TerryCavanagh** [comment]
Probably not! GOG checked the game out back at v0.7 and they weren’t
interested.

If you’re interested in alternative game stores, I’d like to strongly
recommend itch.io!

**Comment by onetruepurple** [comment]
The game has drastically changed since v0.7 though, so maybe consider approaching them after the launch :diceyjester:

**Comment by TerryCavanagh** [comment]
GOG know where I am if they want the game, lol. Closing.
