### ISSUE TITLE
German lockpick translation is wrong

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#1158]
It translates "split in" (teile in) as "divide by" (teile durch).

Natural flow of words, but wrong for the actual card descriptions.

edit: worth noting that the translation for the downgraded lockpick is correct (divided by two rather than split in two)

**Comment by TerryCavanagh** [comment]
Thanks for this!

What is the correct sentence here? `Teile einen Wurf in 2`?

**Comment by YinYin-Falcon** [comment]
Yes!

**Comment by TerryCavanagh** [comment]
Fixed in v1.10. Thanks!
