### ISSUE TITLE
text overflow and other German localisation

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#1160]
I'm gonna drop everything I spot in German here.
First and most severe one: Robot description
![image](https://user-images.githubusercontent.com/3826749/62970153-21101600-be0f-11e9-81c5-7a7c057cf586.png)
all "uneven" (ungerade) slots:
![image](https://user-images.githubusercontent.com/3826749/62975236-40607080-be1a-11e9-802f-58133af87aa1.png)
squawk description has no margin (same for wail, probably all silence):
![image](https://user-images.githubusercontent.com/3826749/62976221-6b4bc400-be1c-11e9-9545-689d697eaba4.png)
blowtorch gadget description:
![image](https://user-images.githubusercontent.com/3826749/62976702-7f43f580-be1d-11e9-9c7f-0d2b152e16ff.png)
special case, the spanner here could be split as
> Schrauben-
> schlüssel

to retain a good margin and text size (you can probably do this with a lot of long German words)
![image](https://user-images.githubusercontent.com/3826749/62976875-e2ce2300-be1d-11e9-8fcc-735b12d730bf.png)

**Comment by TerryCavanagh** [comment]
Thanks for this thread!

**Comment by YinYin-Falcon** [comment]
upgraded cauldron description is entirely out of place
![image](https://user-images.githubusercontent.com/3826749/63112852-8f7ce180-bf91-11e9-98cb-ab7867dc3c53.png)

**Comment by YinYin-Falcon** [comment]
no overflow here, but I noticed this translation doesn't work in context:
![image](https://user-images.githubusercontent.com/3826749/63116747-aaa01f00-bf9a-11e9-9705-0574b03c3e3f.png)
> reason for entering the dungeons:

has been translated as

> reason why **you** have entered the dungeon:

the article sounds wrong to me as well
I'd go with

> Motivation den Dungeon zu betreten:

which means "motivation for entering the dungeon:"

**Comment by YinYin-Falcon** [comment]
the challenges button
![image](https://user-images.githubusercontent.com/3826749/63117058-4fbaf780-bf9b-11e9-92b9-92ac85bf02d7.png)

**Comment by YinYin-Falcon** [comment]
no overflow here, but since it's just one rather than several dice, the article here needs to be "den" instead of "die"
![image](https://user-images.githubusercontent.com/3826749/63155116-48830080-c012-11e9-818e-4c9799e9f2cc.png)

**Comment by YinYin-Falcon** [comment]
fury spell description
![image](https://user-images.githubusercontent.com/3826749/63157993-9864c600-c018-11e9-92c8-978f2aeef7fe.png)
fury gadget description
![image](https://user-images.githubusercontent.com/3826749/63158908-969c0200-c01a-11e9-9b93-545db3ae0ef3.png)
overwhelm
![image](https://user-images.githubusercontent.com/3826749/63159433-db746880-c01b-11e9-8a85-55140eceaf2f.png)
hookshot
![image](https://user-images.githubusercontent.com/3826749/63159530-0ced3400-c01c-11e9-9c29-bded1375f968.png)

**Comment by YinYin-Falcon** [comment]
third jester episode description
![image](https://user-images.githubusercontent.com/3826749/63225099-2681ad80-c1cd-11e9-846e-9ff84d02a13f.png)

**Comment by YinYin-Falcon** [comment]
harmony
![image](https://user-images.githubusercontent.com/3826749/63294655-29fb5e80-c2cb-11e9-97ca-0a7edd8c009d.png)
sour candy
![image](https://user-images.githubusercontent.com/3826749/63294672-32ec3000-c2cb-11e9-8480-fb799e18817f.png)
subdivide
![image](https://user-images.githubusercontent.com/3826749/63294690-3c759800-c2cb-11e9-8784-94a50ca67471.png)
tableslam+
![image](https://user-images.githubusercontent.com/3826749/63294709-47c8c380-c2cb-11e9-9dad-cc19fa4ae2c7.png)

**Comment by TerryCavanagh** [comment]
I believe all of these are fixed now! Thanks!
