### ISSUE TITLE
"if you visit an anvil, reject the upgrade, click back on the anvil without moving the player then use the upgrade, the anvil won't disappear"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1162]
Some guy said this on #bug-reports

**Comment by Not-A-Goldfish** [comment]
This also happens with chests where if you exit and enter the chest will stay. And with trade shops if you exit and enter you keep the item they were asking to trade for.

**Comment by TerryCavanagh** [comment]
Fixed!
