### ISSUE TITLE
inventory button gone from upgrade screen?

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#1165]
<img width="1280" alt="Bildschirmfoto 2019-08-13 um 23 46 41" src="https://user-images.githubusercontent.com/465632/62979644-ab16a980-be24-11e9-9d03-bf0a3ddcc640.png">

is that gone from the release version?

**Comment by TerryCavanagh** [comment]
Ah! This one is a Baer specific one I think :D
