### ISSUE TITLE
sountrack spliting into two albums

### ISSUE THREAD

**Issue by Tonlly** [TerryCavanagh/diceydungeons.com#1167]
The soundtrack on Steam ([link](https://store.steampowered.com/app/1138490/Dicey_Dungeons__Soundtrack/)) splits to two albums - one with tracks 3 and 5, second with the rest.
Also, the third's track's name contains "3. ", others don't have ordering in the name.

**Comment by TerryCavanagh** [comment]
Ohh, sorry about that! Will fix that right away.
