### ISSUE TITLE
Dice barely snap into place

### ISSUE THREAD

**Issue by EMPeter1701** [TerryCavanagh/diceydungeons.com#1168]
I've only encountered this with engineer on a silenced gadget:
[Twitch clip](https://clips.twitch.tv/BumblingImpossibleNostrilDoubleRainbow)
They seemed to be snapping into place when placed somewhat to the right.
I play in a maximized window so maybe it's a scaling issue?

**Comment by iestynne** [comment]
I encountered the same issue when playing as Inventor against Loud Bird
 - I have Magic Dice as my current gadget
 - the bird Silenced me
 - the Magic Dice was greyed out and showed "place two dice to break silence"
 - I tried to put two 5 dice on these slots but it wouldn't accept them
 - after shuffling them around a bit it eventually accepted them and canceled the Silence, but it seemed to take both dice into the same slot
 - it happened a second time and I think I see what's happening a bit more clearly: the left slot won't accept dice, but the right slot will. When you place a die on the right slot it warps over to the left slot, so then you can place a second die on the right slot to complete the action. Weird!

**Comment by TerryCavanagh** [comment]
Fixed!
