### ISSUE TITLE
Improve descriptions for bonus damage

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#117]
![image](https://user-images.githubusercontent.com/2874150/39085868-42ebc07e-4581-11e8-995a-ff9d2802b790.png)

**Comment by pace212** [comment]
Here's another example of that.

![screenshot 2018-04-20 19 12 50](https://user-images.githubusercontent.com/38589027/39085916-b6711332-454f-11e8-86fd-ca9cee17b3f5.png)

The same is true for Throwing Axe+ and probably others too

**Comment by TerryCavanagh** [comment]
Fixed
