### ISSUE TITLE
Furying boomerang to victory can cause the overworld lower UI to shake

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1170]
Here's an example of the bug from a stream, unfortunately I missed the cut off for the play that triggered it, but it involved furying boomerang+ to end a fight:
https://clips.twitch.tv/GrotesqueBillowingPepperoniSeemsGood

**Comment by TerryCavanagh** [comment]
Finally figured this out. Fixed!
