### ISSUE TITLE
French translation: stretched text?

### ISSUE THREAD

**Issue by woctezuma** [TerryCavanagh/diceydungeons.com#1171]
In my "Thief" run, I was transformed into a bear.

When I encountered the final boss, the text for "Ours" ("Bear" in French) was weirdly stretched.

![Final Boss](https://i.imgur.com/5ihK7iF.jpg)

I know the French translation is not finished, and I hacked the "supportedlanguages.txt" file to play in French, so if this explains the issue, please disregard.

**Comment by TerryCavanagh** [comment]
Oh, this is a separate thing from the french translation. It happens in every version! Closing as a duplicate, but thanks for making an issue!
