### ISSUE TITLE
Option to disable screen shake

### ISSUE THREAD

**Issue by insin** [TerryCavanagh/diceydungeons.com#1173]
I've looked forward this since the early playable versions and it's been well worth the wait, thank you ❤️ 

Could we please have an option to disable screen shake?

**Comment by TerryCavanagh** [comment]
Hey! Sorry, I meant to have this one ready for launch, but it slipped my mind. I'll get it into the game as soon as I can!

**Comment by Nightblade** [comment]
+1 i'm very sensitive to screen shake  :(

**Comment by TerryCavanagh** [comment]
This one is *finally* coming in v1.8!

![image](https://user-images.githubusercontent.com/2874150/81925618-4ba23000-9628-11ea-9628-ef4fb4c011c2.png)
