### ISSUE TITLE
Slot Machine card bug with the final unlockable character

### ISSUE THREAD

**Issue by insin** [TerryCavanagh/diceydungeons.com#1174]
On playing a Slot Machine, I got another Slot Machine back, which went into its "used" state when clicked, without replacing itself with another card:

![diceydungeons_bRpp58g5Q1_spoliers](https://user-images.githubusercontent.com/226692/63075928-a8c46480-bf76-11e9-89d9-438859fa97f3.png)

**Comment by TerryCavanagh** [comment]
This one is a duplicate of a bug I *think* I've fixed (https://github.com/TerryCavanagh/diceydungeons.com/issues/939)
