### ISSUE TITLE
In Bonus Round, the Poison rules are only considered if there's enough Curse-based enemies

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1176]
![image](https://user-images.githubusercontent.com/32357485/63093241-59713a80-bf5c-11e9-99e1-21201e38c8c2.png)

From `remixrules.txt`. Should be a simple fix - change `if(cursecount >=2)` to `if(poisoncount >=2)`.

**Comment by TerryCavanagh** [comment]
Fixed!
