### ISSUE TITLE
Robot can get the Skeleton rule in Bonus Round

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1177]
![image](https://user-images.githubusercontent.com/32357485/63093368-c7b5fd00-bf5c-11e9-9f55-b2c7619f43e9.png)

Robot is still offered rules from `hardlist`. The `else` clause should probably have a `hardlist.push('Skeleton');` in it too.

**Comment by TerryCavanagh** [comment]
Fixed!
