### ISSUE TITLE
Innate ability text in wrong place

### ISSUE THREAD

**Issue by OtherworldBob** [TerryCavanagh/diceydungeons.com#118]
Had the following graphical oddity occur when playing v0.5.1, HTML 5 version.
![image](https://user-images.githubusercontent.com/12876244/39087939-e0c2aeb0-45a0-11e8-8d1b-fdda17a851d4.png)
Only occurred for that innate ability which was gained in battle, all other innate ability text moved to the top of the window after appearing further down at the start of a fight.

Apologies if this is a known issue.

**Comment by TerryCavanagh** [comment]
Fixed!
