### ISSUE TITLE
Pirate Hook doesn't work nice with Fury

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1186]
![image](https://user-images.githubusercontent.com/32357485/63121662-e89e4280-bf9c-11e9-8400-4296fc7bdd24.png)

From the dicecord; you're given 2x Re-Equip Next, except... that doesn't make sense in this context. Consider a more complicated script to give it more uses if you use Fury on it; either that or just make it give a single stack of Re-Equip Next.

**Comment by TerryCavanagh** [comment]
Fixed!
