### ISSUE TITLE
In Bonus Round, Cowboy Rule says Enemies always roll a 6, but they don't.

### ISSUE THREAD

**Issue by dragonsbutalsorabbits** [TerryCavanagh/diceydungeons.com#1189]
In the Bonus Round, I picked a random rule for the 4th floor, and it gave me the Cowboy rule. It says "Enemies always roll a six." I picked up Counter Spell thinking I could use it to negate a die since there's a guaranteed enemy six, but the enemy didn't roll any sixes!

In case it matters, I'm the Warrior, and the rules I have are: The Singer, Baby Squid, Loud Bird, and Cowboy. I'm fighting the Loud Bird.
![Dicey Dungeons Aug 15 04-22-41PM](https://user-images.githubusercontent.com/54158525/63133212-f772fe00-bf78-11e9-91c6-1fd2909178c9.png)

**Comment by TerryCavanagh** [comment]
Fixed!
