### ISSUE TITLE
If Curse activates when playing the Jester, the next card from your deck does not come in until you play another card.

### ISSUE THREAD

**Issue by dragonsbutalsorabbits** [TerryCavanagh/diceydungeons.com#1192]
When playing as the Jester, if a Curse goes off and takes your card away, that slot remains empty. The next card in your deck does not come in to fill the empty slot, unless you play one of your remaining available cards. Then the deck fills both empty slots. I assume this is not working as intended for Curse consequences?

The picture shows the empty slot that doesn't get filled in the Jester's hand after a card is removed by Curse.
![Dicey Dungeons Aug 15 07-29-20PM](https://user-images.githubusercontent.com/54158525/63139496-55144400-bf93-11e9-9560-263be9f5d8e8.png)

**Comment by grebnetiew** [comment]
Can reproduce in v1.3, great synergy with the "curse 1 every turn" bonus rule ;)

**Comment by TerryCavanagh** [comment]
This one was fixed in v1.8 I think!
