### ISSUE TITLE
Chest keeps giving reward over and over again.

### ISSUE THREAD

**Issue by dragonsbutalsorabbits** [TerryCavanagh/diceydungeons.com#1193]
Playing as the Jester, I found a chest containing a Spatula. I ignored it and came back later and decided to pick it up, and the chest did not disappear. I tried opening it again, and it gave me another. And another. Possibly an infinitely rewarding chest? At last my quest for infinite kitchen implements is complete.

In case it matters, in between checking the chest the first time and the second time, I went to the shop and defeated an enemy.
![Dicey Dungeons Aug 15 09-01-55PM](https://user-images.githubusercontent.com/54158525/63142803-26509a80-bfa0-11e9-8f5e-3c58879715d8.png)
![Dicey Dungeons Aug 15 09-02-01PM](https://user-images.githubusercontent.com/54158525/63142804-2781c780-bfa0-11e9-8301-6e0a5fbd4d4d.png)

**Comment by dragonsbutalsorabbits** [comment]
Update: after it gave me the fourth spatula, the chest disappeared.

**Comment by TerryCavanagh** [comment]
This is an amazing bug! Ahh!

Thanks for the report - gonna figure it out for today's patch!

**Comment by TerryCavanagh** [comment]
Fixed!
