### ISSUE TITLE
Lojinx not working correctly.

### ISSUE THREAD

**Issue by dragonsbutalsorabbits** [TerryCavanagh/diceydungeons.com#1194]
Playing as the Jester in the Parallel World. Lojinx text says, "Do 2 damage for each jinx, then return the dice."

At the start of the fights, I put 3 different instances of Slapsies jinxes on the enemy and then cast Lojinx, but Lojinx did no damage.

Later in the same fight, I had 2 different instances of Slapsies jinxes on the enemy, and cast Lojinx, and Lojinx did only 2 damage.

Something seems to be wrong with the way Lojinx is counting jinxes.

Before and after casting Lojinx: 
![Dicey Dungeons Aug 15 11-24-06PM](https://user-images.githubusercontent.com/54158525/63147736-e98e9e80-bfb3-11e9-8246-64af2335c9c9.png)
![Dicey Dungeons Aug 15 11-24-15PM](https://user-images.githubusercontent.com/54158525/63147743-ec898f00-bfb3-11e9-8551-350eaf6d43a4.png)

**Comment by TerryCavanagh** [comment]
Oh, this one has been fixed for a while! Closing.
