### ISSUE TITLE
combat5 doesn't loop well

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1197]
https://i.frogbox.es/lv7

Might be too late for revisions given how the bandcamp album has already dropped 🤷‍♂

**Comment by muizzsiddique** [comment]
To me it sounds seamless.

**Comment by ncrecc** [comment]
Notice how the crowd cheering cuts out.

**Comment by TerryCavanagh** [comment]
I think Niamh has no plans to change this one. Closing!
