### ISSUE TITLE
Guardian boss' self-damage lowered by player's block

### ISSUE THREAD

**Issue by PidgeonRat** [TerryCavanagh/diceydungeons.com#120]
Not sure if it's a bug or working as intended, but the Guardian's earthquake attack will only damage itself for the amount it lowers the player's health. Blocked damage is mitigated for both the player and the boss. This seems to go against the text description of the attack.

**Comment by TerryCavanagh** [comment]
Opps! Thanks for the report!

**Comment by TerryCavanagh** [comment]
Fixed for v0.6.
