### ISSUE TITLE
Multiple stacks of Fury don't seem to work correctly with "Maintain Fury" cards

### ISSUE THREAD

**Issue by dragonsbutalsorabbits** [TerryCavanagh/diceydungeons.com#1200]
I'm currently in Parallel Universe as the Jester, if that affects things. I used Fury? to double cast Arf Arf Arf, which gave me two stacks of Fury the next turn.

With Fury 2, I expected any of the "Maintain Fury" cards to cast three times instead of twice. But when I used one (Ruff Ruff Ruff), it still cast twice, like if I only had Fury 1. (It did properly maintain the Fury stacks, though.)

When I next cast an ability that did not "Maintain Fury" (it was Duplicate), the ability cast three times. So, it seems like multiple stacks of Fury do increase the number of casts of an ability usually, but not in the case of the "Maintain Fury" cards.

**Comment by TerryCavanagh** [comment]
Fixed in v2.1!
