### ISSUE TITLE
In Bonus Round, Crystalina getting the Pirate rule breaks it

### ISSUE THREAD

**Issue by dragonsbutalsorabbits** [TerryCavanagh/diceydungeons.com#1203]
In Bonus Round, the Pirate rule gives the player and enemies the "Re-equip" buff. Something seemed to break when Crystalina unlocked the first crystal weapon, like the action of unlocking re-equipped the locked version? Then every Crystalina turn after that, it was like they would swap between two sets of cards that they had. Their proper set of four on one screen, then a set of two or three on the other. (I wish I had screenshotted this, but they swapped on and off the smaller set of abilities quickly). I'm not entirely sure what happened, unfortunately, but they either had way too many abilities or it was just visually breaking.

**Comment by TerryCavanagh** [comment]
Fixed!
