### ISSUE TITLE
Super Enemy - Alchemist

### ISSUE THREAD

**Issue by FallenSystm** [TerryCavanagh/diceydungeons.com#1205]
The game freezes with one dice remaining for the enemy when the super enemy alchemist turns into a bear.  It seems to always happen on turn two.  I am shocking and poisoning the bear if that helps.  I have tried to fight other enemies before doing the fight and the same issue exists.

Only option becomes closing the game.

**Comment by KyleTheScientist** [comment]
It seems like the bear is trying to put a dice in the alchemist's original equipment and waits for that action to go through indefinitely, since the dice that the bear was trying to use lerped to the wrong location.

**Comment by billjamesdev** [comment]
Bump... this is still happening in v1.6.1 Halloween Special that I installed from Steam this month.

**Comment by ncrecc** [comment]
Confirmed fixed for v1.7
![image](https://user-images.githubusercontent.com/11216597/73316165-236cfd80-4200-11ea-9818-6c53052710f7.png)
