### ISSUE TITLE
Dice catching fire without reason (custom rules)

### ISSUE THREAD

**Issue by minirop** [TerryCavanagh/diceydungeons.com#1212]
I was playing episode 6 of the warrior and had 3 rules active: buster, hothead and bully. (burning dice do 5 damages, auto 6 are set on fire, all enemies have a rock)
When I or enemies got 6s at the start of a turn, they were set on fire (normal), but some dice I got by rerolling them were also set on fire without any reason. (2 "3s", 1 "2" and 1 "6").

**Comment by tjm35** [comment]
I'm also seeing this same behavior with only the Hothead rule active.

**Comment by samueldcorbin** [comment]
Saw the same thing with Hothead on Jester bonus round. A gumball machine given a 2 resulted in a flaming 5, a cauldron produced a flaming 2, a duplicated 5 produced two flaming 5s, and an enemy sorceress cauldron produced a flaming 2 for her as well.

**Comment by TerryCavanagh** [comment]
Oh, I think this has been fixed for a while - I completely rewrote the Hothead rule at some point. Closing!
