### ISSUE TITLE
Items in inventory putting themselves in random slots in Inventor Episode 2.

### ISSUE THREAD

**Issue by dragonsbutalsorabbits** [TerryCavanagh/diceydungeons.com#1217]
This doesn't happen for every character, but I'm currently on episode 2 as the Inventor, and every time I go in and out of the Equipment menu on the map screen, the items in my inventory change what slots they're in. They also change slots between looking at them in the Equipment menu on the overworld map and entering battle. After a battle in this episode, of course two items get destroyed and changed to gadgets, but after opening a chest and entering a battle again without opening the Equipment menu, the other items i had kept still changed spots.

I don't mind most of the time as the inventor, since the items change over so quickly, but i've been saving the hammer+s, and I'm like them at least to stay in the same slots.

Screenshot 1: initial order of items in inventory.
![Dicey Dungeons Aug 17 03-56-10PM](https://user-images.githubusercontent.com/54158525/63218118-9b3ee400-c108-11e9-8646-bf615b5c1b29.png)

Screenshot 2: order of items in the inventory, after returning to the overworld map and re-opening the Equipment menu.
![Dicey Dungeons Aug 17 03-56-19PM](https://user-images.githubusercontent.com/54158525/63218123-a5f97900-c108-11e9-9cab-e429c967c9b0.png)

Screenshot 3: order of items after closing the Equipment menu and entering a battle
![Dicey Dungeons Aug 17 04-05-43PM](https://user-images.githubusercontent.com/54158525/63218138-0c7e9700-c109-11e9-8648-b55a6c377573.png)

Screenshot 4: order of items after completing screenshot 3's battle, opening a chest, and entering another battle without opening the Equipment menu.
![Dicey Dungeons Aug 17 04-10-19PM](https://user-images.githubusercontent.com/54158525/63218158-9b8baf00-c109-11e9-9320-c80a36bf2064.png)

**Comment by TerryCavanagh** [comment]
This one was finally fixed in a recent update!
