### ISSUE TITLE
eq.changeslots() with COUNTDOWN removes all slots

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1218]
Probably should do nothing instead of removing all slots.
`Equipment.hx:775: Error: Cannot change slots on Run away! to COUNTDOWN, not supported yet.`
![image](https://user-images.githubusercontent.com/26709843/63218201-9eb98600-c16f-11e9-8e9f-2b38f19153b0.png)

**Comment by TerryCavanagh** [comment]
COUNTDOWN is now supported with `eq.changeslots()` (since v1.9), closing!
