### ISSUE TITLE
"Complete Bonus Round in Hard Mode" challenge awarded on completion of normal mode bonus round

### ISSUE THREAD

**Issue by tjm35** [TerryCavanagh/diceydungeons.com#1219]
On completing my first run of a Bonus Round I was awarded the Beatrice Challenge ("Complete Bonus Round in Hard Mode"), even though the run was not on Hard Mode - since it was my first clear of a bonus round I hadn't even unlocked hard mode yet.

Character: Thief
Starting Equipment: Nunchaku+Master Key
Boss: Beatrice

Version: v1.0.2. 14-08-2019

**Comment by TerryCavanagh** [comment]
Fixed!
