### ISSUE TITLE
Bugs with Sticky Hands [v1.1]

### ISSUE THREAD

**Issue by mellodillo** [TerryCavanagh/diceydungeons.com#1220]
The following bugs occurred during my Thief Elimination Round:
- If Sticky Hands flees, his battle theme keeps playing on the map screen.
- Sometimes, Sticky Hands doesn't use a dice to Run Away.

**Comment by egramatikovska** [comment]
Build number v1.12 | 2021-04-09 15:52:51

The same issue occurs on the Android version. If Sticky Hands flees, the battle theme audio continues in the dungeon.

Logfile:
[Sticky Hands music.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/6358069/Sticky.Hands.music.txt)

**Comment by TerryCavanagh** [comment]
Fixed!
