### ISSUE TITLE
Locked dice status effect on robot is broken

### ISSUE THREAD

**Issue by jrsun** [TerryCavanagh/diceydungeons.com#1225]
When receiving 2 Locked status on the robot, only the first calculated dice is locked. Subsequent dice are available to throw. First 2 dice should be locked.

**Comment by jrsun** [comment]
This was in the second episode (no duplicate dice allowed)

**Comment by findersjeepers** [comment]
Also encountered in the third episode, You Choose You Lose: https://youtu.be/wz-uGeJT-6I?t=545

**Comment by TerryCavanagh** [comment]
Fixed in v1.11!
