### ISSUE TITLE
Infinite upgrades and apples

### ISSUE THREAD

**Issue by zording** [TerryCavanagh/diceydungeons.com#1226]
Infinite upgrade bug still there after update
Found same can be done with apples whilst playing the (pretty amazing) finale as Warrior today 
Also on finale any chance you could add in an option to skip pre and post cutscenes on the finale for repeat play throughs. Whilst they’re awesome the first few times It gets a bit wearing clicking through after that.

**Comment by TerryCavanagh** [comment]
Fixed!
