### ISSUE TITLE
Crash - Robot episode 3 vs Copycat

### ISSUE THREAD

**Issue by bonnermann** [TerryCavanagh/diceydungeons.com#1228]
Currently playing Robot episode 3 (You choose, you lose) on version 1.1. When I fight Copycat and finish my first turn, the screen transition to Copycat's screen happens, then the game hangs for a split second before crashing. Can't seem to find an error log, save game is attached. Please let me know if you need anything else.

[diceydungeons.zip](https://github.com/TerryCavanagh/diceydungeons.com/files/3513616/diceydungeons.zip)

**Comment by bonnermann** [comment]
Fixed in 17-08-2019

**Comment by bonnermann** [comment]
Happens again in my current game on version 1.2 / 21-08-2019

[diceydungeons.zip](https://github.com/TerryCavanagh/diceydungeons.com/files/3536944/diceydungeons.zip)

**Comment by TerryCavanagh** [comment]
Fixed in v1.3! Thank you!
