### ISSUE TITLE
Compression Errors has different level up rewards

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1229]
![image](https://user-images.githubusercontent.com/32357485/63231077-366db180-c20e-11e9-9fe3-23600da08bb4.png)

This seems like a holdover from No Going Back - shouldn't the rewards be the default Heat Sink / Increment?

**Comment by TerryCavanagh** [comment]
Whoops, thanks for noticing! Fixed.
