### ISSUE TITLE
Equipment grid can be left empty by mistake (new player issue)

### ISSUE THREAD

**Issue by iestynne** [TerryCavanagh/diceydungeons.com#1233]
My brother in law just started playing and ran into an unfortunate situation:
 - he played through the first level, up to the Jester first
 - when the prompt told him about changing his loadout, he was confused by that screen and dragged everything across to the backpack... I think he thought he was equipping instead of unequipping
 - he thus ended up fighting the Jester with no cards except Combat Roll... :)
 - once he realized what happened, he quit to title (I don't think there was a flee option for this fight) and when he came back in he had to go through the intro dialog, tutorial and first level again from the start... he was pretty mad about that

Maybe you can add something to warn a player if they have unused equip slots?

**Comment by TerryCavanagh** [comment]
Fixed for v1.10!
