### ISSUE TITLE
Jester crash when using the item from black market in parallel universe.

### ISSUE THREAD

**Issue by kuluszero** [TerryCavanagh/diceydungeons.com#1234]
crashed:	2019-08-19 01:05:56
duration:	00:02:43
error:		Null Object Reference
stack:
states.Combat.repeatlastaction (states/Combat.hx line 1595)
elements.Equipment.doequipmentaction (elements/Equipment.hx line 2138)
Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
motion.actuators.GenericActuator.complete (motion/actuators/GenericActuator.hx line 155)
motion.actuators.SimpleActuator.update (motion/actuators/SimpleActuator.hx line 501)
motion.actuators.SimpleActuator.stage_onEnterFrame (motion/actuators/SimpleActuator.hx line 579)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

**Comment by ncrecc** [comment]
Likely #1114

**Comment by TerryCavanagh** [comment]
Yep, can confirm that this is fixed in v1.9!
