### ISSUE TITLE
Jester bonus round witch doesn't clear

### ISSUE THREAD

**Issue by samueldcorbin** [TerryCavanagh/diceydungeons.com#1236]
Jester bonus round witch sometimes persists forever instead of clearing.

This may be a result of having it active while winning, or maybe having it active while winning via Slapsies damage.

When I went into the next fight, the witch was still active and I still had a visible 4th card, and it remained for three turns until I got another witch, used it, and ended that turn.

**Comment by samueldcorbin** [comment]
It appears that this occurs whenever the player wins a round with the witch active.

**Comment by TerryCavanagh** [comment]
This is fixed for v1.9! Thanks for the bug report.
