### ISSUE TITLE
Clicking on a die in the second row unintentionally activates nearby equipment

### ISSUE THREAD

**Issue by PidgeonRat** [TerryCavanagh/diceydungeons.com#124]
A die in the second row is so close to nearby equipment that a single click will move the die to the equipment and activate it. For example in the screenshot below I would want to click on the die once and then click on poison needle, but after my first click the die moves to bandage and activates.

The game thinks I'm dragging a die close to the bandage when my intention is to click on the die once to use it somewhere else.

![terrydiesnap](https://user-images.githubusercontent.com/38002044/39091641-f7bc0b96-45ac-11e8-9558-98425b53aecf.png)

**Comment by TerryCavanagh** [comment]
Fixed!

**Comment by FelixNemis** [comment]
This is still happening in 0.6.1

**Comment by TerryCavanagh** [comment]
Ah, yep, looks like it is. Reopening!

**Comment by TerryCavanagh** [comment]
I just checked, and this no longer happens - hasn't for a long time I think. Closing!
