### ISSUE TITLE
Poison tool-tip does not update at start player turn/end opponent turn

### ISSUE THREAD

**Issue by mvanvelzen** [TerryCavanagh/diceydungeons.com#1243]
To clarify the objects I'll be talking about:

Poison UI element: (shows how much poison is on a player/enemy)
Poison tool-tip: (the mouse-over text-box that appears when you hover the mouse over the poison UI element)

The bug:
I've found nothing wrong with the poison UI element, it seems to update correctly. The problem is with the poison tool-tip. It seems to update it's displayed damage values correctly when APPLYING poison, but the tool tip does not update it's displayed damage values when an enemy's turn ends. It keeps the values from last turn.

Example:
I have just applied the 4th poison to an enemy. The poison UI element correctly says '4 poison' and the poison tool-tip correctly says 'this will take 4 poison damage at the start of the turn'. 
I pass the turn. 
The enemy correctly takes 4 damage. 
It's my turn.
The poison UI element correctly says 3 poison, but the poision tool-tip still states the enemy will receive 4 damage.

I hope I've explained correctly and clearly what's going on! Loving the game so far, good luck with further development!

**Comment by TerryCavanagh** [comment]
Fixed in v2.1.
