### ISSUE TITLE
Bonus Round Cowboy Rule

### ISSUE THREAD

**Issue by zording** [TerryCavanagh/diceydungeons.com#1244]
Playing bonus round as Inventor in hard mode. Cowboy’s rule is ‘Enemies always roll a 6’ Enemies aren’t always rolling a six however since that rule applied I am consistently rolling 4 sixes every first turn (either linked or I’m very lucky) Other rules I have are Snowman, Vacuum and Alchemist (got alchemist after cowboy rule)

**Comment by Sophira** [comment]
Can confirm that this is still the case in v1.2. When the Cowboy rule is applied, the player rolls 6s for every dice on the first turn.

**Comment by TerryCavanagh** [comment]
This one's fixed!
