### ISSUE TITLE
Bonus Round Jester

### ISSUE THREAD

**Issue by zording** [TerryCavanagh/diceydungeons.com#1245]
Playing hard mode as Jester. Have Scathach rule of Cursed at the start of each turn. When cursed card disappears cards don’t move along to bring a new card on screen. Particularly annoying against gargoyle as he frequently locks 2 dice so the third dice I have disappears with the cursed card and even with snap ready unless I have matching cards with the two remaining I can’t do anything as even if the next card is a match it doesn’t move on screen - frustrating after several turns 
Also have Pirate rule of Both you and your enemies start each fight with a re-equip next - possible that’s causing the issue as the cursed card doesn’t re-equip

**Comment by zording** [comment]
Forgot to say the cards move along fine once another card is used, the next two will move into play so I have three again

**Comment by TerryCavanagh** [comment]
Fixed!
