### ISSUE TITLE
Aurora's attacks need upgraded/downgraded versions

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1246]
Hurricane, Thunder Storm, Heatwave and Snowstorm all need upgraded/downgraded versions.

**Comment by omor1** [comment]
Needed for elimination round. Possibly related to #1338 and #1178, since Aurora can change equipment throughout the battle.

**Comment by JuniorUdale** [comment]
Fixed in 1.3!

**Comment by omor1** [comment]
Is v1.3 released? I commented because I had literally just experienced it in v1.2 (via Steam).
