### ISSUE TITLE
Sneezy Skips Turn

### ISSUE THREAD

**Issue by samueldcorbin** [TerryCavanagh/diceydungeons.com#1252]
While playing the thief bonus round (not hard mode), I had the modifier that makes both you and the enemy get a re-use of the first tool you use each fight. Sneezy rolled a 6, and then simply skipped his turn instead of using it.

**Comment by aloobyalordant** [comment]
Just came across a similar bug while playing Robot bonus round (also not hard mode). Also had the re-equip rule; Crystal and Kraken both skipped their first turns.

**Comment by TerryCavanagh** [comment]
This one was *finally* fixed in v1.9, phew!
