### ISSUE TITLE
[testing branch] Some open issues with SDF font rendering

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1253]
Some positioning issues that have been reported with the SDF fonts:

Text position for EXP after combat:
![image](https://user-images.githubusercontent.com/2874150/63347200-8e133680-c34e-11e9-968c-c31d27a325cb.png)

compared to the old version:
![image](https://user-images.githubusercontent.com/2874150/63347230-9b302580-c34e-11e9-8f7c-9f05d174821a.png)

Monster names in challenge screen:
![image](https://user-images.githubusercontent.com/2874150/63347280-ae42f580-c34e-11e9-9345-816b652f31b1.png)

compared to the old version:
![image](https://user-images.githubusercontent.com/2874150/63347292-b56a0380-c34e-11e9-8b22-cffa646635f4.png)

Character name in Episode 6's status bar overlaps experience display (but this was maybe also an issue in the old version, not sure)
![image](https://user-images.githubusercontent.com/2874150/63347351-d6325900-c34e-11e9-9ea1-8533d7df3e82.png)

Bracketed text is not centred in cards (though, this might be due to a spreadsheet error, and not the font code:)
![image](https://user-images.githubusercontent.com/2874150/63347412-f3672780-c34e-11e9-9b81-b878300180b6.png)

When East Asian text switches to english text mid string on cards (e.g. when using numbers), the english text is offset too low, and sometimes doesn't seem to have enough margin space, like these examples:
![image](https://user-images.githubusercontent.com/2874150/63347544-39bc8680-c34f-11e9-8e94-088a29b44b1b.png)
![image](https://user-images.githubusercontent.com/2874150/63347593-5062dd80-c34f-11e9-966e-6551ac342a50.png)

However in other cases it appears fine, so maybe I'm just imagining things, I dunno!
![image](https://user-images.githubusercontent.com/2874150/63347667-81431280-c34f-11e9-9b68-7adac29c1072.png)

**Comment by TerryCavanagh** [comment]
Update on the text positions around symbols:

![image](https://user-images.githubusercontent.com/2874150/63349451-5bb80800-c353-11e9-9113-041e57c9605f.png)

![image](https://user-images.githubusercontent.com/2874150/63349463-61155280-c353-11e9-84e3-9fe2f9726e5a.png)

**Comment by mrcdk** [comment]
Fixed.
