### ISSUE TITLE
Robot: graphical issue when confused cards error out

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1258]
The error animation loops for some reason:
![Screenshot 2019-08-20 at 18 02 07](https://user-images.githubusercontent.com/48322734/63367874-a5651a80-c374-11e9-8f9e-fb00c9d6e52f.png)
https://clips.twitch.tv/AntsyComfortableAxeDxCat

**Comment by TerryCavanagh** [comment]
This was fixed at some point, I think!
