### ISSUE TITLE
Bonus Round hot head rule

### ISSUE THREAD

**Issue by yogmoth** [TerryCavanagh/diceydungeons.com#1261]
Was having a lot of issues with bonus round rules, the hot hot rule would randomly light dice on fire after re-rolling them with warrior, even if they weren't 6's and random dice would get lit on fire when they weren't 6's. Also when I applied freeze, it wouldn't freeze the 6's that got rolled since they were already lit on fire.

**Comment by TerryCavanagh** [comment]
Fixed!
