### ISSUE TITLE
Bonus Round Rose Rule wording is very unclear

### ISSUE THREAD

**Issue by dragonsbutalsorabbits** [TerryCavanagh/diceydungeons.com#1262]
In the Bonus Round, the Rose rule wording is "Both you and your enemies do +1 extra damage with each attack."

I expected that it would just add +1 damage to all attacks - although I could also see it adding more and more damage with each consecutive attack.

But in practice, it does neither of these things. Instead, it gives me and the enemy the Extra buff - "Do 1 extra damage with each attack this turn." and on each turn, the buff increments by 1.

So at the start of the battle, the enemy and I both have Extra 1. I take my turn, and then at the start of the enemy's turn, their Extra buff increments, so on their first turn, they have Extra 2. Then when my next turn starts, my buff increments so now I'm also at Extra 2. This implementation is confusing (and possibly not intended?) and is not at all what I expected from the wording of the rule.

**Comment by hunky-dory** [comment]
![Screenshot 2019-08-26 at 23 00 14](https://user-images.githubusercontent.com/48322734/63726530-727bc480-c855-11e9-8948-92287cb8e041.png)
The Rose remix tooltip is incrementing every turn (though the extra damage remains at +1 each turn)

**Comment by TerryCavanagh** [comment]
Fixed!
