### ISSUE TITLE
Sticky Hands as opponent in bonus round

### ISSUE THREAD

**Issue by zording** [TerryCavanagh/diceydungeons.com#1264]
All rules that apply at start of turn or battle apply twice against Sticky Hands. ie Snowman’s rule of one dice being frozen at the start of every turn means first turn against Sticky Hands 2 dice freeze, same for blind/poison rules and others assume its to do with Sticky Hands taking his turn first

**Comment by TerryCavanagh** [comment]
Fixed for v2.1.
