### ISSUE TITLE
Recurring Hard Crash Using Frog to Encounter Lady Luck 

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#1265]
Crashes every time on resuming encounter with Lady Luck backstage. 

Lady Luck speaks, camera pans down and Frog's text bubble appears but before text populates the game crashes.

![crash](https://user-images.githubusercontent.com/40739964/63451159-8e283a80-c411-11e9-927d-d257e68edc1e.jpg)

`--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v1.1 / 0.11.0 (mod API)
sess. ID:	dicey_dungeons_2019-08-21_12'36'03
started:	2019-08-21 12:36:03
--------------------------------------
crashed:	2019-08-21 12:37:25
duration:	00:01:22
error:		ERROR in callscenemethod(Combat,update) static : Error: cannot find image "characters/frog/charicon_frog_1080", stack = 
Called from displayobjects.HaxegonSprite.addimageframe (displayobjects/HaxegonSprite.hx line 53)
Called from displayobjects.HaxegonSprite.new (displayobjects/HaxegonSprite.hx line 37)
Called from displayobjects.DrawImage.show (displayobjects/DrawImage.hx line 80)
Called from displayobjects.Textbox.internaldisplay (displayobjects/Textbox.hx line 166)
Called from displayobjects.Textbox.displaytitle (displayobjects/Textbox.hx line 61)
Called from elements.Fighter.showfirstandlastwords (elements/Fighter.hx line 2211)
Called from states.Combat.update (states/Combat.hx line 612)
Called from Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 268)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

`

**Comment by mrcdk** [comment]
Fixed.
