### ISSUE TITLE
Furied? Square Pair still gives dice the next round from Wrecking Ball even though Unavailable.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#1266]
Thief PU.
Dramatic Entrance, Square Pair+  and Wrecking Ball.
Turn 1 use a 4 in Square Pair+  yielding 4  4's.
Turn 2 put a 4 in wrecking ball and Square Pair+ still gives 2 4's back even though it is unavailable.

Edit: [Same as boostcountdowns() affects Unavailable items ](https://github.com/TerryCavanagh/diceydungeonsbeta/issues/175)

**Comment by ncrecc** [comment]
Fixed, see #1898
