### ISSUE TITLE
Aoife's Sabre upgrades and downgrades... weirdly

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1267]
![image](https://user-images.githubusercontent.com/32357485/63465254-cacb5480-c458-11e9-843c-6e310742ee82.png)

Surely the upgrade should let Sabre take any value, and the downgrade should just bash with shield (dealing no additional damage)?

**Comment by TerryCavanagh** [comment]
Yep, good call! Fixed.
