### ISSUE TITLE
No sound on fresh install. Crashes on first combat.

### ISSUE THREAD

**Issue by AiSard** [TerryCavanagh/diceydungeons.com#1268]
![diceydungeons_2019-08-22_04-31-06](https://user-images.githubusercontent.com/33284312/63470214-397ad300-c496-11e9-9dbd-9a10f6e7107f.png)

On fresh install, game has no sound and crashes with the above message as you enter the first fight with the Space Marine.

![image](https://user-images.githubusercontent.com/33284312/63470314-86f74000-c496-11e9-9462-21411d6a9e72.png)

Doesn't seem to generate any error logs, but according to the timestamps, these error logs came when the game was installing? Last log attached.
[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/3527409/_error.txt)

Things tried:
Verify game integrity
Uninstall and reinstall
Run as Admin
fullscreen/windowed

**Comment by TerryCavanagh** [comment]
Heya, thanks for the bug report and error log - this one is very serious, so we're going to look into it ASAP. Hopefully we'll have it figured out for the next patch, which will be sometime in the next week!

**Comment by AiSard** [comment]
fixed in v1.2 :)
