### ISSUE TITLE
Crystalina gaining "Re-Equip" blessing stalling turn indefinitely

### ISSUE THREAD

**Issue by Lizard953694** [TerryCavanagh/diceydungeons.com#1270]
After using the power crystal to gain re-equip, Crystalina used Crystallize to gain a weapon and keep the Crystallize card itself, leaving her with 5 cards, one of which appears to be off-screen. She then proceeded to use 2 cards, then wait forever with a single die remaining.

Edit: Was able to exit and continue run from before the fight
![DiceyDungeonsMyTurnForever](https://user-images.githubusercontent.com/54388347/63486647-091f3e80-c46e-11e9-81b3-24838af2128a.png)

**Comment by TerryCavanagh** [comment]
Fixed!
