### ISSUE TITLE
Equipment is rearranged in battle

### ISSUE THREAD

**Issue by alastajj** [TerryCavanagh/diceydungeons.com#1271]
When you customize the order of your items, the game then rejects your choices and changes them at the start of a battle.

Notice in the screenshots how I've placed the damage items to the left, but then in battle the order is gone:

Before battle:

![image](https://user-images.githubusercontent.com/5744908/63501845-b302d780-c50f-11e9-93be-992eea96cddb.png)

During battle:

![image](https://user-images.githubusercontent.com/5744908/63501862-bac27c00-c50f-11e9-93a9-2cec688954ef.png)

**Comment by TerryCavanagh** [comment]
Fixed in v1.8!
