### ISSUE TITLE
Hothead and Warlock together in Bonus Round make your 6s Burn, instead of Burn?

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1279]
Should Hothead inflict the PU status on your 6s, or not?

**Comment by kortemaki** [comment]
Interesting interaction effect with Frozen? is that the player (or enemy) will suffer Burn damage from rolling a 6 when Frozen? triggers and decrements it to 5.

**Comment by TerryCavanagh** [comment]
Ok, fixed in v1.11!
