### ISSUE TITLE
The list of completed episodes display is incorrect

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#1281]
The normal behaviour is that you can see the grid with the list of episodes on the right of the character in the character choice tab only when you have completed at least the first episode for a given character. However, if I click on the list of challenges and go back to the character choice tab, here is what I get:

![IssueEpisodes](https://user-images.githubusercontent.com/8949232/63533757-bac17c80-c50d-11e9-9168-5bfd9ecf7747.png)

**Comment by TerryCavanagh** [comment]
Fixed!
