### ISSUE TITLE
Bronze Cauldron- 's text just says "Reusable"

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1283]
![image](https://user-images.githubusercontent.com/32357485/63544122-46420a00-c51c-11e9-8162-100a348ee7d2.png)

Simple spreadsheet error - change `Do [sword]1 damage` to `Do [sword]1 damage|`

**Comment by TerryCavanagh** [comment]
Fixed at last!

![image](https://user-images.githubusercontent.com/2874150/94900119-fafa7900-04db-11eb-941e-eafac142f466.png)
