### ISSUE TITLE
Break silence for inventor with one die

### ISSUE THREAD

**Issue by njtrotter** [TerryCavanagh/diceydungeons.com#1288]
Background inventor getting silenced (in this case by loud bird, which I got like 20 turns of confirmation of this bug because I only brought one attack...lots of dodging)

Two issues with this: sometimes dice wouldn't snap into place easily (just repeatedly fiddled with it to eventually snap) and secondly, when I was fiddling with it, sometimes it would snap to the second slot and only take one dice to break the silence

**Comment by TerryCavanagh** [comment]
Fixed in v1.7!
