### ISSUE TITLE
further rosepetal thoughts

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#129]
An upgrade could make rosepetal gear require odds. This would leave the mystery intact and better teach the symbolic meaning than outright explaining the working values. It'd also make the simple rose AI actually stronger in hard mode (not able to dump useless dice into cards). It essentially doubles chance of success (for random dice) from 1/3rd to 2/3rd. However still a useless upgrade for players in the know. And possibly looking like a useless upgrade for players who don't know as well (odds being generally worse than normal slots).

An upgarde could add a maximum slot (3/4). This would make the upgrade universally useful, obviously appear useful as an upgrade, but might make things a little too powerful (the staff poison at least).

An upgrade could make the gear start to do something with a 1. Putting a 1 into a rosepetal staff+ could for example randomly reroll the dice to a 3/5 and return the staff for another use. This increases chances of success from 1/3rd to 1/2 and doubles as bumping utility on top. You can throw several 1s in there before finally using it to attack. (No explanation? This blooming function is a new mystery! Hard sell on the upgrade screen though. Upgraded cards may need to look truly special/shiny/different for anyone to invest without knowing the benefits first.)

An inverted *wilting* rosepetal card of some kind could be fun (not as an upgrade), counting the missing petals. In other words a 1 acts like a 5.

Also for now I'm really happy having players learn it from the rose enemy. Since they get to observe it without expending dice for testing. Even more so with the thief, where one can immediately try to copy a successful action.

**Comment by TerryCavanagh** [comment]
Heya! So, for a resolution on this:

I decided to make the rosepetal upgrades require odds, as a little hint. I'm also going to be making these items rarer by putting the rose enemy in a "rare enemy" bucket and making the rosepetal equipment a rarer drop for warrior. I think that's a decent way to handle this - having the petals around the rose thing in the game, but be very uncommon, and also authentic to the game.

Thanks for writing up these thoughts!

**Comment by TerryCavanagh** [comment]
Rose is now back in the game! Closing!
