### ISSUE TITLE
Precious Egg can get duplicated in Bonus Round with Re-Equip Next

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1290]
![image](https://user-images.githubusercontent.com/32357485/63558147-9aacb000-c543-11e9-9d54-4b1efaa15497.png)
For example, if you get the Pirate rule, this can happen

**Comment by zording** [comment]
I opened an issue yesterday re Keymaster being confused with the Pirate rule and not taking his first turn properly,  now seeing this I think it may be connected as pretty sure one of his key blades duplicated so he had seven equipment not 6.

**Comment by mrwebed** [comment]
![20200725185924_1](https://user-images.githubusercontent.com/1401484/88463200-01032680-cea9-11ea-9a6a-c9727f87532b.jpg)

This issue still exists, as stated above, the Wizzard didn't take their first turn, and duplicating the egg has broken the robots CPU/Dice.

I fled the fight, and the duplicated egg has overwritten a differnet peice of equipment:
![20200725190301_1](https://user-images.githubusercontent.com/1401484/88463286-8b4b8a80-cea9-11ea-9bb3-e95c225ebb8b.jpg)

Now refighting the wizzard has fixed the CPU/Dice:
![20200725190430_1](https://user-images.githubusercontent.com/1401484/88463332-ca79db80-cea9-11ea-9c8b-0a531ddbe997.jpg)

Fight proceeded as normal and the wizzard took his first turn as normal.

**Comment by TerryCavanagh** [comment]
Fixed this for v1.9 - there's a new equipment tag, "cannotreuse", which can be used to ignore the re-equip next status effect. (This should fix a number of related problems too, once I track them all down.)
