### ISSUE TITLE
When affected by a Parallel Universe curse, the "Ignite" skill only partially switches target

### ISSUE THREAD

**Issue by Sophira** [TerryCavanagh/diceydungeons.com#1292]
If you're playing a Parallel Universe run and you get cursed (equipment has a 50% chance of switching target), Ignite (needs doubles, inflict 1 burn, return both dice) will indeed inflict you with a burn and return two dice on the enemy's side of the screen, but you can pick up and drag these dice like normal and use them on your turn.

A proper reversal might be for the enemy to gain +2 dice on their next turn, perhaps?

**Comment by Sophira** [comment]
Ah, I should point out, this is in v1.2 of the game that I'm playing.

**Comment by TerryCavanagh** [comment]
Finally fixed this one! Thanks for the bug report!
