### ISSUE TITLE
French translation of Lament+ is the old version

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1293]
https://steamcommunity.com/app/861540/discussions/0/1639794651166089950/

"On the card "Lamentation", it is said a 6 will freeze 2 dices, but each time i use it with a 6, it only freeze one"

The old upgrade of Lament was "freeze 2 on 6", but it's been changed to just get a flat +2 damage. The french translation needs updating to the new version.

**Comment by TerryCavanagh** [comment]
This was actually even worse than that - regular Lament was mistakenly translated as freezing 2 dice! Fixed now.
