### ISSUE TITLE
Dice rolled by skills are not subject to countering

### ISSUE THREAD

**Issue by deluxeloy** [TerryCavanagh/diceydungeons.com#1297]
I used counterspell to counter sixes against a cowboy, since its abilities revolve around them, pun not intended. Imagine my frustration when my very first run came to a premature end as it proceeded to use the midnight thing, which bypassed my counterspell and allowed it to double tap and kill me on turn one of combat.

Not certain this is intended behaviour, but if it is, "roll 2 sixes" and "if the enemy rolls X" imply that this interaction should have gone differently. A simple rewording to "add 2 sixes" would suffice if that is the case.

![Screenshot 2019-08-24 12 56 35](https://user-images.githubusercontent.com/54471980/63636471-0e4bdb80-c670-11e9-8087-0e0d28b7b48b.png)

Note how in this screenshot, I managed to die despite the counter 6 debuff being active.

**Comment by TerryCavanagh** [comment]
This one's very important - will try to fix it asap.

**Comment by TerryCavanagh** [comment]
Fixed!
