### ISSUE TITLE
Skillcard disappearing if you (somehow) equip something into your skillcard slot?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#13]
![screenshot-2018-3-27_dicey_dungeons_0_2_23rd_march_2018](https://user-images.githubusercontent.com/2874150/37961794-229d2c88-31b1-11e8-8cec-317009f700f6.png)

(via *dunin*)

**Comment by PidgeonRat** [comment]
This bug also appears if a size 1x2 item extends into the skillcard slot.

![bugterry](https://user-images.githubusercontent.com/38002044/38193018-aeae9fd2-3624-11e8-85c1-dbe795a022e0.png)

**Comment by TerryCavanagh** [comment]
Alright, I THINK I fixed this one, but it's really finicky. Feel free to reopen if it reappears in v0.4.
