### ISSUE TITLE
Remove Overwhelm from Precious Egg+ pool

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1306]
With Overwhelm receiving a nerf to reign Kraken it, it's no longer a suitable reward.

**Comment by ncrecc** [comment]
With good dice manips I'd imagine it still being pretty powerful, though you'd have to center your build around making odds into evens.

**Comment by onetruepurple** [comment]
Almost certainly won't change by now (though it still sucks).
