### ISSUE TITLE
Parrying dagger does not lock dice gained during fury action

### ISSUE THREAD

**Issue by eriktheguy** [TerryCavanagh/diceydungeons.com#1308]
searched for issues involving parrying dagger but could not find any

Parrying Dagger locks dice that match []

This works properly against dice rolled during enemy turn, such as [6]s gained from midnight charm. However, if the enemy has fury and uses midnight charm, the first set of [6]s will be locked, but the second will not.

**Comment by TerryCavanagh** [comment]
Closed as duplicate.
