### ISSUE TITLE
Crystalina will not create a new item with 1 countdown remaining

### ISSUE THREAD

**Issue by Lizard953694** [TerryCavanagh/diceydungeons.com#1311]
When Crystalina has 3 Smokey Crystals and a Crystallize with 1 countdown remaining, they will frequently choose to end their turn even though they have 1 more die to finish Crystallizing and literally nothing else to do with it. They eventually did use Crystallize sometime after Turn 22, which became a Life Crystal, leaving them with no way of dealing damage and therefore being unable to defeat me.

Video: https://www.youtube.com/watch?v=iPMe8ETsfgI
![image](https://user-images.githubusercontent.com/54388347/63656287-880ac480-c757-11e9-8495-b2b9cf3e1feb.png)

**Comment by TerryCavanagh** [comment]
Planning to prevent this kind of situation by only allowing one of each type of crystal (separate issue for this somewhere else). Closing!
