### ISSUE TITLE
Very high CPU use facing Super Pirate

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1314]
Someone on twitter reported that their CPU fan goes into overdrive after a couple of seconds on super pirate, and locks up the game. Yikes!

(I've removed this super enemy from the game until I can investigate this further. They probably need a better super design anyway.)

**Comment by onetruepurple** [comment]
Related to the glow effect?

**Comment by TerryCavanagh** [comment]
Could be - they're one of the largest enemies in the game, which maybe causes a bit more work for the shader. Could be something else though!

**Comment by TerryCavanagh** [comment]
Adding a setting to disable filters for people who are having this problem for v1.9.
