### ISSUE TITLE
Bear Charge Upgrade not correct

### ISSUE THREAD

**Issue by njtrotter** [TerryCavanagh/diceydungeons.com#1315]
As bear, the bear charge upgrade (counter 5) bugged and became 10 without any effect. I had previously fought loud bird and entered fight with cowboy and it's counter was 10. Also bear charge says repeat next attack but it has repeated hibernate (not an attack) before

**Comment by njtrotter** [comment]
On a sidenote, the pickpocket item (I was playing thief in this run), is really underpowered--I've never really found a shop where I haven't had enough gold to buy what I want, sometimes buying out everything in the final shop just because. Underpowered in the sense that it provides no meaningful benefits (might as well be an empty chest)

**Comment by TerryCavanagh** [comment]
Ah, this one is fixed!
