### ISSUE TITLE
Confused State Showing information

### ISSUE THREAD

**Issue by njtrotter** [TerryCavanagh/diceydungeons.com#1316]
I don't know if its intentional, but while confused (items are obscured and swapped), the items counters, max/min die, and added damage remained visible. This occurred with bear fighting jester boss and made confusion completely irrelevant

**Comment by TerryCavanagh** [comment]
This is intentional - the idea is that confuse is more effective on some builds than others. If all of your equipment has different slot requirements, then you should be able to figure out what is what. I might obscure the numbers on the countdowns, though!
