### ISSUE TITLE
Suggestion: automatically trash dice below 1, and convert dice above 6 to 6 + leftovers

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1319]
This would allow you to ditch the if(d >= 6){ givedice([6| 1]); } workaround for Bump and automatically fix any potential issues with modded Vise Grip-like equipment

**Comment by JuniorUdale** [comment]
Dice over 6 are already converted properly I believe - see Spanner. ` if(d >= 1) givedice(d| ~combinedice~);`

**Comment by TerryCavanagh** [comment]
Oh, yep, I believe this is handled correctly by the game - some of the script functions just might be a little out of date. Let me know if you run into any cases where it's not working!
