### ISSUE TITLE
stolen fire staff does not trigger on 0

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#132]
![image](https://user-images.githubusercontent.com/3826749/39651223-56cb23d6-4feb-11e8-9b4a-f1580a194f6c.png)

It was activated with a 6 and a 4 after doing a bit of lock picking, duplicating and poison needle.

edit: it triggered upon pressing end turn ...

**Comment by TerryCavanagh** [comment]
Fixed!
