### ISSUE TITLE
remixrules.hx prevents Pirate from appearing with Warlock under the pretense that Pirate changes an effect to its PU version - it does not

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1320]
```Remix.preventclash(['Warlock', 'Banshee', 'Pirate']); //Don't have both Warlock and a remix that changes to PU rules```

Pirate modifier in remix.csv is:

```Rules.addplayerinnatestatus(REEQUIPNEXT[;] 1[;] true); Rules.addenemyinnatestatus(REEQUIPNEXT[;] 1[;] true); ```

**Comment by TerryCavanagh** [comment]
Good catch, thank you!
