### ISSUE TITLE
Stew Pot has no upgraded or weakened version

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1323]
Both the Upgrade and Weakened fields are empty in equipment.csv and there's also no entries for Upgraded/Weakened versions. Resulting in:
![Screenshot 2019-08-26 at 20 07 39](https://user-images.githubusercontent.com/48322734/63716245-6d128000-c83d-11e9-8c1f-3f6566939d83.png) ![Screenshot 2019-08-26 at 20 07 49](https://user-images.githubusercontent.com/48322734/63716244-6c79e980-c83d-11e9-9a3b-ca248178d969.png)

**Comment by TerryCavanagh** [comment]
Fixed!
