### ISSUE TITLE
The Rat King Bonus Round rule replaces enemies on reload

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1326]
https://steamcommunity.com/app/861540/discussions/0/1639794651181814206/

**Comment by JuniorUdale** [comment]
Tried reproducing this in 1.10 alpha and I can't - hopefully this has been fixed at some point?

**Comment by TerryCavanagh** [comment]
Oh, probably! Will close this then!
