### ISSUE TITLE
The Frog rule won't make sense with reduce size upgrades

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1327]
It makes all small equipment big, but some items become small on upgrade. Maybe they should be changed to Jester upgrades with Frog rule?

**Comment by TerryCavanagh** [comment]
Unfortunately, as funny as I find this rule, I don't think I'm going to go ahead with it - technical problems aside, it just causes too many game balance problems, I think.

**Comment by TerryCavanagh** [comment]
Yep, I ended up not implementing this, and in v1.9 Frog represents a different rule change.
