### ISSUE TITLE
Small misbehavior leading to loads of bugs: copycat copies your inventory *every turn*, rather than just on turn 1

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1329]
This causes all sorts of bugs:
- [Copycat can use "once per battle" items without permanently consuming them](https://github.com/TerryCavanagh/diceydungeons.com/issues/1103) - because each turn it restocks a fresh copy of the once-per-battle item that hasn't been used yet
- [Copycat is immune to burnt? dice](https://github.com/TerryCavanagh/diceydungeonsbeta/issues/296) - because each turn it restocks a fresh copy of whatever items it supposedly disabled
- [Copycat's countdowns reset every turn](https://github.com/TerryCavanagh/diceydungeonsbeta/issues/576) - because, again, the restocked cards are at their initial countdowns
- Something I just discovered: if you have Crystallize in your inventory, Copycat will never settle on a permanent weapon with Crystallize until you use Crystallize, then it will just have whatever weapon you got from Crystallize

**Comment by TerryCavanagh** [comment]
I've made this change in v1.3 - thank you!
