### ISSUE TITLE
<d6> in description looks all wobbly

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1330]
![image](https://user-images.githubusercontent.com/11216597/63878573-e0300980-c997-11e9-9d80-bff5f9880650.png)
Is there really no issue for this yet?

**Comment by TerryCavanagh** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/2874150/96826116-402a1f00-147a-11eb-92e0-6c377309382f.png)

**Comment by TerryCavanagh** [comment]
actually, just a few more tweaks -

![image](https://user-images.githubusercontent.com/2874150/96826451-ee35c900-147a-11eb-8d5d-0e6805c9c2aa.png)
