### ISSUE TITLE
Prevent class-specific bonus rules from being generated while you're a bear

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1331]
![image](https://user-images.githubusercontent.com/11216597/63879201-318cc880-c999-11e9-8cac-450361827a92.png)
Bonus round can still offer The Thief modifier ("switch to Finders Keepers rules") while you're a bear, but it does nothing. Not even the skillcard :(

**Comment by TerryCavanagh** [comment]
Ok! In v2.1, if you get the Thief rule while transformed into a Bear, you can keep the skillcard and continue to steal enemy equipment. It's rare, but the rules say what they say!
