### ISSUE TITLE
Consider changing how Pirate Hook works

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1333]
Currently it only works by giving you Re-Equip Next before activated; this leads to some strange behaviour in Parallel Universe. Why should it be different in that mode? While it gives Pirate a status effect, it doesn't actively show up for Pirate, and isn't obvious that something is happening to him.

Since there's no way to directly say "always give the vanilla version of re-equip next", perhaps how the item works should be changed (while keeping the "on 5, you can reuse this" theme)

**Comment by omor1** [comment]
Related to #1300

**Comment by TerryCavanagh** [comment]
Well, I've fixed the Parallel Universe bug now, so I think I'll keep it as is. With the Pirate changes I'm trying in v1.9, the behaviour here makes more sense anyway!
