### ISSUE TITLE
Mimic in Elimination Round doesn't upgrade Mystery Box on turn 2+

### ISSUE THREAD

**Issue by omor1** [TerryCavanagh/diceydungeons.com#1338]
It seems that equipment is only upgraded on the first turn. Since Mystery Box is consumed each turn, on subsequent turn it is only a Mystery Box instead of Mystery Box+.

Related to #1178.

**Comment by TerryCavanagh** [comment]
Hey - I believe this is fixed in v1.3? If I'm wrong, please let me know!

**Comment by omor1** [comment]
It's probably fixed then; I was still running v1.2 when I reported this (I should have noted so, but forgot to do so). See #1246—I was literally playing the game when v1.3 when live 😀.
