### ISSUE TITLE
"Back to Title" and abandon game should be considered a loss

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1339]
Generally people (e.g. me) seem to be going back to the title if it's absolutely clear the next turn won't be survivable, and watching the character die would just be redundant. This should be counted as a loss.

**Comment by TerryCavanagh** [comment]
Ahh, I'm not sure. I need to think about this one for a bit. I know that people are savescumming, but also, I think people can reasonably expect their saves to be intact if they have to quit during battle for whatever reason. Need to be careful not cause a big problem while trying to solve a small one.

**Comment by ncrecc** [comment]
This should only happen if the player returns to the title screen and chooses to start a new game rather than continue.

**Comment by findersjeepers** [comment]
Speaking as someone who also quits and restarts as soon as they see the writing on the wall in order to save the time of actually fully dying -- I'm not super bothered either way, but the pie-in-the-sky IMO would be an "incomplete" stat for incomplete runs (defined as "returns to title **and chooses to start new game rather than continue**", as ncrecc says). The reason for this is because I also sometimes quit and when I'm _not_ in danger of dying, but only purely because I realize I'm going too slowly, or because I screwed something else up that _won't cause death_ but will annoyingly inconvenience the rest of the run.

However, just to be clear, I am perfectly fine with either "no change to current system" or "incompletes as losses". Separate "incomplete" stat is just wishful.

**Comment by omor1** [comment]
Just my 2 cents, but in my opinion abandoning a match is antithetical to the point of the game. After all, Lady Luck could smile upon you! I mean, she _doesn't_, but should _could_. (I've won a number of times after going to to just 1 health.)

**Comment by ncrecc** [comment]
That sounds like a wonderful ideology until you get into elim rounds or Jester runs with especially poor RNG.

**Comment by omor1** [comment]
@ncrecc for what it’s worth, I'm 1-1 on Elimination Round and 2-0 with Jester. Admittedly I haven't been playing long... I'll grant you Witch though (1-5). Dealing 30 health in a single turn isn't unreasonable, though requires some Luck.

What do you mean, I'm not supposed to be disappointed to fail YET AGAIN to win anything? I swear I'll get it next time! I can't _always_ be **this** unlucky!

**Comment by omor1** [comment]
Perhaps a better argument is in The Inevitability of Rust scenario, if you entirely run out of methods of dealing damage.

**Comment by ncrecc** [comment]
Still you can't act like every "certain death" scenario has a silver lining. I'm at 2 hp against Rhino Beetle and not enough resources to kill him, am I going to survive? I'm at 2 hp against Loud Bird and my current resources are nullified from being useful and I'm silenced, am I going to survive? (Actually, there *is* a silver lining here, so maybe I just had to be more positive - if Loud Bird rolls a 1, and next turn he rolls such that he fails to do any damage *and* doesn't weaken the equipment I need to kill him, or does weaken the equipment I need to kill him but fails to do damage to me enough times in a row. And maybe I really *could* do 30 damage in one turn, never mind if my current hand, spellbook, and status effects wouldn't allow for that.)

Even then the issue isn't that I need to man up and stick out my chest (or "git gud"), the issue is that this is a common trend among players, and it still either boils down to pressing a button to see how hard the enemy overkills you or quitting to menu since you know what's going to happen.

**Comment by ncrecc** [comment]
Ahh fuck misread your comment, thought that last paragraph was referring to quitting a near-certain loss and not spinning skull on the wheel.

**Comment by TerryCavanagh** [comment]
Nah, this is fine. Closing.
