### ISSUE TITLE
After latest update (1.3) the game won't run on linux

### ISSUE THREAD

**Issue by dominx** [TerryCavanagh/diceydungeons.com#1340]
I'm on ubuntu 16.04

When trying to run from command line I get:

Called from lime._internal.backend.native.NativeCFFI::boot lime/_internal/backend/native/NativeCFFI.hx line 214
Called from lime._internal.backend.native.NativeCFFI::boot lime/_internal/backend/native/NativeCFFI.hx line 214
Called from cpp.Prime::_loadPrime /usr/share/haxe/std/cpp/Prime.hx line 36
Error : Could not load module lime@lime_application_create__prime

**Comment by TerryCavanagh** [comment]
Sorry about this, it looks like I reintroduced an old linux bug (this one: https://github.com/TerryCavanagh/diceydungeons.com/issues/863). Looking into it now, and hope to have it fixed in a couple of hours.

**Comment by TerryCavanagh** [comment]
Heya! I think this should be fixed now. Please let me know if not!

**Comment by dominx** [comment]
Game launches fine.

**Comment by TerryCavanagh** [comment]
That's great, thank you for confirming!
