### ISSUE TITLE
List of issues with the Russian translation

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1341]
### Ovelapping text:
On the Credits screen: ![image](https://user-images.githubusercontent.com/26709843/63925538-b3e1bf00-ca63-11e9-82db-0b65c3226f24.png)
This one could be fixed by removing the "Перевод на " string which means "Translation to". It's not present with other languages, though. ![image](https://user-images.githubusercontent.com/26709843/63925662-ee4b5c00-ca63-11e9-98ac-ef89a344a6c3.png)
Curse of Greed's flavor text could use a linebreak after the first comma ![image](https://user-images.githubusercontent.com/26709843/63926035-952ff800-ca64-11e9-87c8-b63631d2b8ab.png)
The Elimination Round flavor text needs a linebreak in the first sentence and shouldn't have one of the linebreaks in the second sentence. ![image](https://user-images.githubusercontent.com/26709843/63926167-d0cac200-ca64-11e9-8de9-507b1ae77c46.png)
Thief in the Night's flavor text also needs a linebreak ![image](https://user-images.githubusercontent.com/26709843/63926266-fd7ed980-ca64-11e9-83f7-7ef8c0f9428d.png)
Uptick's flavor text has extra spaces on the second and the third lines. ![image](https://user-images.githubusercontent.com/26709843/63926373-2c954b00-ca65-11e9-9647-182bd7000712.png)

### Wrong translation
The Title button has the wrong meaning of "title" (a descriptive or distinctive name that is earned or chosen) ![image](https://user-images.githubusercontent.com/26709843/63925777-22268180-ca64-11e9-871d-431427479755.png)

### Untranslated
Backstage door unlock conditions ![image](https://user-images.githubusercontent.com/26709843/63926470-55b5db80-ca65-11e9-8b1b-72ccd03be84f.png)

If I find more, I'll add them to the list (is posting them as comments better?)

**Comment by TerryCavanagh** [comment]
Thanks very much for this! Please let me know of anything else you spot - I'll pass it all on to the translator soon!

**Comment by TheMysticSword** [comment]
### Out of bounds text
Toxic Ooze description (might want to use a linebreak or shrunk text)
![image](https://user-images.githubusercontent.com/26709843/64008095-d987ca80-cb2e-11e9-8f89-f36ba829156b.png)
Pirate Hook description (this one definitely needs a linebreak)
![image](https://user-images.githubusercontent.com/26709843/64008251-2bc8eb80-cb2f-11e9-8233-5d2db8c654fd.png)
Polar Star description (might want to shrink text)
![image](https://user-images.githubusercontent.com/26709843/64010051-71d37e80-cb32-11e9-96be-398b974c995c.png)
Venus Fly Trap description could use a line break after the second comma
![image](https://user-images.githubusercontent.com/26709843/64010285-e4dcf500-cb32-11e9-88db-07280814339c.png)
Spatula description needs a linebreak
![image](https://user-images.githubusercontent.com/26709843/64011022-48b3ed80-cb34-11e9-873a-2f0831f7457b.png)
"Start with 2 additional dice" could be shortened to "Start with +2 dice" here
![image](https://user-images.githubusercontent.com/26709843/64009797-f83b9080-cb31-11e9-9c11-bbbcd3af8401.png)

### Overlapping text
Dramatic Exit, and probably all of the small 3 line items that have conditional text under the slots
![image](https://user-images.githubusercontent.com/26709843/64010112-8fa0e380-cb32-11e9-8c9c-190716d1d9f0.png)

### Wrong translation
The LEVEL UP string is literally translated as "TO INCREASE"
![image](https://user-images.githubusercontent.com/26709843/64008425-85c9b100-cb2f-11e9-9344-8316e38bddb6.png)

### Untranslated
Arf Arf Arf Jinx (maybe even all Jinx descriptions?)
![image](https://user-images.githubusercontent.com/26709843/64008870-50719300-cb30-11e9-9fd3-e35ed5990b46.png)
Squawk description
![image](https://user-images.githubusercontent.com/26709843/64011255-c1b34500-cb34-11e9-9b4c-fd71e2ede99b.png)

Thunder description
![image](https://user-images.githubusercontent.com/26709843/64008741-21f3b800-cb30-11e9-9102-7cf9aa0725e2.png)

### Other
The word "EXP" on the victory screen is not in caps
![image](https://user-images.githubusercontent.com/26709843/64008016-b1986700-cb2e-11e9-9cda-48715761bfcb.png)
Innates are still worded like "Yeti weakness to fire"
![image](https://user-images.githubusercontent.com/26709843/64009189-d261bc00-cb30-11e9-8cdd-319b68d185c5.png)

**Comment by TerryCavanagh** [comment]
Thank you!

There are a mix of issues here - some are due to bugs that are on my end, and some are things the translator needs to take a look at. If you don't mind, I'm gonna edit out the things that are bugs on my end so that I can pass this link along for them to look at!

**Comment by TheMysticSword** [comment]
Sure! I'll keep adding to this list while I'm replaying through the game.

### Overlapping text
You Choose, You Lose flavor text needs a linebreak 
![image](https://user-images.githubusercontent.com/26709843/64492053-03589400-d289-11e9-9405-20a633fa9a1e.png)

### Out of bounds text
Robot Request's "50% rolls cause errors" text 
![image](https://user-images.githubusercontent.com/26709843/64492065-2e42e800-d289-11e9-8003-79a08f4e021f.png)
Avalanche description
![image](https://user-images.githubusercontent.com/26709843/64492419-09e90a80-d28d-11e9-9eb7-a50bf593e0a0.png)

### Untranslated
In addition to Thunder being untranslated, it seems that all of Aurora's weapons are untranslated
![image](https://user-images.githubusercontent.com/26709843/64492190-e329d480-d28a-11e9-9c46-7b00f0a1c880.png)

### Mistranslated
The "Maul" in Bear Maul is translated as the maul hammer
![image](https://user-images.githubusercontent.com/26709843/64492296-fbe6ba00-d28b-11e9-8ec9-dbd8b96aef15.png)

**Comment by TheMysticSword** [comment]
### Out of bounds text
Shovel+ description 
![image](https://user-images.githubusercontent.com/26709843/64869153-39679080-d65a-11e9-8ac8-8b6b98b8d058.png)
Lament+ description
![image](https://user-images.githubusercontent.com/26709843/64869677-40db6980-d65b-11e9-8633-c3282aae535b.png)
Whip+ description
![image](https://user-images.githubusercontent.com/26709843/64869737-66687300-d65b-11e9-9173-8028b35846dc.png)
Overwhelm (and Overwhelm+) description
![image](https://user-images.githubusercontent.com/26709843/64871548-dfb59500-d65e-11e9-8782-51b16184a950.png)

### Untranslated
Freeze All inflicted on Robot doesn't have a translated name
![image](https://user-images.githubusercontent.com/26709843/64870625-1a1e3280-d65d-11e9-8f1a-51994047d43b.png)
Two Handed Sword+ description
![image](https://user-images.githubusercontent.com/26709843/64872379-88b0bf80-d660-11e9-8dbb-539ea5462aa4.png)

### Other
Yolanda always uses male pronouns for herself.

**Comment by TerryCavanagh** [comment]
Thanks again for this! I've fixed some issues on my side, and deleted them from this thread so that I can pass it along to my translator!

**Comment by TheMysticSword** [comment]
### Old text
Smog Cloud says that it inflicts Shock instead of Blind
![image](https://user-images.githubusercontent.com/26709843/67143300-91aa3780-f283-11e9-8050-047a46b5308d.png)

### Mistranslated
Confuse's tooltip says "Equipment is mixed up and can fail."
![image](https://user-images.githubusercontent.com/26709843/67143081-f87a2180-f280-11e9-80de-86358c10b137.png)

### Other
Madison's "immune to freeze" innate has the "I understand!" button text copypasted
![image](https://user-images.githubusercontent.com/26709843/67142951-cd430280-f27f-11e9-9cec-deb77cb56311.png)
![image](https://user-images.githubusercontent.com/26709843/67143304-a4bd0780-f283-11e9-928d-b4cec50e00a3.png)

Re-Equip Next doesn't have an underscore between words
![image](https://user-images.githubusercontent.com/26709843/67143102-2f503780-f281-11e9-807e-4b8271681643.png)
![image](https://user-images.githubusercontent.com/26709843/67143315-bacac800-f283-11e9-84f8-38bf09d74838.png)

Reduce By is listed twice, but the second entry just says "reduce by". It overrides the first entry, so in-game it says "reduce by"
![image](https://user-images.githubusercontent.com/26709843/67143114-4f7ff680-f281-11e9-8d7c-0ae3df35b077.png)
![image](https://user-images.githubusercontent.com/26709843/67143323-d209b580-f283-11e9-858a-a1592cea91ed.png)

**Comment by TheMysticSword** [comment]
Most errors here were fixed with the 1.8 translation pass and the rest of them are now fixed in my translation pass. Closing this issue.

**Comment by TerryCavanagh** [comment]
Thanks @TheMysticSword - this was super helpful :)
