### ISSUE TITLE
Figure out a way to warn players when an update will break saves, or maybe even recover them invisibly

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1342]
I changed the generator for Witch in v1.3, and this meant that anyone who had a partially complete Witch run in v1.2 and attempted to load the save would either get a crash or a distorted map. Some way to prevent this happening in future would be a really good idea.

At the very least, we should do the following: 

I'll avoid making any generator changes for v1.4, and implement some kind of system for telling whether or not the underlying generator for a save file has changed since you last played. We could literally hard code add a check for versions and generators to the game, say - if the game had a history of generator changes, and the save file has the version number and current episode, then it could tell if the save file will be broken before it attempts to load it. A screen saying: sorry, the save file is from an earlier version and is incompatible, with a restart run button would be better than nothing.

A step up from that might be to attempt to create a new save file that's working, even if it has different stats. So, we grab as much info as we can from the old save file - inventory, number of monsters left on a floor, etc, and we create a new, fake save from that. That's a lot of work, but people losing save files is a pretty big deal.

**Comment by omor1** [comment]
Save files should probably contain the version number they are for, if they don't already. As stated, that would at least allow for _detection_ of incompatibilities.

**Comment by TerryCavanagh** [comment]
Thankfully, this bug was fixed some time ago - our save format now saves additional data, and can handle small changes to generators.
