### ISSUE TITLE
Commonly reported issues

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1343]
The following (fairly minor) issues get reported a lot, so would be nice to fix in an upcoming patch:
- [x] In some cases, when you make a trade with Val, you can keep the original item.
- [x] Vanished cursed items with countdowns still accept, and consume, dice
- [x] Winning a fight with 0 hp counts as a win, and lets you walk around the map with negative health
- [x] Backing out of an upgrade that you've bought or chosen as a level up reward results in you losing that upgrade completely.
- [x] Dice slots are a little buggy when trying to break Silence as Inventor
- [x] Jester enemy move previewing is buggy
- [x] Either prevent thorns from bypassing shield, or explain that it does somewhere in the game
- [ ] Fix Robot Lock

**Comment by mrcdk** [comment]
`Vanished cursed items with countdowns still accept, and consume, dice` fixed
`In some cases, when you make a trade with Val, you can keep the original item.` fixed
`Jester enemy move previewing is buggy` fixed

**Comment by TerryCavanagh** [comment]
Everything's fixed here apart from the Robot Lock bug, so closing this!
