### ISSUE TITLE
Add a way to view the episode completion screen outside of finishing a game

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1345]
![IMG_20190829_181947](https://user-images.githubusercontent.com/2095534/63958040-dab2ec00-ca89-11e9-8674-f436bd8dff25.jpg)

**Comment by omor1** [comment]
Somewhere on the title menu screen would be nice. Alternatively, to the "left" of the character select screen?

**Comment by TerryCavanagh** [comment]
Not planning to do this - yep, it might have been kind of nice, but the same information is available to the player by just browsing the character selection screen, so it isn't actually needed.
