### ISSUE TITLE
Unfocused (Inventor's Silenced? Limit Break) doesn't work

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1347]
Seen a number of reports of this. The code for Unfocused is:

`var randvalue = random([1 | 2 | 3 | 4 | 5 | 6]); var c = 0; for (mydice in self.dicepool){ if (mydice.available()){ mydice.animatereroll(randvalue| self.screenposition()| c * 0.05); c++; } }`

Initial thought is that `random()` isn't a function?

**Comment by XenonZed** [comment]
By the look of things this can be very easily fixed by just replacing "random" with "rand". I really don't understand how this hasn't gotten fixed yet.

**Comment by TerryCavanagh** [comment]
Finally fixed this one 😅
