### ISSUE TITLE
3 ideas for achievements and progression

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#135]
I played illumine yesterday and got bored pretty quickly, but it did have a pretty cool progression
system which inspired me to write up my ideas for progression in DD.

## (1) Achievement-based progression

I've been noticing which mental tickyboxes myself and others seem to be ticking to mark our progress.

* I beat the game with the $CLASS on $DIFFICULTY!
* I beat the $BOSS on $DIFFICULTY!
* I beat the $BOSS with the $CLASS on $DIFFICULTY!

I would hella enjoy a progression system based on achievements like these or others. For example,
hard mode only unlocks for a class once you've beaten the game with that class.

One potential issue with this is that if I'm trying to get all the $BOSS achievements or even
moreso with the $BOSS+$CLASS achievements, I'd get frustrated if I were trying to get the last one
and I had to rely on a 1/N chance.  I'd just give up instead. Which is fine if no further
progression is unlocked by getting the full set, but if it is, then I would appreciate some way to
stack the deck in my favor to make it more likely to get the one boss I'm missing.

## (2) Diceydex!

Another thing I think would be fun would be a Diceydex of all the cards you've ever owned (not
just borrowed as Thief) and their upgraded versions if you've ever upgraded them. Gotta roll 'em all!

## (3) Activate each card's inner awesomeness

Each card has a secret activation criterion that unlocks its inner awesomeness. For example:
* Shield Bash: deal 100+ damage with this card in one hit
* Hall of Mirrors: use this card to get 20+ dice
* Pickpocket: steal 50+ gold with this card in one run
* Lockpick: split 50+ dice with this card in one run
* Sword: deal 200+ damage with this card in one run
* etc.

and if you activate the card, then in future runs something cool happens, like
* it has a 10% chance of appearing in its upgraded form, and/or
* its drop chance increases if rare, and/or
* it's cheaper in shops

I think about game design all the time, but I haven't actually created a game since highschool.
(I'm a symbolic AI programmer these days.) I'm really enjoying watching your design process with
DD, and it's super fun to get to be part of the process. I've finally found an outlet for my
armchair game design skillz! (:

**Comment by YinYin-Falcon** [comment]
> I would appreciate some way to
stack the deck in my favor to make it more likely to get the one boss I'm missing.

I would appreciate that now already, even without any achievement tracking.  
Something such as picking the environment of the first floor (chance is now 1/(N-2).

Diceydex sounds like a somewhat obvious inventory feature. Especially useful for the inventor to plan ahead (what gadgets do things craft?).

The secret card features sound a bit too unrefined/overpowered/complex.  
What are the activation criteria? How frequently can you do this? Will such extreme changes really be fun (especially when they become the de facto strategy to instakill bosses)?

Stacking odds for certain card drops (similar to getting a certain boss) - possibly via the diceydex - would be great though.

**Comment by TerryCavanagh** [comment]
Good suggestions!

(1) I have a plan in mind for v0.7 regarding the larger game structure that I think people will like. It's not too far away from this, really. We'll see!

(2) Yeah, this is a great idea, definitely something I'll do some version of soon.

(3) Not so sure about this, but I do have plans to some kind of Dicey Dungeon esque *increase of complexity over time* thing, where various goals change the potential make up of dungeon generation. Eg. defeating Cornelius might make Crowbar show up for the thief, etc. I probably won't do much on this front until things are a lot further along, though!

**Comment by pace212** [comment]
@YinYin-Falcon: The features I mentioned _are_ the activation criteria. For example, if, during any run, you ever deal 100+ damage with Shield Bash, that unlocks its inner awesomeness for future runs, which means it's cheaper in shops and/or occasionally drops in upgraded form and/or has higher drop chance if rare.

@TerryCavanagh 

(1) Cool, 0.6 has just dropped and I'm already excited for 0.7 (: 

(2) Rad.

(3) Increase of complexity over time sounds lovely. Your example of "defeating Cornelius makes Crowbar show up for the Thief" I think would be super fun - the additional element I'm suggesting is an element of surprise. "Defeat Cornelius" is a main quest, "Deal 100+ damage in one run with this one specific weapon" is a secret side quest. For example, I wouldn't ordinary do an entire run with the Short Sword as my main weapon, but if I wanted to unlock its inner awesomeness, it'd give me an incentive to focus on a card I wouldn't ordinarily focus on. Usually I just ignore Short Sword, so I'm noodling on ways to encourage diverse play styles.

**Comment by YinYin-Falcon** [comment]
Ah! That makes *much* more sense.  
(the whole "inner awesomeness" made me think of a limit like mechanic - not just altering occurrences for a lot of use)

The drop/shop chance manipulation will be a bit tricky, since that is always shared with *everything* else (something more also means something less).

So you'd need a way to set this yourself after unlocking to avoid messing up the game (I sure don't want to be rewarded with more short sword drops because I had to use it a lot for example - if anything, using something a lot should lower drop chances so I *get to play something else*).

Permanent discount or appearing in upgraded form is easier (as long as the upgrade has no potential down sides). But once more it does mess with the initial challenge and you probably don't wanna add toggles for each and everyone of them.

Unlocking alternative starting load outs per class might be a simpler way to go about it. That way the player always gets to pick the rules up front instead of having them changed in the background.

I agree though, side quest rewards for running certain equipment in addition to main quests of defeating a certain boss/difficulty/class are cool.

**Comment by pace212** [comment]
I would love a progression achievement that was streak-based, e.g. "Complete 3 runs in a row with Warrior".

Completing a run proves that you have some combination of skill and persistence.

Completing 3 runs in a row proves that you've really mastered the class.

At the very least, please add streak statistics when you add stats (:

**Comment by TerryCavanagh** [comment]
So, quite a lot of this is now addressed in beta! I think we can close it. Appreciate the thoughts!
