### ISSUE TITLE
Bear hang

### ISSUE THREAD

**Issue by dominx** [TerryCavanagh/diceydungeons.com#1351]
Version 1.3 with the linux hotfix I guess. IIRC fighter episode 5.

Bear hangs, music and animation still running. The bear of very little brain has trouble deciding.

A screenshot:
https://drive.google.com/file/d/1I95tiOUkAh_AfLKVQ8bAcbqqV-oKnBlo/view?usp=sharing

Quitting to title and continuing works.

**Comment by redfoxDW** [comment]
Experienced the same issue here.
Version 1.3.2 01-09-2019
[screenshot](https://drive.google.com/open?id=1HEBeZcEHlENPVYsoEOfdrxboZirgfXuS)

**Comment by logical2u** [comment]
This seems like the original report of the related issues #1428, #1406, #1469
Also encountered on version 1.4.3, Steam, 64-bit, GL, on Windows 10 during Witch 4 with shock.

In my case, shocking Alchemist performed as expected and resulted in bear change + turn end. Shocking *bear* result in softlock where the bear unshocks an equipment but refuses to spend a die in it. 
![20191003101906_1](https://user-images.githubusercontent.com/56121029/66129946-4297ad80-e5c7-11e9-9aaf-92137413c236.jpg)

**Comment by bjennings76** [comment]
I just experienced this one too.

Steps to Reproduce:
1. Shock the alchemist so they have to change into the bear early.
2. Alchemist turns into a bear (and probably needs dice to spare after change)

Current Results:
Bear tries to play a die, but it hangs at the top of its animation stopping combat progression.
(I think it's trying to go unlock one of the old shocked abilities that are no longer there.)

Expected Results:
The remaining dice move to the new bear abilities and play continues.

Settings screen info:
v1.4.3, 14-09-2019, STEAM, 64-bit, GL

Here's another screenshot in case it helps:
![image](https://user-images.githubusercontent.com/556111/66254023-09c92580-e7cd-11e9-881d-7a8ec8631aeb.png)

**Comment by TerryCavanagh** [comment]
Fixed for v1.7!
