### ISSUE TITLE
Poison tooltip loses its second line when the target takes damage from poison

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1353]
![image](https://user-images.githubusercontent.com/26709843/64010678-b3185e00-cb33-11e9-8830-1261b1b49e98.png)

**Comment by TerryCavanagh** [comment]
Not sure if this one is a still an issue or not, but labeling it so that I remember to check one way or another.

**Comment by TerryCavanagh** [comment]
Fixed in v2.1.
