### ISSUE TITLE
Crash: Aoife AI got confused by [Poison?]? 

### ISSUE THREAD

**Issue by AiSard** [TerryCavanagh/diceydungeons.com#1356]
![diceydungeons_2019-08-30_22-52-51](https://user-images.githubusercontent.com/33284312/64034863-adde0200-cb79-11e9-9ff4-a3879db7e8f7.png)
[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/3560661/_error.txt)

From the error log, I'm guessing [Poison?] made the AI think it didn't have slots on that equipment for some reason?

**Comment by TerryCavanagh** [comment]
This was fixed a few versions ago. Closing!
