### ISSUE TITLE
Bonus round rules hide the turn counter in combat

### ISSUE THREAD

**Issue by Lizard953694** [TerryCavanagh/diceydungeons.com#1357]
![image](https://user-images.githubusercontent.com/54388347/64039167-a1c55680-cb1f-11e9-9145-5a9333c81de5.png)

**Comment by TerryCavanagh** [comment]
This isn't a bug so much as a UI decision that I think I'm now sticking with. The turn counter is only important information for a handful of pieces of equipment, and all of those now have ways to check turn (Polar Star is labelled, Crescent Moon Blade uses special slots).
