### ISSUE TITLE
Stuck on enemy's turn

### ISSUE THREAD

**Issue by Lukaduke** [TerryCavanagh/diceydungeons.com#1359]
Playing as the warrior, reached floor 4 or 5, started first encounter with a crystalina. She has used a couple dice and has two left, a 4 and a 5, with the options blessing and opening her last equipment left, both of which need 4. It has been stuck on her turn for about 10 minutes and she has not decided on what to do. the animations are still in play and the music is playing so it does not seem like it has frozen.

**Comment by keturn** [comment]
Samesies.

Version: 1.4.2, 14-09-2019, 64-bit
for Linux from itch.io

![Screenshot of Crystalina](https://user-images.githubusercontent.com/83819/65381819-93490580-dcad-11e9-8d0d-c2763b72d9d5.jpg)

**Comment by j4chaves** [comment]
Ran into a similar issue with the Warrior on Episode 6.  Version 1.7.1 31-01-2020 Steam 64-bit GL
![20200203224550_1](https://user-images.githubusercontent.com/3156391/73712369-e315ef80-46d7-11ea-9328-ba7aea2b253c.jpg)


![20200203222631_1](https://user-images.githubusercontent.com/3156391/73712292-aba74300-46d7-11ea-8bb0-1ae6e04e6264.jpg)

Beatrice used her first 2 dice normally.  Then used the last 2 to get rid of a poison counter that was placed on her top Bee Sting equipment.  Her last dice was played very quickly compared to the speed an enemy's dice normally are used.  I'm not sure if the modifiers I had during that run had an effect or not.

**Comment by TerryCavanagh** [comment]
Fixed in a recent version!
