### ISSUE TITLE
Do something to make witch more accessible

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1360]
Going by reactions on Steam, the Witch seems pretty hard to get into for most players.

It's been kind of baffling to me since day 1 that witch doesn't have any way to swap out spells or shuffle them, which makes her combo-oriented style - already tricky enough - even harder for newcomers. (And, uh, me. Witch feels pretty weak and unfun for me right now and it doesn't seem coincidental that she needs way more apples than any other class just to survive.) Giving her an inventory might help some. Would require a pretty big design overhaul but maybe just give her the standard inventory screen with backpack sized halved and a "choose prepped spells"/"preview upgrade" part under it, and use the equipped grid for the spellbook.

This would also make "don't tie spells to dice you'd want to use on the spell itself" not glaringly contradict witch being unable to rearrange an inconvenient spellbook due to having filled it up with non-dice specific spells in the early-game.

**Comment by TerryCavanagh** [comment]
No big Witch overhaul is planned at this point, and since this issue was made I did several things to rebalance and improve qol things for Witch, so I consider this settled. Personally, I think there are some design lessons for me to take away from this for whatever the next game is.
