### ISSUE TITLE
Make silence on witch only affect throw dice

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1361]
Right now silencing witch makes her unable to cast spells and then use them, or throw more than 1 dice. (Unless you've stacked up some dice with HoM or Illuminate. But status effects shouldn't swing from "debilitating" to "minor inconvenience" based on a particular card.) That's pretty horrific in an episode where you don't gain dice on level-up.

**Comment by TerryCavanagh** [comment]
Nope - this is a decent suggestion, but I'm happy with the current behaviour.
