### ISSUE TITLE
Crash during Warrior Parallel Universe run

### ISSUE THREAD

**Issue by Kestrel-Pi** [TerryCavanagh/diceydungeons.com#1363]
It's not quite clear quite what was confusing the game here, but I think it might have been to do with the status effects. I had just cast the status effect on the Alchemist that means they have to spend HP to unlock their ability, and because they were too low on health, the turn bounced straight back to me. When it did, all my abilities showed up as unavailable, which confused me -- then the crash happened a split second later. Here is the log:

--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v1.3 / 0.11.0 (mod API)
sess. ID:	dicey_dungeons_2019-08-30_18'25'19
started:	2019-08-30 18:25:19
--------------------------------------
crashed:	2019-08-31 00:16:08
duration:	05:50:49
error:		ERROR in callscenemethod(Combat,update) static : Null Object Reference, stack = 
Called from elements.Fighter.applyequipmentcurses (elements/Fighter.hx line 865)
Called from elements.CombatCommand.execute (elements/CombatCommand.hx line 348)
Called from states.Combat.update (states/Combat.hx line 268)
Called from Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 268)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

**Comment by TerryCavanagh** [comment]
Ah, this looks from the crash log like it was probably the Poison? status effect bug - pre v1.7, it could cause a crash when you only have e.g. one piece of equipment and you get a combination of Shock? and Poison?, and there weren't any pieces of equipment for Poison? to target. Anyway, it's been fixed!
