### ISSUE TITLE
[Robot] [Graphics] Dice sprite stays onscreen after error if placed in multidice item beforehand

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#1365]
This is a purely graphical glitch, as it is not that there are any actual usable dice. However, the dice sprite remains in place after calculating into Error if 1) placed into a multi-dice-slot piece of equipment such as Vise Grip 2) without actually using the equipment.

**Comment by TerryCavanagh** [comment]
Fixed!
