### ISSUE TITLE
Buying and not using a Delete as the Jester spends money but wastes the Delete

### ISSUE THREAD

**Issue by grebnetiew** [TerryCavanagh/diceydungeons.com#1367]
Reproduce: As Jester, play until you get to a shop that sells Delete. Buy it, but don't delete anything (Leave instead). This spends your money, removes the Delete item from the shop, but you lose the opportunity to delete a card.

Expected behaviour: I would expect to get money back and have the item remain in the shop (or to be allowed a Delete if I view my deck after buying and not using the Delete).

(Possibly related to the upgrade/witch variants, but reporting in case you didn't know about it and it's mechanically different.)

**Comment by TerryCavanagh** [comment]
Fixed!
