### ISSUE TITLE
Rusty Sword doesn't have a "_weakened" version

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1368]
![image](https://user-images.githubusercontent.com/26709843/64063287-1d043680-cc0c-11e9-8845-28d3c5d5ecd7.png)

**Comment by ncrecc** [comment]
This is still around (does terry check issues by date opened or last updated?)

**Comment by TerryCavanagh** [comment]
Fixed a while back!
