### ISSUE TITLE
Make the non-steam version "portable"

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1369]
Instead of storing save files in the user's save folders, the non-steam versions of the game on windows and linux should attempt to use the game's local folders, if it can access and write to them.

**Comment by ncrecc** [comment]
Maybe separate versions into "portable" and "non-portable"? I find it quite nice being able to get a new version off of itch and not having to transfer anything over but mods.

**Comment by TerryCavanagh** [comment]
Wayyy too late to be messing about with this sort of thing, considering the dicey_mods.json fiasco
