### ISSUE TITLE
Change Pickaxe+ to have a free 1 rather than switching order of effects

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1370]
Current upgrade is pretty clever but makes no difference in Bonus Round if the Warlock modifier isn't active.

**Comment by ncrecc** [comment]
Same thing with tetraphobia

**Comment by TerryCavanagh** [comment]
I think that's ok: this is really an item that's "for" parallel universe, and I'm ok with that.
