### ISSUE TITLE
[non-English] Jester episode 6, crash when entering combat

### ISSUE THREAD

**Issue by minirop** [TerryCavanagh/diceydungeons.com#1374]
I started the bonus round of the Jester, and when entering the first battle, when there is the sound  playing when the card should appear, the game crash. I tried several languages (French, German, Chinese, etc), the stacktrace is the same:

> \--------------------------------------
> filename:	diceydungeons
> package:	com.terrycavanaghgames.diceydungeons
> version:	v1.3.1 / 0.11.0 (mod API)
> sess. ID:	dicey_dungeons_2019-08-31_17'32'41
> started:	2019-08-31 17:32:41
> \--------------------------------------
> crashed:	2019-08-31 17:33:17
> duration:	00:00:36
> 
> error:		ERROR in callscenemethod(Combat,update) static : Invalid UTF8, stack = 
> Called from haxe.Utf8.length (/usr/share/haxe/std/cpp/_std/haxe/Utf8.hx line 74)
> Called from lime.text._UTF8String.UTF8String_Impl_.get_length (lime/text/UTF8String.hx line 362)
> Called from starling.text.ExtendedBitmapFont.bounds (starling/text/ExtendedBitmapFont.hx line 659)
> Called from starling.text.ExtendedBitmapFont.fillMeshBatchContainer (starling/text/ExtendedBitmapFont.hx line 451)
> Called from starling.text.TextField.updateText (starling/text/TextField.hx line 241)
> Called from starling.text.TextField.recompose (starling/text/TextField.hx line 217)
> Called from starling.text.TextField.getTextBounds (starling/text/TextField.hx line 349)
> Called from starling.text.TextField.get_textBounds (starling/text/TextField.hx line 335)
> Called from displayobjects.HaxegonTextField.localcompose (displayobjects/HaxegonTextField.hx line 151)
> Called from displayobjects.HaxegonTextField.draw (displayobjects/HaxegonTextField.hx line 162)
> Called from displayobjects.Print.draw (displayobjects/Print.hx line 58)
> Called from displayobjects.DeckPanel.drawnextup (displayobjects/DeckPanel.hx line 105)
> Called from displayobjects.DeckPanel.draw (displayobjects/DeckPanel.hx line 176)
> Called from elements.Equipment.render (elements/Equipment.hx line 1760)
> Called from elements.Equipment.draw (elements/Equipment.hx line 1610)
> Called from states.Combat.update (states/Combat.hx line 518)
> Called from Reflect.callMethod (/usr/share/haxe/std/cpp/_std/Reflect.hx line 55)
> stack:
> haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
> haxegon.Scene.update (haxegon/Scene.hx line 53)
> haxegon.Core.doupdate (haxegon/Core.hx line 268)
> haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
> starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
> starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
> starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
> starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
> starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
> starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
> starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
> starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
> openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
> openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

there has been a couple of times where it was a little different:

> error:		ERROR in callscenemethod(Combat,update) static : Invalid UTF8, stack = 
> Called from haxe.Utf8.length (/usr/share/haxe/std/cpp/_std/haxe/Utf8.hx line 74)
> Called from lime.text._UTF8String.UTF8String_Impl_.get_length (lime/text/UTF8String.hx line 362)
> Called from starling.text.ExtendedBitmapFont.bounds (starling/text/ExtendedBitmapFont.hx line 659)
> ... same as above

**Comment by TerryCavanagh** [comment]
Heya - thanks for reporting this! Fix is live right now - https://github.com/TerryCavanagh/diceydungeons.com/issues/1362
