### ISSUE TITLE
Bear Charge Weakened Perseveres Across Battles

### ISSUE THREAD

**Issue by rhamkor** [TerryCavanagh/diceydungeons.com#1375]
Hi there,

I ended up as a Bear (which was a huge surprise!) and upgraded my Bear Charge ability so that it would activate after 5 was put into it.  It got weakened and after that battle it went back up to 10.  I confirmed that this was not just a display error.  I was able to fix it by quitting and relaunching but thought you should know.

**Comment by TerryCavanagh** [comment]
This one is fixed in recent versions!
