### ISSUE TITLE
Jester episode 6 Fury crashes Inventor-card

### ISSUE THREAD

**Issue by villll** [TerryCavanagh/diceydungeons.com#1376]
When playing Jester episode 6, Fury is active and Inventor-card is played, the game crashed. Here's the crash log:

\--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v1.3 / 0.11.0 (mod API)
sess. ID:	dicey_dungeons_2019-08-31_18'47'22
started:	2019-08-31 18:47:22
\--------------------------------------
crashed:	2019-08-31 21:12:18
duration:	02:24:55
error:		Null Object Reference
stack:
states.Combat.repeatlastaction (states/Combat.hx line 1613)
elements.Equipment.doequipmentaction (elements/Equipment.hx line 2146)
Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
motion.actuators.GenericActuator.complete (motion/actuators/GenericActuator.hx line 155)
motion.actuators.SimpleActuator.update (motion/actuators/SimpleActuator.hx line 501)
motion.actuators.SimpleActuator.stage_onEnterFrame (motion/actuators/SimpleActuator.hx line 579)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

**Comment by jsbohnert** [comment]
Also seen this crash, same conditions - bonus rule of Wolf Pup is in action, first hand in the the round includes the Inventor? card on Floor 4. Using Inventor then using the duplicated card results in this crash.

**Comment by mrcdk** [comment]
Fixed.
