### ISSUE TITLE
Venus Fly Trap with isn't repeated when enemy dead, but character could be healed

### ISSUE THREAD

**Issue by meliache** [TerryCavanagh/diceydungeons.com#1377]
I'm doing the third episode of the warrior right now and really need that healing of the venus fly trap. I had hoped that with fury and a 6, it will be executed a second time even though the first time it already kills the enemy. But the second execution would be useful for the healing. It's not really a bug but I believe it would feel fairer if attacks are repeated when the enemy is dead but they have such positive side effects for the player.

**Comment by TerryCavanagh** [comment]
Yep, probably a good suggestion! Duplicate, closing!
