### ISSUE TITLE
Action+ and Picnic Basket+ have broken dice previews

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1383]
![picnic action](https://user-images.githubusercontent.com/11216597/64081933-a6337000-ccd5-11e9-8578-0a3902580421.gif)
I'm not storing two 8s. I'm storing a 6 and a 2, and a 5 and a 3. The only thing I'm storing two of are dice.

Maybe just change the description to "Keep these dice for next turn"?

**Comment by TerryCavanagh** [comment]
Fixed for v1.10!
