### ISSUE TITLE
Crash when poisoning Aoife on Episode 6 (Thief)

### ISSUE THREAD

**Issue by Jacobjeff2** [TerryCavanagh/diceydungeons.com#1385]
There appears to be a crash that happens every time I am fighting Aoife with the thief on episode 6 and I poison her. The bug seems to happen when her Tower Shield equipment is hit with the poison. On episode 6 the poison covers the equipment until she pays the cost of the total poison and the AI must get confused. I have attached the crash log, and I hope this helps in getting the bug fixed.

Thanks for the awesome game.

[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/3564093/_error.txt)

**Comment by hupfen** [comment]
Seconding that this occurs, seemingly on any needs-doubles item. My case was Yeti's Ice Age. https://clips.twitch.tv/RacyHappyApeRiPepperonis  https://pastebin.com/rxNtD7CN

**Comment by TerryCavanagh** [comment]
Fixed!
