### ISSUE TITLE
You can collect booster packs as Jester-turned-Bear (try curse?ing Bear Potion), but they don't give you anything

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1389]

**Comment by ncrecc** [comment]
When I first tried this I noticed lollipop was suddenly in my inventory (it was in my deck), but I don't know if it was always there or if it only appeared after collecting the booster pack (which I didn't get any of the advertised cards from)

**Comment by TerryCavanagh** [comment]
Alchemist is excluded in Losers Weepers now, so this can now longer occur in vanilla.
