### ISSUE TITLE
Revised Kraken is actually stronger due to Overwhelm bug

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1393]
If Kraken uses Overwhelm a single time, it all works as expected. Things get weird when Kraken uses it twice on the same turn:

**1. Miscalculated damage**
First use applies 1 dmg, as expected, incrementing the card to 2 dmg
Second use applies 3 dmg, as the card gets incremented during the attack

**2. Increment bug**
If Kraken uses Overwhelm twice, it will start the next turn with a further +1 damage on Overwhelm

Both bugs (which are probably the same thing) can be seen in this video:
![gif](https://giant.gfycat.com/AdolescentFrightenedAlaskajingle.gif)
https://gfycat.com/adolescentfrightenedalaskajingle

**Comment by TerryCavanagh** [comment]
Great catch, thank you! Fixed in v1.4.
