### ISSUE TITLE
Episodes are unlocking for people even if they lose with the character

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1395]
Was watching a stream, and someone unlocked episodes. However, they lost as Witch - but could still select an episode for her. Episodes 2 and 3 were unlocked and available for them. As per #1322 these should ideally be unavailable until the first episode is completed.

**Comment by TerryCavanagh** [comment]
Ah, I've now changed my mind on this, and this is deliberate!
