### ISSUE TITLE
"Reuseable" Misspelled

### ISSUE THREAD

**Issue by omor1** [TerryCavanagh/diceydungeons.com#1396]
As far as I know, the "proper" spelling of "reuseable" is, in fact, "reusable". It is spelled with the former in at least Pea Shooter. Some others word it as "re-use", which while not perhaps as proper as "reuse", is acceptable.

Very minor text issue, very low priority. Just something I noticed while typing up a different issue.

**Comment by findersjeepers** [comment]
["useable" is a known alternative spelling of "usable"](https://www.merriam-webster.com/dictionary/useable), just as "judgement" is an alternative spelling of "judgment".
