### ISSUE TITLE
Jester "Losers, Weepers" and Reusable Equipment

### ISSUE THREAD

**Issue by omor1** [TerryCavanagh/diceydungeons.com#1397]
In the "Losers, Weepers" episode, reusable equipment (such as Pea Shooter) cannot be cycled out of the hand without the use of the special abilities "Magic Trick" or "Delete". In some sense this is working as intended, but can be frustrating in certain circumstances.

I'm not sure if this is actually a problem, and if it is, how it could be fixed.

**Comment by onetruepurple** [comment]
Reusable equipment is really bad for Jester, which is why he never finds it outside stealing it. Spend the 5 pips on deleting it instead.

**Comment by TerryCavanagh** [comment]
Yeah, this is a deliberate moment for the player - suddenly having Pea Shooter in their hand and realising how much of a problem it is. No plans to change this!
