### ISSUE TITLE
"Could not load module lime"

### ISSUE THREAD

**Issue by Bovido** [TerryCavanagh/diceydungeons.com#1400]
Since the v1.3, the game can’t start. When I launch it on command line, it says :

Called from lime._internal.backend.native.NativeCFFI::boot lime/_internal/backend/native/NativeCFFI.hx line 214
Called from lime._internal.backend.native.NativeCFFI::boot lime/_internal/backend/native/NativeCFFI.hx line 214
Called from cpp.Prime::_loadPrime /usr/share/haxe/std/cpp/Prime.hx line 36
Error : Could not load module lime@lime_application_create__prime

I tried download the game (on itch.io) several times : always the same error. I am on Debian 4.9.

**Comment by TerryCavanagh** [comment]
Heya - sorry about this - I have a fix coming in v1.4 in a couple of days. For now, I recommend rolling back to v1.2 on itch, which you can do on the itch app.
