### ISSUE TITLE
There seems to be something in place to prevent loads of dice from blocking the skillcard, but it's not very robust

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1404]
![image](https://user-images.githubusercontent.com/11216597/64307201-5b2e8c80-cf63-11e9-962e-3c29c2d2a705.png)
Sometimes a dice gets into the corner.
(This was from 1.2)

**Comment by ncrecc** [comment]
![image](https://user-images.githubusercontent.com/11216597/64307447-2242e780-cf64-11e9-8e03-89999877f1e1.png)
And occasionally the dice block off the top of the skillcard

**Comment by TerryCavanagh** [comment]
Yeah, we just removed this at some point. Closing!
