### ISSUE TITLE
Infinite Sine Wave+ combo as Witch

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1405]
![image](https://user-images.githubusercontent.com/11216597/64307334-bceef680-cf63-11e9-8c36-a31b7bc6f169.png)
Sine Wave+: Both dice values +1. Works with sixes. If you put in two sixes, you get two sixes and two ones. If Sine Wave is on 1, and you cast it in the upgraded slot, you're back where you started but with an extra 1.
This could potentially be a turn-1 win unless your opponent is vampire, and it's way too easy to get, since Sine Wave is commonly offered on floor 1 (in Bonus Round, anyway).

**Comment by TerryCavanagh** [comment]
Is this on v1.3? If so, which episode? (I though I removed it in v1.3, but maybe I missed it somewhere)

**Comment by ncrecc** [comment]
v1.3, yep, Witch bonus round

**Comment by TerryCavanagh** [comment]
Uff, I have no idea what's going on here. It's definitely not in any of the generator files for Witch anymore, and it's not offered as a level up reward or anything like that! Is it possible that your version hadn't updated or something?

**Comment by ncrecc** [comment]
Ah, dumb cause - I had some generator files in my mod's data\text\generators\\, then forgot they were outdated when I carried the mod to 1.3.
