### ISSUE TITLE
Newline pipes fail on gadget display

### ISSUE THREAD

**Issue by hupfen** [TerryCavanagh/diceydungeons.com#1407]
Reported on Discord:

https://discordapp.com/channels/423894813646127114/432114401177370624/619104086804922378

https://media.discordapp.net/attachments/432114401177370624/619104080207413259/unknown.png

Oh No! is the only gadget with a newline pipe in its description, so it's the only one currently affected.

**Comment by TerryCavanagh** [comment]
Got rid of these at some point, not planning to support the feature anymore. Closing!
