### ISSUE TITLE
Graphical issue: Confuse can make equipment show up partially outside the screen

### ISSUE THREAD

**Issue by grebnetiew** [TerryCavanagh/diceydungeons.com#1409]
![image](https://user-images.githubusercontent.com/1819251/64446858-3577c380-d0da-11e9-820b-277bbce8721e.png)

In my current (soon to end) run as the Inventor, I was confused by Warlock, and some of my equipment appears partially outside of the playing area. I believe the offending equipment is the ice item that takes Odd and gives Freeze 1.

Using it is possible, it works as expected if you drag dice on top of it.

**Comment by TerryCavanagh** [comment]
Fixed!
