### ISSUE TITLE
Crash with parallel universe Jester's Theif card

### ISSUE THREAD

**Issue by Thebusanman** [TerryCavanagh/diceydungeons.com#1410]
[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/3586397/_error.txt)
In Jester parallel universe i used the Thief card to gain a card for 1 gold, got bear maul+ and used it with a 6 while Fury? and Freeze? were applied end instantly crashed the game. 
Error log for the crash attached.

**Comment by TerryCavanagh** [comment]
Fixed!
