### ISSUE TITLE
Weakening an item with threequarterscountdown upgrade re-applies 3/4 reduction

### ISSUE THREAD

**Issue by hupfen** [TerryCavanagh/diceydungeons.com#1416]
Potentially related to #350.

Issue: when weakening Cornelius in Elimination Round, the Nightmare+ counter progresses faster than the dice put in. The amounts line up with being 3/4 of the final value of the countdown after the turn.

Turn 1:
Nightmare+ starts at 74, Nightmare- starts at 75
6 into Nightmare- for 69

69 * .75 = 51.75

Turn 2:
Nightmare+ starts at 52, Nightmare- starts at 53
4 and 2 into Nightmare- for 47

47 * .75 = 35.25

Turn 3:
Nightmare+ starts at 35 (weaken not applied)
4, 5, and 6 into Nightmare+ for 20

https://clips.twitch.tv/BlatantNaiveFerretDatBoi

**Comment by TerryCavanagh** [comment]
Fixed!
