### ISSUE TITLE
Consider implementing replayable macros sometime in the future

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1418]
Most player actions could be replicated with scripts, right? It wouldn't account for mouse movements or pauses for thinking your turn through, but supposedly the game could keep record of each move performed and allow the player to watch a replay of the entire run.

**Comment by TerryCavanagh** [comment]
Would have been great for playtesting, but we've left this too late for it to be worth doing now!
