### ISSUE TITLE
Soft Lock on a Super Alchemist fight

### ISSUE THREAD

**Issue by ProfessorProf** [TerryCavanagh/diceydungeons.com#1428]
Not sure what caused it - after she turned into a bear, I inflicted Shocked 1. She put one die into the open Maul, one die into unlocking the second Maul, then just kind of stopped. My turn never came.
![image](https://user-images.githubusercontent.com/23191536/64498956-9212e400-d27c-11e9-9ae6-4e33086192ab.png)
Run was Jester 6.

**Comment by TerryCavanagh** [comment]
Fixed for v1.7!
