### ISSUE TITLE
Inventor Fury Gadget doesn't work with all equipment

### ISSUE THREAD

**Issue by SomeGuyCalledRed** [TerryCavanagh/diceydungeons.com#1431]
I found one boomerang, upgraded it, cloned it, and turned the other into a gadget, after which using boomerang with fury caused the second hit not to register. It still came back and hit me, however. It's probably an issue with either the clone getting turned into a gadget or the gadget its self.

**Comment by TerryCavanagh** [comment]
Just checked in the latest version, and it looks like this works correctly now!
