### ISSUE TITLE
The 'Back to Title' button, makes all fights trivial

### ISSUE THREAD

**Issue by SomeGuyCalledRed** [TerryCavanagh/diceydungeons.com#1432]
If I am ever on a boss, and I am going to lose, I can choose to click the 'Back to Title' button through the ESC key and redo the boss. I never did after I found this issue, cause I want the money I spent to mean something, but imagine a Scathach fight - which is arguably the most luck dependent boss - and getting three '6' rolls. I can choose whether I take the loss, or redo for an easier time. All you have to do is remove the option to leave when you are in a battle. 

As people could still cheat thanks to the old alt f4 method, since this is meant to be a game show, what if force quitting and starting up again came with a cutscene. Lady Luck would say something like, "Sorry everyone at home, due to an unexpected occurrence, we had to close down the show this evening". Food for thought.

**Comment by lcenine** [comment]
Cheaters are going to cheat. Be it through save scumming, editing the generator, episode or  modsettings files or using something like  cheat engine.

**Comment by TerryCavanagh** [comment]
You're not wrong, but I'm not planning to change this at this point.
