### ISSUE TITLE
Enemies with 'Return Dice' Equipment causes AI issues

### ISSUE THREAD

**Issue by SomeGuyCalledRed** [TerryCavanagh/diceydungeons.com#1433]
The AI issue is most easily seen and understood with Handyman. If he rolls a 6, he will use it first on Jackhammer. Even though at this point it doesn't matter, he will still try to combine the dice. Before he gets to put his dice into Peashooter, his turn ends, and the die goes to waste. I have only noticed this when he has upgraded equipment so that could be the issue. My guess is that the game registers him using up all of his dice first and ends the turn without checking for more dice. There are other enemies with this property, in particular, Copycat, but Handyman is an easy example.

**Comment by TerryCavanagh** [comment]
This one is fixed in the latest versions!
