### ISSUE TITLE
Equipment rearranges itself in a zig-zag pattern

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1434]
![image](https://user-images.githubusercontent.com/32357485/64555949-5f2d2680-d336-11e9-8586-0cb84ec57d69.png)

Seems to be an issue with the way equipment is sorted. Here, I've arranged the items alphabetically - from left to right, then top to bottom. However, in battle, the items are arranged alphabetically, from top to bottom then left to right (in a zig-zag pattern).

**Comment by TerryCavanagh** [comment]
Fixed in v1.7! (at last!)
