### ISSUE TITLE
After beating the game, to quit and load will transform into jester

### ISSUE THREAD

**Issue by SirianRoux** [TerryCavanagh/diceydungeons.com#1435]
Hello,

I'm sorry for my low level in english.

When you beat Lady Alea (i did it with all characters to see if there is some changes or secrets) and you start a new game, if you quit the game and return (whatever when), you character will be transform to Jester and you will get his weapons. And the bow "change character" will apparear in game but you cannot change your character.

For information, the last time I beat Lady Alea is with Jester (maybe it's related).

Thanks for reading !

EDIT : I launched the game to make some screenshots to illustrate, but the bug didn't happen... I'm so confuse...

**Comment by TerryCavanagh** [comment]
Ah, I think this one was fixed in either v1.7 or v1.8!
