### ISSUE TITLE
Haunted Jar and Slime's remixes don't work together

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1436]
Slime's remix (Start each fight with 2 poison) has to manually decrease the 2 poison due to how innates and poison work together. Haunted Jar's remix (poison doesn't decrease each turn) therefore wouldn't work as expected - ideally you'd stay at 2 poison per turn (yikes!), but you'd in fact stay at 1 poison after the first turn.

**Comment by TerryCavanagh** [comment]
I could fix this issue, but actually these two are kind of a nasty combo, so I've just prevented the clash.
