### ISSUE TITLE
Consider making Vanish a stackable effect

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1438]
This could be neat for modding: make Vanish stackable, and ticks down by 1 every time a dice vanishes. Would probably focus on vanishing higher dice over lower dice. And make Fool's Fire inflict 5 or so vanish. This way player equipment that inflicts vanish could be worth handing out without it being horrendously overpowered.

**Comment by ncrecc** [comment]
Or split it into stackable vanish and vanish all, and make ff inflict vanish all

**Comment by TerryCavanagh** [comment]
Yeah, that probably would have been better than the current solution. I don't think it's worth changing at this point though.
