### ISSUE TITLE
[Inventor] Hellfire gadget is nonfunctional

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#1442]
The Hellfire gadget, created from Flame Spell (as can be obtained by using Reversal against the Wizard and ending the fight on the Wizard's gear), doesn't seem to do anything. The text states that it "burns a random amount", but unless one of the random amounts is zero and I got quite unlucky thrice in a row, it seems to be burning nothing at all.

**Comment by TerryCavanagh** [comment]
Ah, thank you! Fixed now.
