### ISSUE TITLE
Add new views to the translator mode

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1443]
This is a little overdue, but translators need to be able to preview some game text that's currently not easily viewable. This will also be useful for us! 

On this screen, I'd like to add the following new features:

![image](https://user-images.githubusercontent.com/2874150/64774910-fb307b00-d54c-11e9-86bf-f1745fe0720a.png)

**Shopkeepers**
![image](https://user-images.githubusercontent.com/2874150/64775392-f6b89200-d54d-11e9-8eab-73013d8e8bad.png)
![image](https://user-images.githubusercontent.com/2874150/64775302-beb14f00-d54d-11e9-8ee9-174fd86523bb.png)
![image](https://user-images.githubusercontent.com/2874150/64775759-c291a100-d54e-11e9-85b4-3cea5f4063bd.png)

I want to add three new screens that let you view all the Yolanda, Val and Ned dialogue in context. 

All three screens should show the "safe zone" for textboxes, but this is especially important for Ned, where a lot of our translators have ended up overlapping the equipment.

These screens should click through all the possible dialogue for the shopkeepers, so that we have it all in one place - similar to how the Lady Luck Introductions screen works (see Translator Mode -> Cutscene Test -> All Introductions).

The shopkeeper dialogue lines are located in shopkeepers.csv. Yolanda is "shop_initial" and "shop" in the Who column, Val is "trade_initial", "trade" and "trade_return", and Ned is "blacksmith_initial" and "blacksmith". You can ignore the ones that end in "_final", "_special" or "_bear", as they have different layouts.

**Remix Rules**
![image](https://user-images.githubusercontent.com/2874150/64776071-7004b480-d54f-11e9-8a06-99f126eab869.png)

I'd like to add a screen to let you see all the remix rules in the game in one place.

**Contestant Descriptions**
![image](https://user-images.githubusercontent.com/2874150/64776120-83178480-d54f-11e9-93c9-a5858d82c88b.png)

I'd like to add a screen to let you see all 24 Contestant Description signs in one place - there are four for each character depending on what point in the game you're in.

**Boss Dialogue**
![image](https://user-images.githubusercontent.com/2874150/64776225-b5c17d00-d54f-11e9-8687-09882d3420df.png)

When you view enemies in the translator mode, you have buttons available to make them say the various things they can say. However, this doesn't currently work for Bosses:

![image](https://user-images.githubusercontent.com/2874150/64776294-d093f180-d54f-11e9-9515-2edc15fdbc10.png)

Boss intro text is located in `cutscenes/specialenemyencounters.csv'.

![image](https://user-images.githubusercontent.com/2874150/64776349-eef9ed00-d54f-11e9-928c-98840528c24e.png)

**Episode Descriptions and Rules**
![image](https://user-images.githubusercontent.com/2874150/64776399-0d5fe880-d550-11e9-9fe3-6d121d96087c.png)

I'd like to add a quick screen to allow translators to check all the episode descriptions and rules in one place, with the same rough layout we use. (A lot of translators have line width issues here)

**Comment by mrcdk** [comment]
Done.
