### ISSUE TITLE
[Jester] [PU] If Multicardi is Curse?d, player still receives Multicardi effect

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#1451]
In the Parallel Universe episode, if the player triggers a Curse? using the Witch backup card Multicardi, the curse animation plays, the card disappears, and one stack of Curse? disappears, but the player still receives the Multicardi effect of a fourth card appearing in the hand and covering the Next Up UI.

Furthermore, the Multicardi effect persists into the next turn, even if it is in a new fight.

**Comment by TerryCavanagh** [comment]
Fixed (backup cards no longer trigger curse)
