### ISSUE TITLE
Animation Speed isn't saved along with the rest of your data

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1454]
![image](https://user-images.githubusercontent.com/32357485/64920859-16e98a80-d7b4-11e9-8fd8-0b812788107c.png)

This setting resets to "Very Fast" upon loading the game.

**Comment by TerryCavanagh** [comment]
Random bug of the day - should be an easy fix!

**Comment by TerryCavanagh** [comment]
Fixed for v1.9.
