### ISSUE TITLE
Boomerang and alive with negative life

### ISSUE THREAD

**Issue by TotesCoax** [TerryCavanagh/diceydungeons.com#1457]
I was on inventor, fighting stick man. I had 3 life left, wanted to go down swinging and used boomerang to just go out doing dmg. I used the attack, got negative life, but the stick man gave me the victory dialog and I got returned to map.

Entered another battle and upon first attack it was game over.

![bug in dicey dungeons](https://user-images.githubusercontent.com/55361250/64926214-0bed2500-d7c9-11e9-9a9e-13c872fdf8e6.PNG)

**Comment by findersjeepers** [comment]
Duplicate of #203

**Comment by TerryCavanagh** [comment]
Fixed!
