### ISSUE TITLE
Lock affix applied on reroll

### ISSUE THREAD

**Issue by Meptl** [TerryCavanagh/diceydungeons.com#1458]
Update: Initially I thought this was specific to enemies and a certain equipment. Turns out it applies to all rerolls.

I'm on episode 1-6 and encountered Handyman. I used a "Fishing Net" to lock a dice. Handyman AI used "Spanner" (Combine dice) on the remaining two dice. Handyman AI receives 1 or 2 dice and 1 of the dice receives a lock visual.

I have one case where the AI did not use the locked dice and another case where it uses the locked dice on the "Hammer" equipment.

Version 1.4.2, 14-09-2019

**Comment by Meptl** [comment]
This may apply to any reroll. Just experienced it with the Gargoyle and the "Avalanche" equipment.

**Comment by Meptl** [comment]
Just applied to my own dice on "Combat Roll" (Warrior - reroll). Updated the issue title. I however can't use the dice!

**Comment by Kailaria** [comment]
I want to add on that, even if this was fixed for Steam (which I've heard it was based on some streamers' experiences?), it is still not fixed on itch.io.

**Comment by TerryCavanagh** [comment]
Thanks for reporting this - it should now be fixed on both steam and itch!
