### ISSUE TITLE
Thief Ep.3 Infinite locked dices on Paper Knight

### ISSUE THREAD

**Issue by BenoitLarouche** [TerryCavanagh/diceydungeons.com#1459]
![image](https://user-images.githubusercontent.com/9299801/64927566-8a05f780-d7da-11e9-8e3c-88009307e2b8.png)
See image. Ennemy applies 2 Lock debufs, but the debuf is never subtracted. On every duplication, split, or even Trips, the 2 locks are re-applied, completely breaking the game progression.

![image](https://user-images.githubusercontent.com/9299801/64927597-dfda9f80-d7da-11e9-819e-b3dc85b792c2.png)

**Comment by TerryCavanagh** [comment]
This one was fixed before v1.5!
