### ISSUE TITLE
Burn doesn't affect Robot in Finale

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1462]
![Screenshot 2019-09-17 at 09 56 28](https://user-images.githubusercontent.com/48322734/65027041-9355a800-d931-11e9-9040-e6219c77b706.png)
Maybe this is a side-effect of Robot Calculate's status handling, which appears here because Robot's just using regular old dice?

(It does trigger when you switch characters to someone else)

**Comment by TerryCavanagh** [comment]
This one's fixed now! (thanks to the rules cpu character variable)
