### ISSUE TITLE
finale: Robobot not included in [machines] list

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1463]
![gif](https://giant.gfycat.com/RightDefenselessDiamondbackrattlesnake.gif)
HD: https://gfycat.com/rightdefenselessdiamondbackrattlesnake

In case it's not a deliberate character judgment, I was surprised that Robobot didn't count as a machine in the example above :)

**Comment by TerryCavanagh** [comment]
This is now fixed, at last! (thanks to https://github.com/TerryCavanagh/diceydungeons.com/issues/1767)
