### ISSUE TITLE
Game crash on Steam version due to a file write issue, despite appearing not to have any file write issues

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1466]
![image](https://user-images.githubusercontent.com/2874150/65187844-cea4c380-da64-11e9-8ece-1e78a6d28ebe.png)
![image](https://user-images.githubusercontent.com/2874150/65187863-d95f5880-da64-11e9-9e5f-4cd52f67def5.png)
![image](https://user-images.githubusercontent.com/2874150/65187880-e714de00-da64-11e9-9db3-9f9bceb2034d.png)
![image](https://user-images.githubusercontent.com/2874150/65187912-fa27ae00-da64-11e9-9828-e0c0aaad794c.png)
![image](https://user-images.githubusercontent.com/2874150/65187921-001d8f00-da65-11e9-81ce-77143c27eb04.png)

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/65188171-b2555680-da65-11e9-900e-b970b8b10e03.png)

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/65189578-4a087400-da69-11e9-9ee3-68ad7d2187e4.png)

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/65189618-64dae880-da69-11e9-83df-3228148d47e5.png)
This will be because the game doesn't do the achivement checking until after you press play on the title screen (in the `Game.initialloadachievements` function)

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/65191212-2b0ae180-da6b-11e9-856f-8ff7dccfcca2.png)

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/65191252-45dd5600-da6b-11e9-8aee-a1e32b9bb4c7.png)

**Comment by mrcdk** [comment]
Sounds like a permissions issue. If they are trying the old problematic file and it's causing issues but a new one isn't I don't know what else it can be. The itch.io app has an [sandbox mode](https://itch.io/docs/itch/using/sandbox.html) (disabled by default I think) which will limit the files a process can read/write and will run the game with a less-privileged user on Windows. So if they have it enabled that's may be the issue.

**Comment by TerryCavanagh** [comment]
From searching the discord, it sounds like this person got the game running, so I guess it was due to some kind of itch sandbox setting, or some other thing particular to thier computer. Closing!
