### ISSUE TITLE
Reloading a save with a changed generator will remake the dungeon, but any Super Enemies will be lost

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1468]
![image](https://user-images.githubusercontent.com/32357485/65338409-0b3a0180-dbc2-11e9-8d83-a02e40209ebe.png)

This is floor 4 - it contained Super Stereohead, Wicker Man, and Kraken before loading. After loading, Stereohead has been demoted to his regular level 2 form.

**Comment by mrcdk** [comment]
Fixed.
