### ISSUE TITLE
Softlocking enemy Super Bear

### ISSUE THREAD

**Issue by luciematics** [TerryCavanagh/diceydungeons.com#1469]
I'm playing the Warrior:3 scenario, and the Super Alchemist-transformed Super Bear won't act after being shocked twice and unshocking one of the Bear Maul attacks. Everything keeps running, but the bear doesn't feel like mauling my soon-to-die face, evidently. I'm running the latest version on Linux and replicated this issue with two different equipment sets and on different turn.

![bear](https://user-images.githubusercontent.com/55614075/65368435-f6d02600-dc0e-11e9-8620-801cfc7805b3.png)

**Comment by 5thHorseman** [comment]
I have a save where this happens pretty reliably. I'll try to find it and upload it asap.

**Comment by 5thHorseman** [comment]
Here's the save should start with the shape shifter as a valid enemy. Attack, shock them as much as possible. It happened to me both times I fought her and am not sure I can win without (or even with, really) using the shock.

[continuesave.zip](https://github.com/TerryCavanagh/diceydungeons.com/files/3934876/continuesave.zip)

**Comment by TerryCavanagh** [comment]
Finally figured this one out! Should be fixed for the upcoming patch!
