### ISSUE TITLE
Witch card for Jester when cursed just goes away with no new card to replace it

### ISSUE THREAD

**Issue by purple-pixie** [TerryCavanagh/diceydungeons.com#1470]
When Witch gets Cursed, it just goes away and doesn't give you a new card (let alone 2)

It does seem to make space for the extra card, and it removes your view of upcoming cards, but it leaves you just 2 cards in hand. I didn't test what happens if you then play more cards but I imagine that's stuff you can more easily find out if it's relevant.

![image](https://user-images.githubusercontent.com/1550193/65386365-ad78f700-dd32-11e9-9704-ef0d25d52e0a.png)

**Comment by findersjeepers** [comment]
See #1451

**Comment by purple-pixie** [comment]
> 
> 
> See #1451

This was regular Curse not Curse? because episode 6 and that doesn't mention not drawing a new card, but it's definitely related

**Comment by Frostplays-ZERO** [comment]
~~witch card~~ ALL cards vanish and do not get replaced when Cursed (iirc)

**Comment by TerryCavanagh** [comment]
Fixed (backup cards no longer trigger curse)
