### ISSUE TITLE
Booster packs appearing as triple pickups instead of Booster Packs

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1472]
When playing as Jester, booster packs are instead appearing as treasure chests on the map, and show triple chests when picked up:

![image](https://user-images.githubusercontent.com/2874150/65453690-9b36b000-de3b-11e9-89ee-60370db814c6.png)

It seems like they're getting picked up as ITEM rather than BOOSTERPACK. Could be due to the save format change?

**Comment by mrcdk** [comment]
Ops, silly c&p mistake, fixed!
