### ISSUE TITLE
GPU usage skyrocketing when super enemies appear

### ISSUE THREAD

**Issue by FionaFodona** [TerryCavanagh/diceydungeons.com#1473]
Whenever a super enemy appears on screen, GPU usage jumps from 5 to 99 percent, and quickly reverts back to 5 whenever the enemy is removed from the screen, for example when the inventory is opened. This is causing major lag, and crashing the game most of the times I try to enter a fight with a super enemy, which I'd assume is because of the white glow they have? I have no programming knowledge, and the game runs smoothly when no super enemies are present. Any idea why this is?

**Comment by FionaFodona** [comment]
Oh right! I should probably include the error message:
![dd error message](https://user-images.githubusercontent.com/55717077/65462394-1c864680-de2c-11e9-9768-a28b0e3b5f5f.png)

**Comment by TerryCavanagh** [comment]
Thank you, this is very helpful! The glow effect on super enemies is implemented with a shader, which is probably what's causing this unfortunately. I'll add a setting to turn that off in a future version.

For now, you should be able to fix this by just updating your graphics drivers! If you're on a laptop, make sure that you update *both* your onboard card and GPU card (usual an Intel and nvidia combo!).

**Comment by 00-Evan** [comment]
I've also been experiencing some performance issues with super enemies. Running a GTX 1080 at 1440p and latest drivers on game version 1.4.3. My GPU usage is usually at a steady 20% when in combat, but I just tested against super slime and had ~40% GPU usage with some stutter, but still high framerate. Some super enemies appear to be worse than others as well, I recall super marine being particularly bad.

**Comment by TerryCavanagh** [comment]
(Adding a setting to v1.9 to disable shaders.)
