### ISSUE TITLE
Minor UI bug: Attempting to open locked episode doors makes other doors unusable.

### ISSUE THREAD

**Issue by 00-Evan** [TerryCavanagh/diceydungeons.com#1474]
I was able to reproduce this on 1.4.3 with either the Witch or Jester, Episodes 1-3 completed. I clicked on the episode 6 door and the "this episode is locked" text persisted regardless of where I moved the mouse, and other doors would not longer be clickable. Backing out of the episode menu and then back into it allows doors to be clicked again.

This likely shows up in other cases where episodes are locked too, but I only had those two to test with.

**Comment by mrcdk** [comment]
Fixed.
