### ISSUE TITLE
Equipment with [;] in title shows up fine in the editor, but when given to you, game treats [;] as an actual comma

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1475]
So if I have modded items named "Padlock" and "Cookie Cake" and try to give myself an item named Padlock,Cookie Cake, it literally gives me Padlock and Cookie Cake:
![image](https://user-images.githubusercontent.com/11216597/65647939-4a0af580-dfce-11e9-98c4-40bd48adbcbe.png)
If I try to introduce a comma into any title where I'm not doing this on purpose (like with a card I made, "Berlin, Massachusetts Key") it usually just crashes the game by requesting at least one card that doesn't appear in equipment.csv, as expected

**Comment by Matz-42** [comment]
I want to suggest actually keeping this in-game, I dont see a reason why someone should absolutely be able to put [;] in an equipment name. This would allow putting 2 (or even more?) equipments in a chest pretty easily.

**Comment by ncrecc** [comment]
I don't want to literally put left-bracket semicolon right-bracket into a card name. [;] renders as a comma in most places.

**Comment by ncrecc** [comment]
May as well use [;] for commas in equipment names and | as a literal seperator of two equipments. Or vice versa.

**Comment by TerryCavanagh** [comment]
Fixed in v1.10!
