### ISSUE TITLE
Spannersword, if dodged, steals dice

### ISSUE THREAD

**Issue by mbodrov** [TerryCavanagh/diceydungeons.com#1479]
ver 1.4.3

When the enemy dodges your Spannersword, the Spannersword goes away still holding the two dice in it. You are left with no dice.

Expected behavior: the attack is dodged but you get back the combined dice.

This can possibly be happening with other dual-purpose "attack + manipulate dice" equipment as well.

**Comment by findersjeepers** [comment]
Similar issues originally reported in #489 and still confounding players.

**Comment by mbodrov** [comment]
It appears that yes, Dodge is the culprit. Any dodged attack produces nothing, as if it never happened.

Short of fixing Dodge, changing its description from "The next attack against you does no damage" to "The next attack against you has no effect" could be a stopgap measure.

**Comment by TerryCavanagh** [comment]
Dodge was fixed in v1.9!
