### ISSUE TITLE
Equipment disappears after shop purchase

### ISSUE THREAD

**Issue by cpoliver1989** [TerryCavanagh/diceydungeons.com#1483]
Pre-requisites - Must be playing Witch with a full Spellbook

Steps to reproduce

1. Go to shop to browse spells
2. Purchase a new spell
3. Select "Ignore It"
4. Click Shop again to browse spells again

Expected Results:  The purchased spell would remain in the shopkeeper's possession and the gold would not be removed until a user successfully added the spell to their spellbook.

Actual Results:  The gold is removed upon clicking the "Buy" button on the shop screen.  This creates a unique use case for Witch, where the user can then second guess their purchase and click "Ignore It" to "drop" the spell.  The spell is then deleted from both the user's inventory and the shopkeeper's inventory, causing the user to waste gold and get nothing in return.

Suggested Fix:  Have the spell remain in the shopkeeper's possession if the user clicks "Ignore it."  This would allow a user to simply repurchase the spell if they find enough gold on the same floor. 

(Best Fix would be to change the gold deduction from clicking the "Buy" button to instead only reduce when the spell is successfully added to the Spellbook.  However, that may be too drastic of a change, since gold deduction is global across all characters.)

Twitch clip to illustrate the issue

[https://clips.twitch.tv/ElegantFunnyAniseBrainSlug](url)

**Comment by TerryCavanagh** [comment]
We've implemented refund systems for normal shops, but it needs to be extended for Witch spells before v1.10!

**Comment by onetruepurple** [comment]
Still valid in v1.11!

**Comment by TerryCavanagh** [comment]
Fixed for v1.11!
