### ISSUE TITLE
If name overflows to another next line in equipment screen, second line isn't centered

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1484]
![image](https://user-images.githubusercontent.com/11216597/66173954-d34ea780-e620-11e9-9cd8-41b7b07608ad.png)
I could swear it used to be centered

**Comment by TerryCavanagh** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/2874150/94226978-8d30d900-ff40-11ea-80cf-fbc57ab914aa.png)
