### ISSUE TITLE
In Bonus Round, Drake (the enemy) isn't considered for Haunted Jar (the remix)

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1486]
![image](https://user-images.githubusercontent.com/32357485/66256638-d6b07300-e787-11e9-8ab9-5e7dd87ae90b.png)
A curse-related remix is more likely to show up if Scathach is the boss, so a poison-related remix should be more likely to show up if Drake is the boss.

**Comment by TerryCavanagh** [comment]
This one's been fixed for a while, just forgot to close it!
