### ISSUE TITLE
Thief steals unchanged items while the Marshmallow rule is in effect

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1492]
![image](https://user-images.githubusercontent.com/32357485/66514148-79dcf180-ead4-11e9-8714-1cec869c5b8e.png)

Marshmallow is in effect, and while fighting Fireman I stole a Fireball (this persisted throughout the fight)

**Comment by TerryCavanagh** [comment]
This one is fixed in the final v1.5 version!
