### ISSUE TITLE
Crystallize with Re-Equip summons offscreen crystal weapons

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#1493]
If Crystalina counts down the same Crystallize twice using the Re-Equip blessing, two crystal weapons are summoned, but one of them remains offscreen even if the first is subsequently used.

E.g.:
Crystalina turn 1:
-counts down Crystallize 1
-crystal weapon A is summoned offscreen because Crystallize 1 is Re-Equipped
-counts down Crystallize 1 again
-a second crystal weapon, B, is summoned, this time onscreen

Crystalina turn 2:
-uses onscreen crystal weapon B
-crystal weapon B disappears as expected but crystal weapon A does not come to occupy the vacant space
-uses offscreen crystal weapon A

I experienced this with Bonus Round Hard Mode Crystalina with the Re-Equip sourced from the Pirate rule, but perhaps presumptuously presume that it applies to Crystallize as well as Crystallize+, and that it applies to Re-Equip from Power Crystal as well as the rule.

**Comment by TerryCavanagh** [comment]
Fixed!
