### ISSUE TITLE
"goes first" innate text bestowed by Sticky Hands disappears after the first turn if enemy already has an innate

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1496]
I ran into this with Madison - her innate displayed "Madison is immune to freeze, and goes first." then after her turn ended (or was it mid-turn?) her innate reverted to "Madison is immune to freeze."

**Comment by TerryCavanagh** [comment]
Intended! This particular innate is programmed to disappear after the first turn. It just looks a little weird when an enemy has more than one innate.
