### ISSUE TITLE
Dodge stacks, Dodge? does not

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1497]
Just going by statuseffects.csv
This does have a minor effect in-game: if you get the Loud Bird rule in BR and run into an enemy that can dodge naturally, normally the dodge stacks, but if you have Warlock rule as well it won't, meaning Loud Bird rule won't be as bothersome with those enemies while Warlock is active.
Also probably applies to zany modded items that grant multiple dodge (if any exist).

**Comment by ncrecc** [comment]
As for how it would be implemented, seems kind of obvious to me: if the coin flip succeeds and enemy dodges the attack, decrease dodge? counter by 1

**Comment by TerryCavanagh** [comment]
Fixed, thanks!
