### ISSUE TITLE
AI bug: Wisp chose to put its last 2 in Backfire+ (or unstunning Backfire+?) when it could have annihilated me with Lightning Rod+. 

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#150]

**Comment by ncrecc** [comment]
Also, wizard would rather unlock a stunned spell than use another one.

**Comment by joshtriplett** [comment]
Similarly, the wizard can put a 3 into Backfire even though it could just as easily put that same 3 into a helpful spell.

**Comment by TerryCavanagh** [comment]
Wisp is gone now! Bye wisp!
