### ISSUE TITLE
[Thief] Hook does not properly re-equip multiple-use items

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#1502]
Rather than re-equipping after the item's multiple uses have been expended (e.g., Bump+'s two uses), the item is re-equipped after only one use. In essence, rather than getting to "re-equip" a particular item, the actual behavior is that you get one extra use. This is unintuitive at best. 

Issue may be broader than Hook, but I have not investigated in those other contexts at this time. Since Hookshot specifies +1 use, perhaps that text can be reused rather than changing the behavior.

**Comment by TerryCavanagh** [comment]
Ahhh this is intended. I think it's clear enough in context that re-equip grants an extra use of a particular equipment rather than resets the entire stack. Not planning to change this.
