### ISSUE TITLE
Illuminate causes effects to trigger multiple times

### ISSUE THREAD

**Issue by omor1** [TerryCavanagh/diceydungeons.com#1505]
Effects (such as Freeze and Burning) are triggered once after dice are regularly rolled and once more after dice are added due to Illuminate. For Freeze this seems to trigger all instances, so that the total effect is doubled (i.e. Freeze 2 effectively becomes Freeze 4), while for Burning this seems to only add one additional instance (i.e. Burning 4 becomes Burning 5).

This was probably caused by the fix for #1318.

For concrete examples, I played Witch episode 3 (Countdown). When facing Buster, he managed to burn 5 dice in a single turn. This is plainly impossible; while Buster is a fearsome dragon, he's not _that_ fearsome.

v1.5

**Comment by JuniorUdale** [comment]
https://youtu.be/AnbCyLHnHGQ?t=16m18s 
![image](https://user-images.githubusercontent.com/32357485/67420231-24214280-f5c6-11e9-9427-4cf8eaf3e145.png)
Here's some footage of this bug in action!

**Comment by TerryCavanagh** [comment]
I think this might be fixed, but I need to check - labelling it as a v1.10 issue!

**Comment by TerryCavanagh** [comment]
This particular case is fixed, so closing to simplify the issues list (a similar but distinct case is still open on the tracker)
