### ISSUE TITLE
[Jester] [LW] Cards stuck in place after using Delete

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#1506]
When I used Delete to permanently delete any card from my deck during a battle, the empty space remained in my hand and the other cards did not move leftward to occupy it until I used one of the two remaining cards on screen. If I deleted two cards in a row, the cards WOULD move leftward to occupy the emptied middle slot, but no further.

**Comment by TerryCavanagh** [comment]
Fixed in v1.8
