### ISSUE TITLE
Witch Thief which breaks when you enter a shop into triple rules

### ISSUE THREAD

**Issue by xboredim** [TerryCavanagh/diceydungeons.com#1507]
Ok so I decided to quit out of a bonus round for the witch and take a bonus round thief I choose the finders keeper rules then quit out before it loaded thinking I didn't want it before I decided to renter it cause actually it'd be quite fun. Suddenly I got the witches equipment and my side bar didn't appear and I was the witch sprite. I entered a shop it broke but it reloaded again so I just avoided the shop and choose the wolf puppy rule. Realized my side power somehow became change fighter before I cleared out the next floor then entered the shop which broke it making it so the hard mode rule and the rest were blank with all my equipment was gone despite my sprite changing back and when I reloaded it loaded the wulf puppy rule again with the previous one showing up to 3 times. I was also level 1 with 2 stars despite fighting everything up to the 3rd floor. I did in fact get triple fury and stole an equipment when I opened the game. Overall SUPER FUN but I figured I should report this.
<img width="1440" alt="Screen Shot 2019-10-19 at 6 26 38 PM" src="https://user-images.githubusercontent.com/56777976/67153586-f88a1980-f2a0-11e9-8fd8-036ba3d48bbb.png">
<img width="1440" alt="Screen Shot 2019-10-19 at 6 26 55 PM" src="https://user-images.githubusercontent.com/56777976/67153601-4272ff80-f2a1-11e9-9630-7c57027d4fe9.png">
<img width="1440" alt="Screen Shot 2019-10-19 at 6 27 13 PM" src="https://user-images.githubusercontent.com/56777976/67153609-61719180-f2a1-11e9-839d-be75ed67b4c4.png">
<img width="1440" alt="Screen Shot 2019-10-19 at 6 37 20 PM" src="https://user-images.githubusercontent.com/56777976/67153616-6f271700-f2a1-11e9-87c3-ba0af90e9b63.png">
<img width="1440" alt="Screen Shot 2019-10-19 at 6 37 27 PM" src="https://user-images.githubusercontent.com/56777976/67153623-7817e880-f2a1-11e9-869b-584ba69cbb03.png">
<img width="1440" alt="Screen Shot 2019-10-19 at 6 37 36 PM" src="https://user-images.githubusercontent.com/56777976/67153631-7fd78d00-f2a1-11e9-986a-37cd2a93baa6.png">

**Comment by TerryCavanagh** [comment]
Unfortunately, I think we fixed this for one of the recent updates 😅
