### ISSUE TITLE
Clean up weirdness caused by references to Sneezy's past design

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1508]
* Sharp Spike's current name is kind of weird since it no longer bears any similarity to Spike. It should either be renamed or removed entirely.
* Sneeze gadgetizing to Magic Lockpick doesn't make sense now that it doesn't split dice. Accelerate, maybe?

**Comment by TerryCavanagh** [comment]
Am happy with the legacy naming of Sharp Spike, not going to change that.

Good call on changing the Sneeze gadget to Accelerate, though! I've gone ahead and done that.
