### ISSUE TITLE
If you don't have anything to trade, have Val stay there and wait until you get one of the tradable items instead of disappearing

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1517]

**Comment by ncrecc** [comment]
Further suggestion: Val should never have one fixed trade; if you had an item val wanted to trade you but then destroyed it (e.g. Jester delete, Inventor) Val should find something else to offer, and only show "the shopkeeper sighs, it looks like she's not interested..." if you currently have no items whatsoever on you that she would be willing to trade for

**Comment by TerryCavanagh** [comment]
Val now never refuses to trade, the game always falls back to "something". The only time you should see this screen now is in very weird modding situations where you literally have no equipment.
