### ISSUE TITLE
Expect the Unexpected has no level 6 reward

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1518]
`episodes.csv` contains `leveluprewards(6[;]  [~WitchUpgrade~[;] ~WitchPrecast~]);`, when it should be `**leveluprewards(6[;] ~~[;] [~WitchUpgrade~[;] ~WitchPrecast~]);` - the empty string is causing no rewards to be offered.
![image](https://user-images.githubusercontent.com/32357485/67589052-7b065380-f74f-11e9-87e1-fce16cf68ae9.png)

**Comment by TerryCavanagh** [comment]
Fixed!
