### ISSUE TITLE
Inventor Card failing to trigger Jester special

### ISSUE THREAD

**Issue by OnlyAnAlligator** [TerryCavanagh/diceydungeons.com#1522]
I've noticed an odd interaction that the Jester's inventor card has with Ice shatter+, with it failing to trigger either the Jester's discard or snap special abilities. It will trigger Jester specials with other cards, and I have yet to test whether the problem is specific to Ice shatter+, is general to all + cards, or affects the base Ice Shatter (no plus) as well. I am using the latest build on Steam

**Comment by TerryCavanagh** [comment]
Finally figured this one out! Closing!
