### ISSUE TITLE
Add "On re-equip" column to equipment.csv

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1525]
This would enable a fast fix for #1290 (though would need something like e.maintainreequip)

**Comment by TerryCavanagh** [comment]
Ok, I've thought about it and decided not to do this - while it technically would be useful to have a special way to deal with this situation, I can add the functionality later as a variable in the `onexecute` script. For now, the priority is to work around the re-equip bugs on `giveequipment()` scripts, which I've done for v1.9.
