### ISSUE TITLE
Polish version problems

### ISSUE THREAD

**Issue by Pieczyyea** [TerryCavanagh/diceydungeons.com#1526]
Hello, 
There is a problem with font in polish translation, which makes some words to overlap on each other, sometimes making text undeadable (also no challenges word in right corner on character selection screen):
![20191028174219_1](https://user-images.githubusercontent.com/7414249/67698522-ccf6e580-f9aa-11e9-85f6-ab125a1b8502.jpg)
![20191019120043_1](https://user-images.githubusercontent.com/7414249/67698524-ccf6e580-f9aa-11e9-9302-ae6948893700.jpg)

**Comment by TerryCavanagh** [comment]
Thanks for reporting this! Should have the missing strings fixed in v1.6.1 tonight, and I'll sort out the line length issues in the next update!
