### ISSUE TITLE
Music stops working when you die and defeat an enemy on the same turn

### ISSUE THREAD

**Issue by bubbyboytoo** [TerryCavanagh/diceydungeons.com#1527]
Playing as the Inventor in the Halloween Special, I only had 1 HP left while my enemy (the Pirate, if that matters) had 6, and I used a 6 with Double-Edge to finish him off. While I won the battle, afterwards the overworld and battle songs became completely silent. The victory music wasn't affected, oddly enough, and while I'm not 100% certain on it I'm pretty sure the shop music was muted too.

**Comment by TerryCavanagh** [comment]
Fixed in v1.9!
