### ISSUE TITLE
[Halloween] Stuck looping on Continue/New Game screen

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#1529]
After a quit to title and attempted restart, attempts to select "Continue" redirected me back to the "Continue"/"New Game" screen. This persisted even after a restart. "New Game" worked, so it seems like a savefile issue.

Possibly irrelevant details: 
* testing branch was active
* Halloween was activated via the main menu button
* it was a Warrior run; I regretfully cannot remember which fight
* language was Traditional Chinese
* run was not first run of the session

**Comment by TerryCavanagh** [comment]
Figured this one out for v1.6.1!
