### ISSUE TITLE
Traditional Chinese localization issues [Halloween and base game]

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#1530]
I will collect here Traditional Chinese localization issues which I have found. Last updated 03Nov2019.
 
**Mistranslated:**
* **Snake Eyes jackpot ability is mistranslated as giving you a 2 ("2點骰子"); it should say that you are given two 1s ("兩個1點骰子")** [31Oct]
* **Pickaxe+ is mistranslated as being identical to unupgraded Pickaxe; it should have weaken before damage ("1弱化+_傷害")** [03Nov]
* **Dark Shadow is mistranslated as inflicting two *types* of condition ("2種"); it should say two *stacks* ("2層")** [03Nov]

Outdated:
* Pirate Hook?+ still has the incorrect description from non-PU Pirate Hook [03Nov]

Unlocalized:
* Most of the text on the new mod creation menu [30Oct]
* Solenoid card description [29Oct]
* Hedge Clipper card description [29Oct]
* Extra Turn status effect hovertext [29Oct]
* Parallel Universe backup card names: Witch?, Inventor?, Warrior?, Thief?, Robot? [30Oct]
* Slapsies text, both pre- and on activation (e.g. "In two turns, take 6 damage" and "SLAPSIES: Take 6 damage") [30Oct]
* "Slapsies+" status effect name [30Oct]
* Lady Luck's weakened Judgement (the one that does extra damage against full health) [30Oct]
* Several of Lady Luck's punishments:
** "Next turn, gain 99 Curses" [30Oct]
** "Next turn, burn all dice" [30Oct]
** "Next turn, blind all dice" [30Oct]
* "Blind all dice: In 1 turn, blind all dice" [30Oct]
* "Blocked __" (PU Protection? activation text) [31Oct]

Missing text:
* Witch level-up screen offering choice between upgraded and prepared slots is missing the word "slot" for the upgraded-slot choice: currently truncated at "已經升級的", should say "已經升級的欄位" [01Nov]

Needs a linebreak (currently clips past boundary):
* Overwhelm card description [29Oct]
* Ice Age card description [29Oct]
* Divine Dagger card description [30Oct]
* Parrying Dagger card description [31Oct]
* Double Rubble episode description on episode select screen -- just before "為什麼" would be good [03Nov]

Misplaced linebreak:
* Rat King defeat line: "[...] 王權萬古長/！總有 [...]" -- linebreak should be after the exclamation point, not before [31Oct]
* Kraken defeat line: "「戰鬥」/？" -- linebreak would look better before "「戰鬥」" [03Nov]

Overlaps:
* In combat: Inventor's name overlaps with her dice count [29Oct]

**Comment by TerryCavanagh** [comment]
Thanks for these! I've applied everything I could, and the changes will be reflected in v1.10!
