### ISSUE TITLE
"Back to title" from mod screen while in Halloween mod breaks Halloween mod

### ISSUE THREAD

**Issue by muizzsiddique** [TerryCavanagh/diceydungeons.com#1531]
If you were to relaunch the game with the Halloween mod active, you can go to the mod menu and immediately press "back to title" and then try to play the Halloween mod as normal. Some graphics will be missing and then the game would crash upon starting, as if it unloaded the mod while it was still using the mod.

**Comment by TerryCavanagh** [comment]
Ok, fixed this particular issue! (Although there are some issues in general with mod loading that I still want to look at after v1.10.)
