### ISSUE TITLE
Suggestion: Custom Status Effects in a manner akin to rules.addextrascript()

### ISSUE THREAD

**Issue by Frostplays-ZERO** [TerryCavanagh/diceydungeons.com#1533]
When i saw that the Halloween Special had added Spooky Fury and Haunt, I was hoping that we finally had arbitrary script injection via Status Effect (i.e. Spooky Fury would be `(~if(chance(50)){infictself(FURY); removestatusself(~spooky_fury~|1);}~|~playerequipmentuse~)` and Haunt just the Sneezy Remix in status effect form).

It was disappointing to find that no, they're STILL hardcoded.

Anyway, could you please add that? It would be fairly simple to do and a godsend for modders everywhere.

**Comment by ncrecc** [comment]
Everything currently hardcoded in Halloween Special is planned to be exposed at some point:
![image](https://user-images.githubusercontent.com/11216597/68071877-6af50200-fd55-11e9-9794-1e5f9881b5d7.png)

**Comment by Frostplays-ZERO** [comment]
I'm glad to hear it. I wonder how they're handled internally?

**Comment by TerryCavanagh** [comment]
Added custom status effects to modding in v1.9!
