### ISSUE TITLE
"manifest" folder bizarrely popped up in mods folder, game crashes on load if it's not in the same folder as diceydungeons.exe

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1535]
Specifically the logless crash ``[lime.utils.Preloader] ERROR: There is no asset library with an ID of "default"``

I don't remember ever seeing the manifest folder before today, or experiencing any preloader crashes like this before. Is this part of some misconfigured update? (Using Steam version)

**Comment by ncrecc** [comment]
To be clear, the bug here is mostly that manifest suddenly popped up with no warning *in an incorrect folder*

**Comment by TerryCavanagh** [comment]
Not sure what happened here, but I think without follow up reports I have to close this one as a bizarre once off that's probably not reproducible. If this ever happens again, please create a new issue!
