### ISSUE TITLE
Cards bunch in top left of screen after loading save

### ISSUE THREAD

**Issue by flankattack** [TerryCavanagh/diceydungeons.com#1539]
Episode: Jester 2
Version: v1.6.1 halloween special, 31-10-2019, STEAM, 64-bit, GL
Mode: Windowed
Steps to reproduce:
1. Save a run.
2. Load the run.
3. Start a battle.
4. The cards will all gather in the top-left corner before being spread out into the correct slots.

See the added image or video at around the 17 second mark for more information.
![image](https://user-images.githubusercontent.com/57522264/68461383-ff3bf900-026e-11ea-8f84-601dd4441f1a.png)
[video](https://drive.google.com/file/d/1j0b7I7kDZoF6b7w9JIQd3LoG1Sp_s0IA/view?usp=sharing)

**Comment by TerryCavanagh** [comment]
This one is fixed in v1.9!
