### ISSUE TITLE
Copycat refuses to move after using bump+

### ISSUE THREAD

**Issue by flankattack** [TerryCavanagh/diceydungeons.com#1540]
Episode: Jester 2
Version: v1.6.1 halloween special, 31-10-2019, STEAM, 64-bit, GL
Mode: Windowed.
Steps to reproduce:
1. Add the bump card.
2. Upgrade the bump card.
3. Battle Copycat.
4. Hand over control to Copycat.
5. Copycat will bump a die a couple times and then pause, never to finish its turn.

See the [video](https://drive.google.com/file/d/1j0b7I7kDZoF6b7w9JIQd3LoG1Sp_s0IA/view?usp=sharing) at around the 43 second mark for more information.

This can block the user's progress in the run (as illustrated in the video) if the Copycat must be fought and there are sufficiently few cards such that the Copycat will eventually use bump+.

**Comment by TerryCavanagh** [comment]
Hey! Looks like this one got fixed with changes to AI since v1.6. Thanks for the bug report!
