### ISSUE TITLE
Bear charge + still requires 10 dice on next turn after being weakened

### ISSUE THREAD

**Issue by tiffcw** [TerryCavanagh/diceydungeons.com#1549]
Depleated bearcharge+ from 5 to 2, then enemy weakened it to bearcharge-, counter changed to 4. I then brought the counter down to 1 while it was still bearcharge-, then on the next turn after recovering, the counter now starts at 10 instead of 5. Persists into next turns and battles

**Comment by TerryCavanagh** [comment]
Fixed in v1.9!
