### ISSUE TITLE
Snap sometimes doesn't work on Jester Elimination Round

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1552]
Not sure what's going on here, but have had one player report it and it's pretty serious if this is the case!

**Comment by ncrecc** [comment]
Might just be how trying to snap a card with its duplicate from Call for Backup Inventor doesn't always work

**Comment by TerryCavanagh** [comment]
Yep, you're right! Looks like this is a duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/1522 and https://github.com/TerryCavanagh/diceydungeons.com/issues/1096, thanks!
