### ISSUE TITLE
Enemy equipment is substituted in episodes that substitute equipment

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1555]
Specifically Two Handed Sword on Skeleton, but possibly some other cases (you should check!)

**Comment by ncrecc** [comment]
Also applies to Midnight Charm -> Iron Shield swap in Worse Than a Curse for Cowboy

**Comment by TerryCavanagh** [comment]
Ok! I wrote a safety check to look for cases where this happens, and it appears to just be Cowboy in Warrior 3 (Which was essentially a mistake that I've reverted) and Skeleton's Two Handed Sword for Jester Episodes (which I've swapped to use Backfire instead, since no enemies actually use it). Fixed!
