### ISSUE TITLE
"You have found x" text for substituted equipment you find in a chest (i.e. Marshmallow rule) is incorrect, and refers to the replaced equipment

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1559]
![image](https://user-images.githubusercontent.com/11216597/68811036-a63cde00-063d-11ea-9d20-5dd1353734a1.png)

**Comment by TerryCavanagh** [comment]
Recently fixed a bug with this particular string, should be working now!
