### ISSUE TITLE
Overworld music sometimes refuses to play on floors 2 and 4 for seemingly no reason

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1562]
Shouldn't be hard to replicate, enable click Z to teleport modding cheat and just keep going down floors in random episodes a bunch. This doesn't seem to be related to any specific episode. This *might* be related to how floor 2 is always supposed to use music from floor 1, and floor 4 is always supposed to use music from floor 3, but I'm not sure how

**Comment by TerryCavanagh** [comment]
I got stuck on this bug for a long time, but I've finally tracked it down! Fixed for v1.7 🎉
