### ISSUE TITLE
The game doesn't care about the X offset on the PNG boss animations

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1563]
No matter what X value is set in CombatAnimationOffset, the image's X origin point is always in the middle of the screen. I tried setting it to `400|-160` and `-160|-160` and both of them give the same result
![image](https://user-images.githubusercontent.com/26709843/68992808-818d7400-0892-11ea-88d3-4808cbea42b7.png)

**Comment by TerryCavanagh** [comment]
This is fixed in v1.9 with the addition of a new field in `fighters.csv`.
