### ISSUE TITLE
Yeti crash; attempting to use Ice Age locked by Poison?

### ISSUE THREAD

**Issue by Sir-Sneaky** [TerryCavanagh/diceydungeons.com#1567]
Currently on a Bonus Round with the Warlock rule that changes status effects, trying to fight a Yeti. Whenever the poison locks his Ice Age and he rolls doubles on the same turn, the game crashes at the start of his turn with an "AI thought this dice fit in this equipment, but it doesn't" error.

Attached are two crash logs and a screenshot of the game's state when the second crash occurred.

[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/3856283/_error.txt)
[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/3856284/_error.txt)
![Program_Manager_2019-11-17 (2)](https://user-images.githubusercontent.com/928558/69016301-17d49f00-0952-11ea-916c-abae60ef1881.png)

**Comment by TerryCavanagh** [comment]
This is fixed now!
