### ISSUE TITLE
French translation of Poison Cloud is the old version (claims to shock 2 rather than blind 2)

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1570]
![image](https://user-images.githubusercontent.com/11216597/69099832-bf70d080-0a29-11ea-983b-9d5b327a64c0.png)

**Comment by TerryCavanagh** [comment]
Fixed for v1.8!

![image](https://user-images.githubusercontent.com/2874150/74036796-4300e480-49bd-11ea-9cd2-1eb7eaf6f6c0.png)
