### ISSUE TITLE
@ comments in equipment names aren't really hidden anywhere except on the equipment graphic itself

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1571]
![image](https://user-images.githubusercontent.com/11216597/69100219-b03e5280-0a2a-11ea-99fc-d583417d6d62.png)
![image](https://user-images.githubusercontent.com/11216597/69100134-8127e100-0a2a-11ea-9877-cb736bade860.png)

(Obtained through editor, don't worry)

This has been around for a while but with no issue made for it. See also #1426 - Jester's "next up" skillcard doesn't hide the @ comments either

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/73201036-5ea3f980-4138-11ea-9083-af81d6b58316.png)

![image](https://user-images.githubusercontent.com/2874150/73201052-65327100-4138-11ea-9464-99f6ff988ce8.png)

![image](https://user-images.githubusercontent.com/2874150/73201247-e5f16d00-4138-11ea-8301-cd42189ff4fc.png)

Fixed for v1.7! (unless I've missed any cases where this happens)
