### ISSUE TITLE
Dice with invalid values (not 1-6) should display their value on the dice as text

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1575]
Would be useful in case a modded item accidentally gives you, for example, an 8 and you have no idea why you can't put this "one" in an ODD slot, or why it deals 8 damage and not 1.
![image](https://user-images.githubusercontent.com/26709843/69423863-125bc800-0d49-11ea-9609-655ee58dff94.png)

**Comment by TerryCavanagh** [comment]
Only d6s allowed, sorry 🤣 

(in all seriousness, this is a great suggestion, but I don't want to deal with whatever dark corners of the game might break as a result of this change, or any of the bugs that might arise from people trying to use out of bounds dice.)
