### ISSUE TITLE
Low health loop isn't stopped by title screen music

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1577]
Going to ping @TerryCavanagh because the fix for this is so simple: on line 20534 of new_soundevents.json (right below the properties for music_titlescreen), replace
```
		"stopsounds": [{
			"channel": 1
		}]
```
with
```
		"stopsounds": [{
			"channel": 1
		},
		{
			"file": "sfx/battle/lowhealth"
		}]
```
Or replace new_soundevents.json with this copy of it, with the change already made: https://i.frogbox.es/m0e

**Comment by TerryCavanagh** [comment]
Thank you for the bug report, and for making it so easy to fix :D
