### ISSUE TITLE
Elemental attacks aren't increased enough by Weaken?

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1582]
So if you attack Snowman with a 5 in Whip, while they have 1 Weaken?, they take 11 damage instead of 12. It seems like it's calculating (5 x 2) + 1 instead of (5 + 1) x 2 - not sure if this is intended?

**Comment by TerryCavanagh** [comment]
Oh, I think this is fine. Weaken? is like bonus damage on top, not to the base - makes sense to me.
