### ISSUE TITLE
The leveluprewards array is reset to an empty array after saving and loading

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1583]
Calling `trace(levelupselections);` in `Script: Change Floor` in Bonus Round prints `[InitialEquipment:Sword]` or similar. However, if you save and load the game, this just prints `[]`.

Maybe this is the cause behind sometimes not getting level up rewards in Bonus Round?

**Comment by TerryCavanagh** [comment]
Ahah! I knew there was an issue for this somewhere.

Anyway, we fixed this in v1.9, finally!
