### ISSUE TITLE
Multiple lock doesn't work with robot

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1591]
If you have multiple lock as Robot, only one dice is ever locked.

This is an old bug that 1.5 tried to fix, but that fix accidentally caused lock to apply *for all new dice generated* so it got reverted immediately. Doesn't seem to have an issue made for it though, and generally seems to have faded into obscurity.

**Comment by findersjeepers** [comment]
Duplicate of #1225

**Comment by ncrecc** [comment]
Oh, thanks!
