### ISSUE TITLE
Got character from last chapter after loading a game with warrior

### ISSUE THREAD

**Issue by Geoodees** [TerryCavanagh/diceydungeons.com#1598]
I did a quick run of the last chapter as the inventor. Then I did chapter 4 of warrior. I took a break, and after loading I got the inventor with a party. Reloading again crashes the client. Reloading a third time reloads the floor I was on as the warrior, but with starting equipments.

Crash dump from second load
`--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v1.6.1 halloween special / 0.13.0 (mod API)
sess. ID:	dicey_dungeons_2019-12-30_16'25'21
started:	2019-12-30 16:25:21
--------------------------------------
crashed:	2019-12-30 16:25:25
duration:	00:00:04
error:		ERROR in callscenemethod(DoYouWantToContinue,update) static : Error: Trying to create equipment "null" (null) from template, but cannot find a matching template in equipment.csv., stack = 
Called from elements.Equipment.create (elements/Equipment.hx line 169)
Called from elements.Equipment.new (elements/Equipment.hx line 17)
Called from elements.Fighter.createskillcard (elements/Fighter.hx line 352)
Called from utils.ContinueSave.applysaveddata (utils/ContinueSave.hx line 399)
Called from states.Episodestate.continuegame (states/Episodestate.hx line 358)
Called from states.DoYouWantToContinue.update (states/DoYouWantToContinue.hx line 46)
Called from FadeControl.update (FadeControl.hx line 78)
Called from Screen.endrender (Screen.hx line 277)
Called from states.DoYouWantToContinue.update (states/DoYouWantToContinue.hx line 71)
Called from Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 268)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 182)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)`

Attaching a screenshot from frist load.
![diceybug](https://user-images.githubusercontent.com/1905803/71588328-5cdb1c00-2b21-11ea-84c4-0425b0e83e7f.png)

**Comment by TerryCavanagh** [comment]
Fixed!
