### ISSUE TITLE
Flight has an associated gadget (Quick Thinking), Flight? does not

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1601]
This is, I believe, the only way Inventor can scrap something to Broken Gadget outside of Val/Yolanda rule: get Warlock rule in BR, find Berlin Key and scrap it to reversal, use reversal on Loud Bird and obtain Flight?
(Same issue exists with Dodge and Dodge?, but that's not as important)

**Comment by TerryCavanagh** [comment]
Fixed! Thanks!
