### ISSUE TITLE
Dictionaries can't be defined in generator files (and presumably elsewhere)

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1603]
![image](https://user-images.githubusercontent.com/32357485/71703764-5cb37880-2dce-11ea-989d-791548a284cc.png)

`var dict = [1 => "one", 2 => "two"];` is the offending piece of code. This isn't a *massive* issue since dicts aren't exactly a commonplace item, but it's worth considering adding these in

**Comment by TerryCavanagh** [comment]
This, unfortunately, is a limit of hscript's dynamic typing that I can't realistically work around 😔
