### ISSUE TITLE
If Jester is the boss with the Alchemist rule active, he can transform into a bear, preventing you from unlocking him

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1605]
I believe this was a reported bug that never got around to being fixed - someone in the bug report channel reported it though.

> I really don't know if it's a bug, but I already fought the jester as a boss once and it didn't unlock it for me as a playable dice. I don't know if it would have anything to do but it transformed into a bear midfight because of an episode 6 rule

**Comment by TerryCavanagh** [comment]
Yikes! This is a good one

**Comment by ncrecc** [comment]
Not a thing, reporter sent this message a while after:
[7:29 PM] MrCityWaffles: I deleted my previous message, got the jester after 3 more runs, but the bear interaction is kind of weird

**Comment by TerryCavanagh** [comment]
This is weird and actually kind of cool, and since it doesn't actually seem to block progress, I think I'm going to leave it in!
