### ISSUE TITLE
New Aoife is rather weak due to bonus on Charge! causing her to prefer it over broadsword even if broadsword can do more damage

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1606]
Which makes me wonder why the bonus is in place: is ai unable to judge "damage equal to getstatusself" correctly? Or is it like old wisp and bonus is because Charge! is a more interesting item than Broadsword?

**Comment by TerryCavanagh** [comment]
You're not wrong, but it feels like a mistake to mess with this now.
