### ISSUE TITLE
Gold Dagger and Silver Dagger deserve a buff

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1608]
Juggling Ball was recently made size 1, and considering how Gold and Silver Dagger are like sidegrades of it, it would make sense to give them a size reduction as well

Gold Dagger+'s upgrade is also kind of rubbish because it doesn't give you another value on which you get a new dice. Consider making both Gold and Silver Dagger upgrade to an unrestricted slot?

**Comment by TerryCavanagh** [comment]
Yep, good call! I've made some changes here.
