### ISSUE TITLE
Disable safety checks by default

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1613]
Safety checks do not need to run in release versions of the game - this is totally unnecessary, and is causing slowdowns for some bigger mods. Turn it off by default.

**Comment by ncrecc** [comment]
Will modders be able to turn it back on? (Or turn specific safety checks back on?)

**Comment by TerryCavanagh** [comment]
Yep! I'm planning to move the modsettings file out of data entirely and place it in the save folder, where it should always have been. Modders will be able to turn them on manually in that file.

**Comment by TerryCavanagh** [comment]
Done!
