### ISSUE TITLE
Polar Star disabling other equipment

### ISSUE THREAD

**Issue by brynjarb** [TerryCavanagh/diceydungeons.com#1615]
While playing warrior's "Parallel universe" my unupgraded Polar Star was unavailable on odd turns, as it should be. It also made another (seemingly) random equipment unavailable on even turns. This did not always occur, but I saw it happen twice in a handful of fights.

**Comment by TerryCavanagh** [comment]
Heya!

Any chance this was related to the Fury limit break? It works differently in Parallel Universe!

**Comment by brynjarb** [comment]
Hi!

That may absolutely be the case. Thanks for the quick reply!

**Comment by TerryCavanagh** [comment]
No worries, thank you for reporting bugs! Let me know if you run into anything else that doesn't look right! 👍
