### ISSUE TITLE
Some enemies don't act in warrior's "Bonus Round"

### ISSUE THREAD

**Issue by brynjarb** [TerryCavanagh/diceydungeons.com#1616]
The rules were Yolanda, Pirate, Bounty Hunter, and Sorceress, but it seemed like the second rule triggered some enemies to freeze even though they had plenty of dice and equipment. Could the "Re-equip next" be too heavy to calculate? The passive enemies I recall were Rat King and Aurora.

Cheers
Brynjar

**Comment by TerryCavanagh** [comment]
Ah, yep, something is bugged with enemy AI and re-equip next. I need to investigate this one and fix it for v1.8, it's one of the more serious open AI bugs.

**Comment by mimpedro** [comment]
Happened to me in Jester's bonus round, too. Sneezy and Dragon do absolutely nothing.

**Comment by TerryCavanagh** [comment]
Fixed! It turns out there was a bug with re-equip next when considering countdown equipment (i.e. Aurora, Sneezy, Buster, Rat King...). This should now work correctly in v1.9.
