### ISSUE TITLE
[v1.7] The @Something part after an equipment name can be shown with Rules.swap()

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1617]
For example if I had two equipments, one named "Test1@A" and another "Test2@B" and the following rule change: `Rules.swap(~Test1@A~, ~Test2@B~);`
They will properly swap between each other but the @ part after the name will be fully visible on the equipment.

**Comment by TerryCavanagh** [comment]
Ok! I guess I'm fixing this one!

**Comment by TerryCavanagh** [comment]
Ok, fixed!

https://streamable.com/p5f89e
