### ISSUE TITLE
[v1.7.1] Luck takes precedence over Luck+

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1618]
In the very edge cases where you might have Luck and Luck+ at the same times, only Luck has an effect. This is due to how equipments that uses Luck are made, here if we take Premium Heart script as an example:

`var odds = 10; if(getstatusself(~luck~) > 0){ odds += 10; } else if(getstatusself(~luck+~) > 0){ odds = 100; } attack(d); if(chance(odds)) { self.textparticle(~Success!~); inflictself(FURY); }`

Success odds with no effects: 10%
Success odds with Luck: 20%
Success odds with Luck+:100%
Success odds with Luck and Luck+: 20%

One way of fixing this would be to swap the if(){} and else if(){} around like that:

`var odds = 10; if(getstatusself(~luck+~) > 0){ odds = 100; } else if(getstatusself(~luck~) > 0){ odds += 10; } attack(d); if(chance(odds)) { self.textparticle(~Success!~); inflictself(FURY); }`

**Comment by ncrecc** [comment]
Or just keep the original ordering and drop the else

**Comment by TerryCavanagh** [comment]
Always happen to have nice easy ones to fix 😄 

I just removed the `else` from the functions for each one. Fixed!
