### ISSUE TITLE
[v1.7.1] Marshmallow rule doesn't take Wicker man and Banshee into account for generation

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1619]
Despite the two of them being over level 3 and inflicting either Burn or Freeze, the presence of Wicker Man and Banshee in the dungeon doesn't count towards the required 3 enemies for Marshmallow rule to generate.

**Comment by TerryCavanagh** [comment]
Fixed in v1.9!
