### ISSUE TITLE
Equipment stunned in battle still shows as stunned on the "make gadget" screen

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#162]
![](https://my.mixtape.moe/ozfsky.png)

**Comment by OtherworldBob** [comment]
In a similar vein, the Lightning Rod has filled in damage stats in the Gadget creation screen too:
![image](https://user-images.githubusercontent.com/12876244/40574997-c9d6f4be-60d4-11e8-9156-18a0cbeb94cb.png)
As it doesn't impact the creation of the gadget (as far as I can tell!) it seems a little unusual.

**Comment by TerryCavanagh** [comment]
Fixed!
