### ISSUE TITLE
Provide ARM Linux build

### ISSUE THREAD

**Issue by TheWhoAreYouPerson** [TerryCavanagh/diceydungeons.com#1623]
Primary motivation is to allow those using Chromebooks or Raspberry Pis to play Dicey Dungeons.
Most Chromebooks use the **aarch64/arm64** architecture, and are already able to use regular Linux applications through the Linux (Beta) feature to use applications like [community builds of Visual Studio Code](https://code.headmelted.com/#chromeos-install-scripts).

I imagine this would also be a good intermediary step (compiling for ARM, that is) to any upcoming mobile releases/ports.

Here are my outputs of [lsb_release/lscpu/uname/(/proc/cpuinfo)](https://gist.github.com/TheWhoAreYouPerson/3805b184e415bf5cbbbad04aac5d62d1) if it helps.
Thank you for your time, and the great game!

**Comment by TerryCavanagh** [comment]
This one is likely not happening anytime soon, sorry :(
