### ISSUE TITLE
Upgraded Memory Leak description is unintuitive

### ISSUE THREAD

**Issue by Splurmphy** [TerryCavanagh/diceydungeons.com#1624]
The upgraded Memory Leak for the Robot lists 2x(dice+1) damage on the Equipment screen. However, when using it, it behaves like the un-upgraded version of just 2x(dice), but starting at a max possible dice value of 6 as opposed to the un-upgraded 5 (see pic).

[This was while using the popular More Fluff mod, but the item is from vanilla DD.]

<img width="1440" alt="Screen Shot 2020-02-02 at 6 03 30 PM" src="https://user-images.githubusercontent.com/60587028/73617500-6575b500-45ed-11ea-8494-6d58761b1cb8.png">
<img width="1440" alt="Screen Shot 2020-02-02 at 6 04 19 PM" src="https://user-images.githubusercontent.com/60587028/73617502-6c9cc300-45ed-11ea-839a-5f5a05e440f9.png">

**Comment by ncrecc** [comment]
Memory Leak and its upgrade are specifically coded so that if the card has any extra dice slots, it decreases those before decreasing the maximum on the normal slot. Extra 1s are removed entirely.

You're likely confused because the more fluff item "Garbage Collection" works very similarly but maintains the extra 1 instead of sacrificing it. ~Jack your mod is broken again fix it~

**Comment by Splurmphy** [comment]
Ah—in that case, the upgraded description should probably be changed to reflect that, since it nowhere says the +1 will disappear. Thanks!

**Comment by ncrecc** [comment]
You may want to rename this issue to "Upgraded Memory Leak description is unintuitive" since there's nothing bugged here.

**Comment by mimpedro** [comment]
I came here to report this bug, but now I came here and apparently this is how it's supposed to work? Doesn't really make sense. Basically, the upgraded effect only lasts 1 turn, and from the second turn it behaves exactly like the normal version? It's very weird for a card that's only useful after a few turns.
