### ISSUE TITLE
Bow Wow Wow only works for Jester

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1629]
Consider making this work for all characters? Either that, or make it Special so others can't get it via e.g. Yolanda.

**Comment by TerryCavanagh** [comment]
For v1.9 I've made it so this card doesn't show up any more. This is kind of a weak card conceptionally that really only works with the Parallel Universe rules, and honestly isn't actually needed there (since Unavailable cards discard together anyway).
