### ISSUE TITLE
self.getvar returns 0 in an on end turn script added by Rules.addextrascript if the var it's trying to get wasn't also set in that script

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1630]
Take this remix rule:
``Rules.addextrascript(~trace(self.getvar(\~blahblah\~));~[;] ~endturn~); Rules.addextrascript(~self.setvar(\~blahblah\~|\~foooooobar\~); trace(self.getvar(\~blahblah\~));~[;] ~beforestartturn~); 
``
This traces "foooooobar" to the console before the start of the player's turn, then traces 0 at the end of the turn. If ``self.setvar(\~blahblah\~|\~foooooobar\~);`` is moved to be inside the end turn script, then it traces "foooooobar" as expected.
I'm not really sure what a workaround for this would be :/

**Comment by Matz-42** [comment]
This is actually due to a totally different but weirder bug, end of turn scripts added with Rules.addextrascript() actually trigger for the enemy.
So if you were to use target.getvar() instead of self.getvar() in the end of turn script you would actually get your variable value.
