### ISSUE TITLE
[v1.7.2] Echo Blast and Echo Blast? have different upgrades, that apparently leads to crashes when trying to upgrade Echo Blast?

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1634]
Echo Blast upgrade is a `change_power` that actually only gives a FREE1 spot (So it should probably be changed to a `add1` upgrade)
Echo Blast? upgrade is a `simplify` and Echo Blast?_upgraded doesn't even exist in equipment.csv when Echo Blast_upgraded does.
Apparently this lead to a "cannot find a matching template in equipment.csv" error when trying to upgrade Echo Blast?.

Echo Blast? upgrade should be changed to match Echo Blast one.

**Comment by TerryCavanagh** [comment]
Fixed for v1.10!
