### ISSUE TITLE
[v1.7.2] End of turn scripts added by Rules.addextrascript() trigger for the enemy instead of the player

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1635]
(This is actually what's causing [issue#1630](https://github.com/TerryCavanagh/diceydungeons.com/issues/1630) as well)
For some reason if you use:
`Rules.addextrascript(~WhateverScript~[;] ~endturn~); `
the script will be executed at the end of the player turn as expected, but will act as if the enemy is using it, so something like `attack(1);` will actually damage the player in that instance, while `attackself(1);` will damage the enemy.

**Comment by TerryCavanagh** [comment]
Fixed in v1.9!
