### ISSUE TITLE
Yeti don't like "Poison?"

### ISSUE THREAD

**Issue by Linkyop** [TerryCavanagh/diceydungeons.com#1636]
Game crashed, when his turn started. 1.7.2.

Video: https://streamable.com/n4lqs
Log: [_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/4176884/_error.txt)

**Comment by ncrecc** [comment]
Duplicate of #1567 
(Which itself is technically a duplicate of #1356 since this bug relates to AI and multislot equipment in general)

**Comment by TerryCavanagh** [comment]
Fixed!
