### ISSUE TITLE
[v1.7.2] French translation: Weird wording for blind

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1639]
The current french translation for blinding dice is;
"Aveugler sur [blind]1 dé" / "Aveugler sur [blind]2 dés"
Which roughtly translates to:
"To blind on [blind]1 dice" / "To blind on [blind]2 dice"

A better translation would be:
"Aveugle [blind]1 dé" / "Aveugle [blind]2 dés"
Which would translate to:
"Blind [blind]1 dice" / "Blind [blind]2 dice"

Edit: For reference here are all equipments using this wording:
- Ink Splat
- Camouflage
- The Shadow
- Justice
- Custard Pie
- Dust Cloud
- Smog Cloud (If the french description didn't incorrectly show it as Shock instead)

**Comment by TerryCavanagh** [comment]
Fixed! Thank you!
