### ISSUE TITLE
Wizard mode (feature suggestion)

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#164]
This could make it easier to gather info for the diceydungeons wiki, and/or poke around for new bugs. Things like:

Infinite inventory with access to all currently implemented equipment
Dummy opponent with a similarly customizable inventory whose moves would be selected by the player
Ability to swap out your inventory & opponent's inventory in the middle of a fight
Access to all gadgets
Selecting what/how many dice you have

Barebone interface would do as long as it's functional. Main point is that it would be available for players (maybe with some cheatcode on the title screen).

**Comment by TerryCavanagh** [comment]
Done, sort of!

**Comment by ncrecc** [comment]
- Infinite inventory with access to all currently implemented equipment
Sort of! "Special" equipment isn't selectable, which includes normal cards like Heat Sink that just aren't supposed to be used by most classes.
- Dummy opponent with a similarly customizable inventory whose moves would be selected by the player
Customizing the enemy's inventory was implemented (then taken out), but not selecting their moves. I suppose both can be done by modding your own enemy into fighters.csv and giving them really specific bonuses based on what turn it is.
- Ability to swap out your inventory & opponent's inventory in the middle of a fight
This never became a thing, doesn't matter much though.
- Access to all gadgets
Yep, except those only granted by special cards... though I don't know if any gadgets fit in that category.
- Selecting what/how many dice you have
Check. Selecting how many dice you have was put in editor, selecting *what* dice you have is currently implemented as a beta-exclusive debug feature.

It's a shame dd wiki shut down :( someone should start something like that again
