### ISSUE TITLE
[v1.7.2] French translation: Confusing wording for self-damaging equipments

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1640]
Backfire description in french currently is:
"Fait perdre [heart]5 PV"
("Cause the loss of [heart]5 LP")

This is obviously pretty confusing, as you might think it's causing the enemy to lose those health points instead of the player.

A better translation would be:
"Perdez [heart]5 PV"

This of course applies to the upgraded and weakened version of Backfire as well.

Edit:
This actually apply to all equipments that have a "Lose [heart]1 health" somewhere in their description, so this also includes:
- Backfire
- Stumble
- Nail Bat
- Candle
- Shadow Dice
- Blood Let
- Front Line

**Comment by TerryCavanagh** [comment]
Fixed! Thank you!
