### ISSUE TITLE
[v1.7.2] French translation: Subdivide+ description is exactly the same as the non-upgraded version

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1641]
Subdivide+ current description is:
"Casse un dé en deux|parties égales"
("Split a dice in two equal parts")
which is exactly the same description as the non-upgraded version, it doesn't reflect the "as evenly as possible" part of the Subdivide+ description.

Subdivide+ description could be changed to:
"Casse un dé en deux|parties les plus égales"
("Split a dice in the two most equal parts")

**Comment by TerryCavanagh** [comment]
Fixed!
