### ISSUE TITLE
[v1.7.2] French translation: Dramatic Exit is incorrectly presented as a healing effect instead of a maximum life point boost

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1642]
The current french description of Dramatic Exit is:
"[sword]1 dégât[;] si le coup est|fatal: restaure [heal]2 PV"
("[sword]1 damage[;]if the hit is deadly: restore [heal]2 LP")

This is obviously not what Dramatic Exit does, the description should instead be something in the like of:
"sword]1 dégât[;] si le coup est|fatal: +[heart]2 PV max"
("[sword]1 damage[;]if the hit is deadly: +[heart]2 max LP")

**Comment by TerryCavanagh** [comment]
Fixed! Thank you :)
