### ISSUE TITLE
[v1.7.2] French translation: Thunder Storm incorrectly described as "shocking a dice"

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1643]
Thunder Storm's current description in french is:
"[shock]4 dégâts|Choc sur [shock]1 dé|[gray](Une fois par combat)"
("[shock]4 damage|Shock on [shock]1 dice|[gray](Once per battle)")

This is obviously misleading and should be changed to:
"[shock]4 dégâts|Inflige [shock]1 Choc|[gray](Une fois par combat)"
("[shock]4 damage|Inflict [shock]1 Shock|[gray](Once per battle)")

**Comment by TerryCavanagh** [comment]
Done!
