### ISSUE TITLE
[v1.7.2] French translation: Last Stand? and Last Laugh? don't have an ellipsis in the translation

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1644]
Last Stand?: "Survivez pendant 3 tours|[gray](Une fois par combat)"
Last Laugh?: "L'ennemi survivra aux|trois prochains tours"

Should be changed as to keep the fact that something isn't right about the effect, to this:
Last Stand?: "Survivez pendant 3 tours...|[gray](Une fois par combat)"
Last Laugh?: "L'ennemi survivra aux|trois prochains tours..."

**Comment by TerryCavanagh** [comment]
Fixed! Thanks again :)
