### ISSUE TITLE
[v1.7.2] French translation: Memorise description gets out of bounds

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1645]
![image](https://user-images.githubusercontent.com/60510894/74337312-55ee2d00-4da0-11ea-9bad-2f7dda3c5b6f.png)
This could probably be fixed by changing the position of the line break from this:
`Remplace le sort de la case <slotdoubles>|par le sort inattendu`
To this:
`Remplace le sort de la|case <slotdoubles> par le sort inattendu`

**Comment by TerryCavanagh** [comment]
This one is fixed in 1.8 development 👍
