### ISSUE TITLE
[v1.7.2] French translation: Mirror Cauldron description is overly complicated and confusing

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1646]
Current description is:
"Octroie un dé|Sur un 6: vous le garderez|pour tout ce combat"
("Give a dice|On a 6: you will keep it|for this whole fight")

This might be confusing, as someone might think the player gets the dice back when using it, or maybe that the extra dice for the fight will always be of the value of the dice they just rolled. Looking at how Hall Of Mirrors is worded in french, I think a clearer and more consistent description would be:

"Octroie un dé|Sur un 6: +1 dé|pour ce combat"
("Give a dice|On a 6: + 1 dice|for this fight")

**Comment by TerryCavanagh** [comment]
Yep, good call! Implemented for v1.10.
