### ISSUE TITLE
[v1.7.2] French translation: Pitchfork description gets out of bounds

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1647]
![image](https://user-images.githubusercontent.com/60510894/74339410-4ec91e00-4da4-11ea-94cd-b457cbb02da5.png)
Could be fixed by changing the description from:
`[sword]<d6> dégâts|Inflige [fire]1 Brûlure et [shock]1 Choc`
to:
`[sword]<d6> dégâts|[fire]1 Brûlure et [shock]1 Choc`

**Comment by TerryCavanagh** [comment]
This one is already fixed in development! I've used `[sword]<d6> dégâts[;] inflige [fire]1|Brûlure et [shock]1 Choc`

Appreciate these issues, thank you! I'll run them past my French translators 👍
