### ISSUE TITLE
[v.1.7.2] French translation: The "(Always offered as scrap)" translation is extremely confusing and vague

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1648]
In the french translation, the (Always offered as scrap) part is translated to:
"(Trouvé dans les débris)" which literally means "(Found in the scraps)"

I suggest changing the wording to something less confusing, and going by the fact that in the french translation when inventor has to scrap something part of the text shown is: "Choisissez un objet à recycler" ("Choose an object to recycle") I think a good wording for it would be:

"(Toujours recyclable)"
"(Always recyclable)"

For reference here are the equipments using the wording:
- Scrap Metal
- Scrap Kettle
- Scrap Spear
- Scrap Club
- Scrap Book
- Scrap Bump
- Scrap Nettle
- Rotten Egg (`@1` to `@6`)
- Iced Latte

**Comment by TerryCavanagh** [comment]
Done. Good suggestion, thank you!
