### ISSUE TITLE
[v1.7.2] French translation: Squawk being translated to "Croassement" doesn't make sense as a Loud Bird equipment

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1649]
Squawk is translated to "Croassement" in the french translation.
However in french "un croassement" is used to describe the cry of a crow or a raven, and I don't think Loud Bird is either of those.

I would suggest translating it to "Piaillement" instead which is a more generic word for a loud bird cry.

**Comment by TerryCavanagh** [comment]
Sounds good! Fixed for v1.10.

**Comment by TerryCavanagh** [comment]
Actually, my translators disagree on this one, so I've reverted it!
