### ISSUE TITLE
Redesign/scrap wisp

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#165]
It's too complicated, and not fun. I think an enemy using something as complicated as a lightning rod just ultimately doesn't work.

You could reuse the sprite and name for a new enemy in v0.8 once you've done the elemental redesign.

**Comment by joshtriplett** [comment]
I find it an interesting opportunity for strategy; you have to figure out how to whittle it down at a level where you can afford to get hit, then take it out in one turn. (Or alternatively, make sure you've protected yourself well enough.)

**Comment by TerryCavanagh** [comment]
Done. Might try a different enemy that plays with these ideas in future, though!
