### ISSUE TITLE
[v1.7.2] French translation: The Alternate status effect version of some equipments don't have a description that properly reflect their change

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1650]
Some ? versions of equipments that change with Alternate status effects, don't have a proper change in their descriptions to reflect the change of the status effect, this is the case for the following status effects:

**Weaken equipments:**
"Affaiblit x equipment(s)" _("Weaken x equipment(s)")_ should be changed to "Inflige x Affaiblissement(s)" _("Inflict x Weaken")_ or "Affaiblit l'ennemi" _("Weaken enemy")_ if there is only 1 weaken.
Affected equipments:
- Shovel?
- Sonic Wave?
- Echo Blast?
- Earthquake?

**Blind equipments:**
"Aveugler sur x dé(s)" (which is an incorrect translation, see #1639) should be changed to "Aveugle pour x tour(s)" _("Blind for x turn(s)")_.
Affected equipments:
- Ink Splat?
- Camouflage?

**Freeze equipments:**
"Gèle x dé(s)" _("Freeze x dice")_ should be changed to "Inflige x Gèle(s)" _("Inflict x Freeze(s)")_.
Affected equipments:
- Snowball?
- Freeze Spell?
- Ice Shard?
- Ice Crystal?

**Comment by TerryCavanagh** [comment]
Fixed all! Thank you for all for these, they'll be applied in v1.10 🎉
