### ISSUE TITLE
[v1.7.2] French translation: Accelerate (gadget) description is somewhat confusing

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1651]
Accelerate description is:
"Tous les compteurs à 6"
("All countdowns at 6")

This can be somewhat confusing, as this can be understood as setting all counters to 6 instead of reducing them, a more fitting translation could be:
"Reduit les compteurs de 6"
("Reduce countdowns by 6")

**Comment by TerryCavanagh** [comment]
Makes sense! Changed for v1.10.
