### ISSUE TITLE
Crash: Using "Yoink" when enemy has no equipment

### ISSUE THREAD

**Issue by shickey** [TerryCavanagh/diceydungeons.com#1652]
Here's a *very* particular set of circumstances that just caused a crash while I was playing:

- Play as Jester in Bonus Round (I was playing hard mode, but I don't think it matters)
- Have the "status effects work differently" rule applied to the round (specifically, so that Curse functions as Curse?)
- Play against Aurora
- Curse? Aurora (I was using the "Evil Laugh" set of cards, though again, I don't think it matters)
- Have the Curse? trigger when Aurora tries to "clear the weather" thus disabling the card and giving you the dice. Now Aurora has *no* cards and won't have any cards on subsequent turns
- Have the "Yoink" card in your hard
- Try to play "Yoink" after Aurora has been left with no cards
- Crash!

Screenshot:
<img width="1440" alt="Screen Shot 2020-02-12 at 9 45 53 AM" src="https://user-images.githubusercontent.com/1489558/74346786-14e52100-4d7e-11ea-939b-5c2c1560dac3.png">

Crash log attached:
[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/4192958/_error.txt)

**Comment by TerryCavanagh** [comment]
Thank you! This is a great bug report - always appreciate crash logs and reproduction steps!

**Comment by shickey** [comment]
Sure thing! Thanks for a great game! My favorite of the last few years, for sure!

**Comment by TerryCavanagh** [comment]
Fixed in v1.9! (Mood Change can no longer trigger curse, which prevents this situation)
