### ISSUE TITLE
[v1.7.2] French translation: Ruff Ruff Ruff and Yip Yip Yip have their right parenthesis colored red

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1653]
Self explanatory.
**Ruff Ruff Ruff:**
![image](https://user-images.githubusercontent.com/60510894/74347306-31e71780-4db1-11ea-94fa-35609c9283e5.png)
**Yip Yip Yip:**
![image](https://user-images.githubusercontent.com/60510894/74347442-62c74c80-4db1-11ea-99a7-45b0c8a19ecf.png)

**Comment by TerryCavanagh** [comment]
Fixed!
