### ISSUE TITLE
[Suggestion] Consider adding seperate "smart" and "automatic" AIs for the use of Countdowns equipments

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1654]
This would be used in order to let some enemies make some better plays; Namely Sneezy, Rat King, Buster, Beatrice and I guess Copycat. All that while keeping the way some other enemies work the same, namely Alchemist, Aurora and Crystalina.

The "automatic" AI, would look at countdowns and use them the same way the AI already does right now, always using countdowns in their order in the inventory, this is necessary so enemies like Alchemist Aurora or Cystalina don't break.

The "smart" AI would consider every Countdown possible, and woudn't restrict themselves to the first one available in the inventory and would take into consideration the power of the countdown, aswell as using dice as effectively as possible.

Which enemy uses which AI could be simply defined in fighters.csv, and this might give a use for the AI column which is currently unused.

**Comment by TerryCavanagh** [comment]
No longer an issue! With v1.11, we've substantially optimised countdown equipment, and this runs much faster now.
