### ISSUE TITLE
[v1.7.2] French translation: Keymaster wanting to take dice as slaves

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1656]
In the french translation Keymaster's line:
`Oh, nicely done! Really solid fighting there!||You're going to make such a great minion once you lose!`
Is translated as:
`Oh, joli ! Un bien beau combat !|Je serai enchanté de faire de vous mon|esclave, lorsque vous finirez par perdre !`
Which itself would translate to:
`Oh, nice ! A really beautiful fight!|I will be delighted to make you my|slave, when you will eventually lose !`

Obviously the problem here is Keymaster's enthusiasm about the character being a minion being miscomprehended and mistranslated as Keymaster making them his personal minion, and I guess minion being translated as "esclave" (slave) is a poor choice of word.

**Comment by TerryCavanagh** [comment]
I need to check this one with my translators to see what they want to do, but we will probably be changing it. (We actually had exactly the same problem with Dutch, and changed that)

**Comment by TerryCavanagh** [comment]
Resolved! This line is changed to:

```
Oh, joli ! Un bien beau combat !
Vous ferez un excellent larbin lorsque vous finirez par perdre !
```
