### ISSUE TITLE
"enable right click to instanty win" modsetting is no longer functional

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1660]
Right-click does not make you win regardless of whether you set it to true or false, and the right arorw on the top-left no longer shows up either.

**Comment by JuniorUdale** [comment]
It's a typo from an older version. If you remove the typo and rename it to "enable right click to instant**l**y win", then setting it to `true` works as expected.

**Comment by ncrecc** [comment]
Well, I'm dumb then
