### ISSUE TITLE
[v1.7.2] Spatulasword is a Witch spell despite being size 2 now

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1664]
Images speak for themselves:
![image](https://user-images.githubusercontent.com/60510894/74958716-a81af800-5409-11ea-8221-382b3c2c154b.png)

**Comment by ncrecc** [comment]
Presumably the solution will be this:
![image](https://user-images.githubusercontent.com/11216597/75071358-3901da00-54c3-11ea-98e0-4aee06ce394f.png)

**Comment by TerryCavanagh** [comment]
Fixed! (I just removed this from the unexpected spell list)
