### ISSUE TITLE
Make upgraded enemies use the deckupgrade version of equipment, if available

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1667]
This should solve the issue of e.g. Handyman's Hammer not really "upgrading" for Elimination Round.

**Comment by TerryCavanagh** [comment]
Yep! This is a good call, so I made this change for v1.8. It affects three enemies: Handyman (very minor change), Rhino Beetle (an acceptable power increase), and the new Bounty Hunter (Electromagnet now starts at 5 instead of 4.)
