### ISSUE TITLE
[Suggestion] Make Silence? weaken the Skill Card aswell.

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1669]
PU Silence is currently pretty weak compared to normal Silence, making it weaken the skillcard as well would make it a little better and kind of unique since Skillcards aren't supposed to be weakened in normal gameplay.
This should be easy to implement for Thief and Warrior, and would just require giving some skillcards actual weakened version.
For Inventor and Witch it's a bit more tricky. For inventor maybe giving each possible Gadget a weakened version could work, as for Witch something like disabling throwing dice, or maybe make every spell require 2 dice to prepare would be interesting.

**Comment by ncrecc** [comment]
We had a nice discussion about this last May, terry seems to have overlooked it though:
![image](https://user-images.githubusercontent.com/11216597/75210562-6f538980-574f-11ea-9a39-5520dbbd1122.png)

**Comment by TerryCavanagh** [comment]
This is a cool suggestion: but I'm not planning to change how PU Silence works at this point in development. Sorry!
