### ISSUE TITLE
[Suggestion] For modding, make innates referenced into a csv file

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1670]
This could add the ability to change innate text, add new innates, and possibly add simple On evenements scripting for innates.

**Comment by TerryCavanagh** [comment]
Innates are not getting any changes at this point; but since this issue was created it's now possible to do whatever custom innates you want with invisible status effects! (innates are just strings, so you can make them say whatever you want)
