### ISSUE TITLE
[1.7.2] Copycat using Saw Wave fails to generate the dice

### ISSUE THREAD

**Issue by ikdzu** [TerryCavanagh/diceydungeons.com#1673]
When a Copycat attempts to use Sine Wave, the dice don't generate for the enemy and he essentially wastes them as he doesn't attempt to reuse them.

I was playing as Robot, level 4.
I was playing the bonus round game type.
I had Keymaster and Hothead rules applied.

**Comment by ncrecc** [comment]
AI doesn't understand "must equal x", Copycat likely tried to force dice that don't equal 7 into Saw Wave.

**Comment by ikdzu** [comment]
Ah, that'll maybe explain it.  The AI turn ended too quickly and I didn't actually see the dice values he was using.  Is this an already existing issue then?  If so, I will close.

**Comment by TerryCavanagh** [comment]
Fixed!
