### ISSUE TITLE
Thief's stolen items are unaffected by the Keymaster rule

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1675]
![image](https://user-images.githubusercontent.com/2095534/75814565-41df8f00-5d92-11ea-83c5-786b8836ab1c.png)

![image](https://user-images.githubusercontent.com/2095534/75814655-6b001f80-5d92-11ea-8ca6-305c8ea87870.png)

**Comment by TerryCavanagh** [comment]
Fixed in v2.1.
