### ISSUE TITLE
[Traditional Chinese] translations of status effects

### ISSUE THREAD

**Issue by CookieAlien** [TerryCavanagh/diceydungeons.com#1676]
- Frozen (被冰凍了) is a weird translation (although it's correct), just use 冰凍 
- description of Frozen?: 減少所有骰子的價值<value>, could be 減少所有骰子的點數<value>點
- Burn (燃燒) is good, so Burn?(火燒?) should also be 燃燒?
- description of Burn?: move 使用 to the last word of the description
- 驚嚇 is not a good translation of shocked, it is one of the translations of shock, but it refer to one's reaction to something unexpected. To refer to get electric shocked use 觸電 or 麻痺 instead.
- description of weaken: 暫時禁用隨機裝備(as same as shocked) should be 暫時弱化隨機裝備
- description of weaken?: 每次攻擊可造成[sword]<value> 額外傷害, "可造成" means "can deal', could be "受到" instead. Also.(在每次遭受[sword]1點弱化時) means "everytime when taking 1 weaken", could be "每層增加[sword]1點傷害"
- description of poison: "穿透" is a little better than "穿過"
- description of poison?: "在你的回合結束時，計次會歸零" means "countdown reduces to zero each turn", could be "在你的回合結束前將計數歸零"
- description of throns?:"每個[sword] 1點提供一個[thorns]刺" means "each [sword] gives one spike[throns] ", could be "每個[thorns]荊棘提供[sword]1點傷害"
- shield(防禦) and shield?(盾牌): could use 護盾 and 護盾?

There's much more but I don't have time to cover all of them.

**Comment by TerryCavanagh** [comment]
Thanks for this - I've applied most suggestions to the game for v1.9!
