### ISSUE TITLE
Rose bonus rule (+1 damage) does not count towards Witch challenge (12 damage with thrown dice)

### ISSUE THREAD

**Issue by yogurt-on-github** [TerryCavanagh/diceydungeons.com#1677]
The extra damage from the Rose bonus round rule, which makes all attacks deal +1 damage, does not seem to count towards the Witch challenge ("do 12 or more damage in one turn by throwing dice").

The thrown dice do 2 damage each, as expected, but even dealing 14 damage with dice in one turn was not recognized by the game. (The enemy did not have armor or reduction.)

The enemy *did* have dodge, but thrown dice bypass dodge, so I don't think this was relevant. 

Version 1.7, Steam edition.

**Comment by TerryCavanagh** [comment]
Thanks for the bug report! This one is now fixed in v1.9.
