### ISSUE TITLE
v1.7 Witch: Blizzard Visual Glitch

### ISSUE THREAD

**Issue by Regalus27** [TerryCavanagh/diceydungeons.com#1678]
Sometimes after casting Blizzard, the card will vanish like a normal piece of equipment from other classes. At the start of your next turn, Blizzard will have reappeared, so it is a purely visual glitch from what I can tell.

The situation I encountered this in is was:
Illuminate | Blizzard
Illuminate | Blizzard*

The bottom right Blizzard would vanish after being played.

Other notes:
 - The top two slots were prepared slots.
 - Illuminate was on spell slot 5
 - Blizzard was on spell slot 4
 - Both Blizzards were being filled with double 5's
 - The version of the game is the most current version on steam, March 8, 2020. 

Let me know if you need further information, I'll probably remember to check this thread again.

**Comment by TerryCavanagh** [comment]
This is now fixed! Sorry, I should have closed this years ago - found it during this current issues cleanup round.
