### ISSUE TITLE
[Suggestion] In statuseffects.csv, add in a new "Positive Status?" Column for its interactions with Reduce?

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1682]
Reduce? is currently hardcoded to not work for specific Status effects (Some Positive status effects).
The problem with that first is that some positive status effects are still blocked by Reduce? Second is that it will always block ALL modded status effects, no matter if they're "good" or "bad".

The solution to that is to add a simple column in statuseffects.csv, that let's specify if a status effects is a positive status effects. Reduce? will simply then not block positive status effects.

**Comment by TerryCavanagh** [comment]
Done! You can now specify whether or not Reduce By? blocks specific status effects in statuseffects.csv.
