### ISSUE TITLE
[1.7.2] The AI considers all slots of an equipment to be the same, leading to either crashes or suboptimal plays.

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1683]
(This causes issue #1548 aswell)

The AI will consider all slots on a multi-slot equipments to be the same as the first one, this can have several effects:

If the first slot is more restrictive than the other ones, this might lead to the AI making suboptimal plays.
For example with a MAX3/NORMAL equipment, the AI will see it as a MAX3/MAX3 and never put a 4,5 or 6 into the second slot no matter what.

If the first slot is less restrictive than the other ones, or takes totally different values than the other ones, this might lead to the game crashing with the error "AI thought this dice fit in this equipment, but it doesn't.".
For example with a NORMAL/MAX3 equipment, the AI will see it as a NORMAL/NORMAL and may attempt to put a 4,5, or 6 into the second slot leading to the above error.

**Comment by TerryCavanagh** [comment]
(This bug has increased in importance a bit with v1.8, with Flame War+ and System Shock+. If Bounty Hunter borrows those it can crash the game.)

**Comment by TerryCavanagh** [comment]
Fixed in v1.9! The AI now correctly considers multislot equipment slot by slot.
