### ISSUE TITLE
Game freezes when exceeding 42 (full vertical height) on-screen dice.

### ISSUE THREAD

**Issue by AdrianCollado** [TerryCavanagh/diceydungeons.com#1684]
When 42 dice on-screen are exceeded (7 rows of 6, fully filling the screen vertically), the game will lock up and eventually need to be killed. This was tested on Windows.

This crash occurred when playing as the Witch against Sticky Hands, as it was possible to continually go through turns (purposefully) without actually winning, while continuing to increase the number of dice on the screen at the start of each turn. When the game attempts to start the next turn where some dice would be off-screen at the start of the turn, the game will completely freeze. It will remain in this state until it is forcibly killed.

The setup for this was done by using Hall of Mirrors to increase the number of dice each turn, and Hex to prevent the Sticky Hands from running away (by using shock). Additionally, no damage-dealing attacks were used.

**Comment by TerryCavanagh** [comment]
Fixed for v1.9!
