### ISSUE TITLE
Player loses all shield when gaining dodge

### ISSUE THREAD

**Issue by mimpedro** [TerryCavanagh/diceydungeons.com#1685]
Happened in a Bonus Round with Robot.

In the same turn, I used:
**Forcefield**, which made me gain 4 shield
**Power Crystal+** (obtained from egg), which made me receive the "Dodge" status, but I lost all shield.

**Comment by JuniorUdale** [comment]
Are you sure that you lost the shield immediately after getting Dodge? Which enemy were you up against, and which rules were in effect?

**Comment by mimpedro** [comment]
Sorry, I only wrote down this much info. As far as I can remember, I didn't have any other status effect at the time, and it happened in my turn, so what the enemy did didn't affect much the situation. As for the rules, I can't remember :(

I think this bug can be discarded if the devs can't reproduce it, because after these questions I'm starting to question my memory (maybe the shield was not even added in first place?). I could try to reproduce the bug, but since it depends on getting a Power Crystal from an egg, it will be a little bit hard :(

I'll be sure to write down more info (and maybe a screenshot) next time I stumble across a new bug.
