### ISSUE TITLE
Got normal weapon without counters in Inevitability of Rust

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#1689]
Same as issue  #1350 but with a Staff and in v 1.7.2. The Staff has no counter. On upgrade a counter appeared on the upgraded version.

No idea how to replicate.

**Comment by ncrecc** [comment]
Was it weakened at any point?

**Comment by lcenine** [comment]
I don't _think_ so. But maybe. I'm sure I didn't notice it when it first started to occur.

**Comment by TerryCavanagh** [comment]
Fixed in v2.2!
