### ISSUE TITLE
Enemy assumes cards with multi-slot shock have all slots in the same position

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1696]
Ran into trouble with this while making a silly implementation of silence for enemies: ![](https://media.discordapp.net/attachments/473868039167934464/706708886354395248/unknown.png)
Stereohead softlocks the game because he tries to shove two dice into the same slot, and then sits around waiting for something to happen.

**Comment by TerryCavanagh** [comment]
This one won my third bug lottery for today. It's pretty low priority, but I'll see what I can do!

**Comment by TerryCavanagh** [comment]
Done! 😄 

https://streamable.com/q41hcb

I'm as surprised as anyone that this got fixed. All hail the random bug lottery!
