### ISSUE TITLE
1.8 YCYL comments

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1699]
- ~Ruby Weapon is *very* overpowered here, the dice to roll minimum is nothing - even Short Circuit requires more dice to be rolled than it. Minimum of like 5 dice should work~ now 4 dice, terry considering 5
- Meteor is power creep on Plasma Cannon and similarly extremely powerful, maybe just remove it from the generator entirely?
- Overall this kind of goes in the opposite direction of YCYL and gives you so much freedom you can steamroll pretty much everyone in your path (one turned most enemies I came across). Consider having some maximum amount of dice you can roll, and increase that on level-up the way other characters get dice and normal robot gets cpu? Maybe make the 6 dice you can choose from entirely random rather than being 1-6?
- ~Sharp Spike is now useless as you can't roll two ones in a turn until you get Duplicate+ (or get lucky with Juggling Ball), and then you only get 4 damage out of it~ Will be removed
- ~Dexterity Charm + Duplicate + (anything that does damage) is a gamebreaker combo that lets you win the instant you activate Dexterity~ Known:
[3:03 AM] terry: no: I intentionally want to leave a space in the game for people to realise they can pull off an infinite damage turn
[3:03 AM] terry: I just want to make it harder to pull off, i.e. size 2 + larger countdown
[3:04 AM] onetruepurple: Counterfeit instead of Duplicate :marshmallow:
[3:04 AM] terry: Counterfeit is size 2, right?
[3:04 AM] terry: Hmm, that works!
[3:04 AM] terry: ok, yeah, I like that :slight_smile:
(also Duplicate will be a late-game shop item rather than a guaranteed levelup reward)
- ~Apparently using Ruby Weapon while you have dexterity activated lets you use it and still keep the dice due to TerryCavanagh/diceydungeonsbeta/issues/144 (since the initial slot is "locked" and has no dice input). Keep this in mind in case you replace Dexterity Charm with Hookshot or something~ Will be addressed

**Comment by ncrecc** [comment]
Actions taken so far (via dicecord):
![image](https://user-images.githubusercontent.com/11216597/82747882-6a609f00-9d6b-11ea-8f24-d3ff0ab2a39c.png)

**Comment by TerryCavanagh** [comment]
Thank you for compiling this! I like how this episode has finished up :)
