### ISSUE TITLE
Crash Putting Dice In Crowbar+

### ISSUE THREAD

**Issue by FelixNemis** [TerryCavanagh/diceydungeons.com#170]
game crashed and dissapeared while I was putting a dice in the crowbar+
here's the error log
![screenshot from 2018-05-18 19 47 09](https://user-images.githubusercontent.com/6477924/40263204-a99c4b14-5ad4-11e8-881c-8fe6bf3d097f.png)

**Comment by onetruepurple** [comment]
I've not encountered this ever. Possibly it fixed itself?

**Comment by TerryCavanagh** [comment]
I haven't seen this one in 2019, I think it's fixed!
