### ISSUE TITLE
Translator Mode enabled in 1.8 build

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1701]

**Comment by ncrecc** [comment]
Although I do think there should be some way to reenable it, side-by-side item version comparisons is really useful:
![image](https://user-images.githubusercontent.com/11216597/82745980-81e25c80-9d58-11ea-901c-d29f1e3bdd11.png)

**Comment by TerryCavanagh** [comment]
This one's not a bug - I'm planning to expose this feature to players and modders via the `-translator` command line argument in v1.8! It's enabled by default in testing.
