### ISSUE TITLE
Chocolate Cookie+ not using correct countdown value

### ISSUE THREAD

**Issue by Codeacious** [TerryCavanagh/diceydungeons.com#1703]
The first combat I used it in the correct value of 9 was displayed & used, but the following combat used an incorrect countdown value of 12, which is the non-upgraded amount.

I didn't get a chance to see if it reset after use or in the following combat, as I lost the encounter.

![image](https://user-images.githubusercontent.com/1146658/82763092-e08bf280-9db9-11ea-8509-27f8b39c4065.png)

**Comment by TerryCavanagh** [comment]
Ah, thanks! I thought this one was fixed already, but I must have missed a case - are you playing on Steam or Itch? If Itch, what version number is displayed in the option menu?

**Comment by Codeacious** [comment]
This was on Steam.

**Comment by TerryCavanagh** [comment]
Cool, thanks!

**Comment by TerryCavanagh** [comment]
@Codeacious Are you playing offline, or have you maybe disabled updates on steam? I was extremely sure this bug was fixed in v1.7, and I can't reproduce it in the latest versions!

**Comment by TerryCavanagh** [comment]
Ahah! Nevermind, I've reproduced this in v1.8!

**Comment by TerryCavanagh** [comment]
Phew! Fixed for v1.9. This was a pretty intricate one 😅
