### ISSUE TITLE
Gamepad: Spamming X allows you to skip multiple turns and messes with things

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1711]
![image](https://user-images.githubusercontent.com/2874150/82815231-4d99a800-9ee0-11ea-96d9-78e1a4c559f6.png)
![image](https://user-images.githubusercontent.com/2874150/82815244-538f8900-9ee0-11ea-9376-6927248fc9ab.png)

**Comment by randomnine** [comment]
Fixed!

**Comment by TerryCavanagh** [comment]
👍
