### ISSUE TITLE
3-line size 1 cards with explanatory text below the slot (e.g. "needs doubles") cause text overflow

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1714]
![image](https://user-images.githubusercontent.com/11216597/82838366-012b7980-9e9a-11ea-94a2-af5e62c5a812.png) ![image](https://user-images.githubusercontent.com/11216597/82838369-038dd380-9e9a-11ea-8db3-e17222770dbe.png)

3-line size 2 cards with explanatory text work fine (if the positioning is slightly awkward), which makes this a little more important if at some point Witch will be able to use size 2 cards scaled down to size 1 (#1664, see comment):
![image](https://user-images.githubusercontent.com/11216597/82838436-359f3580-9e9a-11ea-8e51-3b40be013dd6.png)

3-line size 1 cards with no explanatory text work, of course
![image](https://user-images.githubusercontent.com/11216597/82838450-43ed5180-9e9a-11ea-9a37-d016106804a5.png)

My suggestion would be finding some way to make the explanatory text comfortably overlap the slots (though still rendering behind actual dice). Here's my mockup attempt:
![image](https://user-images.githubusercontent.com/11216597/82838522-80b94880-9e9a-11ea-8681-dd74340efe38.png) ![image](https://user-images.githubusercontent.com/11216597/82838552-94fd4580-9e9a-11ea-9bcb-720d8b9f1419.png)

**Comment by TerryCavanagh** [comment]
Fixed - see https://github.com/TerryCavanagh/diceydungeons.com/issues/2139/.
