### ISSUE TITLE
Gamepad: Playing too fast on uptick causes you to lose dice

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1716]
```
Playing Uptick with Thief, looks like you can burn dice on uptick if you go too fast.
```

**Comment by ncrecc** [comment]
I think the poster meant inserting dice into the uptick skillcard too fast could result in a net loss. codyfun reported something like that earlier iirc

**Comment by randomnine** [comment]
Fixed!

**Comment by randomnine** [comment]
Thanks, found it! This will be fixed in the next build.
