### ISSUE TITLE
Gamepad: More glitches when using gamepad and viewing enemy moves

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1718]
![image](https://user-images.githubusercontent.com/2874150/82866280-2094d600-9f70-11ea-8df6-0a90c360cff4.png)
![image](https://user-images.githubusercontent.com/2874150/82866293-25f22080-9f70-11ea-8005-195f6ebe44aa.png)
![image](https://user-images.githubusercontent.com/2874150/82866307-2db1c500-9f70-11ea-8867-ff5091a02edb.png)
![image](https://user-images.githubusercontent.com/2874150/82866321-34403c80-9f70-11ea-8e3f-40423711bcd3.png)

**Comment by randomnine** [comment]
I've fixed several of these issues. Should be much harder to find in the next build :)
