### ISSUE TITLE
new floor map

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#172]
good

- reminiscent of classic tabletop boards
- supports strategic approach many players already took
- no more duds (beating a foe to discover a dead end)
- less clicking
- skipping apples!
- much easier to read
- probably much easier to build variety (I have yet to play enough to guess at whether these are all hand crafted or also generated layouts - either way it seems simpler to make)

bad

- the game is now slower (I have to wait for my character to arrive - most tedious when comparing shops at opposing map corners)
- hover over for enemy details won't work for touch systems
- cannot skip the ladder
- repopening a shop or upgrade requires 2 clicks (step off and back on)
- no more exploration (I hope you can stitch that back in to *some* degree without compromising the good stuff)
- pointless empty tiles, especially on the first floor, but also the occasional 1 tile longer than needed runaround later
![image](https://user-images.githubusercontent.com/3826749/40266125-f1bbdfe2-5b45-11e8-8466-7728bf20bba8.png)

okay ... seeing a spiralling rat king floor made me smile

**Comment by TerryCavanagh** [comment]
Thanks for this!

I sped up movement speed in v0.7.1 due to this issue! Appreciate the input!
