### ISSUE TITLE
Reduce? shouldn't block self inflicted status effects.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#1720]
Doing random build runs and had Cloak and Random Blessing. Cloak has a countdown of 4 and Random Blessing has a countdown of 10. Using wrecking ball you never get to successfully trigger Random Blessing due to reduce?'s behavior which makes Random Blessing pretty useless.

**Comment by TerryCavanagh** [comment]
Fixed in v1.9!
