### ISSUE TITLE
Power Crystal and Secret Weapon don't have sound effects for Re-Equip Next or Reduce

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1721]
This is because the sound effect is `sfx(~_~ + randomstatus.toLowerCase());`, but `_reequipnext` and `_reduce` aren't sound effects (ideally `_recycle` and `_shield` would be used)

**Comment by ncrecc** [comment]
May as well just add some entries to newsoundevents.json named \_reequipnext and \_reduce that just point directly to \_recycle and \_shield

**Comment by JuniorUdale** [comment]
This seems to be fixed now.
