### ISSUE TITLE
Backstage is a bit broken in this update

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1723]
![image](https://user-images.githubusercontent.com/32357485/83190568-875def00-a12a-11ea-97b5-d9978fd2986b.png)
![image](https://user-images.githubusercontent.com/32357485/83190582-8cbb3980-a12a-11ea-9c35-5dd1c3fce15b.png)
Lady Luck doesn't appear in the cutscenes.

![image](https://user-images.githubusercontent.com/32357485/83190656-aa889e80-a12a-11ea-94e1-37f7bd3f4aaa.png)
The game crashes when you enter the final floor, with a "Null Object Reference" error - it doesn't create any log, either.

**Comment by TerryCavanagh** [comment]
Thanks! Fixed for v1.8.1 :)
