### ISSUE TITLE
Reached a dead end in tutorial

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1725]
For some reason, the Jester and exit did not spawn for this player:

![image](https://user-images.githubusercontent.com/2874150/83242826-8ee1ce80-a1e4-11ea-9c58-33cbc69efb91.png)

I've tried multiple times, but I can't reproduce this bug! It's extremely serious so hopefully it was just a weird fluke.

**Comment by randomnine** [comment]
Found a repro!

After picking up the first equipment (Matchstick or Bump), go to your Equipment screen and move it to the Backpack. The next stage won't trigger until Matchstick and Bump are both equipped.

**Comment by TerryCavanagh** [comment]
Solution to this should be to just force you to re-equip everything for the Jester fight. It's a little weird, but less weird than people losing the fight because they just went in with Matchstick or having the game softlock here.

**Comment by TerryCavanagh** [comment]
Ok, fixed! I've just made it so that the game puts everything back in your hand for the Jester fighter, regardless of what you do. It's a little imperfect, but it's better than the messy alternatives and it fixes the problem.
