### ISSUE TITLE
Encyclopedia doesn't extend the gadget skillcard past 2 buttons tall when used more than once in combat

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1733]
![](https://cdn.discordapp.com/attachments/398621536191512576/716539261070868500/unknown.png)

**Comment by TerryCavanagh** [comment]
Surprised this one has stuck around so long! Gonna make sure it's fixed for v1.10.

**Comment by TerryCavanagh** [comment]
Fixed!
