### ISSUE TITLE
Reversal provides the enemy with once-per-battle items you have already used

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1734]
> I used Reversal once to send Encyclopedia over to the enemy, at which point it was no longer removed from the battle, then I decided I really didn't want the enemy's equipment, so I used Reversal again and was able to use Encylopedia a second time to get Flash Freeze

**Comment by JuniorUdale** [comment]
This is also true for Yoink; Bounty Hunter can steal once per battle items you've used

**Comment by TerryCavanagh** [comment]
Fixed in v1.11!
