### ISSUE TITLE
Snapping Lament+ (or any item with a FREE slot) generates dice

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1735]
![image](https://user-images.githubusercontent.com/32357485/83362356-94781980-a388-11ea-8f94-58cd92bead33.png)
![image](https://user-images.githubusercontent.com/32357485/83362357-98a43700-a388-11ea-83f1-80a8f0b555cd.png)
These dice are usable, you can pick them up and use them as normal

**Comment by TerryCavanagh** [comment]
Fixed!
