### ISSUE TITLE
Using enemy equipment stolen with Yoink crashes the game

### ISSUE THREAD

**Issue by lheofacker** [TerryCavanagh/diceydungeons.com#1738]
It happened two times stealing Camouflage from Kraken. As soon as you lock the dice into the equipment, the game soft crashes (both times a 5 was used)
It also happened after using Rat from Rat King, but the game froze during the exception handling

It may be because the equipment had counters, but I didn't get the chance to test anymore than that
When you use a smaler die that doesn't set the counter to 0, nothing happens

All three times in the same Jester run (chapter 6, with the modifiers: Hothead, Vacuum, Haunted Jar and **Bully**)

**Comment by TerryCavanagh** [comment]
Thanks! Will fix this one for v1.8.2.

**Comment by TerryCavanagh** [comment]
Hi! Question about this one: how did you get Yoink in this episode? Where you playing with a mod active?

**Comment by lheofacker** [comment]
Hi! No mods. 
I got Yoink from the Jester's level up event. On the first one I took the Witch's power (the one that lets you hold one extra card), and then i took Yoink second

Sorry i failed to get the exception's stack trace, though

**Comment by TerryCavanagh** [comment]
Found it! This will be fixed in v1.8.2. Thanks for the report :)
