### ISSUE TITLE
Crash when trying to view a custom character's "complete episode 1" cutscene

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1739]
...Or maybe when trying to view *any* "complete episode" cutscene while using a custom character. Not sure.
![image](https://user-images.githubusercontent.com/11216597/83371410-6d254a80-a390-11ea-9119-eb4e10d8f8bb.png)
Confirmed by the maker of the Pyromaniac character mod:
![image](https://user-images.githubusercontent.com/11216597/83371427-757d8580-a390-11ea-9984-fdaff31b96f9.png)
(This still exists, first screenshot is on 1.8)

**Comment by TerryCavanagh** [comment]
This was fixed with Reunion! We have proper support for custom cutscenes and cutscene flags now.
