### ISSUE TITLE
Call for Backup Warrior appears in Bonus Round, despite the player not getting any Bops

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1748]
There's a couple of ways you could fix this:

* Remove it from the pool altogether (so you only get CfB Warrior?)

* Add another version "Call for Backup Warrior@BonusRound" that deals +1 damage per blammo (though you would need to fix #1729 first)

**Comment by ncrecc** [comment]
Dupe (or main issues page version) of TerryCavanagh/diceydungeonsbeta/issues/504, the alternate +1 per blammo thing sounds like a good fix though

**Comment by TerryCavanagh** [comment]
Fixed! (The second solution is tempting, but doesn't add much I think and would require a new localisation string)
