### ISSUE TITLE
Decrementing e.totalusesremaining to 0 for Rust equipment doesn't destroy it

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#1753]
Decreasing the durability of items in Inventor 3 (Rust) can be done manually by reducing the equipment variable "totalusesremaining". Once that variable reaches 0, however, the equipment is not destroyed. Instead, it behaves like equipment normally does in other episodes (usable once per turn, never breaking).

There also doesn't seem to be any function dedicated specifically to destroying pieces of equipment in Rust.

**Comment by TerryCavanagh** [comment]
Fixed in v2.2!
