### ISSUE TITLE
The FIGHT! banner is wrong in the Russian translation

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1757]
![image](https://user-images.githubusercontent.com/26709843/83967444-c2a2af80-a8da-11ea-9131-91f59bc010f8.png)
It says "Б бОЙ!", but should be "В БОЙ!".
The first Б makes no sense (imagine the FIGHT! banner saying BIGHT! instead), and the second б is lowercase while all other letters are uppercase, which makes it look off.
This seems to be a new issue, haven't noticed it before 1.8

**Comment by TerryCavanagh** [comment]
Ahh, whoops - I was trying to fix this in v1.8 :( Thank you for the correction, we'll get it right in v1.9!

(Incidently, I did a big text formatting pass on Russian for v1.8. Have you noticed anything else?)

**Comment by TerryCavanagh** [comment]
This should finally be fixed now for v1.9!

![image](https://user-images.githubusercontent.com/2874150/84844702-79005480-b092-11ea-9ae8-db365bd73e9f.png)
