### ISSUE TITLE
Add in a way to get a list of absolutely all equipments in the game, special equipments included. (Maybe the same thing for other stuff too, like Skills or Enemies)

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#1758]
Self explanatory, at the moment we can only get a list of all non-special equipments, if we want a list of special equipments we can't get it.

**Comment by TerryCavanagh** [comment]
Fixed for v1.9! From migration guide:

The functions `getequipment` and `getparticularequipment` have both been removed. There is a single new function, `getequipmentlist`, that is now used instead. It takes the arguments `getequipmentlist(target:Fighter, conditions:Array<String>, excludetags:Array<String>)`.
 
   `target` can be either fighter, or null if you want to consider all equipment. 
   `conditions` is a list of tags to match list criteria - you might for example just want to get a list of `appearsforparts`" to get all the scrap equipment. (A useful thing to know here is that all equipment is automatically tagged as either "large" or "small" when loaded.)
   excludetags is a list of tags to exclude from the list - most in game functions that use this exclude `excludefromrandomlists` and `skillcard` tagged equipment, but you can exclude anything you like.
