### ISSUE TITLE
Vampire can be killed by a weapon other than Wooden Stake

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#176]
To reproduce:

Editor, Thief vs. Vampire. Give Thief a Wooden Stake, a bunch of dice, and a bunch of HP. Get Wooden Stake down to 1 and Dagger the vamp down to 2. End Turn. Wooden Stake. Dagger. Vamp dies. Dagger does the killing blow.

You still have to use the Wooden Stake on the killing turn, but the descriptions imply that it has to deal the killing blow.

I'm curious whether you'll consider this a bug or a kindness (:

**Comment by TerryCavanagh** [comment]
Haha, this is pretty funny :D I got a bit lazy with the implementation, but it's not a big deal to fix this. Eventually :P

The wooden stake removes the "survive" status effect for one turn - so I think this bug would occur with any equipment! So long as you then defeated the Vampire on the same turn that you use the wooden stake, the order doesn't actually matter...

**Comment by lcenine** [comment]
Maybe just rewording the description would make it a non-issue. Something along the lines of: Wooden stake is used in a round to allow the vampire to die.  Something like that.

**Comment by TerryCavanagh** [comment]
Finally fixed this with the new action system rewrite :P

```
if(target.hp <= 1) { removestatus(SURVIVE| ALL); attack(1); } else{ target.textparticle(~No effect!~); }
```

**Comment by TerryCavanagh** [comment]
oh, whoops! Just realised that should technically be:

```
if(target.hp <= 1 && getstatus(SURVIVE) > 0) { removestatus(SURVIVE| ALL); attack(1); } else{ target.textparticle(~No effect!~); }
```

**Comment by TerryCavanagh** [comment]
Fixed.
