### ISSUE TITLE
Setting the font size in equipment name leads to display name inconsistencies in a number of places

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1760]
![image](https://user-images.githubusercontent.com/26709843/84080122-215c4c00-a9f5-11ea-8f99-caaa958352ba.png)
Here the string for bottom-left item is `[85%]Серповидный клинок`

**Comment by TheMysticSword** [comment]
Also happens in the trade post
![image](https://user-images.githubusercontent.com/26709843/84080794-32598d00-a9f6-11ea-949b-d16bedc8874b.png)

**Comment by TerryCavanagh** [comment]
Ah, thank you - I'll figure out a way to fix this in code without changing the localisation files themselves.

**Comment by TerryCavanagh** [comment]
Fixed for v1.9!

![image](https://user-images.githubusercontent.com/2874150/91633284-88a2fe80-ea2e-11ea-90d8-9189a35e547b.png)

![image](https://user-images.githubusercontent.com/2874150/91633292-9b1d3800-ea2e-11ea-89c4-de11cee2ee59.png)
