### ISSUE TITLE
Lady Luck remix rule and "Lady Luck" string in the credits share the same entry

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1761]
![image](https://user-images.githubusercontent.com/26709843/84081498-8022c500-a9f7-11ea-96bb-a5a416bf5f1f.png)
Every entry in the Special Thanks page of the credits is in dative case in the Russian translation, except for Lady Luck, which makes it look out of place. If you change this entry to use dative case, then the Lady Luck remix rule also gets changed to that, making the remix rule name look out of place instead.
![image](https://user-images.githubusercontent.com/26709843/84081565-a7799200-a9f7-11ea-9d76-e6ca67c540c6.png)
![image](https://user-images.githubusercontent.com/26709843/84081609-bb24f880-a9f7-11ea-935d-b79b498d351a.png)

**Comment by TerryCavanagh** [comment]
Aha! Ok, cool - I'll add a fix for this for v1.9. What are the correct translations for both cases?

**Comment by TheMysticSword** [comment]
Should be "Госпоже Удаче" in the credits and "Госпожа Удача" in the remix rule

**Comment by TerryCavanagh** [comment]
Ok, this is fixed!
