### ISSUE TITLE
"Finale" string beside finale cards in Jester's Next Up can't be localized

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1763]
![image](https://user-images.githubusercontent.com/26709843/84272561-01d53880-ab47-11ea-9a54-b8abb0cda180.png)
Adding `,Finale,Финальная,Jester Combat,` to `strings.csv` does nothing

**Comment by TerryCavanagh** [comment]
Fixed! Sort of. On refection, the word "Finale" is basically just clutter here, so I just removed it:

![Dicey Dungeons Jul 20 03-25-47PM sc](https://user-images.githubusercontent.com/2874150/87901018-6fa54600-ca9d-11ea-9ff6-3b9a18a3eda4.png)
