### ISSUE TITLE
Items that maintain Fury will only activate twice on Fury regardless of the amount of Fury stacked

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#1766]
Say the player has 3 Fury stacked up. Normal items will activate 4 times, but an item which maintains Fury like Ruff Ruff Ruff will only activate twice, as though the player had only one Fury.

**Comment by kortemaki** [comment]
I'm not certain this is the same or related issue, but I had a similar experience when using Boomerang+ with Fury 3.  The action only executed twice, and I lost my Fury stack.

**Comment by TerryCavanagh** [comment]
This one is fixed now!
