### ISSUE TITLE
Crash if Copycat uses calculator, maybe

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1769]
Poissible that this is something else (or related to a megaquest equipment, maybe)

![image](https://user-images.githubusercontent.com/2874150/84620802-77168400-af20-11ea-9e41-36b8d9c005e0.png)

(Enemies not understanding needs X equipment is an open issue, but crashing is new)

**Comment by ncrecc** [comment]
Most likely #1683/#1548 - Sonar has one odd slot and one even slot, and the linked issues say AI considers both slots to be the same and crashes the game when it forces a non-fitting dice

**Comment by TerryCavanagh** [comment]
Oh, of course!

**Comment by TerryCavanagh** [comment]
Fixed for v1.9!
