### ISSUE TITLE
If Copycat steals a Call for Backup card, you can click it while previewing enemy moves, which hard-crashes the game

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1772]
https://www.reddit.com/r/DiceyDungeons/comments/ha99ja/the_game_didnt_like_that/

**Comment by ncrecc** [comment]
Also slightly important for modding since enemies can more commonly have call for backup cards there

**Comment by TerryCavanagh** [comment]
Fixed for v1.9!
