### ISSUE TITLE
Spatulasword+'s description does not accurately reflect the damage it deals while being used

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#1778]
Spatulasword+ flips the dice before dealing damage, but the dice slot in the description doesn't match this. For example, putting 1 in would deal 6 damage, but the description will say "then do 1 damage" instead of "then do 6 damage".

I'd recommend adding a new slot type for this called `<slotflipped>` or similar. This would also be useful for modders.

**Comment by onetruepurple** [comment]
Can you do `(7 - <d6>)`?

**Comment by XenonZed** [comment]
No, there is no support for manually typed out operations auto-updating the description.

**Comment by TerryCavanagh** [comment]
This is a weird case, but: done! With v1.9's updating descriptions as you hover over, this was important to get right -

![spatulasword](https://user-images.githubusercontent.com/2874150/87901530-d9721f80-ca9e-11ea-9454-a0148f82bc19.gif)

The new slot variable is `<flipd6>`.
