### ISSUE TITLE
The "Triple Gadget" achievement can't be achieved by using the "same" gadget 3 times in Rust

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1779]
![image](https://user-images.githubusercontent.com/32357485/85203403-84a78180-b305-11ea-8e3a-3f23d1e9bc98.png)
So they used Clone Device, used Counterfeit+ a bunch of times, destroying it; used the second Clone Device, then used up another Counterfeit+ then used a third Clone Device. This should probably unlock the achievement, since you're using the "same" gadget 3 times.

**Comment by TerryCavanagh** [comment]
Fixed in v1.9!
