### ISSUE TITLE
AI bug: Bandit doesn't unstun Run Away+

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#178]
To reproduce in Editor:
* Warrior, Tazer, Snowball
* Bandit
* Hard mode
* Bandit will Pickpocket
* Use both Tazer and Snowball
* Bandit will have 4 dice, only 1 of which is frozen, but it will end turn instead of unstunning Run Away+

Hopefully this is a general AI bug regarding stun, instead of just a one-off Bandit bug.

**Comment by TerryCavanagh** [comment]
Fixed!
