### ISSUE TITLE
Allow the player to walk past Mimics and Rotten Apples, as if they were real chests and apples

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1785]
One people thought they'd found a bug where they couldn't move, but it turns out it was a Rotten Apple. Maybe it would be better here if players could bypass Mimics and Rotten Apples? Sure, it would mean they could skip enemies, but that's probably not actually a big deal.

**Comment by TerryCavanagh** [comment]
on reflection: it sorta trivialises rotten apple to always be able to fight it when it suits you

also, this wouldn't work on gamepad controls, which is a problem

Probably best to leave it as is. Leaving this issue open for now to continue thinking

**Comment by Matz-42** [comment]
The way I see it, having rotten apples and mimics be able to "ambush" you if you're trying to go past them is a way better solution to that.

**Comment by JuniorUdale** [comment]
An alternative to this - highlight the paths that the player will use when they hover over a map tile. This would stop confusion in this specific case; the player would see that their path is blocked by an apple, and presumably would investigate to see that it's not a normal apple at all!
