### ISSUE TITLE
The Crystal Sword weapon reappears half off the side of the screen if you look at the enemy's moves

### ISSUE THREAD

**Issue by AndrewRCrosswait** [TerryCavanagh/diceydungeons.com#1786]
At first I thought the glitch was that the sword disappeared, but I hadn't read the card fully, haha. Still led me to a different bug, though.
So without realizing I was supposed to lose the crystal sword, on a whim I viewed the enemy's actions, and when I went back to my weapons the crystal sword was stuck off the side of the screen. I still couldn't interact with it. If it helps I have it equipped in the leftmost slot, this does this with all the enemies I've tried this with, and my game is in fullscreen.
Hope this helped!
![20200701192550_1](https://user-images.githubusercontent.com/43223415/86300451-e0f58580-bbd0-11ea-8f70-9dc7c42d9623.jpg)

**Comment by TerryCavanagh** [comment]
Hey!

Thank you for the bug report - this one is actually fixed locally already, and will be included in v1.9, coming soon!
