### ISSUE TITLE
Crowbar+ applies to already-used offscreen equipment

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#179]
To reproduce in editor:
* Thief
* Give Staff, Snake Eye Charm, Crowbar
* Upgrade Crowbar
* More Dice, More HP
* Bandit
* Put a 6 in Crowbar+. Staff will go to 2, Snake Eye Charm will go to zero.
* Put a 5 in Crowbar+. Staff will go to zero, and the offscreen Snake Eye Charm will go from 6 to 1.
* End turn.
* On your next turn, you'll see that Snake Eye Charm is 1 instead of 6.

I'm assuming this is not intentional (: 

This could be related to #143 or possibly even #170

**Comment by TerryCavanagh** [comment]
So it does! Thank you!

**Comment by pace212** [comment]
Reproduced in v0.15

**Comment by ryanbowles** [comment]
Reproduced in v0.16 using the Thief, Staff, and Crowbar+

**Comment by onetruepurple** [comment]
Resolved in v0.17
