### ISSUE TITLE
Re-equip stacks, but when using any card while you have re-equip, all re-equip is consumed at once

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1793]
![superduper](https://user-images.githubusercontent.com/11216597/87129150-e3a24b80-c25e-11ea-952a-76c741804c79.gif)
This leads to blatantly wrong behavior in some modded items

**Comment by ncrecc** [comment]
Not sure whether this is the case with alt reequip

**Comment by TerryCavanagh** [comment]
This one has been fixed in v1.9!
