### ISSUE TITLE
In the final battle, getplayername() returns who you won as, instead of your starting character

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1796]
So if you get the final blow with e.g. Frog instead of Warrior, the text boxes that would normally be your dice speaking are crammed into the top-left corner instead. This makes it look like Jester is speaking, even if you didn't play as them.
![image](https://user-images.githubusercontent.com/32357485/87259925-9adcd380-c4a6-11ea-8a7a-ffb7543bf0de.png)

**Comment by TerryCavanagh** [comment]
Fixed!
