### ISSUE TITLE
Damaging yourself causes thorns to further damage you, including picking up burned dice

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1797]
Damage from a burnt dice shouldn't be considered as coming *from* any particular entity.
This also affects self-damage taken from Boomerang and Double Edge, although in that case taking thorns damage is more logical since you're literally attacking yourself.

**Comment by TerryCavanagh** [comment]
This is a duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/1455! I suspect this is fixed already, I just need to double check it.
