### ISSUE TITLE
Copycat has trouble with this collection of equipment

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1799]
![image](https://user-images.githubusercontent.com/2874150/87514317-9b04eb00-c6c1-11ea-9d13-b4ff84d7d33b.png)

**Comment by ncrecc** [comment]
The culprit is most likely Berlin Key, based on some tests I did with a custom enemy layout the AI really doesn't like equipment that uses animatereroll on individual dice in the dicepool

**Comment by TerryCavanagh** [comment]
It was Berlin Key! That was throwing script errors in the console, so I just wrapped the script in an `if(!simulation) {` check.

Also, as of v1.9, this situation was no longer causing a softlock, so this can be closed now.
