### ISSUE TITLE
"Re-use equipment" trumps Fury instead of stacking with it

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#180]
I encountered this with the Inventor with Fury gadget, but it probably happens with other furies too.

* Activate Grappling Hook
* Activate Fury
* Put a 6 in Hammer

It only attacks once. It's reusable, so the Grappling Hook worked, but the Fury didn't.

**Comment by TerryCavanagh** [comment]
Fixed.
