### ISSUE TITLE
Stolen countdowns as Thief count down quicker than usual

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1807]
https://streamable.com/ec4eum

No effect on gameplay (unless you're doing something timing related like use two items simultaneously) but it just seems off

**Comment by TerryCavanagh** [comment]
Ahh, I can't believe this one is still in the game. I think I'd just mentally edited out noticing it. Will make sure it's fixed for v1.9, thanks!

**Comment by TerryCavanagh** [comment]
Fixed!
