### ISSUE TITLE
Pace's thoughts on v0.7 / 0.7.1, and some suggestions for future versions

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#181]
## Warrior

I played about 8 Warrior+ runs.
Ye Olde Shield Builde still pwns. I almost always win with YOSB.

For a challenge, I tried not taking Shielde Bashe and it's medium difficulty (50% win rate)

...Unless I join the Guild of Sacrifice, in which it becomes quite hard (0%).

I love Crystal Sword. I love it furiously.

Dire Wolf Howl is OP, and I got it twice and I've heard others say they got it, so you might want to double-check its rarity.

## Thief

I played about 6 Thief+ runs.
I find Thief+ more difficult than Warrior+.
If I upgrade Dagger at first opportunity, I win about half the time.

For a challenge, I tried not upgrading Dagger, and I've only won twice.
Both times my Thief was level 3 because I had to avoid Dire Wolf and Knight.
Both times were against Cornelius, though, so that hardly counts as a victory.

I kept trying for a Crowbar+ build but I could never get enough good countdown items.
The closest I came was Crowbar+, Snake Eye Charm, Staff, Dodge, Dagger.
I made it to Turn 8 against Knight+, got him down to 15hp, but couldn't pull it off.
I would have won if I had had Dagger+.

The Guild of Assassins is cool. I find it worse for most situations, but
handy when you need to deal a bunch of damage fast. And it's nice how
Unlucky Roll powers up Backstab. It would probably be a more even trade
on normal mode.

## Inventor

I played 3 Inventor+ runs. (This was on v0.7.1, the others were 0.7)

I lost the first two and won the third. Thinking ahead is key so you'll have the
gadgets you need for the right enemies.

The Guild of Innovation is super fun.
I adore the text when creating a second gadget: "Again! Again! You are overcome with inspiration!"

## Overall

I love the node-based map. It makes each decision strategically interesting with no filler.

I love all the streamlining. 1 gold matters. 1 xp matters. Fewer clicks for shops and upgrades and ladders.
It makes it feel punchy and fast and keeps the focus on the action.

The AI seems much better than 0.6. It rarely plays obviously suboptimal moves.

I find the complexity to be, from least to most complex, Warrior, Thief, Inventor.

I find the hard mode difficulty to be, from easiest to hardest: Warrior, Inventor, Thief.
Although maybe I would win more as Thief if I upgraded Dagger. I just got bored of doing that.

My personal preference of which class is the most fun, from super fun to quite fun: Thief, Warrior, Inventor
Inventor is super cool and I love playing it once in a while, but it takes more micromanagement, planning, and precision.
I think it's _awesome_ that it exists, and sometimes I'm in the mood for that, but for me Thief strikes
the optimal balance of variety and forethought. Stealing enemies' equipment is just so cool and fun!

### Game balance
* make non-Shielde-Bashe Warrior builds more viable. Nerf Shielde Bashe, or nerf shields (e.g. with more shield-bypassing attacks), or make the alternative better
* make non-Dagger+ Thief builds more viable
* a different reward for winning while a member of each guild (achievement? an unlock for future runs?)

### Tweaks
* make Dire Wolf Howl less common for Warrior
* bring back the "Blocked!" pop-up when your shield absorbs the full amount of an attack

### Rephrasings
* rephrase suggestion for Guild of Power: "Adds +1 to dice pool" or "Gets +1 dice permanently" to clarify that your dice pool is not going to increase every turn (like Wisp's does)
* change Sword upgrade text to "Upgrading Sword makes it more powerful" so that it will match Broadsword and be more clear
* change Tazer upgrade text to "Upgrading Tazer makes it easier to play."

**Comment by pace212** [comment]
Oh! And I forgot to mention that I love the option to skip enemies. It adds a whole new element of strategy: planning your route through the dungeon. Depending on the enemies, I often stuck with level 3 instead of fighting for level 4. The benefit (a few items and +1 dice) is often not worth the cost (losing lots of health and possibly dying).

**Comment by TerryCavanagh** [comment]
This is *great*! Thank you for the feedback! :)

**Comment by TerryCavanagh** [comment]
These playtesting posts were incredibly useful, @pace212! I'm cleaning up the issues list at the moment, and I'm gonna close them all now, but just wanted to take a moment again to thank you for all the great feedback, all the way through the project!

**Comment by pace212** [comment]
I'm glad they were so useful! It's been a lot of fun to help out. It's really gratifying to see some of my ideas and feedback shape the game in small ways, to feel like I helped out a little bit. Your appreciation plus your clarity about where _you_ want the game to go make it both fun and fulfilling to contribute. And of course, the fact that Dicey is really fun to play doesn't hurt (:
