### ISSUE TITLE
Items like Skeleton Key and Call for Backup Robot? should check if the dice are tweening, to avoid issues with Fury

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1810]
https://streamable.com/v3d1us

Presumably a simple fix, just make sure to check `if(mydice.available() && !mydice.intween())` in those items instead of just `if(mydice.available())`

A full(ish?) list of items to change is Skeleton Key, Magic Reroll (not obtainable except by random events; best to change this just in case), Call for Backup Robot, Table Slam, Berlin Key and Giant Spatula.

**Comment by ncrecc** [comment]
Or potentially rewrite animatererolldice so it doesn't break if called on dice that are tweening

**Comment by TerryCavanagh** [comment]
This is fixed in reunion! (the animate function works better now)
