### ISSUE TITLE
Halloween: Crash on using Bass Drop

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1816]
![image](https://user-images.githubusercontent.com/2095534/88453615-de511d80-ce68-11ea-9997-6baa04772dd6.png)

Couldn't reproduce this after loading though.

**Comment by TerryCavanagh** [comment]
Reproduced this one!

![image](https://user-images.githubusercontent.com/2874150/96678371-18bf4d80-13b9-11eb-822c-909a0ff10c31.png)

Looks like it occurred due to animations happening mid turn causing problems for future equipment use. Fixed for v1.10!
