### ISSUE TITLE
Consider splitting excludefromrandomlists into that and an "exclude from temporary random item draws" tag

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1821]
Some items shouldn't appear for things like Call for Backup Robot where the item only stays for one turn, but they work just fine for things like the Yolanda and Val rules where you keep the item indefinitely. For example a modded item I have "Do x damage, on 6, next use inflicts 2 burn" has to be marked as excludefromrandomlists for that reason - and for a vanilla example, the Transformer set of items. There are some modded items that can actually *break* if included in temporary draws because they're coded assuming they weren't summoned from another item and won't suddenly disappear once the turn ends.

**Comment by ncrecc** [comment]
Of course mods can just do this themselves but it would be nice for vanilla to also do so

**Comment by TerryCavanagh** [comment]
I don't think I need this functionality for vanilla, and as you say, mods can make this change themselves if they need it. Closing!
