### ISSUE TITLE
Dice preview on enemy cards instantly changes as soon as enemy moves their dice

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1824]
![squidhead](https://user-images.githubusercontent.com/11216597/88469138-e4241e80-cebb-11ea-8fb2-b9b99f9ff68d.gif)
It's a bit jarring, should probably only change once the dice is in regular range (the same range it would take for the dice preview to change if the player were to use it)

**Comment by TerryCavanagh** [comment]
Hmm, actually, on reflection I kind of like this. You get used to it very quickly, and it introduces some welcome legibility. I'm going to leave it the way it is.
