### ISSUE TITLE
Ideally, gadget preview bubbles should all be the same length unless gadget text would explicitly be too long for the bubble otherwise

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1825]
![shovel](https://user-images.githubusercontent.com/11216597/88469194-ad023d00-cebc-11ea-91c4-b06feb2ef09e.gif)
There's a lot of padding that makes the bubble lengths inconsistent

**Comment by TerryCavanagh** [comment]
Fixed!
