### ISSUE TITLE
Lucky Star casts backwards

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1826]
Before the On Dodge column and items like Cauldron returning dice independently of doing damage, this made sense since it let you use the dice manipulation part even if the enemy has dodge. Now it just feels out of place.

**Comment by ncrecc** [comment]
Same with Rubber Mallet and Boxing Gloves

**Comment by TerryCavanagh** [comment]
Fixed for all three!
