### ISSUE TITLE
When an equipment is unshocked, whatever the value of d would be for the shock equipment is added to the value of d for the real equipment

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1829]
For example, Poison?ed equipment has whatever number Poison? is at added to its dice total until the equipment is used:
![image](https://user-images.githubusercontent.com/11216597/88469751-a8d91e00-cec2-11ea-94c3-05c9ccf1c6c0.png)
https://streamable.com/aazbyt
And normal shocked equipment adds whatever number you used to unshock it to the dice total of the card underneath
![ssord](https://user-images.githubusercontent.com/11216597/88473649-9fb17680-ceed-11ea-8c35-f68aa8c17b2b.gif)

**Comment by ncrecc** [comment]
![bouapha](https://user-images.githubusercontent.com/11216597/88721058-d5c04780-d0f3-11ea-9074-d433acda9ea7.gif)
Same thing happens with addjestercard for some reason (not giveequipment though)

**Comment by TerryCavanagh** [comment]
Fixed this for v1.9!
