### ISSUE TITLE
Boomerang and Double Edge do not do self-damage if dodged

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1832]

**Comment by ncrecc** [comment]
On the same line, consider making Wrecking Ball still reduce countdowns if dodged, since that's the part that affects you and not the enemy

**Comment by TerryCavanagh** [comment]
Fixed! (Boomerang dodge is a little bit lazy, but it's functionally correct at least. Might clean it up in future.)
