### ISSUE TITLE
Version of halloweenspecial bundled with 1.9 preview is an earlier build than what was actually used for the Halloween event

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1838]
For example, these bugs are still present: 
TerryCavanagh/diceydungeonsbeta/issues/762 (Hole Puncher, Shredder, and Polarity Flip have no upgraded or downgraded versions in-game)
TerryCavanagh/diceydungeonsbeta/issues/741 (Mana and Fury need to reset at the start of each turn in the Witch episode)
TerryCavanagh/diceydungeonsbeta/issues/728 (Solenoid appears to start at 0 damage)

**Comment by TerryCavanagh** [comment]
Fixed!
