### ISSUE TITLE
Translation error in French for Pirate Challenge screen text?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1846]
![Traduction error 02](https://user-images.githubusercontent.com/2874150/88620469-a9053380-d0e5-11ea-854a-bae27e95cd50.png)

Got an email from someone to say that this should be `Un pirate, n'a jamais peur! Arrrh!`, not `Un pirate, l'a jamais peur! Arrrh!`. (if any French speakers reading could weigh in here, that would be very useful!)

**Comment by Matz-42** [comment]
Can confirm that "Un pirate, l'a jamais peur" doesn't really mean anything and it definitely looks like a typo of "n'a"

**Comment by TerryCavanagh** [comment]
Thanks - fixed!
