### ISSUE TITLE
When playing with a controller, thief's stolen card is still highlightable after being used

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1847]

**Comment by randomnine** [comment]
I haven't been able to reproduce this yet. I've hardened the code a bit to eliminate some possible causes.

**Comment by TerryCavanagh** [comment]
Yeah, I don't see any evidence of this in the current build. Gonna assume it's fixed unless I get another report of it after v1.9 (in which case, I'll reopen the issue with more details)
