### ISSUE TITLE
Bonus Round's "Complete this episode to unlock hard mode" text doesn't get localized

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1848]
![image](https://user-images.githubusercontent.com/26709843/88687446-b59f8100-d111-11ea-852a-a4d6dfc04f2c.png)
![image](https://user-images.githubusercontent.com/26709843/88687553-dbc52100-d111-11ea-9dd0-b5ddedef28ce.png)

**Comment by TerryCavanagh** [comment]
Fixed this one in v1.9!

![Dicey Dungeons Aug 16 07-58-47PM ja](https://user-images.githubusercontent.com/2874150/90331340-13313a00-dffb-11ea-9b29-7cb35911a5f4.png)
