### ISSUE TITLE
runscript always takes self to refer to the player, even if called by the target

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1856]
For example if an enemy equipment or "on start turn" fighter hook calls for blah.hx, and blah.hx is ``self.hp -= 5;``, the *player* will lose 5 health, not the target. If it's ever ambiguous who would be self and who would be target, self and target should both be null (players can supply fighters as arguments for scripts, right?)

**Comment by ncrecc** [comment]
Perhaps add two extra arguments to runscript that just mean "these fighters are the actor and target of the script, in case the game asks"

**Comment by TerryCavanagh** [comment]
This one is extremely difficult to fix without a pretty major rewrite of how runscript is implemented. You can work around it pretty easily by just passing the fighter as an argument, if needed, which of course people have been doing since v1.9!
