### ISSUE TITLE
Using blinded dice on spellbook reveals what it is by highlighting the spell, and you can also cancel that spell, returning the same dice but without blind

### ISSUE THREAD

**Issue by NeypahTit** [TerryCavanagh/diceydungeons.com#1860]
This essentially makes blind on witch a total joke, as long as someone realizes they can do this

**Comment by ncrecc** [comment]
Makes sense to just disable canceling totally when you insert a blind dice - the whole point behind putting a blind dice in the spellbook is you have no clue what you'll be casting. See also #1834

**Comment by TerryCavanagh** [comment]
Fixed for v1.9.2!
