### ISSUE TITLE
[4:04 PM] codyfun123: Sweets_upgraded behaves incorrectly with 2 and 3 missing HP.

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1867]
[4:04 PM] codyfun123:
``
if(self.maxhp - self.hp == 0) { inflictself(SHIELD| 3); sfx(~_shield~|~~|0.2); } else if(self.maxhp - self.hp == 1) {  inflictself(SHIELD| 2); attackself(-1); sfx(~_shield~|~~|0.2); } else if(self.maxhp - self.hp == 3) {  inflictself(SHIELD| 1); attackself(-2); sfx(~_shield~|~~|0.2); } else { attackself(-3); sfx(~_heal~); }
``
[4:04 PM] codyfun123: Sweets_upgraded behaves incorrectly with 2 and 3 missing HP.

(If your max HP minus your self HP is 3 (i.e. you're 3 HP away from full health), it gives you 1 shield and heals 2. If you're 2 HP away from full health, you just heal 3 and get no shield.)

**Comment by TerryCavanagh** [comment]
Whoops, fixed! Script is now:

```
if(self.maxhp - self.hp == 0) { 
  inflictself(SHIELD, 3); 
  sfx("_shield","",0.2); 
} else if(self.maxhp - self.hp == 1) {  
  inflictself(SHIELD, 2); 
  attackself(-1); 
  sfx("_shield","",0.2); 
} else if(self.maxhp - self.hp == 2) {  
  inflictself(SHIELD, 1); 
  attackself(-2); 
  sfx("_shield","",0.2); 
} else { 
  attackself(-3); 
  sfx("_heal"); 
} 
```
