### ISSUE TITLE
Hailstone's upgrade is bizarre compared to Cannon Fire's upgrade

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1869]
![image](https://user-images.githubusercontent.com/11216597/89080069-e5d76180-d355-11ea-9cb0-61e1026a4e27.png)
Assuming #1868 is unintentional, Hailstone+ does 1 more damage and inflicts 1 more status than Cannon Fire+, as well as saying "deal damage" instead of "do damage" (though cannon fire is all "deal damage") and "inflict freeze" instead of "freeze dice"

**Comment by TerryCavanagh** [comment]
Yep, not sure how this one happened - probably a spreadsheet error. Fixed now!
