### ISSUE TITLE
Warlock and Slime's rules should probably clash, or have Slime check if poison is alternate or not before decreasing the amount of poison on you

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1871]
![image](https://user-images.githubusercontent.com/32357485/89111889-1ea93080-d453-11ea-8e3c-45da7eb5cd57.png)

**Comment by TerryCavanagh** [comment]
Yep, I've added a prevent clash here! Seems like the easiest fix.
