### ISSUE TITLE
Noted by Jackeea: dice preview for Spiked Shield spoils whether the dice is odd or even for blind dice

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1874]
![image](https://user-images.githubusercontent.com/11216597/89129699-4937cf80-d4cd-11ea-8a2e-3a5a654d3b0b.png)

**Comment by ncrecc** [comment]
"If even" previews and "if odd" previews should both show ??? when you hover a blind dice over the dice slot

**Comment by TerryCavanagh** [comment]
(actually let's mark this A, since many players will see this on the very first run)

**Comment by TerryCavanagh** [comment]
Fixed! Also fixed the sfx and cast direction while I was at it

**Comment by ncrecc** [comment]
Fixed cast direction as in removing the SPIKEDSHIELD value for Cast Backwards?

**Comment by TerryCavanagh** [comment]
Yes, exactly!
