### ISSUE TITLE
Maybe ditch the rosewood material, or make it a bit less common

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#189]
Watched a youtube playthrough earlier and saw someone discover the rosewood material.

I'm not sure that's working very well.

It's also become the, like, only viable Warrior poison build. That all needs some rethinking, I think. If there's going to be a warrior poison build (built around Detonator etc), there needs to be some better warrior poison gear.

**Comment by joshtriplett** [comment]
The rosewood equipment seems fine, but having it be "upgrade to see how it works" seems problematic. Once you know how it works, why ever upgrade it? Instead, what if upgrading it added a third die value that worked?

**Comment by TerryCavanagh** [comment]
Have a plan in action here covered by other issues. Closing!
