### ISSUE TITLE
more than 6 slots equipped

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#19]
![image](https://user-images.githubusercontent.com/3826749/38162044-8d643800-34da-11e8-85e3-a572603ab099.png)
Pickedup up the wooden shield.
Obtained the shield grip via level up.
Picked up nudge and bump.
Never opened the inventory so far.

edit: The nudge disappeared entirely upon buying an iron shield and opening the inventory.

**Comment by TerryCavanagh** [comment]
Thanks for this! This one's pretty critical, appreciate the bug report!

**Comment by TerryCavanagh** [comment]
Fixed.
