### ISSUE TITLE
Dodge stacks, but the counter does not decrease when it activates

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#1909]
If an enemy has 2 or more dodges and one is triggered, the counter remains at 2 and only disappears once all of the dodges have been triggered.

**Comment by XenonZed** [comment]
See also: https://github.com/TerryCavanagh/diceydungeons.com/issues/1497

**Comment by TerryCavanagh** [comment]
Fixed, thanks!
