### ISSUE TITLE
Improve variation on level up choices

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#191]
Level up choices are currently completely static. Consider more deliberate choices that vary from game to game.

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/51800964-6d0ebb00-222f-11e9-843b-0c213a5044fb.png)

**Comment by onetruepurple** [comment]
Jester has this as of v0.16.

Not sure if there's enough time to explore this for all the other classes, but I think the Witch would be a little more interesting if the choice between Burning Light/Electric Shock/Ice Shard was limited to just 2 of those, every time.

**Comment by TerryCavanagh** [comment]
This is addressed now in beta for the final episodes of each character, which makes the earlier static choices work better by comparison. Closing!
