### ISSUE TITLE
Blind?'s counter doesn't decrease properly

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#1910]
The counter for the parallel universe blind status doesn't decrease at the end of the turn like it should, instead remaining at its highest amount. This is only visual; the actual value of the status decreases properly. It can still be increased properly (if there's one turn of blind left and the counter is at 2, inflicting 2 blind will increase the counter to 3).

**Comment by TerryCavanagh** [comment]
Squeezed a fix for this one into v1.11!
