### ISSUE TITLE
Text formatting issues & some suggestions to names in Traditional Chinese Language

### ISSUE THREAD

**Issue by CookieAlien** [TerryCavanagh/diceydungeons.com#1913]
Text formatting issues
- The "episodes" text is slightly too high
- The second row description of Thief ep.2 is slightly shifted to the right
- The description of Inventor ep.2 is too long to have only one line
- The first description of Jester is too long to fit in the box with only 2 lines

(Sorry but I can't upload images somehow)

Suggestions to names
- Warrior's name could be "戰士", "阿兵哥" is a common name of soldier.
- Thief ep.2 "Finders Keepers" could be "先搶先贏", to match with Jester ep.3 "Losers, Weepers" as "輸者自泣"
- Enemy names:
1.Banshee 哭腰女妖 
哭腰 is a swear word in Taiwanese, consider 報喪女妖 instead.
2.Bully 惡霸比利
比利 is not needed as it's the transliteration of Billy.
3.Crystalina 克里斯多琳娜
克里斯多琳娜 is the transliteration of Crystalina, consider a new name with 水晶 in it.
4.Kraken 烏賊克拉肯
克拉肯 is the transliteration of Kraken, the proper translation to kraken is 海怪.
5.Cornelius 小山田圭吾
小山田圭吾 is a Japanese singer, with Cornelius as his stage name. Consider changing it unless the enemy actually refers to that singer.

**Comment by TerryCavanagh** [comment]
Made some of these name changes, thank you - will do the text formatting changes after v1.9.

**Comment by TerryCavanagh** [comment]
Fixed! Thanks!
