### ISSUE TITLE
Missing text in Limit Break tooltips

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#1919]
"Ready!" text is missing when the limit break is fully charged:
![20200904193326_1](https://user-images.githubusercontent.com/66463691/92296841-2d718000-eef6-11ea-9038-89a6a333fb0e.jpg)

Text indicating how much damage is needed to charge the limit break is absent until the player takes damage:
![20200904194552_1](https://user-images.githubusercontent.com/66463691/92296839-28accc00-eef6-11ea-8a18-21d677b09d34.jpg)

**Comment by TerryCavanagh** [comment]
Yep, not sure why this started happening. Gonna fix it for v1.9!

**Comment by TerryCavanagh** [comment]
Still no idea why this was happening, but I think I've fixed it for v1.9.
