### ISSUE TITLE
Enemies with multi-use equipment in Rust have unlimited uses of that equipment instead

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1926]
This seems to be related to #756 . Consider a similar solution - ban RoboBot, Baby Squid, Mimic, Kraken, Gargoyle, Paper Knight, Aoife, Audrey and Madison from the episode (enemies with multi-use equipment)

**Comment by TerryCavanagh** [comment]
Thanks for this - definitely gonna fix this one for v1.9.

**Comment by TerryCavanagh** [comment]
Fixed.
