### ISSUE TITLE
Enemies refuse to use multi-slot equipment, notably Handyman and Skeleton

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1937]
https://streamable.com/pb355i
https://streamable.com/c868fm
https://streamable.com/lyxmbe

Probably related to the AI change that lets them use multi-slot items with different slots

**Comment by TerryCavanagh** [comment]
Yikes

This one needs a v1.9.1

**Comment by TerryCavanagh** [comment]
Fixed!

v1.9.1 incoming
