### ISSUE TITLE
Dire Wolf Howl needs a _weakened version, as its countdown gets changed to 0 when unweakened

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1940]
![image](https://user-images.githubusercontent.com/32357485/93246051-19ded880-f784-11ea-9d67-d61e8a995b86.png)

**Comment by TerryCavanagh** [comment]
Oh, boo, I thought I'd got all of these! Will make sure it's fixed before Switch!

**Comment by TerryCavanagh** [comment]
Fixed!
