### ISSUE TITLE
If enemies get a Rock due to Bully remix rule and that Rock is weakened, and they use the weakened rock, they still have a rock on the next turn

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1941]
Probably a good sign when the remaining bugs in the game are as difficult to express as this 😅

**Comment by ncrecc** [comment]
First thought was this might be a return of the "once-per-battle items can be used next turn if used when weakened" bug

**Comment by JuniorUdale** [comment]
Pretty sure this is a duplicate of #424 - it happens for all once per battle items.

https://streamable.com/tlyfro

**Comment by TerryCavanagh** [comment]
Fixed!
