### ISSUE TITLE
Consider changing Drake's non-PU innate description to something more general, "can only be killed with a special item"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1942]
1.9's new generators include a "vampireitem" array for each generator, which may prompt modders to add other items similar to Wooden Stake that can kill Drake (as I already have) - but the innate still says he only can be killed with Wooden Stake specifically

(Keep the special innate text when fighting him as Bear though, aside from also removing mention of Wooden Stake - that one's hilarious)

**Comment by TerryCavanagh** [comment]
No, I don't think this one is a good idea, sorry - it makes the vanilla case less clear, and doesn't really accomplish anything - modders can always just implement a custom innate string if they need it for whatever shenanigans they might be getting up to.
