### ISSUE TITLE
Game crashes when Copycat has either Cheat Code or Fixed Payout

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1943]
[error.txt](https://pastebin.com/siTjhqcV)

I don't think this happens with any other items - I had a quick skim through any `robotonly` items and none of them crashed. (Copycat just refused to use them if they would do nothing, like e.g. Heat Sink).

The same crash happens when Bounty Hunter steals one of these items.

**Comment by TerryCavanagh** [comment]
Fixed! And thank you for testing the other items, that's extremely useful :)
