### ISSUE TITLE
"You have found Rotten Egg@6!"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1944]
![image](https://user-images.githubusercontent.com/11216597/93405871-36e6da80-f85c-11ea-8173-1043c9c3eec0.png)

**Comment by ncrecc** [comment]
This isn't the result of substitution shenanigans or anything, just Rotten Egg being put into a generator as normal

**Comment by TerryCavanagh** [comment]
Weird! Wonder if this one got reintroduced somehow? I'll investigate.

**Comment by TerryCavanagh** [comment]
Fixed!
