### ISSUE TITLE
Gadget preview persists into fights, and can block the description of some items

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1949]
![image](https://user-images.githubusercontent.com/32357485/93642797-9b3da180-f9f6-11ea-8866-87ff29525e32.png)

Ideally this wouldn't persist into fights, or the toggle would be present there too

**Comment by TerryCavanagh** [comment]
Uff, can't believe I missed this. I'm going to make a quick update to the steam build.

**Comment by TerryCavanagh** [comment]
Fixed.
