### ISSUE TITLE
Mirror Cauldron doesn't generate in Witch episode 5

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1953]
This is my bad! In `generators/witch_paralleluniverse.hx`, line 57 here should be `items = [floor2items.pop()];`

![image](https://user-images.githubusercontent.com/32357485/93670888-8dd7f400-fa96-11ea-9dbe-df882950884f.png)

**Comment by TerryCavanagh** [comment]
Fixed!
