### ISSUE TITLE
Counter Spell doesn't work against the Jester enemy

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1954]
Related to #1806 , because they have predetermined dice rolls, Counter Spell doesn't work as you'd expect.
![image](https://user-images.githubusercontent.com/32357485/93670503-c6c29980-fa93-11ea-84a2-11f312546823.png)

**Comment by TerryCavanagh** [comment]
Fixed! (real world example of https://github.com/TerryCavanagh/diceydungeons.com/issues/1800)
