### ISSUE TITLE
Add delay() commands before execute for *all* items that give dice, for Copycat's sake

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1959]
I just ran into a Copycat fight where he ended his turn after he used all his dice in Lucky Star, I suppose because he was out of dice for a second. This could easily happen not only with Lucky Star but with Spannersword, Duplicate, Lockpick, or any other dice manipulators.

**Comment by TerryCavanagh** [comment]
Done!
