### ISSUE TITLE
If you somehow manage to use the Finders Keepers card more than once in a battle, you should be allowed to steal more than one item

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1971]
This is possible by using the Hook limit break. It's a little disappointing that this combination *doesn't* work.

**Comment by TerryCavanagh** [comment]
Related issue: Hook *actually doesn't work* with the Finders Keepers card, because Fury and Re-Equip don't affect skillcards. So if you were to go ahead and implement this, it would cause an inconsistency. It's *probably* not worth it at this point.

**Comment by JuniorUdale** [comment]
Finders Keepers is also not once per battle. This is where the main point of confusion comes from, from the streams I've watched. People activate it, see it pop up the next turn, and think "oh, can I activate it multiple times?"

Making it once per battle would help alleviate some of the confusion.

**Comment by TerryCavanagh** [comment]
Made a change in v1.11 to more clearly make Finders Keepers once per battle.
