### ISSUE TITLE
If you run out of space to steal equipment in Finders Keepers, ???

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#1972]
There really needs to be a better reaction from the game when this happens. Particularly important if you implement https://github.com/TerryCavanagh/diceydungeons.com/issues/1971

**Comment by onetruepurple** [comment]
Make the backpack bigger?

**Comment by TerryCavanagh** [comment]
I've added a "discard something from your backpack" screen to v1.11, so this is no longer a problem. Fixed!
