### ISSUE TITLE
Crowbar builds still aren't really good

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#198]
Issues:
 - When you get the crowbar, it's clearly inferior to the poison needle. It would only be worth it if you could be sure that it would eventually pay off - but it might not.
 - Making a viable crowbar build is really hard. There's not enough good countdown equipment yet.
 - You basically *have* to upgrade the crowbar for it to work effectively.

I'd like the crowbar to be, like, the third viable thief build, so will try to tweak this a bit more.

**Comment by onetruepurple** [comment]
Maybe consider providing Snake Eye Charm very early (i.e. the first Thief chest pool) to make Dagger+Crowbar a viable level 2 game.

**Comment by TerryCavanagh** [comment]
This is a good call!

**Comment by TerryCavanagh** [comment]
Ok! Trying that change out for v0.16. Gonna leave this issue open for one last big consideration before release, though.

**Comment by onetruepurple** [comment]
Crowbar builds are now probably too good, making this issue resolved.

**Comment by TerryCavanagh** [comment]
Yep, agreed! This can go :)
