### ISSUE TITLE
Ghost Dice

### ISSUE THREAD

**Issue by retroporter42** [TerryCavanagh/diceydungeons.com#1983]
Playing in 1.9, as the Jester against the Wisp. If the Wisp inflicts vanish and you use your limit break to snap a pair of cards. When the animation shows two dice of the same value activating the cards, due to vanish one of the dice is removed as it is played. This results in a 'ghost dice' floating on the screen that can't be interacted with.
https://gyazo.com/d2c6fcd81c148a84a279e2bba57ee828

**Comment by JuniorUdale** [comment]
Duplicate of #1969

**Comment by TerryCavanagh** [comment]
Fixed for v2.1!
