### ISSUE TITLE
Trader does not update trades to match upgraded equipment

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1995]
![](https://i.frogbox.es/lrn)
I'm guessing this happened because I initially approached the trader with non-upgraded Toxic Ooze, then upgraded Toxic Ooze through a level-up reward.

**Comment by TerryCavanagh** [comment]
Ok, I've fixed the underlying crash bug here (https://github.com/TerryCavanagh/diceydungeons.com/issues/1885), which makes this one kind of a very non-serious edge case thing. Gonna de-prioritise it!

**Comment by TerryCavanagh** [comment]
Actually, this was an easy enough fix. Done!
