### ISSUE TITLE
getting blank buttons sometimes

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#2]
<img width="412" alt="bildschirmfoto 2018-03-24 um 12 02 22" src="https://user-images.githubusercontent.com/465632/37863239-451ca76e-2f5b-11e8-93a4-81a95a664dd7.png">

**Comment by TerryCavanagh** [comment]
Fixed - this was due to losing context in starling. Haxegon now flushes it's caches on `openfl.events.Event.CONTEXT3D_CREATE` events.
