### ISSUE TITLE
septic bomb is expensive

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#20]
It takes two slots, two dice that need to equal 7, requires other equipment to build up poison to be effective and doesn't bypass shields as I expected from a poison themed card.

Any of these might be great:

- smaller slot
- countdown instead of equal 7
- "Do [poison] poison damage" and "[gray](Deals [poison][d6] damage)"
(dealing direct poison damage based on the targets poison value, hence bypassing shields)

**Comment by TerryCavanagh** [comment]
I think you're right. Will tweak this for next week's build!

**Comment by TerryCavanagh** [comment]
Trying out a *requires 4* slot. Let's see how it feels!
