### ISSUE TITLE
auto playing cards makes it hard to judge details

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#200]
For some time now I've thought antidote just clears all poison and was a little confused when I once noticed some poison being left. I'm blaming this a little on there not being a whole lot of time to see the final text of a card upon inserting the dice.

It might be great to show respective dice pips inside the card slot and the final text below *while* hovering an applicable dice over it.

This would also further help with knowing whether a dice can/will drop into a card (or another nearby or just next to it).

Perhaps a similar thing can apply to cards an enemy is moving dice into (showing pips and final effect before the dice is in) as well as only clicking on dice and cards yourself (sliding them in the same way).

**Comment by TerryCavanagh** [comment]
Yep, good point! Hmmm.

**Comment by TerryCavanagh** [comment]
So, this one came up on today's random bug fix lottery! Yikes, an oldie 😅 

Occasionally I look through the oldest open issues on the list, and I always stop myself from closing this one because I still want to do this:

```
It might be great to show respective dice pips inside the card slot and the final text below while hovering an applicable dice over it.
```

This shouldn't be too difficult, I think, and is a nice QOL feature. (At this stage I'm probably not going to do the enemy equivalent though, since that would get pretty messy.)

**Comment by TerryCavanagh** [comment]
So! This one is done - both on the player side and the enemy side:

https://streamable.com/u23zl0

I'm not 100% sure what I think of it yet - it feels a bit weird, after getting so used to how it worked before. In some situations I really like it - it's great having that extra half second preview on the enemy turn, for example. And it feels really, really nice on gamepad. But I'm not as sure about it with mousing over cards?

Will leave it in for v1.9 testing and see how it goes down. Closing!
