### ISSUE TITLE
Encyclopaedia doesn't reset bonus gadget if you flee

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#2027]
![Screenshot 2019-06-29 at 00 15 23](https://user-images.githubusercontent.com/48322734/60375861-42ee3e80-9a03-11e9-946e-e97848f77531.png)
1. Trigger Encyclopaedia for bonus gadget
2. Flee fight
3. Return to fight opponent again, the Bonus gadget will still be there, and encyclopaedia will be available to use again, allowing a third gadget to be obtained.

**Comment by TerryCavanagh** [comment]
Fixed!
