### ISSUE TITLE
Boomerang bug

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#203]
winning a fight with the boomerang while "killing yourself" with it will result in the battle finishing as usual and the player having 0 HP on the map.

**Comment by joshtriplett** [comment]
Related: winning the fight with the boomerang results in your equipment starting to move offscreen as the enemy dies, then stopping for a moment when the boomerang swings back to hit you.

**Comment by Keefaz** [comment]
I encountered this bug in v0.15.1 and won the fight with -1 HP. =/

**Comment by TerryCavanagh** [comment]
Uff, ok, this bug has been hanging around forever. I'm just going to make the following very simple change: you *cannot* kill yourself with Boomerang if you've defeated the enemy - the game will cap you at 1 HP instead.

**Comment by TerryCavanagh** [comment]
Fixed!
