### ISSUE TITLE
"Spear" items are oddly named now that Spear itself is named Six Shooter

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2030]
Maybe introduce another standard card named "Spear" that only takes 6? 1x1, needs 6, do [] damage, and upgrade makes it min 5, perhaps?

**Comment by TerryCavanagh** [comment]
Ah, actually, on reflection, it isn't worth doing this. I forgot about Magic Spear, and having a pre-existing spear weapon that's identical aside from the upgrade is likely to just cause more confusion, not less. Gonna leave things as they are.

**Comment by ncrecc** [comment]
Magic Spear does 10 damage, though. Could be thought of as like the difference between Sword and Broadsword.

**Comment by TerryCavanagh** [comment]
But unupgraded, Spear and Magic Spear would be exactly the same (except I guess maybe in size). That just feels too weird to me!

**Comment by ncrecc** [comment]
Ah, miscommunication - Magic Spear already does 10 damage when unupgraded. Here's what it looks like next to the hypothetical basic Spear:
![image](https://user-images.githubusercontent.com/11216597/94633547-9f41ad00-029b-11eb-854e-b4cf13f37986.png)
(Perhaps you're thinking of nerfing Magic Spear? :p)

**Comment by TerryCavanagh** [comment]
Oh, sorry, replied to this on my phone first thing this morning and got confused

This situation:

![image](https://user-images.githubusercontent.com/2874150/94642048-9815b000-032a-11eb-9eb1-d116007fcda3.png)

...just feels very off-model to me, and I don't really see what's to be gained by making any changes here. Happy to be convinced if you feel strongly enough, though!
