### ISSUE TITLE
Unshock?ing items does 3 shock damage, but it's described as just losing 3 HP

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2042]
https://www.youtube.com/watch?v=QVc0w1nfZPE&t=1m57s

**Comment by onetruepurple** [comment]
Seems resolved in Reunion Alpha 5 (look at the limit break before and after):

https://cdn.discordapp.com/attachments/612439117741031444/941811508390809610/unknown.png

https://cdn.discordapp.com/attachments/612439117741031444/941811891892797480/unknown.png

**Comment by TerryCavanagh** [comment]
Cool! Closing 😄
