### ISSUE TITLE
Putting dice in cards with a status effect blocking dice from being inserted before the card is visibly affected lets you use it as normal

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2043]
Applies to poison?, weaken (for downgraded equipment with different filters than the original card), burn? (for multi-use equipment), silence, shock, shock?, and fury? (for multi-use equipment - doing so also cancels out the "unavailable this turn" effect until next turn)

**Comment by TerryCavanagh** [comment]
This one is fixed now in an upcoming version!
