### ISSUE TITLE
[rc1] Sprites flicker when state changes

### ISSUE THREAD

**Issue by sstangl** [TerryCavanagh/diceydungeons.com#2047]
For example, when I click a "Take" button on an equipment screen, or following a fight, the sprites seem to vanish for a single frame.

**Comment by TerryCavanagh** [comment]
Man, my brain has totally edited this out by now, but this is still a thing and it still looks very rough. Let's finally fix this before v1.10.

**Comment by TerryCavanagh** [comment]
Ok! I've fixed a couple of these and things are looking much better now! Because this is kind of a broad issue, I'm going to make some new issues specifically for the ones I still have left to fix, and close this one. Thanks!
