### ISSUE TITLE
Remix - Furied Super Alchemist doesn't ever trigger Bear Potion

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#2049]
Playing Jester Remix.

Remix options  so far are Wolf Puppy and Rat King.

So I encounter Super Alchemist and she will never use her dice to trigger Bear Potion. She just ends the round without doing anything with 1 left in the Bear Potion Countdown.

Below screenshot is round 15 or so.

![remix](https://user-images.githubusercontent.com/40739964/61813366-888c0480-ae13-11e9-8d19-ac5da3ed5374.jpg)

and 4 rounds later:

![remi2](https://user-images.githubusercontent.com/40739964/61813533-e1f43380-ae13-11e9-9f39-1b2c342ec94e.jpg)

**Comment by TerryCavanagh** [comment]
This one was fixed at some point! (can no longer replicate it, it's probably due to Bear Transform ignoring Fury)
