### ISSUE TITLE
Enemy scripts don't carry over when polyjuicing

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2055]
At least "Before Combat" does not, not sure about others: https://www.youtube.com/watch?v=H4_rTHF02QY&t=9m10s

**Comment by onetruepurple** [comment]
I was able to successfully another enemy into a Sorceress earlier - is that using a different method or can this be closed?

**Comment by TerryCavanagh** [comment]
Think this is fixed, yep!
