### ISSUE TITLE
Remix: Bully's extra Rock ignores the Lady Luck rule

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2060]
![image](https://user-images.githubusercontent.com/2095534/62004539-bd0b0380-b126-11e9-8e6f-9ad0c67410c2.png)

**Comment by onetruepurple** [comment]
Getting the Bully rule on a Hard Bonus rule is neither rare nor does it require weird actions

**Comment by TerryCavanagh** [comment]
Changed - but all I’m trying to do here is to sort by severity and frequency, and work my way down from the top. So something like this, which is only a problem if you get a particular bonus rule on hard mode, is gonna be seen less often that something that comes up on a standard start to finish run of the game. It’s really more like 2.5 I guess

**Comment by onetruepurple** [comment]
Apologies, didn't mean to be rude. But you've always had a tendancy to underestimate how often and how much people actually replay the game :')

**Comment by TerryCavanagh** [comment]
no worries!

**Comment by TerryCavanagh** [comment]
Fixed in v1.11!
