### ISSUE TITLE
Starting item suggestions for Bonus Round

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2065]
Witch: Magic Dagger + Magic Key
Thief: spatula and dagger?

(Feel free to suggestion more, anybody reading!)

**Comment by TerryCavanagh** [comment]
Some suggestions here that I'd still like to try! (more are welcome, anyone reading!)

**Comment by ncrecc** [comment]
Inventor:
Sledgehammer
Electromagnet
Venus Fly Trap
Bumpblade, Keyblade
Fire Potion
Scissors
Dark Shadow

Thief (since he's "stealing"):
Magic Missile, Magic Shield
Flower Pot, Snapdragon
Missing Score, Capacitor

**Comment by TerryCavanagh** [comment]
Many of these were considered and added, this should have been closed!
