### ISSUE TITLE
Curse activates while selecting a character during Finale

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2075]
![image](https://user-images.githubusercontent.com/32357485/62814522-43e9b400-bb09-11e9-89c5-3a120d11f9ff.png)

**Comment by TerryCavanagh** [comment]
I have a new way to fix this since v1.9, which should make this an easy fix!

**Comment by TerryCavanagh** [comment]
It sorta looks like this was maybe already fixed. Still, I put `curseavoid` tags on all the relevant cards, to be sure to be sure.
