### ISSUE TITLE
Highlight active dice better

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#208]
Almost nobody picks up on the click controls. Make the active dice highlighting a lot clearer!

**Comment by ncrecc** [comment]
https://github.com/TerryCavanagh/diceydungeons.com/issues/215 is a longstanding duplicate of this

**Comment by TerryCavanagh** [comment]
Ok, technically this version of the click controls is long gone, and when we implement the feature for mobile we're just going to start over. Therefore, this should be closed (along with any other alpha click control issues)
