### ISSUE TITLE
I beat Backstage and got the "beat a boss on level 4" achievement

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2081]
https://cdn.discordapp.com/attachments/552131784939405332/608659311023095808/unknown.png

**Comment by plasmaster09** [comment]
wait how is this a negative effect
it makes getting the achievement easier

**Comment by TerryCavanagh** [comment]
It's a little weird to unlock achievements in the finale episode out of context (e.g. defeating an enemy with full health doesn't mean much if you switch characters). I've changed this so that most achievements can't be unlocked in the finale episode.
