### ISSUE TITLE
Mechanical Arm's counter ignores vanished dice

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2083]
![image](https://user-images.githubusercontent.com/2095534/62530403-b4aa7b00-b840-11e9-89ad-d20e0df4f692.png)

**Comment by ncrecc** [comment]
If vanished dice still count toward the CPU counter it makes sense they'd count toward total rolls

**Comment by TerryCavanagh** [comment]
This one could go either way, but I think I like it as being generous on the player's side.
