### ISSUE TITLE
Parallel universe curse + keyblade crashes game

### ISSUE THREAD

**Issue by wlaub** [TerryCavanagh/diceydungeons.com#2091]
Parallel universe curse went off on keymaster's lock, then the game crashed at the start of my turn. Playing as robot.
log here: [_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/5287332/_error.txt)

**Comment by ncrecc** [comment]
Yep, game doesn't like when new equipment suddenly appears in the player's loadout before their turn starts. I think the new equipment just needs .resetfornewturn('player') run from it

**Comment by TerryCavanagh** [comment]
Thanks for the bug report! Fixed now for v1.10.
