### ISSUE TITLE
Starspear probably shouldn't inflict Blind, since it's a player item

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2099]
`attack(4); inflict(rand([CURSE| LOCK| FIRE| ICE| WEAKEN| SHOCK| POISON]));`

If this is because Blind doesn't work well in PU, then Starspear needs to be changed. Either way, there's a slight inconsistency here!

**Comment by TerryCavanagh** [comment]
Determination is meant as a player item, so this is deliberate. Blind isn’t *really* meant as thing you can inflict on enemies!

**Comment by JuniorUdale** [comment]
In which case, Starspear should probably get Blind removed from it, since that's a player item too.

**Comment by TerryCavanagh** [comment]
Yep, that's a good point!

**Comment by TerryCavanagh** [comment]
Done!
