### ISSUE TITLE
can't slot dice into inventory sometimes

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#21]
maybe if i drag dice before the animation has started? not sure. they won't slot at all

<img width="991" alt="bildschirmfoto 2018-03-31 um 12 52 59" src="https://user-images.githubusercontent.com/465632/38162504-90a81f1a-34e2-11e8-930d-8150bbec82b3.png">

(I couldn't slot for the rest of the fight, I just died )

**Comment by TerryCavanagh** [comment]
Annoyingly I've never had this one happen when I'm playing, so I've got no idea what's going on here... I'll try dragging quickly and seeing if I can reproduce!

**Comment by TerryCavanagh** [comment]
YESSSS, finally got this one
