### ISSUE TITLE
Crowbar applies to counts of equipment that's already been used

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#210]
![newfrozen](https://user-images.githubusercontent.com/2874150/40438135-3044d3a6-5eaf-11e8-9b44-7a4eaa675010.gif)

```
I see reports that the the crowbar+ works on stunned items. I think it also
keeps adding to the counts of items after they've been used, so they come
back at 0 in the next turn.  For example, in this build, I put all my dice
trough the crowbar+. After reaching 12, the midnight charm activates, gives
me two sixes, ande disappears from the screen because it has been used for
the turn. I feed the two sixes to the crowbar+, using them on the remaining
stuff. When my next turn starts, the midnight charm is at 0. and activates
immediately (same for the grappling hook, etc.). So the only explanation I
have is they must have replenished their counts after being used and
disappearing in the previous round.
```

(Could be a clue to the bug where some equipment comes back starting the turn at zero)

**Comment by joshtriplett** [comment]
While this is certainly a bug, personally, I find it an interesting aspect of a Crowbar+ build as well.

**Comment by hupfen** [comment]
Still occurs in v0.16. I agree that it has some interesting strategic value but I felt _very_ OP by the end. https://www.youtube.com/watch?v=jf-x6KNuYrE

**Comment by mrcdk** [comment]
this is fixed. Crowbar doesn't affect used, shocked or cursed equipment anymore.
