### ISSUE TITLE
If you quit during a Frog rule run and reload, the new boss's HP won't be adjusted - so you can change e.g. Frog's HP from 100 to 9

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2109]
It seems like the Frog rule script must be getting re-run, but the HP adjusting part isn't working for some reason.

**Comment by plasmaster09** [comment]
ironically one of the ways to potentially solve this would be to employ the same substitution-actuator shenanigans that I've had to use to get around the whole "only save the bare minimum" thing myself

**Comment by TerryCavanagh** [comment]
Fixed for v2.1!
