### ISSUE TITLE
You can reach the "0 health but still alive" state with Cactus' rule

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2124]
![image](https://user-images.githubusercontent.com/32357485/95666319-64b7fa00-0b50-11eb-952e-29f7744bcf2d.png)

Same thing as #203 but under different circumstances.

**Comment by kvxoqdnn** [comment]
I also got this, but from the cactus enemy's thorns. I was able to heal back to regular health using the apples on the map screen and continue on as normal, but without any battle music apart from the low health heartbeat sound.

**Comment by TerryCavanagh** [comment]
Fixed! Added a separate check that covers both of these cases!
