### ISSUE TITLE
6 to all counts/99 to all counts text in the Accelerate and Overdrive gadgets is a little unclear

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2125]
Originally this was a space issue, but that's less of an issue now since the text size decreased. There's probably room now to change this to `Add 6 to all counts` or maybe even `Reduce all countdowns by 6` or something like that.

(This is a very easy fix, but it does require updating all the localisation spreadsheets too)

**Comment by ncrecc** [comment]
"Add" might imply *raising* the countdowns

**Comment by TerryCavanagh** [comment]
Yeah, hmm! Actually come to think, that might have been the original working, and I think it was changed for exactly that reason 🤔

**Comment by TerryCavanagh** [comment]
Turns out these fit as "Reduce countdowns by X"! Fixed.

![image](https://user-images.githubusercontent.com/2874150/95701720-e6637100-0c91-11eb-95bd-127ef3436d4f.png)

![image](https://user-images.githubusercontent.com/2874150/95701851-2d516680-0c92-11eb-87b0-c9da24eae196.png)
