### ISSUE TITLE
"No effect!" damage indicator is always shown in English

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2127]
When using an item that deals no damage to the enemy (for example, using Fireworks when the enemy has no status effect), the displayed text is always shown as "No effect!" in English. This is probably solvable in the same way as "New Gadget!" by just removing the exclamation mark, since languages already provide a translation for "No effect" without the exclamation mark.

Tested on v1.9.1 (Translator Mode).

**Comment by Ereza** [comment]
![no_effect](https://user-images.githubusercontent.com/285008/95753293-b58b3800-0ca1-11eb-889b-c125328906da.png)

**Comment by TerryCavanagh** [comment]
Aha! Fixed, thank you!

**Comment by Ereza** [comment]
The issue is still in v1.10, at least in some cases, see screenshot:

![image](https://user-images.githubusercontent.com/285008/101685620-44c98780-3a68-11eb-97a0-47d546dd84bc.png)
