### ISSUE TITLE
At least one jinx and its description are partially shown in English

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2128]
While in the final battle with Lady Luck, at least one of the jinxes ("Lock two dice") appears in English. The description is also partly shown in English, since the tring is dynamically constructed ("In 1 turn, {jinxaction}." or "In {numturns} turns, {jinxaction}.")

I think it might happen with other jinxes too.

Tested on v1.9.1 (Translator Mode).

See attached screenshot:

![lock_two_dice](https://user-images.githubusercontent.com/285008/95753831-73aec180-0ca2-11eb-9950-86262d31c0a2.png)

**Comment by TerryCavanagh** [comment]
Ohh, this probably happens with a few of the Lady Luck jinxes. Thanks! I'll dig into this and see if I need to get some new strings translated!

**Comment by TerryCavanagh** [comment]
Yikes! So, looks like there are 4 Lady Luck jinxes hardcoded into the game:

![image](https://user-images.githubusercontent.com/2874150/96816803-81640400-1465-11eb-809a-a632d31534bb.png)

Looks like I'm going to have to get some new strings translated!

**Comment by TerryCavanagh** [comment]
As it turns out, I actually have all four terms localised already in equipment.csv - but I will need to check that they're all correct in this context with my translators before this version ships. Can close this issue now!

![image](https://user-images.githubusercontent.com/2874150/96823359-e32b6a80-1473-11eb-93a3-297ff66b5cf4.png)

**Comment by TerryCavanagh** [comment]
Whoops, tiny bug with that fixed:

![image](https://user-images.githubusercontent.com/2874150/96823532-3b626c80-1474-11eb-92e4-e7d96f354ca8.png)
