### ISSUE TITLE
Clarify how Lockpick splits up dice

### ISSUE THREAD

**Issue by LewisDyer** [TerryCavanagh/diceydungeons.com#213]
When I first saw the lockpick, I would expect it to split dice as evenly as possible (i.e a 6 splits 3/3, a 5 splits 3/2, and so on) - but it doesn't seem to do this.

Could it be made clearer how this works (e.g telling you how it splits up in the description, or perhaps showing you a preview of what the dice splits into)?

**Comment by TerryCavanagh** [comment]
Hey - thanks for the report and suggestion, but having thought it over, I think the game is better with the uncertainty of the outcome of a lockpick use. I'm going to leave it as is. Closing this.
