### ISSUE TITLE
When enemy first transforms into a bear from Alchemist rule, the Bear Maul cards slide on-screen, then disappear and slide on-screen again

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2131]

**Comment by TerryCavanagh** [comment]
Uff. Annoyingly, I'm certain this one was fixed in an earlier version, so I guess something broke it.

**Comment by TerryCavanagh** [comment]
Well, this one has mysteriously stopped happening in my test builds, so I guess something *fixed* it again. Easy come easy go!
