### ISSUE TITLE
Missing sound effect as you start the final fight

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2133]
When Lady Luck turns around, there's an awkward silence. The console traces

`PlaySoundsCommand.hx:107: music/combat/ladyluck/wheeloffortune.ogg not found in LoadStuff.availablesoundslist` 

as well as 

`AudioControl.hx:195: warning: ladyluck/personality/ is empty (or doesn't exist).`

**Comment by TerryCavanagh** [comment]
Fixed!
