### ISSUE TITLE
Short Circuit should not inflict blind

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2134]
Little edge case I missed (in fact, I think this is the most common way to inflict blind on enemies!)

**Comment by JuniorUdale** [comment]
Isn't Thief stealing equipment like Ink Splat/Camoflage more common? I've seen that pop up more often than Short Circuit hitting the 1/8 chance to blind enemies. Are you planning on changing that interaction somehow (e.g. by giving enemy blinding equipment the `cannotsteal` tag)?

**Comment by TerryCavanagh** [comment]
Already done, I just forgot this!

**Comment by TerryCavanagh** [comment]
Fixed.
