### ISSUE TITLE
Level 4 Jester can inflict Silence on Robot

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#2138]
![image](https://user-images.githubusercontent.com/26709843/96369116-824d1b00-1171-11eb-867c-d33549938254.png)
Was Robot's Silence immunity removed with the implementation of usecpuinsteadofdice?

**Comment by TerryCavanagh** [comment]
Oh, yikes!

I guess I should rethink that Jester silence attack 🤔

**Comment by TerryCavanagh** [comment]
Ok, fixed! Jester Enemy level 4 gets Shriek instead of Wail now.
