### ISSUE TITLE
If the displayed description has more than 3 lines and the item is size 1, the first line will overlap with the NEEDS X string

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#2139]
With the introduction of the Magician remix rule, any three-line equipment description can overlap with these conditional slot strings. This would be even more common when you're playing with a different language, as three-line descriptions are often required in localized strings. Example image:
![image](https://user-images.githubusercontent.com/26709843/96460885-251e9b80-123d-11eb-9142-5d497414585d.png)

**Comment by ncrecc** [comment]
See also #1714 (although that issue didn't address magician rule or translations)

**Comment by TerryCavanagh** [comment]
Oh right, yep - with localisations, this becomes a thing that basically every player who plays in those languages will see. I'll try to figure out a fix for this soon.

**Comment by TerryCavanagh** [comment]
Fixed. It's not pretty, but hopefully it shouldn't be something you see very often.

![image](https://user-images.githubusercontent.com/2874150/96680963-00056680-13be-11eb-85c5-56ce378cc80c.png)
