### ISSUE TITLE
Show current gadget in inventory or character sheet (??)

### ISSUE THREAD

**Issue by kindfulkirby** [TerryCavanagh/diceydungeons.com#214]
I tabbed away from the game (Inventor run) and when I got back I had forgotten what my current gadget was.

Showing it in the inventory or somewhere else would be useful.

**Comment by TerryCavanagh** [comment]
Inventor needs clearer communication about their gadgets. Adding this one to High Priority for launch.

**Comment by TerryCavanagh** [comment]
Uff, ok, I agree that this would be a really nice thing, and it's a shame it's not in the game. But honestly, I just don't know where to put it at this point - there's just no room in the UI for it. So I'm just going to live without it. Closing.
