### ISSUE TITLE
Text resize tags remove colour

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#2140]
![image](https://user-images.githubusercontent.com/26709843/96717571-1ca29e00-13c0-11eb-8033-eebeeb680e8f.png)
![image](https://user-images.githubusercontent.com/26709843/96717588-22987f00-13c0-11eb-8584-8cad0e6a579a.png)

**Comment by TerryCavanagh** [comment]
ohh - this is easy to fix for this particular case, but not so much in general. Does this come up anywhere else, or just in these limit break tooltips?

**Comment by TheMysticSword** [comment]
Don't remember seeing this particular combo anywhere else, will report if I find this again!

**Comment by TerryCavanagh** [comment]
Oh, hmm - looks like this isn't happening in my development build, so I must have fixed it already?

![image](https://user-images.githubusercontent.com/2874150/96808017-82923280-145f-11eb-914e-385e8fd69e91.png)

The code for this definitely looks like it shouldn't be removing the colour symbol:

```
TooltipManager.updatetooltipline("player_limitbreak", 0, {func: function() return "[yellow]" + Locale.removesymbols(Locale.translate(Game.player.limitbreak.name)) + "[]"}, Col.WHITE, "headerfont", Text.CENTER);
```

I think this is probably working correctly, so I'm going to close it! If you still see this in the v1.10 testing build, let me know and I'll reopen!
