### ISSUE TITLE
Highlight effects are much too subtle

### ISSUE THREAD

**Issue by jmickle66666666** [TerryCavanagh/diceydungeons.com#215]
When selecting a dice, and other highlight effects, it is barely noticeable that the element is highlighted. Adding a border and/or changing color would help a bunch in terms of readability. (I didn't even notice the highlighting was happening for many versions)

**Comment by ncrecc** [comment]
Highlights/"active dice" no longer exist per #208

**Comment by TerryCavanagh** [comment]
As with https://github.com/TerryCavanagh/diceydungeons.com/issues/208, this version of click controls has been removed, so this issue isn't relevant. When we reimplement click controls for mobile, we're starting over. Closing!
