### ISSUE TITLE
Credits screens issues when using the Halloween mod

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2152]
When loading the Halloween mod, the credits screens have several issues:

- Dice people except for Warrior and Thief are shown in their silhouette form (even with everything unlocked in both the base game and the Halloween Special).
- The "Beta testing" screen should be moved upwards if possible, since it gets too close to the bottom.
- Japanese publishing and localization screen shows no credits at all.

Tested on v1.10 alpha 1.

See screenshots:

![credits_1](https://user-images.githubusercontent.com/285008/97207266-1c3c4580-17ba-11eb-9170-288744210001.png)
![credits_2](https://user-images.githubusercontent.com/285008/97207269-1cd4dc00-17ba-11eb-9728-53a396956cd9.png)
![credits_3](https://user-images.githubusercontent.com/285008/97207271-1d6d7280-17ba-11eb-9f0b-7db7d7250937.png)

**Comment by TerryCavanagh** [comment]
Whoops, forgot that Halloween Special has a separate `credits.csv` file (which got out of sync). Thanks! Fixed.
