### ISSUE TITLE
Dice slot icon is partially unseeable at 90% text size (Crescent Moon Blade)

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2156]
![image](https://user-images.githubusercontent.com/11216597/97391082-c39da300-18b4-11eb-8f74-426f494d4372.png)

**Comment by TerryCavanagh** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/2874150/97545886-90295880-1a1b-11eb-95b1-3092bbfd427c.png)
