### ISSUE TITLE
Witch's Hall of Mirrors / Mirror Cauldron Chest doesn't appear

### ISSUE THREAD

**Issue by crisdiazg** [TerryCavanagh/diceydungeons.com#2159]
After 1.9 actualization, Hall of Mirrors / Mirror Cauldron chest doesn't appear in Floor 2 as usual. 

![Capture](https://user-images.githubusercontent.com/62227122/97448324-8bbb4d80-18fe-11eb-8e91-a0eb3b30f896.PNG)

**Comment by TerryCavanagh** [comment]
Thanks for the bug report! This one is fixed in the latest v1.10 build!
