### ISSUE TITLE
First-time players don't understand how battles work

### ISSUE THREAD

**Issue by jmickle66666666** [TerryCavanagh/diceydungeons.com#216]
Twice just now in the discord, a player was confused about the battles, saying they ended their turn without doing anything because they didn't know what was happening. Some indication that you need to drag dice into the slots would help tremendously.

Perhaps a "ghost finger" showing a dragging motion from the dice to the player's first equipment would be good? Something unintrusive but helps show the player the main mechanics.

**Comment by TerryCavanagh** [comment]
Added a tutorial in v0.16, which I think sorts this out finally!
