### ISSUE TITLE
Buster and Wicker Man's Bonus Round's rules can appear in the same run

### ISSUE THREAD

**Issue by crisdiazg** [TerryCavanagh/diceydungeons.com#2160]
In the same run in Bonus Round, Buster and Wicker Man rules can be applied at same time, prioritizing Wicker Man's rule. Those rules should be mutually exclusive.

**Comment by TerryCavanagh** [comment]
Good catch! This is an easy fix I'll take care of right away.

**Comment by TerryCavanagh** [comment]
Fixed!
