### ISSUE TITLE
Fight! Sign in Spanish's translation is wrong

### ISSUE THREAD

**Issue by crisdiazg** [TerryCavanagh/diceydungeons.com#2161]
I decided to play the Spanish translation and the "Fight!" sign is actually translated into another language

![Capture](https://user-images.githubusercontent.com/62227122/97453845-20747a00-1904-11eb-89be-c0866debadcc.PNG)

**Comment by TerryCavanagh** [comment]
Ah, yep - already fixed for v1.10, thanks. This was a google drive error that messed up a couple of our localised assets (the Italian "You Win!" sign was broken too). Fixed in the steam testing branch!
