### ISSUE TITLE
Add some other use for unused equipment

### ISSUE THREAD

**Issue by Somulos** [TerryCavanagh/diceydungeons.com#217]
Currently equipment can't be used for anything other than combat, which means that unused equipment just sort of rots away in your backpack. There should be an ability to use that equipment for something else (maybe turn it into money or XP or use it to upgrade other items) with the tradeoff obviously being not being able to swap it in between battles anymore.

**Comment by YinYin-Falcon** [comment]
Heh, I mostly want to sell things at shops.

Have you played the inventor yet? You are forced to scrap an equipment after every fight.

**Comment by TerryCavanagh** [comment]
I think, for better or worse, this is just part of the game now. Closing!
