### ISSUE TITLE
Boxing Gloves should deal damage on 1, like other "deal [] damage, on _, do ____" items

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2174]
![image](https://user-images.githubusercontent.com/32357485/98314811-b37d7600-1fce-11eb-8fc7-6139f5eecfeb.png)

Either that, or get the description changed to "deal [] damage, on 1, gain 1 reduce instead"

**Comment by TerryCavanagh** [comment]
Whoops, yep, meant to revert that before v1.10 😅 Oh well. v1.11 or v1.10.1 it is!

**Comment by TerryCavanagh** [comment]
Fixed for v1.11! (or v1.10.1, whichever comes sooner)

I kinda like the new behaviour, so I've changed the string to `Do [sword]<d6> damage, on 1, gain [reduce]1 instead`. Localisations still have the old description, but that's ok - I'll update that next time I get some new strings.
