### ISSUE TITLE
When Reduce by? blocks an effect, the text is shown in English

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2184]
While playing in Parallel Universe, when "Reduce by?" blocks an effect, a text is shown above the player character. This text is always shown in English, at least for the "Blocked ice?!" case, but probably others too. Maybe it could be changed to "Blocked!" instead, since this string is already available in the translations?

Tested on v1.10.

See attached screenshot:

![blocked_ice](https://user-images.githubusercontent.com/285008/99138280-e0193980-262f-11eb-9e2e-1976a1ae6a9e.png)

**Comment by TerryCavanagh** [comment]
Thanks! This one should be an easy fix for v1.11!

**Comment by TerryCavanagh** [comment]
Fixed! (cc https://github.com/TerryCavanagh/diceydungeons.com/issues/2197)
