### ISSUE TITLE
Now that we have the curseavoid tag, consider allowing Skeleton/Dire Wolf in the final episode

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2186]
Banshee would need to be left out because she can freeze (and is superior to Skeleton in many ways, though that's a different discussion). However, Skeleton and Dire Wolf would probably fit in fine if important equipment like Wheel of Fortune was given the `curseavoid` tag.

**Comment by TerryCavanagh** [comment]
Good suggestion! I'm going to make this change today :)

**Comment by ncrecc** [comment]
Making Curse never trigger for Lady Luck might fit in with her "naturally" ultra-lucky rolls

**Comment by TerryCavanagh** [comment]
Done! Skeleton can now appear in this episode!

Banshee is still excluded because of Freeze, and I decided not to add Dire Wolf either because it would be a little weird to potentially have a run where Wolf Puppy fights Dire Wolf.
