### ISSUE TITLE
There is an extra "Lady Luck[]" localization string in fighters.csv

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#2193]
This one fixes #1761
`,Lady Luck[],Госпоже Удаче,Lady Lucks name as it appears in the credits screen (needed for grammer reasons),`
The second one appears later in the file and overrides the previous one, reverting the fix for #1761
`,Lady Luck[],Госпожа Удача,Alternate version for Bestiary icon,`
![image](https://user-images.githubusercontent.com/26709843/99871796-1db52e00-2bff-11eb-8575-4cecf634bfc2.png)

**Comment by TerryCavanagh** [comment]
Sorry about the reversion! This one is fixed again for the next version!
