### ISSUE TITLE
Several AI issues

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#220]
Actolyte would rather unstun Divine Rod than cast Verse of Sorrow (Divine Rod requires 3 dice, Actolyte has 3 dice); Actolyte unstuns Divine Rod even if it doesn't have sufficient dice to cast it

Druid (old) with two 1s and one 3 would rather put 3 in health crystal than put 3 in staff with 3 countdown remaining

Wiz would rather unstun a spell he doesn't have the die for than place the unstunning die into its appropriate spell

Barbarian (old) would rather put a die 3 or below into Throwing Axe than put it into Fists

Wisp with just one 3 would rather put 3 in backfire than use 3 to unstun

v0.8: Stereohead with one 3, one weakened Sonic Boom and one regular Sonic Boom, would rather put 3 into weakened move instead of regular power move

v0.8: Wisp with only one burned 4 apparently tried to pick up the 4, dealing 2 fire damage, but could not place it anywhere.

v0.9: Blowfish would rather place a die in a stunned Spike than place it in Pop!

v0.10.1: Baby Squid with two 2s would rather unstun Ink Splat and use Headbutt than use Headbutt twice

**Comment by joshtriplett** [comment]
Related: the AI will often choose to unlock a piece of equipment even if it has others of that equipment; seems like it has a preferred order to use them in.

**Comment by TerryCavanagh** [comment]
All of these issues apply to the old AI, which has been completely replaced. Fixed!
