### ISSUE TITLE
Verse of Sorrow is listed in editor under "Shields"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#221]
1-damage attack with no additional side-effects.
Given the context (Acolyte's side weapon) maybe it should be under Magic

**Comment by onetruepurple** [comment]
Made me think there could exist some kind of Acolyte+Knight amalgam, with three dice, several Scrap Metal cards and a very low % of a double Shield Bash.

**Comment by TerryCavanagh** [comment]
Ditto with healing crystals

**Comment by TerryCavanagh** [comment]
Fixed!
