### ISSUE TITLE
Ring of Sacrifice does not protect against poison death

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#222]
It goes against "cannot die this turn," but part of me feels like that's intentional because poison happens after the turn is over.
You also get poison damage on the turn that you flee

**Comment by YinYin-Falcon** [comment]
I think poison happens _at the start_ of a turn. So yes, you cannot technically protect against it as your actions only come afterwards - which is an issue in itself.

**Comment by TerryCavanagh** [comment]
Fixed with Last Stand redesign!
