### ISSUE TITLE
[BR][PU?] When Warlock rule is applied, Fireball's name is not modified

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#2223]
Snowball becomes Snowball?, but Fireball retains the same name; this particularly stands out when fighting the Marshmallow.

**Comment by ncrecc** [comment]
This is because Fireball does not need a ? version. Snowball needs one because part of its description, "freeze 1 dice," is nonsensical when freeze? affects all dice.
