### ISSUE TITLE
Freeze can affect Spare Dice cards when playing as Jester

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2226]
Can't believe I hadn't encountered this one before! Very easy to reproduce this in Jester episode 2. Worth checking that it doesn't come up in regular episodes too.

(marked as Positive/Neutral because it's actually kind of a benefit if your spare dice card "catches" the freeze effect)

**Comment by ncrecc** [comment]
Not just as Jester; it's this way for characters with normal equipment layouts (and probably Witch) too

**Comment by TerryCavanagh** [comment]
Fixed!
