### ISSUE TITLE
Make Dicey Dungeons more gender- and race-inclusive

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#223]
I suggest that not all the gendered characters (protagonists and enemies) be male in the final version!

Given the current art style, none of them look particularly gendered, but I've heard you refer to them as "he" in the discord which is what made me think to mention this. So this is a suggestion for:
- **the future art style**
- **in-game text** (I don't think there are currently any pronouns or other gendered words in the in-game text, but who knows what the future may hold)
- **the lore** - which you hold the canon of. If, for example, you want the protagonists to be gender-neutral dice, that's great, but would be undermined if you refer to the protagonist as "he".

(My headcanon is that the Inventor is Agatha from Girl Genius in dice form.)

As for race inclusivity, the human enemies already have two skin tones which is awesome, and adding a third darker skin tone would be even awesomer.

I may, if pressed, admit that Dicey Dungeons will not solve sexism or racism, but every little bit helps (:

**Comment by TerryCavanagh** [comment]
Yeah, this is worth figuring out! Thank you for creating the issue!

(Slight spoilers: The characters get *transformed* from humans to dice people. I see the warrior as male, the thief as female and I'm not sure about the inventor yet.)

**Comment by pace212** [comment]
Whoa that's a cool premise!

**Comment by ttheuer** [comment]
As a non-binary person, I'd love see some non-binary representation!
HMU (on Discord, preferably, I don't check github notifications all that often) if you need input for that :wink:

**Comment by BaconCatBug** [comment]
Or how about they make the characters whatever they want? If I wanted SJW nonsense I'd seek it out in university.

**Comment by Zeks** [comment]
Yes yes, let's make queer _dice_, then include a bunch of absolutely unnecessary comments/arts making sure ppl can't miss that they are queer when every other character except a witch is gender neutral and witch is female _by definition_.

**Comment by Zeks** [comment]
Note: I still think that Terry can and should do whatever the hell he wants with his characters. It's just my 2 cents why  ppl asking for gender inclusivity aren't doing anyone (except those whose ego sells with each bastion fallen) a service.

**Comment by TerryCavanagh** [comment]
(Zeks, I assume you're zekses from the discord? We disagree on this, but I appreciate you being civil about it.)

Ok: I feel like you have three main concerns:
(1) That I will feel pressured by this issue, and therefore compromise my own vision for the game.
(2) That, if I have gender non conforming characters in the game, I will have to address that in the game at length, and that therefore the story will become "about" gender in some way.
(3) That I will end up making one of the characters non-binary.

(1) I don't feel pressured by this issue, or by your response to this issue. I appreciate people's suggestions and feedback, but ultimately, I'm going to do what I think is best for the game.
(2) Dicey Dungeon's story is likely to end up being pretty minimal and saturday-morning-cartoon-like, so I think it would be weird to spend time in cutscenes having the characters talk about anything that's not about their adventure. I feel like this fear is misplaced.
(3) Dunno, maybe! Why not? Having more characters in the game that people can relate to is a strictly good thing.

As an aside, you've come across as quite "DON'T DO THIS" where other people have been "maybe consider such-and-such" - but you've also said that you think I should do what I want with the characters so I'll take you at your word on that.

**Comment by BaconCatBug** [comment]
On point 3, shoehorning in characters for the sake of "diversity" is actually the bigoted thing to do. Make whatever characters YOU want to make, don't let the shrieking SJW harpies dictate to you in any way, shape or form what YOU want to do with YOUR characters.

**Comment by ttheuer** [comment]
Yes, horrible how shrieking and angry the people in this thread have been... *shakes head*

Funny how they all used the word "SJW" and seem to want to pressure Terry into accepting their "binary only" and "less women" position :thinking:

**Comment by Zeks** [comment]
Funny how someone can't read. I've stated my arguments against non-binary
and you've not even tried to argue your point.
And I've never said I want less females also. Apparently you can't into
irony.
