### ISSUE TITLE
Counter doesn't apply to dice rolled via Illuminate

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2233]
![image](https://user-images.githubusercontent.com/11216597/100912641-bd47ab80-349e-11eb-95dc-5209547931cd.png)
Could be a resurgeance of #1800, I've seen some other incorrect countering in this run (e.g. have counter 2, use an item that gives two 3s, 3s may be locked)

**Comment by TerryCavanagh** [comment]
This one is fixed now!
