### ISSUE TITLE
Generators can crash under certain circumstances

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2234]
Some generator have empty lists in the generators to be consistent with the other episodes. For example, YCYL has this: 
`var commonlist_advanced = ["Ray Gun", "Juggling Ball", "Hammer", "Spiked Shield", "Short Circuit"];
var floor2basic = [];
var floor2advanced = ["Forcefield"];`
However, if a mod tries to append to `floor2basic`, then the results get replaced with 0s for some reason. This causes crashes!

To fix this, in `data/text/scripts/flexible_generator.hx`, line 22 needs to be made more robust:
![image](https://user-images.githubusercontent.com/32357485/100953288-3203ff80-350a-11eb-97ed-2201b94485e3.png)
![image](https://user-images.githubusercontent.com/32357485/100953312-40eab200-350a-11eb-851a-b51d2daa6b05.png)

This is technically a modding issue, but it's preventing mods from working properly (in my experience, about ~10-20% of the tim the game crashes on YCYL).

**Comment by TerryCavanagh** [comment]
Ah ha! I'll fix this for the next update, thanks!

**Comment by TerryCavanagh** [comment]
Thanks @ncrecc! https://github.com/TerryCavanagh/diceydungeons.com/issues/2235

**Comment by TerryCavanagh** [comment]
Fixed! Thanks @JuniorUdale and @ncrecc!
