### ISSUE TITLE
Supplied 1-line fix for flexible_generator.hx to prevent arcane headaches with erroneous .concat() behavior on empty arrays

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2235]
Change line 22:
```haxe
			itempools[i] = itempools[i].concat(itemstoadd[i]);
```
to this:
```haxe
			if(itempools[i].length > 0) itempools[i] = itempools[i].concat(itemstoadd[i]); else itempools[i] = itemstoadd[i].copy();
```

Context: vanilla's YCYL generator, for some reason, has an empty array for floor2basic (which is never directly pulled from but gets lumped into a commonlist). More Fluff's YCYL generator has an item in that array. When the non-empty array gets concatted onto the empty array, for some reason the contents of the non-empty array are changed entirely to "0".

![image](https://user-images.githubusercontent.com/11216597/100953820-50093a00-34e1-11eb-9241-6022d02e40d0.png)
![image](https://user-images.githubusercontent.com/11216597/100953828-54cdee00-34e1-11eb-883e-04f50abde1fa.png)

**Comment by TerryCavanagh** [comment]
Fixed! Thanks.
