### ISSUE TITLE
[BR] Rose and Crystalina rules have unexpected interaction

### ISSUE THREAD

**Issue by findersjeepers** [TerryCavanagh/diceydungeons.com#2236]
Although the phrasing of Rose rule is "Both you and your enemies **do** +1 extra damage with each **attack**", when Crystalina rule is also active, Rose rule causes the player to take one additional damage from the leftover-dice penalty. For instance, if four dice are left over, the player takes 5 damage, even though this was not damage done by an **attack from the enemy**.

**Comment by TerryCavanagh** [comment]
Yep, makes sense! Fixed.
