### ISSUE TITLE
Bonus round rule randomness possibly broken?

### ISSUE THREAD

**Issue by Slikk2k** [TerryCavanagh/diceydungeons.com#2238]
I've noticed that when launching the game with the powershell command start-process -wait, I'm able to see debug information printed to the console. This is most interesting when playing the bonus rounds; when first starting a bonus round, this is printed:
```
Remixstate.hx:76: set 2_ to [Buster,Keymaster,Wolf Puppy,Rose,The Witch,Rat King,Mimic]
Remixstate.hx:76: set 3_ to [Snowman,Wicker Man,Magician,Vacuum,Slime,Cactus]
Remixstate.hx:76: set 4_ to [Bully,Wizard,Sorceress,Alchemist,Beatrice,Bounty Hunter,Cowboy]
Remixstate.hx:76: set 5_ to [Paper Knight,Cornelius,Rhino Beetle,Loud Bird,Drake,Space Marine,Fireman]
```
Which appears to be a list of random rule choices for each floor, and is different each time you start a bonus round. What happens throughout the round is that the first rule in each floor is always what you are offered - i.e. on floor 2 the game will offer the Buster rule, on floor 3 the Snowman rule, and so on. Not very random, but maybe still the intention, I'm not sure.

Where it gets really interesting is, if you reject the offered rule and choose to get a random rule instead, then you always receive the second rule choice for that floor - i.e. if I reject the Buster rule on floor 2, I will get the Keymaster rule instead, nearly 100% of the time. The other rule choices for the floor appear to be ignored. Edit: of course, right after posting this, I was given the third choice for a floor for the first time. In any case, it appears that the second choice is chosen most often, which isn't very random.

I could be interpreting this totally incorrectly of course, and this is the intended mechanic, so I apologize if so. It just seems odd that the game would choose a list of 6-7 rules per floor, and then ignore all but the first two in the list each time.

This is with version 1.10 of the game.

**Comment by TerryCavanagh** [comment]
Aha! This is actually working as intended!

The way the game works is that it pre-fills the bonus rule selections in these arrays. The top one is what gets presented to you, and the second one is what you get if you press "random". The ones below that are fallbacks for if you select something that conflicts with a rule you've chosen - e.g. if you choose the Warlock rule, then you can't get offered Wicker Man.
