### ISSUE TITLE
Recurring in-combat crashes to desktop-- Nvidia/OpenGL issue? 

### ISSUE THREAD

**Issue by Bard09** [TerryCavanagh/diceydungeons.com#2245]
(Crossposted from Steam here: https://steamcommunity.com/app/861540/discussions/1/2965020518362153393/) 

I just purchased the game and am receiving intermittent CTD during combat. Sometimes it is as few minutes after resuming my save; sometimes several hours afterwards.

I checked Windows Application Event Viewer and found the following items...

Application Error:
```

Faulting application name: diceydungeons.exe, version: 0.0.0.0, time stamp: 0x5fa4064f
Faulting module name: nvoglv64.dll, version: 27.21.14.5671, time stamp: 0x5f75532b
Exception code: 0xc0000409
Fault offset: 0x00000000011584c9
Faulting process id: 0x1be8
Faulting application start time: 0x01d6c50ccf15db99
Faulting application path: D:\Steam\steamapps\common\Dicey Dungeons\diceydungeons.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_8dccece3a1276290\nvoglv64.dll
Report Id: b52ca3c7-2042-4f5b-a346-8e175c7af663
Faulting package full name: 
Faulting package-relative application ID:
```

Nvidia OpenGL Driver:

```
A TDR has been detected. The application must close. Error code: 7 (pid=7144 tid=14548 diceydungeons.exe 64bit) Visit http://nvidia.custhelp.com/app/answers/detail/a_id/3633 for more information.
```

Not aware about how to obtain the game-generated crash logs; if you provide info on where they're located, I'm happy to provide them!

**Comment by TerryCavanagh** [comment]
Hey, this one absolutely looks like a bug with your computer's hardware, sorry. I strongly recommend a complete clean install of your graphics drivers to rule out software issues:

https://www.driversupport.com/knowledge-article/how-to-reinstall-graphics-driver-in-windows-10/

Good luck!

**Comment by TerryCavanagh** [comment]
Hi there! I know it's been a few years, but did you ever try a graphics card driver reinstall? Did it fix the issue?

**Comment by Bard09** [comment]
I've since upgraded to a new OS (Windows 11) with a new graphics card (Nvidia 3060) and it's seemingly resolved the issue for me at least.  So far everything has been perfectly stable since the upgrade.

My gut is that the issue was related to the fact I was using a really old Nvidia card (a 680) at the time.
