### ISSUE TITLE
Robot "You Choose you Lose" Locked dice do not function correctly when equipment fails. 

### ISSUE THREAD

**Issue by Cody-KW** [TerryCavanagh/diceydungeons.com#2249]
When going through the "You choose you lose" episode in the robot campaign. When choosing dice that also cause equipment to fail causes the equipment to fail like normal. However the dice itself does not lock as well. In the screenshot below you can see that my first roll succeeded and was locked. However my second roll failed destroying my  equipment but giving me the dice normally. 

Steps to Repro: 
1. Paper Knight/Rhino Beetle Lock dice
2. Choose Dice
3. Equipment Fails
4. User gets dice. 

![PaperKnight_Robot_LockedBug](https://user-images.githubusercontent.com/75864569/102137717-e19d7380-3e20-11eb-9d06-3317e06e8b78.png)

**Comment by XenonZed** [comment]
Appears to be the same issue as #1225

**Comment by TerryCavanagh** [comment]
This one was fixed!
