### ISSUE TITLE
Display options on Switch (and controller in general) are not working correctly

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#2251]
Holding up or down on the controller quickly moves the selection between combat animation and back.

Combat animation and Disable screen effects can be selected by moving the controller direction left and right (as if they were next to each other, but you cannot hold it). And pressing down on Disable screen effects goes to the back button.

The steam version has similar issues.

The most pressing issue however is that the combat animation, once changed, snaps to the slowest setting and cannot be changed anymore:

https://streamable.com/ybhyz3

(I did use touch controls first - in case that may have triggered it)

**Comment by YinYin-Falcon** [comment]
In case anyone runs into this here first :)

workaround: https://diceydungeons.com/switchanimationspeedworkaround.html

**Comment by TerryCavanagh** [comment]
Big yikes on this one :(

Thanks for the write up, @YinYin-Falcon! We'll get this fixed asap!

**Comment by TerryCavanagh** [comment]
This is fixed in the latest live switch version!
