### ISSUE TITLE
Reversal should ignore cannotsteal; it's very strange for a gadget to say it gives you all the enemy's equipment and then... not

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2259]
If #2260 is resolved, this could potentially cause a situation where player goes up to Crystalina or Keymaster, thinking they're about to loot a bunch of great equipment, then clicking Reversal and getting nothing. Also, currently unstolen equipment is destroyed anyway (e.g. using Reversal on Kraken, who has Camoflague, results in you not getting Camoflague but Kraken not having it either), but if this gets fixed, then an unfair situation could result where Reversal fails for seemingly no reason and the player has to hope the enemy won't do too much damage to them when they flee.

(Also, blinding the enemy doesn't matter when they can't use their dice on anything.)

**Comment by TerryCavanagh** [comment]
Yep, good call - changed!
