### ISSUE TITLE
Inventor can keep stolen items

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#226]
you can make items stolen by steal gadget into gadgets with inventor even though you don't get to keep them as is after the battle

(probably related to yoink bug)

**Comment by joshtriplett** [comment]
You *can* keep them after the battle if you have inventory space.

**Comment by onetruepurple** [comment]
Duplicate of #134

**Comment by TerryCavanagh** [comment]
Yep! Closing this one.
