### ISSUE TITLE
Confusing icon

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#227]
![unknown](https://user-images.githubusercontent.com/2874150/40687033-3dc3f8c2-6391-11e8-90c8-1ee0461503e7.png)

suggestion: change this icon

to an animated that shows all the faces
instead of 3
because i feel like that might confuse someone at first

"three [3] sixes" confused me too at first

yeah, at first i thought the bosses gained one 3 die every round

**Comment by camtauxe** [comment]
An animated icon might be too distracting as most other UI elements don't move. Perhaps the icon could just show the die at an angle so it's not obviously displaying any one side.

**Comment by TerryCavanagh** [comment]
Fixed!
