### ISSUE TITLE
Thief BR's itempool has "Underadedice" instead of "Ungeradedice"

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2271]
![image](https://user-images.githubusercontent.com/32357485/102933038-5ca60000-4499-11eb-9b2f-8c79b92a12fb.png)

`scripts/diceydungeons/itempools/thief_remixgenerator/vanilla.hx`. This only appears as a very rare trade (about 8.1% chance), but this presumably crashes the game!

**Comment by TerryCavanagh** [comment]
Whoop, yes it would! Fixed!
