### ISSUE TITLE
Rotten Egg + Curse = Game Crash In Parallel Universe Switch Version

### ISSUE THREAD

**Issue by XenoSpider101** [TerryCavanagh/diceydungeons.com#2275]
Was playing as the Inventor on Episode 5: Parallel Universe. Was fighting the Banshee enemy on floor five. I was inflicted with curse by the Banshee during the fight, and I used a dice on the Rotten Egg Equipment. The Curse status activated and the game then crashed. Reloaded the game and fought the Banshee again. Did the same sequence of events to see if it was consistent and it was.

**Comment by TerryCavanagh** [comment]
Thank you! This is a useful report!

**Comment by TerryCavanagh** [comment]
Fixed, thank you!
