### ISSUE TITLE
Reduce by? mentions a status's *internal* name when it blocks that status, instead of its display name

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2280]
I usually internally prefix my statuses with ncr_ to avoid potential naming conflict; e.g. ncr_error, ncr_vanish, ncr_silence. The statuses themselves are supposed to display without the ncr_ part, but when you block one of them with Reduce by?, the text particle that pops up shows e.g. "Blocked ncr_error!"

**Comment by TerryCavanagh** [comment]
Fixed!
