### ISSUE TITLE
Consider making Blight/Detonator rarer for Warrior's earlier episodes, since he only has 2 weapons that synergise with them

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2282]
For Warrior, Blight appears in the `warriorshops` `floor3item` and `floor5item` lists, and Detonator also appears in the last two. However, the only weapons that synergize with them are Claw and Toxic Ooze. While you definitely *can* get a poison build going, Blight and Detonator show up far too often when all you've gotten is a Claw from a shop. Consider curtailing how often those two can show up, since they're a dead drop most of the time.

**Comment by TerryCavanagh** [comment]
Yeah, agreed - I think I'm actually just going to remove both items from the episode!
