### ISSUE TITLE
"Reverse Next Target" status effect should not trigger on equipment tagged "curseavoid"

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#2283]

**Comment by TerryCavanagh** [comment]
Uff, fixed. Not 100% sure if this is the right call, though! But I guess if somebody's marked a card as curseavoid, there are good reasons for not having it's target reversed, even if it does lead to the trade off unexpected behaviour of simply not triggering the status effect...

**Comment by XenonZed** [comment]
An alternative might be to have another tag specifically for preventing this status from triggering.
