### ISSUE TITLE
Switch crash on defeating Lady Luck

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#2284]
Might be the same as #2279 - but it happened after a different dialogue:
`The software was closed because an error occurred.`
Right upon pressing A on the "...and AMAZING." dialogue.

I had the Robot and Singer left and defeated her with a high note > sad verse combo.
(I think after losing a fighter the previous round / not switching fighters that round)
And this was the very first backstage run.

**Comment by TerryCavanagh** [comment]
This one was fixed!
