### ISSUE TITLE
Feedback on the Arabic translation

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2285]
A public issue to collect feedback on the Arabic translation of Dicey Dungeons, starting with one issue I spotted myself in testing: During the tutorial, the Hothead fight is missing text wrapping in when it introduces the Fire status.

**Comment by saljam** [comment]
This is great! I'm loving the translation!

Here's what I spotted:

1. "Shaders" in the option menu is a little too enthusiastically right-to-left:
![Screenshot 2021-01-12 at 14 46 36(1)](https://user-images.githubusercontent.com/751023/104355815-1de8f000-5503-11eb-8d72-42eb8bebfba6.png)


2. Should these side-by-side messages be on top of each other? (is this tutorial issue you already mentioned?)
![Screenshot 2021-01-12 at 14 36 34(1)](https://user-images.githubusercontent.com/751023/104356020-5b4d7d80-5503-11eb-84f4-2a5fb57b5e93.png)


3. Looks like two synonyms for "level" is used (مستوى/مرحلة) in the map view. one for enemies and one for your level.
![Screenshot 2021-01-12 at 16 06 13(1)](https://user-images.githubusercontent.com/751023/104355250-4e7c5a00-5502-11eb-81a4-77f0deb00471.png)

4. Tiny nit: the text touches the bottom of the border in this box. This one is with the first boss fight, there may be others.
![Screenshot 2021-01-12 at 14 39 22(1)](https://user-images.githubusercontent.com/751023/104355574-cba7cf00-5502-11eb-9e31-813a737894d5.png)

**Comment by TerryCavanagh** [comment]
Thank you! This is really helpful! 2 and 4 I can fix myself, I'll pass 1 and 3 on to my editor!

**Comment by saljam** [comment]
no worries! a couple more:

1. the question mark is on the wrong side of the numbers in the message from radio head (looks like another bidi bug. bidi is hard!)
![bidi](https://user-images.githubusercontent.com/751023/104816679-a2de4d00-5814-11eb-831d-f1f9e8deb4e4.png)

2. end turn button translated as اِنْهَ الدور could that be a typo? maybe for something like أنهي الدور?
![turn](https://user-images.githubusercontent.com/751023/104816785-20a25880-5815-11eb-9ad1-c9d5b921a17c.png)

**Comment by TerryCavanagh** [comment]
Some more feedback from other places!

Somebody on twitter said that the translation is "rough" on this screen, but didn't say exactly where:
![image](https://user-images.githubusercontent.com/2874150/105115073-17b4ce00-5b18-11eb-888f-c44e759d51a0.png)

**Comment by TerryCavanagh** [comment]
On discord, one player offered the following feedback:

```
Game:
    Enemies could perhaps gain Al- prefix for their titles when they are single adjectives to compensate for the title case.
    Episode 2:
    Hey lady luck, I'm doing great aren't I?: إنني أؤدي ببراعة، أليس كذلك؟
    Status: Curse: Shouldn't it be لعنة to match the other instances? like in Curse of Greed and Worse than a Curse. نحس would be Misfortune.
    Classes:
        Locked: مقفل
            with this contestant = بهذا المتسابق (with: to use, not to accompany)
        Thief:    Title: I think the word لص is more appropriate than سارق, like thief in the night (1 Thess 5:2) كَلِصٍّ فِي اللَّيْلِ
            Hamza in لأفوز
        Inventor: comma seperated from فزت 
Settings:
    Display:
        Disable shaders: Not translated nor transliterated.

    Languages (as well as in Credits):
        Welsh = الويلزية
        Proper Hamza in English, Irish, Spanish and Italian.
```

**Comment by TerryCavanagh** [comment]
Thanks for the feedback! We've just updated the steam build with changes based on this thread, so are now closing it. Please keep it coming! For further feedback on the latest version, please see the new thread here! https://github.com/TerryCavanagh/diceydungeons.com/issues/2299
