### ISSUE TITLE
Graphical glitches in the final episode (Switch)

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2286]
![image](https://user-images.githubusercontent.com/32357485/104324279-24fe0700-54df-11eb-979e-503b5da3de96.png)
![image](https://user-images.githubusercontent.com/32357485/104324308-2cbdab80-54df-11eb-9c31-b7bda2744a12.png)
![image](https://user-images.githubusercontent.com/32357485/104324313-2deed880-54df-11eb-8e72-cebc00451148.png)

https://discord.com/channels/423894813646127114/617437262908489748/798552304508862465

Apparently it fixed itself upon reloading, though. Maybe related to #2284 ?

**Comment by TerryCavanagh** [comment]
Yikes

https://twitter.com/just_Yakob/status/1363331016081903616

**Comment by TerryCavanagh** [comment]
We fixed this!
