### ISSUE TITLE
Re-Equip Next? is used up when removing a dice from a Spare card, but nothing happens

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2288]

**Comment by ncrecc** [comment]
"Spare" meaning one of the spare dice cards, e.g. Spare 1, Spare 2, Spare 3, etc.

**Comment by TerryCavanagh** [comment]
Fixed!

I considered do the fun thing here of properly implementing the status effect for these cards - i.e.  taking two dice instead of one - but this is such an niche thing, and there are so many edge cases like gamepad controls, upgraded versions etc that it didn't seem worth the trouble. 😐
