### ISSUE TITLE
Suggestion to add a clash to Kraken and Cactus rules

### ISSUE THREAD

**Issue by NeypahTit** [TerryCavanagh/diceydungeons.com#2289]
I don't think its fair to just give extra ton of unnecessary brain work just so you don't randomly die from Cactus rule.

**Comment by Matz-42** [comment]
I'm personally more for keeping it in.
It's an interesting combination, that makes Kraken rule more interesting than it is normally.

I'm not a fan of the "Adding clashes for rules combo that may be a bit harder together" design.

**Comment by TerryCavanagh** [comment]
Yeah, I've got no plans to change this - this exact clash is something I want to happen, very occasionally, to very, very lucky players!
