### ISSUE TITLE
Bounty Hunter rule does nothing when YCYL is active (The Robot rule)

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2291]
"You will never roll a 6", but the 6 on your dice panel is still available.

**Comment by TerryCavanagh** [comment]
Aha!

Of course, the obvious fix for this is to just prevent another rule clash. The less obvious fix is more fun. Therefore:

![robot+bountyhunter](https://user-images.githubusercontent.com/2874150/105147370-05a35180-5b51-11eb-92b7-f6a625af09ec.png)

Ok, that was a fun little diversion. Fixed! 🎉
