### ISSUE TITLE
Health/level UI moving/shaking outside of battle

### ISSUE THREAD

**Issue by kortemaki** [TerryCavanagh/diceydungeons.com#2292]
I defeated the Paper Knight using a Boomerang+ with Fury, though the enemy was defeated after the first strike of the boomerang.  I believe my Warrior took both hits of the backswings, but then after the battle the Warrior Level 4/Health bar section of the UI was violently jittering/vibrating in place.  I was low health at the time, but this persisted even after eating an apple which should have brought me above the low health threshold.  I can't recall having seen anything like this before, and it made it difficult to read that part of the UI.

Reported in 1.10

**Comment by TerryCavanagh** [comment]
Got it! Fixed, thanks for the bug report!
