### ISSUE TITLE
Four Leaf Clover item doesn't ignore fury

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2293]
Four Leaf Clover can be furied even though Luck doesn't stack. This could lead to disappointment if a player gets Fury Spell from Precious Egg (or get lucky with Premium Heart) and expects furying Four Leaf Clover to make luck increase twice... then sees their fury wasted with nothing more happening than if they used Four Leaf Clover once

**Comment by TerryCavanagh** [comment]
Good call, fixed!

**Comment by JuniorUdale** [comment]
Also re-equip next - it could probably do with the `cannotreuse` tag too

**Comment by TerryCavanagh** [comment]
Uff, actually...

**Comment by XenonZed** [comment]
Maybe also consider changing the Four Leaf Clover upgrade to be multiple uses instead; I think it would be more interesting and less overpowered.

**Comment by ncrecc** [comment]
> Maybe also consider changing the Four Leaf Clover upgrade to be multiple uses instead; I think it would be more interesting and less overpowered.

I second this. Four Leaf Clover+ kind of destroys balance outside of its native habitat.

**Comment by TerryCavanagh** [comment]
Nah, I like Luck+ being a 100% sure thing, sorry.

**Comment by TerryCavanagh** [comment]
Ok! Change made: Luck now stacks!
