### ISSUE TITLE
Freeze? for Robot is not consistent with Freeze? for other characters

### ISSUE THREAD

**Issue by METHODIUS-OSANNE-ALEFELPEPARIA** [TerryCavanagh/diceydungeons.com#2295]
Freeze? decrements all dice by 1. From this statement, it would easily be inferred that Freeze? affects all dice equally. For the Robot, which rolls dice one-by-one, Freeze? should decrement each dice rolled by the number of stacks of Freeze? applied, without ever changing the number of stacks of Freeze.

However, for the Robot, Freeze? is handled the same way as regular Freeze: it is applied to all dice, then decremented by 1, every time a calculation is carried out. This makes Freeze? fail to affect all dice equally, as shown in the following clip:

https://user-images.githubusercontent.com/73432011/105440640-e0722880-5ca1-11eb-9683-2d2b257dada2.mp4

Freeze all? is handled the same way as infinite stacks of freeze, creating an even more absurd scenario, as shown in the following clip:

https://user-images.githubusercontent.com/73432011/105440971-89208800-5ca2-11eb-982f-833ef81965c5.mp4

A proper fix would be to:

- Make Freeze? for Robot apply to the dice produced by the calculation only (instead of to all dice) and never decrement.
- Make inflict(ICE[;]ALL) inflict 5 layers of Freeze? if the Freeze status is alternate. This makes it a bit more consistent with regular Freeze all.

**Comment by TerryCavanagh** [comment]
Hmm, yep, this makes sense! I'll make the change.

**Comment by TerryCavanagh** [comment]
Done! This will be up for testing in v1.11 soon!
