### ISSUE TITLE
Backstage: Monstercards are not immune to curse

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2296]
![image](https://user-images.githubusercontent.com/11216597/105620015-4b1c8480-5dc6-11eb-96dd-e0b0f286f896.png)

**Comment by TerryCavanagh** [comment]
Thanks for creating this issue! Really important one that I thought had been fixed already, uff.

**Comment by TerryCavanagh** [comment]
Ok, figured it out! Fixed 🎉
