### ISSUE TITLE
In Parallel Universe, Sonic Wave? upgrades to Sonic Wave+ (not the alt version)

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2298]
![image](https://user-images.githubusercontent.com/11216597/105621219-43afa800-5dd3-11eb-987c-fbc6beaebfe9.png)
Sonic Wave can be gotten by stealing from Stereohead with the Reversal gadget

**Comment by TerryCavanagh** [comment]
Fixed! Looks like it was maybe due to using `change_requirements` as the upgrade type instead of `change_power`? I'm not sure. Anyway, seems to be working now:

![image](https://user-images.githubusercontent.com/2874150/106096394-60f2c680-6185-11eb-95b7-0768abe2ab2c.png)
