### ISSUE TITLE
Consider adding the capability to set an enemy as the boss of the dungeon with Frog rule modifiers via the console

### ISSUE THREAD

**Issue by METHODIUS-OSANNE-ALEFELPEPARIA** [TerryCavanagh/diceydungeons.com#2301]
The current -boss="X" command sets an enemy to be the boss of the dungeon, but doesn't change its health or level (important for some modded items). 

In addition, if we set a super enemy to be the boss of the dungeon, the preview screen ([Player name] vs. [Boss image + Boss  name]) does not show that the enemy is a super enemy. The name is identical to that of the regular enemy, and the image doesn't have the white backdrop.

Suggestions:
- Add a functionality to the -boss command such that we can set an enemy as the boss with Frog rule modifiers. If the enemy has no Frog rule modifier, throw an error message.
- If a super enemy is set as the boss, use identical health modifiers as the equivalent regular enemy, and indicate that the enemy is a super enemy on the preview screen.

**Comment by TerryCavanagh** [comment]
Fixed!

 - The Dramatic Boss Intro screen now shows if your boss is a Super enemy.
 - If you're using the Frog remix rule (which you can force with the `-remix=` parameter), the boss will use the Frog rule stats instead.
 - Testing this out for v1.11, not 100% sure about it yet: The Frog rule now selects super versions of enemies if they're available.
