### ISSUE TITLE
If a temporary item (e.g. given by giveequipment() where maketemp is false) is weakened mid-turn, it will no longer be temporary

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2303]
Can probably be solved by just copying over more properties from the base equipment to the new equipment in the downgrade() function (e.g. temporary_thisturnonly, what the source equipment was if that's a variable)

**Comment by TerryCavanagh** [comment]
Fixed! (uh, I think.)
