### ISSUE TITLE
Magic Key becomes unrestricted when downgraded

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2312]
![image](https://user-images.githubusercontent.com/32357485/107779109-d2fa0c80-6d3c-11eb-8c94-f17e29692139.png)

Should probably keep being even

**Comment by onetruepurple** [comment]
It won't split a 1 into two 1's, so it's not strictly a bug.

**Comment by TerryCavanagh** [comment]
Fixed!
