### ISSUE TITLE
Consider changes to how "on damage inflicted" works

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2313]
A thing a lot of modders want to do with this hook is modify the damage that was just dealt, which doesn't work right now:

![image](https://user-images.githubusercontent.com/2874150/107833815-59b5f480-6de4-11eb-9ef2-df1747d11f4b.png)
![image](https://user-images.githubusercontent.com/2874150/107833826-60dd0280-6de4-11eb-98fc-0b670ab04cb6.png)

**Comment by METHODIUS-OSANNE-ALEFELPEPARIA** [comment]
Consider this: elemental weaknesses account for shield (e.g. if Aoife is weak to ice, and has 6 shield, using Absolute Zero nullifies her shield and does 44 damage).

I really think that the `on damage inflicted` hook should account for shield in the same way as well.

**Comment by JuniorUdale** [comment]
A few more things to note (from fiddling around with this hook today):

- This hook runs when the enemy takes poison damage (if the status effect is still active on your turn), which generally isn't something that the player wants. Maybe also give the player access to the damage *type* that was inflicted (so e.g. Staff would be fire), to give them better control over things like this?
- This hook doesn't run when the enemy takes 0 damage due to things like shield or reduce (or an attack just naturally dealing zero damage). I don't see any reason why it shouldn't - things like thorns activate on 0-damage attacks, and if a modder only wants to consider positive attacks, a check for `if(dmg > 0)` does the job.

**Comment by TerryCavanagh** [comment]
Some very good suggestions here, thank you!

>     * This hook doesn't run when the enemy takes 0 damage due to things like shield or reduce (or an attack just naturally dealing zero damage). I don't see any reason why it shouldn't - things like thorns activate on 0-damage attacks, and if a modder only wants to consider positive attacks, a check for `if(dmg > 0)` does the job.

I absolutely see what you would want this, but having dug into this a little bit, it's too delicate to mess with. The `attack()` script function calls another internal function to check for things like shield and thorns, and if that adjusts the damage to 0, it doesn't call the usual `fighter.reducehp()` function, which is what ultimately calls the status scripts. It's pretty dangerous at this point to rewrite any of that, because it might break all sorts of things in people's mods, or even in the base game.

(the rest of this I'm working on though, almost done)

**Comment by TerryCavanagh** [comment]
...uff, actually, so much for this, sorry. Same problem with trying to add a return value to the status scripts - it soon becomes a mess that's dangerous to try to untangle, considering what it might potentially break.

It also seems like it is possible to adjust damage dealt directly with the current hooks, it's just a bit of a nightmare. Roughly:

You start by just directly adjusting `f.hp`, ensuring that it doesn't exceed `f.maxhp` or you run into problems.

You can fix the limit values yourself like this:

```
if (f.limitbreak != null){
  f.limitvalue += amount;
  if (f.limitvalue > f.limitmax){
    f.limitvalue = f.limitmax;
  }
}
```

Dealing with shield/reduce etc is a little trickier, but you could basically reproduce the game's internal logic, which is:

```
public static function applyphysicalblock(actor:Fighter, target:Fighter, amount:Int):Int{
		//Actor is the one attacking, target is the one taking damage
		//If actor is null, damage is self inflicted
		if (target != null){
			if (target.hasstatus("blockall")){
				return 0;
			}
		}
		
		if (actor != null){
			if (actor.hasstatus(Status.PIERCE)){
				//Ignore blocking if you have piece status!
				return amount;
			}
		}
		if (Rules.bonusdamage != 0){
			amount += Rules.bonusdamage;
		}
		if (target.hasstatus(Status.ALTERNATE_WEAKEN)){
			var increasestat:StatusEffect = target.getstatus(Status.ALTERNATE_WEAKEN);
			amount += increasestat.value;
		}
		if (target.hasstatus(Status.REDUCE)){
			var reducestat:StatusEffect = target.getstatus(Status.REDUCE);
			amount -= reducestat.value;
			if (amount <= 0){
				amount = 0;
				return 0;
			}
		}
		if (target.hasstatus(Status.SHIELD)){
			var stat:StatusEffect = target.getstatus(Status.SHIELD);
			if (stat.value > amount){
				//Completely blocked
				stat.value -= amount;
				stat.displayvalue = stat.value;
				return 0;
			}else{
				//Partially blocked
				amount -= stat.value;
				target.removestatus(Status.SHIELD);
				return amount;
			}
		}
		
		return amount;
	}
```

On the plus side, I made the following change for v1.11:

In status "On damage inflicted" and "On damage taken" scripts, "dmgtype" now contains the type of damage inflicted. Default is "none", which just means non-elemental. e.g. "shock", "poison", "none".
