### ISSUE TITLE
Unable to break Silence on Switch

### ISSUE THREAD

**Issue by mjsztainbok** [TerryCavanagh/diceydungeons.com#2319]
I'm fighting the Loud Bird as the Inventor and it Silenced me. I have 2 dice available but when I select the Silenced operation it doesn't allow me to select dice to unbreak the silence
![16140644847574730533724777856625](https://user-images.githubusercontent.com/67809434/108812338-cad37580-7563-11eb-978b-f15e9d9b580c.jpg)

**Comment by TerryCavanagh** [comment]
Thanks for the bug report! This was a tough one to track down, but fixed! Turns out it *only* happens in this particular episode (inventor 2)
