### ISSUE TITLE
[1.11 testing] Robot's CPU counter is incorrect if you error under the effects of Freeze?

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#2327]
To replicate: load into a fight in episode 5 with a freezing enemy. Here I spawned in Yeti and got frozen? twice:
![image](https://user-images.githubusercontent.com/66463691/110693613-def2b600-81a4-11eb-9f08-135e459d322a.png)
The counter is correct before you error. Seems to be using the unfrozen values of the dice.

**Comment by TerryCavanagh** [comment]
Fixed!
