### ISSUE TITLE
UI error when a Super Wizard gains an additionnal dice

### ISSUE THREAD

**Issue by fusiondax** [TerryCavanagh/diceydungeons.com#2328]
I noticed that when a Super Wizard uses Hall of Mirrors, its name and his dice count above his health bar overlap. This sounds like a simple oversight (it is a quite specific case). Its has next to no impact, but a fix should be easily made.

![UI display bug](https://user-images.githubusercontent.com/10747739/110987527-33c93480-833d-11eb-943c-069b79b18016.png)

**Comment by TerryCavanagh** [comment]
Ah yep, this one is fixed already in the v1.11 update in the testing branch! Thanks!

https://github.com/TerryCavanagh/diceydungeons.com/issues/2311
