### ISSUE TITLE
[1.11 testing] Dragging to scroll on Jester's delete/upgrade UI no longer snaps to individual cards

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#2329]
Found this while messing around with the Jester. This can lead to situations like this, if you move in between two cards:
![image](https://user-images.githubusercontent.com/66463691/111056740-b84fac00-843e-11eb-8a5b-777dd3c28c44.png)
![image](https://user-images.githubusercontent.com/66463691/111056743-bbe33300-843e-11eb-960a-8c84a8890124.png)
Sour Candy appears to be the highlighted card, but pressing "destroy" removes Ruff Ruff Ruff.

**Comment by XenonZed** [comment]
Prior to this update, the button would disappear while you were scrolling, and the view would snap to the nearest card once you stopped.

**Comment by TerryCavanagh** [comment]
Thanks for this! Fixed for today's update!
