### ISSUE TITLE
discourage "I'll do what I want and hope I don't run into anything that counters it" playstyle

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#233]
Okay, I've been playing enough Dream Quest for the past few days that I have some thoughts to share.

## Top 3 criticisms of Dream Quest for Dicey Dungeons to avoid (or embrace)

The only three criticisms I've read of Dream Quest are:
1. bad art
2. unfair enemies, e.g. hag, lich
3. too grindy

As for 1, you're on it.

As for 2, people complaining about frustrating enemies, you're listening and taking their feedback into consideration. For example, you're rethinking immunity after hearing a lot of player's frustration at having total immunity render their whole build ineffective. And you've also got a different perspective on this, because unbalanced enemies are one of the things you love about Dream Quest. I agree with you, but with one caveat that I'll get to eventually.

As for 3, the way I see it there are three types of unlocks in Dream Quest:
a) do this well in the game (e.g. reach the third floor, beat this specific boss)
b) do this challenging wacky thing in the game (e.g. get rid of all your cards, have 10 cards in play at once)
c) play the game a lot
 
It's only Type C that I take issue with. I think A and B achievements/unlocks are fun. Type-A achievements reward me for doing well, and that feels great. Type-B achievements reward me for playing the game differently than I would usually play it, and I enjoy the variety. These are the types of achievements I suggested in my previous post.

But Type C achievements are just grindy and dull, and if you need them to progress (e.g. unlock a new class or key card) then I'm not a fan of that design choice.

### Backstory
My first win was on my 11th run, my first run as the Monk. I used the Action strategy: get lots of Action cards that let me draw more cards and get more Action Points so I can get through my whole deck every turn. (Happened to crush Lich first try, btw.) Then I did the exact same thing with the Thief. It was pretty straightforward once I learned the Action trick and unlocked a few useful things.

Next I tried to win with Warrior and had a rough time of it. Each time I lost, I asked myself, "Why did I lose?" and the obvious answer was "I ran out of HP" but why did I run out of HP? Did I not kill the enemy fast enough? Did I not have enough defense? Did I not have enough healing? Without the Action trick to allow me to play lots of cards, I just wasn't able to do as much, and Warrior doesn't get enough Action drops to make the Action strategy work. My first Warrior win was when I focused entirely on defense. My theory was that Warrior is going to do enough damage, so don't worry about damage, just worry about staying alive. It was way tougher than the Action strat but I did it!

I tried Monk again later, and realized that I had gotten lucky on my first Monk run because Action cards don't always drop enough to make the Action strat work. I did have one great Action Monk run, where I was pwning everything until the final floor, on which there were two hags and a sphinx. The sphinx would have forbidden Action cards, so that's a non-starter, and hag, well, hag. So I just skipped them and fought the boss at lvl9, but it was Kraken, and Ink Spray completely wrecks the Action strat. It was wonderful.

### Takeaway
I love how every strategy has a counter. But I don't love how RNG-dependent it is. I'm not forced to add a non-physical damage card to my deck; I can just avoid Wisp or hope it doesn't appear. I'm not forced to balance my card types; I can just avoid Sphinx or hope she doesn't appear. After my loss against Kraken, my takeaway wasn't, "Aha, I need to tweak my Action strat so it won't die to Kraken", my takeaway was, "Let me try the exact same strategy and hope Kraken doesn't come up".

If, in Dicey Dungeons, I go for a poison build and I encounter an immune enemy, or I go for a control build and I encounter an enemy with gobs of equipment and gobs of dice, I'm not completely fucked like I would be in Dream Quest. I just swap out my poison/control equipment for my second-string equipment and do my best.

That's AWESOME. This is one area in which I think Dicey Dungeons is better than Dream Quest - it encourages backup strats.

However, I wonder if there's opportunity for Dicey Dungeons to do even better. Back to DQ for a sec, imagine that the exact same Kraken fight had happened to me, except with Thief instead of Monk, because Thief's default strat is Action strat. I'm disappointed that the easiest answer is "Just try again and hope I don't get the Kraken". How could the game instead encourage me to play Thief and come up with a strat that can beat the Kraken? Perhaps some special achievement/unlock "Beat Kraken with Thief"? That would be cool - but I'd want to be able to choose a Kraken run instead of rely on RNG that I won't know until the final floor.

In Dicey Dungeons, you see most enemies on most runs, except the boss. I love that! It means that you've got to expect Knight and plan your build around Knight, because you're probably going to have to fight Knight. This is the only downside I see to being able to skip enemies. It encourages more of the Dream-Quest-esque "I'll do what I want and hope I don't run into anything that counters it" playstyle, which I find repetitive, boring, and disengaging.

## Filler Enemies

After playing 40 runs of DQ so far, I'm noticing that about 2/3 of the enemies feel like filler enemies. There's nothing special about them. They're not weak to anything, they're not strong against anything, they don't have any particularly interesting cards... you just Play All, repeat, and move on.

This is another way in which I prefer Dicey Dungeons to Dream Quest. Every encounter (well, like 80-90% of encounters) in Dicey Dungeons feels interesting and fun!

I think part of the reason for this is that the unlocks in DQ increase the character's power but don't increase the dungeon's power. If, for example, after 10 unlocks, all goblins got replaced with something new, different, a little bit harder but a lot more interesting - I would love something like that.

Dicey Dungeons feels tighter than Dream Quest. Fewer enemies but more interesting enemies with less filler. I love it.

## My favorite things about Dream Quest (so far)

I think you've captured one of my favorite things about Dream Quest: the imbalance and/or synergy of different card types. You can either go for a very imbalanced strategy (almost all cards of one type in DQ, Shield Bash or Crowbar or Poison in DD) or you can go for a synergistic strategy, where you have some of each card type that support each other. For example, if I'm playing Action strat, I want Haste (a spell card) and Wisdom (a mana card) despite the fact that neither of them is an Action card. Wisdom gets me (almost enough) mana to play Haste, and both of them keep the cards flowing. In Dicey Dungeons it's similar: Inventor might want to pick up that Target Shield, Thief might want to pick up that weapon.

I love how the different classes in Dicey Dungeons all feel radically different. Some of the classes in Dream Quest aren't nearly as interesting. So that's 3 ways in which I think DD is better than DQ (:

I am enjoying the crap out of Dream Quest's progression system. The only 4 (well, 4*4) achievements I don't like are the "die N times", "take N steps" etc. ones - the Type C achievements I've already bitched about at the very beginning. But every single other achievement is fun to get and gives an interesting reward! The achievements+unlocks are what's got me hooked on Dream Quest - it feels great to have a sense of progress and continual discovery. But I've already written a whole other long thing about progression (#135) so I'll stop there.

**Comment by pace212** [comment]
I finally completed a Dream Quest run with the Wizard. Several great mana cards and two copies of Storm meant I got to take 2-3 turns to the enemy's 1.

Dicey Dungeons's equivalent (although I guess it's more of a Professor equivalent, who I haven't unlocked yet) is getting Dire Wolf Howl or Divine Rod, and completely devastating the boss.

It's an amazing feeling, in both games. It feels kind of like you broke the game, like you outthought the developer! But in fact it's an intentional (and brilliant!) part of the design!

**Comment by TerryCavanagh** [comment]
Appreciate the write up, thank you! It's really interesting to see the thoughts of a new Dream Quest player from the perspective of a Dicey Dungeons player!

I do want to increase the amount of enemy and equipment variation in Dicey Dungeons, so it's likely things will get less predicable as time goes on. The thing about Dicey always showing you the same enemies is more accident than design, haha. 😅  Dicey's thing of settling on a board before combat means that you *have* to think about equipment loadout a lot more than you do in deckbuilders like Dream Quest, because your layout either works or doesn't. It's a constraint that I'm still trying to figure out and work with.

(Also, probably worth saying this out loud, for whatever it's worth: while Dream Quest is obviously a huge inspiration - it's not the *only* inspiration, and that I'm not aiming to do a one to one equivalence with it and Dicey Dungeons. My frequent name checking of it is more about paying respects to it as one of the overlooked giants of the genre, rather than a desire to directly compete! Dicey Dungeons is, I think, ultimately a very different game to Dream Quest, even though it's clearly in the same genre.)

**Comment by pace212** [comment]
Re enemy variation: LOL I guess that makes this issue a WONTFIX 😀 But yeah, if my preferred randomness sweet spot doesn’t line up with your vision, then c’est la vie - all I can do is tell you what I find fun and what I find frustrating, and let you sort it all out. To be precise, though, I’m all for enemy variation, the only thing I find frustrating is too much of the “let me try the exact same strategy again and hope I get better RNG” effect, which feels too grindy to me. This effect is sometimes - but not always! - a result of too much enemy variation in ways that can make or break a build.
