### ISSUE TITLE
Rusty Sword changes colour at the wrong time

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#2334]
The script for Rusty Sword checks that `self.hp / self.maxhp < 0.5` to determine whether to deal double damage.
Meanwhile the status effect scripts check that `self.hp / self.maxhp <= 0.5` to make the equipment change colour.

This means that at exactly half HP, Rusty Sword will change colour despite not dealing double damage.

**Comment by TerryCavanagh** [comment]
Thanks for this! Fixed for v1.12.
