### ISSUE TITLE
Jester can't do anything if you avoid bringing weapons

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#234]
If you know in advance what the Jester does, then you can use it as an opportunity to fully heal. Just unequip anything that can do damage, and bring a healing item (First Aid Kit, Healing Crystal, Bandage). The Jester will steal your items but not be able to do anything to hurt you with them. When you're done, either Flee, or use a damage-dealing gadget or ability (such as Backstab) to win.

**Comment by joshtriplett** [comment]
(This may or may not be a *bug*.)

**Comment by TerryCavanagh** [comment]
Fixed!
