### ISSUE TITLE
Mood Change should be marked "cannotsteal"

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#2342]
Aurora doesn't spawn for Inventor or Thief, but this should probably be done just in case.

**Comment by XenonZed** [comment]
Aurora should also probably be banned from Jester 1, 4 and 6, since Call for Backup Thief appears in those episodes.

**Comment by TerryCavanagh** [comment]
Yep, good call! Fixed for v1.12.
