### ISSUE TITLE
Dice appearing on the enemy's moves screen

### ISSUE THREAD

**Issue by cerovest** [TerryCavanagh/diceydungeons.com#2346]
During the warrior n°3 i used a reroll and went to see the enemy moves before the dice appeared on my screen and now it's blocked on the enemy screen.
![diceydungeons_1eQgbRCJhp](https://user-images.githubusercontent.com/52970171/112656864-196d7b80-8e52-11eb-8c00-6eb142dad8f8.png)
![diceydungeons_UwWtvsFTNo](https://user-images.githubusercontent.com/52970171/112656867-1a9ea880-8e52-11eb-9a27-7d2faafc4661.png)

**Comment by TerryCavanagh** [comment]
This one is fixed now!
