### ISSUE TITLE
Disregard, second round of combat resolved the issue

### ISSUE THREAD

**Issue by Cody-Hornberger** [TerryCavanagh/diceydungeons.com#2347]
If you kill an enemy while copying a damaging move of theirs as the thief, it seems the move you're copying is brought with you into the copycat fight if you have no equipment. This means the copycat enemy can't fight back in this circumstance.

**Comment by Cody-Hornberger** [comment]
Disregard, it seems that only holds for the first round of the fight, after that round you also have no equipment and it's just a stalemate.

**Comment by TerryCavanagh** [comment]
Yeah, it is possible to kludge fights with copycat as many classes, but at this point I'm comfortable with that. Thank you, though!
