### ISSUE TITLE
AI should not waste time doing things that don't change the outcome

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#235]
The AI often spends time using items that don't change the outcome. For instance, the Engineer will often use the Spanner to combine dice even if it already has a 6, even though it can just feed all its remaining dice into the Electromagnet. Especially noticeable in hard mode, since it can reuse the spanner.

The AI should always try to use the simplest set of actions that achieves the same result; if it can do the same amount of damage while using less items, it should do so, to avoid wasting time.

**Comment by TerryCavanagh** [comment]
In general this is fixed, but your particular example is still happening for another reason: https://github.com/TerryCavanagh/diceydungeons.com/issues/646

Closing this as it's now a more general duplicate. Thanks!
