### ISSUE TITLE
Gadget creation should let you look at your inventory and the map

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#237]
When creating a gadget, you should be able to look at the rest of your equipment and inventory (to know what else you have) and the map (to know the upcoming enemies).

**Comment by onetruepurple** [comment]
Coming in here a year late, but: I think implementing this would actually take away a lot of the Inventor's "having to plan ahead" aspect.

**Comment by joshtriplett** [comment]
On June 2, 2019 12:28:17 AM PDT, onetruepurple <notifications@github.com> wrote:
>Coming in here a year late, but: I think implementing this would
>actually take away a lot of the Inventor's "having to plan ahead"
>aspect.

I don't think this would remove the inventor's need to plan ahead; it would just remove the need to memorize information you *did* already have access to previously, so that you can do that planning.

**Comment by TerryCavanagh** [comment]
Basically agree that this is a good idea and seems like an important part of encouraging more strategic play for inventor. Adding this one to High Priority for launch.

**Comment by TerryCavanagh** [comment]
Hmm, looking back over issue now, this is a very good suggestion and I agree that would have been a nice thing - but this is a ton of work, and it's not so nice a feature so as to justify the work. No longer planning to do this at this point in development.
