### ISSUE TITLE
inflictself(~extradamage~); doesn't work if applied during turn?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2389]
Not sure why, but during testing I tried this and it doesn't seem to take effect. It's probably fine, but worth checking to see that you haven't broken anything.

**Comment by ncrecc** [comment]
In the public builds, extradamage the status doesn't do anything, it has to be paired with changing ``Rules.bonusdamage``

**Comment by TerryCavanagh** [comment]
Ahh, of course - forgot how hacky that implementation was.

Hmm, I guess at this stage I can't really change that, in case I end up breaking some modding stuff - but I might implement an alternative Extra Damage status that's a bit easier to work with.
