### ISSUE TITLE
[lessthan] symbol

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2392]
The less than symbol (<) cannot be used in descriptions, since it denotes the start of a preview (e.g. <d6>). The greater than symbol (>), however, only denotes the *end* of a preview, and is used in several base-game items to denote an item requiring mana higher than a certain amount for a special effect. Having a [lessthan] symbol akin to [;], for equipment with special effects requiring *less* than a certain amount of mana (without just writing it as > and then swapping the two numbers), would be useful.

**Comment by TerryCavanagh** [comment]
Fixed! In the next update, the `[lessthan]` symbol can be used to display the < character.

![image](https://user-images.githubusercontent.com/2874150/125230285-0f4b8c00-e320-11eb-9ad8-4325e56432eb.png)

As a workaround until then, you can actually just append `data/text/symbols.csv` to do this yourself:

![image](https://user-images.githubusercontent.com/2874150/125230367-2c805a80-e320-11eb-8fed-d2a06e9f767f.png)
