### ISSUE TITLE
Magician's rule occasionally tries to change REQUIRE1 into REQUIRE1, which doesn't change anything

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2394]
![image](https://user-images.githubusercontent.com/32357485/125482157-a3ef4f45-ad4c-45fd-8f9b-adc4cbb783ad.png)

This is at the end of the `substituteall` function, for changing the slots of an item with just 1 slot. The highlighted `'REQUIRE1'` should be a `'REQUIRE2'`. Currently this means that an item with just a REQUIRE1 slot can have its slot flash, the "slots changed!" thing pop above it, and for nothing to happen, which looks buggy.

**Comment by TerryCavanagh** [comment]
Ahah! Thank you for the report, very easily fixed - thanks!
