### ISSUE TITLE
All of the following status effect enemies should be excluded in Jester reunion: Thorns, Confuse, and Lock

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2408]
All three are kind of run enders

Where confuse comes up as a "random" status, it's probably ok, but random lock isn't. You could swap out enemy equipment that inflicts random statuses for versions that don't inflict lock in the Jester episode so as to reduce the number of excluded enemies (Which is unfortunately going to have to be fairly high)

(of course the lock list will change as soon as you introduce the Thief episode anyway)

**Comment by plokmijnuhby** [comment]
don't forget vanish

**Comment by TerryCavanagh** [comment]
Vanish is fine 😄

**Comment by Matz-42** [comment]
Could be interesting for some of them to go the same route as shock and switch them to their PU variant instead.

**Comment by TerryCavanagh** [comment]
Done!
