### ISSUE TITLE
Add an early card that makes mana more tempting

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2414]
Perhaps Zlonk could upgrade to have a mana spend to match Skipping Rope's mana gain? Or another card entirely, something like "Do x damage, cost x mana, do double" - the key is that the card is useful even if you don't have mana, but makes mana gain a real choice rather than a curiosity.

this should help with an issue that a number of players have identified, where you get access to mana before mana is useful, and end up having to "trust" that it'll eventually pay off as a choice, which feels bad

**Comment by onetruepurple** [comment]
![image](https://user-images.githubusercontent.com/2095534/127739477-58a43d7b-aca3-47f7-80e0-e663ca2832ed.png)
?

**Comment by TerryCavanagh** [comment]
Feeling pretty happy about this!

![image](https://user-images.githubusercontent.com/2874150/173635655-11b3186f-d406-46c3-9047-17f61d9a6f45.png)

The upgrade station on floor 1 "reveals" the mana component of the episode - one card that you start with upgrades to give you mana, one card that you start with upgrades to use mana.

(Cold Fission was a decent suggestion, thank you! Not for this purpose, though.)
