### ISSUE TITLE
Simplify how *Equipment is implemented

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2422]
yes yes the current implementation is very clever in it's own way, but it's a maintenance nightmare and it's unmoddable. It's also incompatible with multiple stacks of *equipment, which is something you should probably support.

The solution here is to improve status effect tooltip modifying. (this can probably wait until after alpha 2 though)

**Comment by onetruepurple** [comment]
This will probably need to be implemented for Inventor Credits as well.
