### ISSUE TITLE
You can buy both *equipment cards on floor 2?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2425]
This is supposed to be a choice, not sure how this player managed it. Must have made a mistake somewhere?

![image](https://user-images.githubusercontent.com/2874150/127599265-21e4c537-eb43-477c-adc5-46f6c0e2967e.png)

(this screenshot is from an unrelated bug report about https://github.com/TerryCavanagh/diceydungeons.com/issues/2410)

**Comment by plokmijnuhby** [comment]
The prices in that shop are set to 3 and 2, and you can kill six enemies on the first two floors. So you can completely afford both.

**Comment by TerryCavanagh** [comment]
I feel like I'm missing something dumb, but how do you kill six enemies on the first two floors? There should be 2 on Floor 1 and 3 on Floor 2 with the standard enemy generator?

**Comment by Matz-42** [comment]
Yeah you only encounter 5 enemies on the first 2 floors. You can however get 6 coins total with the help of Sticky Hands and a good shop position.

**Comment by TerryCavanagh** [comment]
Fixed.
