### ISSUE TITLE
Dice highlight (when clicking a die) is barely noticeable

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#243]
When you click a die, before clicking on a piece of equipment to put it in, the die becomes very slightly brighter; however, the effect is so subtle that it's almost unnoticeable. The highlighted die should be much, much more obvious.

**Comment by TerryCavanagh** [comment]
Dice highlight has been removed completely since Marlowe's graphics got added! This still needs to be done, but closing since it's a duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/208.
