### ISSUE TITLE
Null Object Reference when you finish an episode

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2436]
That probably shouldn't happen

**Comment by TerryCavanagh** [comment]
Oh hey look I figured out why this is happening

![image](https://user-images.githubusercontent.com/2874150/128149424-e2f55076-c75a-4340-a7fe-a35eae3fa1eb.png)

**Comment by onetruepurple** [comment]
Valid in alpha 2
