### ISSUE TITLE
Gauntlets introduces a colourblind accessibility issue

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2437]
I like Gauntlets, but this is a real shame, since I've avoided accessibility issues in the game so far. Have a serious think about an implementation or design change here that might work. Could go as far as to graphically distinguish red cards with a pattern in the episode.

**Comment by TerryCavanagh** [comment]
Ok, well; I've tried applying a subtle notch to red cards so that colourblind players can tell that they're different:

![image](https://user-images.githubusercontent.com/2874150/127989837-ea9f7090-909b-45c4-b36f-951acf7bc200.png)

![image](https://user-images.githubusercontent.com/2874150/127989738-bdbff4c0-24f2-402a-a33c-01752de15ae4.png)

I could get Marlowe do draw something better of course, but my feeling right now from this test: I don't know if I like this solution. I'll leave it in alpha 2 for now and re-assess later.

**Comment by TerryCavanagh** [comment]
Made it a little bit less subtle:

![image](https://user-images.githubusercontent.com/2874150/127990725-e0a2b997-4a68-42ff-9093-fc433ccbb5c9.png)

![image](https://user-images.githubusercontent.com/2874150/127990763-adf38c8c-5536-42f0-a1d0-30f6a2a99d5c.png)

**Comment by ncrecc** [comment]
Is the notched red card thing just for when Gauntlets is in your inventory/deck, or always?

**Comment by TerryCavanagh** [comment]
Right now I'm just overriding the texture, so it'd be all red cards, across all episodes. (Yeah, still unsure about this)

**Comment by onetruepurple** [comment]
Unless you very specifically say "the red cards have a notch on them btw", this solves almost nothing.

**Comment by onetruepurple** [comment]
Would it make sense to re-use Warrior's left card title alignment here, and then use some kind of symbol in the right corner on the cards that can be affected by this?

**Comment by TerryCavanagh** [comment]
Been a while since I've thought about this issue, wow - can't believe the first public Reunion alpha was back last July!

Yeah, marking special eligible cards with a symbol is a good idea. Probably worth playing around with - this idea definitely needs some iteration.

(It doesn't look like I wrote it down here, but I was considering just having this card duplicate anything with the [sword] symbol. Though, that has some problems too!)

**Comment by TerryCavanagh** [comment]
Have got a new design for Gauntlets that should work better, so this is no longer an issue.
