### ISSUE TITLE
Items taken with the Steal gadget can be converted into gadgets or kept permanently at the end of a fight

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#244]
Is this a bug or a feature? Maybe inventor really does just force the enemy's equipment out of its hands, kill the enemy, then turn that equipment into a new gadget, but that seems pretty brutal.

**Comment by joshtriplett** [comment]
Honestly, this is hard to pull off and really satisfying when you can, so personally I'd love to see a form of it stick around.

**Comment by ncrecc** [comment]
Related: in 0.9, if Thief steals a mystery box (i.e. from Mimic), activates it, and then kills the enemy on the same turn, it gets to keep whatever equipment it got from the mystery box as long as it fits into the inventory.

**Comment by ncrecc** [comment]
...however, the Mystery Box bug is actually really cool and it would be neat if other classes could get non-standard items by defeating Mimic somehow.

**Comment by ncrecc** [comment]
I have a hunch this isn't quite considered a bug anymore.
