### ISSUE TITLE
Elaborate that *Equipment is once-per-battle

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2442]
I thought I'd be able to use Boots of Speed twice to get two Skipping Ropes per turn :(

**Comment by TerryCavanagh** [comment]
Oh, hmm, yeah that's a problem

These cards are already very crowded - I'm not sure how to indicate that without making them a lot messier. I'll have a think.

**Comment by TerryCavanagh** [comment]
Done!
