### ISSUE TITLE
"throwing axe can't be reused [on odd], even if you have re-equip"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2448]
not a bug per se but a bit of ugliness? make throwing axe's "miss" effect just deal no damage, like divine axe, instead of erroring before execute

**Comment by TerryCavanagh** [comment]
(throwing axe also fails on the Inventor episode, for the same reason)

**Comment by TerryCavanagh** [comment]
Kludged in a Reunion specific fix for this!
