### ISSUE TITLE
Give the Slime a snazzy beret

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#245]
When I was working on a mock enemy design on Discord, I accidentally gave the Slime a beret (actually the top of Cornelius' head).

![Image of Yaktocat](https://media.discordapp.net/attachments/423894814124146689/453238286664728596/unknown.png)

I think this is a massive improvement and the future art director should strongly consider this visual.

**Comment by TerryCavanagh** [comment]
Fixed!
