### ISSUE TITLE
Why is needs doubles equipment banned from Inventor Reunion?

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2457]
If needs doubles is banned, why wouldn't objectively more exclusive equipment like Divine Rod or Breadcrumbs be banned? Needs doubles isn't even that hard to use - especially having Combat Roll always available; that and Focus.

**Comment by TerryCavanagh** [comment]
Yeah, I think I agree! I'll allow doubles in the next iteration.

**Comment by TerryCavanagh** [comment]
Fixed!
