### ISSUE TITLE
"Prevent player from getting upgraded equipment that reduces size" check in Inventor Reunion fails somehow

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2458]
After using up Wicker Staff+, I got Gemstone Staff+, which was size 2 in-battle but reverted to size 1 when the battle ended.
Same thing happened to Jackeea with Battle Axe+:
![image](https://user-images.githubusercontent.com/11216597/128234627-4f1191dd-f97b-4d54-bf6b-91e7c1f1f968.png)

**Comment by ncrecc** [comment]
Also 
![image](https://user-images.githubusercontent.com/11216597/128234563-b7542502-afa4-4ab2-8c15-50ed7e74a068.png)

**Comment by TerryCavanagh** [comment]
Got it! This one was a bit subtle!
