### ISSUE TITLE
General sense that Inventor Reunion is too easy

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2464]
Not necessarily a big deal; easy but fun is a pretty good place to be. But worth thinking about how you could make the episode more challenging in an interesting way!

A couple of the already suggested solutions here:

 - Less dice: this one sort of works I think, but would mean unlucky arrangements could end up leaving you very, very stuck
 - More enemy health: probably works to some extent, might end up making things grindy, though.

**Comment by onetruepurple** [comment]
Could solve both this and #2463 if you were to not offer HP in shops.

**Comment by TerryCavanagh** [comment]
Couple of changes here that I think address the issue - the big one is that you get one less dice in the episode, which makes things a little harder by the end. There's also less HP going around!
