### ISSUE TITLE
Activating one of multiple mystery boxes opens the other one

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#247]
Exact steps to reproduce:

With a max-level witch, Mystery Box, and two upgraded spell slots, I put a Mystery Box in each of the two upgraded spell slots, then next turn I put doubles in the upper-right box. The upper-right box faded out as unusable, and the lower-left one popped open (revealing a Tremor).

**Comment by TerryCavanagh** [comment]
This technically would still happen if Mystery Box was still a witch spell, but it isn't, so, this is effectively fixed!
