### ISSUE TITLE
Life Steal steals more health than the target has

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2484]
Same as #440.

Fixed by the following script:
```
if (d > target.hp)
	drain(target.hp);
else drain(d);
```

**Comment by ncrecc** [comment]
Should be a direct change to ``drain()`` for futureproofing. Also note that alternate_weaken and damage modifiers have to be factored in.

**Comment by TerryCavanagh** [comment]
Fixed! I made the change to drain, so this is basically future-proof and takes the new damage modifying scripts into account too.
