### ISSUE TITLE
Keyblade does not return the dice when dodged

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2488]

**Comment by ncrecc** [comment]
It says right there in the "On Dodge" script, ``givedice(d);`` - what circumstances was this under? Did the enemy use it on you? Did you use it as a random item in Inventor Reunion and the enemy had dodge?

**Comment by TerryCavanagh** [comment]
Hmm, yeah, I need more information here - can't replicate this one on my side.

**Comment by onetruepurple** [comment]
Seems like I messed up, sorry.
