### ISSUE TITLE
Some Sorceress Guild random spells can't be used within 1 turn

### ISSUE THREAD

**Issue by PogoBeta** [TerryCavanagh/diceydungeons.com#249]
Rolled a Witch, joined Sorceress Guild. On one turn, my randomly-chosen spell was "Meteor" with a 60-pip countdown. I tried dumping a few dice into it just to see if "activating" it would lock it in place for the next turn, but it was replaced as expected. Later in the same fight, I received "Wooden Stake" with a 40-pip count.

While I understand the "win some, lose some" aspect of the Sorceress Guild, I think it would make sense to either allow countdown spells to remain until fully resolved or to remove from the random-spell-pool any countdown spell above a certain threshold (maybe scaling with level due to increased dice-per-turn). Hall of Mirrors and Broomstick make some of these spells more accessible, but 60 pips in a single turn seems like it would require some stars to align.

**Comment by TerryCavanagh** [comment]
This one still comes up as an issue in v0.17 (it's the "Expected the Unexpected" episode now). I think I'm pretty happy with the idea of "drawing a dud", which is what's intended here - it's part of what makes the challenge interesting, and I personally find it pretty funny to draw a Wooden Stake or Backfire or something else that I can't use. Thank you for creating the issue, but I'm going to leave this as is!
