### ISSUE TITLE
Kaleidoscope can take away all your dice

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2491]

**Comment by TerryCavanagh** [comment]
Eh, I think this is ok. The player needs to do it deliberately, after all, and in a way it'd be disappointing if it didn't do what you expected. Gonna keep this!

![image](https://user-images.githubusercontent.com/2874150/130232900-d308c200-039f-4e1f-8f77-28a0011b04e7.png)
