### ISSUE TITLE
Incorrect behaviour and damage display for Kapow+

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#2492]
After using one Kapow previously:
![image](https://user-images.githubusercontent.com/66463691/129423279-4c7d8e28-fc7c-4877-8e91-1d7d4b941e77.png)
The card says it will do 2 damage, since it's tracked using the same variable as normal Kapow. It does 4 damage when I use it. Based on the description however, it should be doing 3 damage in this scenario (1 base damage + 2 for one Kapow used).

**Comment by XenonZed** [comment]
The current script is:
`attack((self.getvar(~kapowcount~) + 1) * 2); self.setvar(~kapowcount~| self.getvar(~kapowcount~) + 1);`
It should be:
`attack((self.getvar(~kapowcount~) * 2) + 1); self.setvar(~kapowcount~| self.getvar(~kapowcount~) + 1);`

**Comment by TerryCavanagh** [comment]
Thanks! Fixed now :)
