### ISSUE TITLE
Prevent easter egg equipment from appearing in Inventor Reunion in the early game

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2498]
The easter eggs will be cool but maybe kind of baffling if you're just starting off and instantly see a modded equipment with a credit status effect - prevent them from appearing until floor 4, maybe?
Or maybe detect somehow if this is your first run and if so prevent them from appearing until floor 4, then for the rest of the runs allow them to appear whenever

**Comment by TerryCavanagh** [comment]
Yeah, that's probably a good call. (I've been thinking along these lines for the next iteration regarding what can show up and when for the episode as a whole)

**Comment by TerryCavanagh** [comment]
Done! Guest items are rate limited to every four items now, they won't show up more than 1 at a time, and you won't see them until you're level 2. This should make them feel like a cool welcome treat instead of a confusing or overwhelming thing.
