### ISSUE TITLE
At trading booth, equipment being taken is always shown at full durability

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2499]
![image](https://user-images.githubusercontent.com/11216597/130499631-9974f80b-01c9-4061-a233-0df79dd48759.png)

**Comment by TerryCavanagh** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/2874150/174085328-ccc56c8b-230b-495b-9ea3-56d069a0efd2.png)
