### ISSUE TITLE
Game crash when buying tremor as the witch

### ISSUE THREAD

**Issue by FelixNemis** [TerryCavanagh/diceydungeons.com#250]
here's the log output
![screenshot from 2018-06-08 22 08 33](https://user-images.githubusercontent.com/6477924/41187120-b1210c86-6b68-11e8-9d17-2422ea7c9b82.png)

**Comment by pace212** [comment]
Reproduced.

Starling.hx:648: [Starling] Context ready. Display Driver: OpenGL Vendor=WebKit Version=WebGL 2.0 (OpenGL ES 3.0 Chromium) Renderer=WebKit WebGL GLSL=WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
diceydungeons.js:91570 
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 91569
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 91402
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 91355
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 121182
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 90884
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 37155
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 649
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 121182
diceydungeons.js:91575 Uncaught Error: There's no spell template for "Tremor".

**Comment by TerryCavanagh** [comment]
Fixed! Thanks!
