### ISSUE TITLE
Inventor Reunion: If an equipment is dodged on its final use, nothing will replace it

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2502]
Final use of Short Sword was dodged:
![image](https://user-images.githubusercontent.com/11216597/130501919-07895bd3-5a6c-4eba-8e03-ed0ceee211bc.png)
![image](https://user-images.githubusercontent.com/11216597/130501942-f4cb6fa5-ebac-457a-a9f4-a8920dc6c842.png)

**Comment by TerryCavanagh** [comment]
Fixed!
