### ISSUE TITLE
spellbook preview

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#251]
It would be great to have that in a fight as well (overlay active spells with one you click/hover from the book). I tend to forget the specifics of newly learned things (like am I shocking or weakening with even/odd or vice versa?).

**Comment by TerryCavanagh** [comment]
I think a lot of people have gotten very used to this now, but I think it's very important for new players. Adding this one to High Priority for launch.

**Comment by TerryCavanagh** [comment]
Done in v1.9!
