### ISSUE TITLE
pre/rearrange spells?

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#252]
I feel like the spell book inventory should do a bit more than a preview.

One thing I immediately wanted to do was rearrange spells.
(like swap something significant onto 1 before fighting a curse)

Another was to set a few default ones to start a fight with.

Both could be limited and expanded via upgrades.

**Comment by BarbzYHOOL** [comment]
Yes, because as usual curse enemies are impossible to beat in hard mode (or almost impossible)

**Comment by TerryCavanagh** [comment]
Done!

(Still don't have a swap station, but there's a separate issue for that. You can prepare spells in v0.9, though!)
