### ISSUE TITLE
Combination equipment activates automatically the turn after it gets cursed

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#2529]
If a combination (e.g. triples) is filled and the equipment gets affected by a curse, the equipment will activate immediately at the start of the next turn. The slots do not get reset when the item gets cursed.

**Comment by TerryCavanagh** [comment]
This one doesn't seem to happen anymore - pretty sure I fixed it while fixing up some other unrelated combination bugs!

**Comment by Matz-42** [comment]
Can confirm this still happens in the reunion release.

**Comment by TerryCavanagh** [comment]
Fixed in v2.1, finally!
