### ISSUE TITLE
Stock Exchange should mention that the two coins you get aren't necessarily the same as the coin you put in

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2532]

**Comment by TerryCavanagh** [comment]
I think I'll just change it to work this way - thanks!

**Comment by Matz-42** [comment]
Wouldn't that make it a worse duplicate then? (which to be fair it kind of already is)

**Comment by TerryCavanagh** [comment]
(this item is actually removed completely now)
