### ISSUE TITLE
Bleeding ring + quicksilver belt VS thorn shield on Raged orc

### ISSUE THREAD

**Issue by Fxbouffant** [TerryCavanagh/diceydungeons.com#2535]
The game seems to hang / crash when playing with a bleeding ring: "When you take damage, restore +3 HP" and a Quicksilver Belt: "For each +1HP you restore in battle, deal 1 damage" versus a Raged Orc which has Thorn Shield: "Each time you take Damage in your own turn, opponent takes Damage equal to Damage"

**Comment by TerryCavanagh** [comment]
Uh - hmm.

Could you possibly provide a screenshot?

**Comment by NeypahTit** [comment]
I am so confused, a screenshot would really do wonders here

**Comment by Fxbouffant** [comment]
I'm sorry but it's too late to provide a screenshot. I'll go in more details.
The issue happens not in my turn but on the enemy's turn:
- Rage Orc damages me for 1HP
- Bleeding ring triggers which heals me for 3HP
- Quick silver belt triggers which damages Rage Orc for 3HP
-  Thorn Shield then triggers on Rage Orc damaging me for 3 HP
- The bleeding ring then triggers again and the cycle continues indefinitely

**Comment by TerryCavanagh** [comment]
Weird. Are you using any mods? What language are you playing in? 

If you can take any screenshot from the game whatsoever that includes any of these items, that would be a big help. None of this if familiar so right now my theory is that you've gotten confused and have posted this to the wrong github...

**Comment by Fxbouffant** [comment]
Sorry I mistake this game for Dicey Elementalist

**Comment by TerryCavanagh** [comment]
Lol 😂
