### ISSUE TITLE
Copycat vs Robot crashing on Xbox One

### ISSUE THREAD

**Issue by DyneReborn** [TerryCavanagh/diceydungeons.com#2578]
Unsure of which specific equipment is causing the issue: but the AI is taking enough time to try to decide its actions that it actually locks the game up and causes it to crash. 

Equipment used during fight

Plasma Blaster
Lucky Star
Missing Score
Overclock
Mechanical Leg
Fixed Payout+

**Comment by TerryCavanagh** [comment]
Thanks for the bug report! We have a patch for Xbox almost ready to go which should fix this!

(For anyone reading curious about what's causing this: the console versions no longer use Crashdumper (a major optimisation!), which changes how script errors are handled. Previously, things like Copycat attempting to use Overclock would fail silently, tracing an error message. Unfortunately, on consoles, these errors will now cause outright crashes. Thankfully, it's actually pretty rare - but we've written a test scenario program to make sure that none of these script errors occur anymore.)
