### ISSUE TITLE
Crash in classic menu after done the witch Haloween episode

### ISSUE THREAD

**Issue by JuSuperSonic** [TerryCavanagh/diceydungeons.com#2581]
Hi,

Get this one after in the classic menu after finish the Halloween episode of the Witch !

--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v1.12.2 / 1.0 (mod API)
sess. ID:	dicey_dungeons_2021-11-20_17'06'53
started:	2021-11-20 17:06:53
--------------------------------------
crashed:	2021-11-20 17:27:59
duration:	00:21:05
error:		ERROR in callscenemethod(ChallengeScreen,update) static : Error: Trying to create equipment "Wrong Answer" (Wrong Answer) from template, but cannot find a matching template in equipment.csv., stack = 
Called from elements.Equipment.create (elements/Equipment.hx line 170)
Called from elements.Equipment.new (elements/Equipment.hx line 18)
Called from elements.Fighter.new (elements/Fighter.hx line 290)
Called from states.ChallengeScreen.update (states/ChallengeScreen.hx line 320)
Called from Reflect.callMethod (C:\coding\haxe\openfl\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 265)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 178)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 456)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

**Comment by TerryCavanagh** [comment]
Excellent find, thank you! Fixed!
