### ISSUE TITLE
UI suggestion for Witch: Drag dice directly to the field to cast a spell

### ISSUE THREAD

**Issue by pacesmith** [TerryCavanagh/diceydungeons.com#259]
I just noticed myself drag a 4 into the upper-left spell slot, wanting to cast Magic Missile into that slot. I think it's unambiguous, so why not make it a UI shortcut?

**Comment by YinYin-Falcon** [comment]
I want that too.

One potential issue: a player might never learn that they can recast and replace spells, if this is the first method they use. That would be fatal. To deal with that someone else suggested adding a remove/clear option.

**Comment by joshtriplett** [comment]
I agree, this would make the UI much smoother. Perhaps a small "cast" slot right next to each spell slot, that sticks around even with a spell cast and overwrites the spell when used?

**Comment by pace212** [comment]
I think the current UI makes it clear that you can recast and replace. If you put a dice into "Cast Spell" (which is an obvious place to put a dice) then all four areas are highlighted, even if they already contain equipment.

**Comment by TerryCavanagh** [comment]
I still want to try this! I see people doing it all the time in videos, and even I do it absent mindedly when playtesting occasionally. Adding this one to High Priority for launch.

**Comment by TerryCavanagh** [comment]
Ahh, probably not going to happen now.
