### ISSUE TITLE
Crash on Xbox as thief against copy cat

### ISSUE THREAD

**Issue by THNeal** [TerryCavanagh/diceydungeons.com#2590]
Reproducible crash happens after player's first turn when copy cat turn begins.

Environment: 
Xbox Series X

Character / floor detail:
Thief: Door #4, floor 3. 17/32 health. Mushroom theme.

Equipped: 
Dagger+ (0,0), Bump (0,1), counterfeit (0,2:1,2), lockpick (1,0), snake eye charm (1,1)

I suspect it's related to some combination of item(s) that I have equipped. Autosave thankfully puts me right back at the start of the battle so I've tried to narrow the issue down:

Individual equipment ruled out by unequipping and restarting battle:
Bump, Snake eye charm, counterfeit

Had to stop there. Good luck.

**Comment by TerryCavanagh** [comment]
Hey! Thanks for the bug report. We're aware of this issue and it's already fixed in testing - patch coming soon!
