### ISSUE TITLE
Xbox Series X Crash Back To Dashboard - Jester vs Copycat

### ISSUE THREAD

**Issue by JxxD** [TerryCavanagh/diceydungeons.com#2591]
V 1.0.0.0 Xbox Series X

Game constantly crashes back to XBOX Dashboard when fighting Copycat.
For me its currently happening in Jester Bonus round 5 (or 6) Level:4 Floor:4

**Comment by TerryCavanagh** [comment]
Sorry about that! Thanks for the bug report - this is fixed in the upcoming patch!
