### ISSUE TITLE
can drag "2" die into upgraded shield slot with max value 1

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#26]
<img width="237" alt="bildschirmfoto 2018-03-31 um 13 11 18" src="https://user-images.githubusercontent.com/465632/38162635-13594e64-34e5-11e8-9e74-6cbfc0bee8a0.png">

i can drag it in, presumably it should't be allowed :)

**Comment by TerryCavanagh** [comment]
Oh, whoa! Can you play it with the 2 in there?

**Comment by TerryCavanagh** [comment]
Ok, fixed!
