### ISSUE TITLE
Thief steal can get an item weakened by the player's own attack

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#260]
Normally, the thief's steal ability obtains a copy of the enemy's equipment without regard for its current status; for instance, stun doesn't carry over, and the player's copy of countdown equipment has its own countdown independent of the enemy's. However, after using a Stereohead's own weaken ability against it, on the next turn the steal ability stole a weakened version of the Sonic Wave.

EDIT: Retesting, it's possible that this was a result of a weaken effect from the enemy applying to the stolen equipment, which is still odd but more understandable.

**Comment by TerryCavanagh** [comment]
Yeah, this is due to the stolen card getting the weaken status! I've fixed up the animations in v0.9, and hopefully this is more clear now. Closing!
