### ISSUE TITLE
Reversal with no equipment might be causing a crash on console

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2609]
Need to investigate, doh. Same basic issue as the copycat thing.

(oh, this probably means that you need to look extra hard for problems with Reunion Rotten Apple, too)

**Comment by TerryCavanagh** [comment]
>yeah, I think this happens if you have no equipment
it seems like a fix is to look at the enemy's moves, then look back to your moves again
since the crash happens just before the game animates your new equipment into place 

Extremely useful note!

**Comment by mrcdk** [comment]
This was fixed when we fixed iterating over empty arrays in hscript a few months ago!

**Comment by TerryCavanagh** [comment]
Oh, right! Fixed!
