### ISSUE TITLE
Copycat crash on latest Xbox version

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2615]
Seems like I've missed a case!

Player was on the upgraded player equipment path versus Copycat, ` two boomerang+, two battle axe+, and two midnight charm +`

(wonder if this just has something to do with copycat in this episode specifically)

**Comment by ncrecc** [comment]
could be something to do with battle axe+ having a deckupgrade that enemies like rhino beetle use instead of the reduced size upgrade

**Comment by TerryCavanagh** [comment]
Ohh, yeah it is possible that I've missed a deckupgrade check when I did the automated tests...

It sounds like this was happening in Warrior episode 2, though, so I think a script error on Copycat + player having upgraded equipment is the most likely cause here.

**Comment by Volatile-Agent** [comment]
Version 1.0.0.2 on Xbox One: Thief (Level 3) vs. Copycat in Elimination Round, floor 3, with equipment Dagger+, Snake Eye Charm, Pea Shooter, Lockpick, Healing Crystal, and Crowbar. Freezes at start of Copycat’s first turn and eventually returns to home screen. Removing either Lockpick or Crowbar seems to fix it.

**Comment by TerryCavanagh** [comment]
https://github.com/TerryCavanagh/diceydungeons.com/issues/1213

**Comment by TerryCavanagh** [comment]
Fixed now.
