### ISSUE TITLE
character select music no longer has crowd cheering

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2617]
since the character select music was changed from the specific ``characterselect`` version of come on down to the original version, ``combat7``, you no longer hear the crowd cheering in the background. readd crowd cheering as a separate audio file with the same length as combat7?

**Comment by TerryCavanagh** [comment]
This one is down to a decision made by Chipzel - (part of some small edits made for the Switch version) so I'm not expecting to change.
