### ISSUE TITLE
berserk doesn't affect damage sound effects

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2620]
e.g. crowd doesn't cheer when you score 10 damage because berserk made a 5-damage attack into 10 damage

**Comment by TerryCavanagh** [comment]
Ah, yep - this one should be easy to fix internally, just need to make `sfxdamage` aware of changes to the damage modifier

**Comment by TerryCavanagh** [comment]
Done!
