### ISSUE TITLE
Spiky Sneeze occasionally didn't reduce countdowns

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2625]
https://user-images.githubusercontent.com/32357485/149407971-299f3999-2e93-4bf9-9fdf-7a33198dc5b8.mp4

This happened a few times, but only while I had a countdown (Ancient Terror) as my stolen card

**Comment by TerryCavanagh** [comment]
Fixed - Spiky Sneeze wasn't working for any stolen cards.
