### ISSUE TITLE
Casting a new spell on top of Bump still bumps afterward

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#263]
Player: Witch, Lots More Dice
Enemy: Archer
Fight! Cast Bump into lower-right. Cast Magic Missile into lower-right. Put a 2 into Magic Missile.

It not only does 5 damage as expected - it also bumps the 2 into a 3!

This happens even if the Bump was already there at the beginning of your turn, but the bonus-bump doesn't persist across turns.

**Comment by pace212** [comment]
A side effect of this is that Fury Charm doubles the hidden Bump instead of doubling the actual attack ):

**Comment by pace212** [comment]
Looks like hydrophilic attack noted this and generalized it:
"hydrophilic attack - Today at 7:47 AM
The way I think it works is that if you replace an unused spell with a new one, and then insert a dice that would be accepted by both the new and the old equipment, both effects will trigger simultaneously"

**Comment by TerryCavanagh** [comment]
Fixed! Thanks :)
