### ISSUE TITLE
roll the bones shouldn't be able to bring enemy (or player) to 0 dice

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2643]
for consistency with kaleidoscope and bear hug, at least, and to avoid some potentially very unsavory situations the player could get into

**Comment by TerryCavanagh** [comment]
After a short discussion about this on the dicecord, the solution I like is to just use bonus scores to prevent Skeleton from reducing your dice to 0.

**Comment by TerryCavanagh** [comment]
Done!
