### ISSUE TITLE
Equipment that inflicts new status effects in Reunion should just describe the effect, not say e.g. Inflict 1 toxic

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2644]
Instead, it should say "Inflict 1 poison whenever the enemy uses equipment". This removes the ambiguity about what the new status effects are going to do.

(Probably not worth bothering for e.g. Password)

**Comment by onetruepurple** [comment]
I agree but I'll miss seeing the super slick red Sting icon on the red Queen Bee card.

**Comment by TerryCavanagh** [comment]
Yeah; also, there is something lost at the same time about seeing a new card and not knowing what it's going to do. Still, it's the right call! (done now)
