### ISSUE TITLE
Transformation graphics and name don't reset if you use your limit break beforehand

### ISSUE THREAD

**Issue by not-mario** [TerryCavanagh/diceydungeons.com#2645]

**Comment by not-mario** [comment]
![image](https://user-images.githubusercontent.com/96184156/149538531-7069f929-54fa-4ab1-8783-8dff5b62a5d9.png)
example seen here

**Comment by not-mario** [comment]
This also causes a crash if you level up afterwards.

**Comment by TerryCavanagh** [comment]
Fixed!
