### ISSUE TITLE
Progress editor is available in Reunion, and crashes the game if accessed

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2647]
It should not be available if any mods are active.

**Comment by ncrecc** [comment]
are you sure this isn't a reunion-only issue? most of the time it doesn't crash mods and is incredibly helpful for debugging cutscenes

**Comment by TerryCavanagh** [comment]
Oh, this is a name-confusion thing I think: the Xbox/Switch versions introduced a new feature, a progress editor that lets you edit your save file. This is distinct from the progress editor in the translator mode options, which is more of a developer tool.

Anyway, the (public) Progress Editor shouldn't be accessible when mods or active, but the (translator mode) Progress Editor is fine, that's not going anywhere.

**Comment by TerryCavanagh** [comment]
Oh, that's weird - can't reproduce this one. I must have misunderstood the comment on the dicecord.
