### ISSUE TITLE
Shop did not sell me the item but took my gold

### ISSUE THREAD

**Issue by alexirpan** [TerryCavanagh/diceydungeons.com#265]
I was playing as the Witch, and in a shop on Level 4 I tried to buy a Spell (Tremor). It took 4 gold but didn't open the menu to ask what spell I wanted to replace. This happened twice. I was playing on the Flash version.

Not sure if this is relevant, but my Spellbook was:

1. Cauldron
2. Rainbow Blast
3. Life Drain
4. Magic Missile
5. Electric Shock
6. Duplicate

and I was in the Sorcerer's Guild and had an upgraded spell.

**Comment by TerryCavanagh** [comment]
Fixed! Thanks!
