### ISSUE TITLE
die locked with parrying dagger becomes unlocked

### ISSUE THREAD

**Issue by MyosotisArae** [TerryCavanagh/diceydungeons.com#2650]
I used parrying dagger with the robot. The die was locked at the begining of the enemy's turn, but was unlocked as soon as he used an other die in an equipment, each time, whatever the enemy.

**Comment by TerryCavanagh** [comment]
This sounds like the expected Parallel Universe behaviour. Parallel Universe "Lock?" works differently - it forces dice to be played in a specific order, so once you've played the first dice, all the remaining ones are unlocked. In a lot of cases this isn't as powerful as the usual Lock status effect, but for certain enemies (like e.g. Skeleton), it can cause them to lose their entire turn!
