### ISSUE TITLE
Rake doing 5 damage is probably more interesting than the current <d6>, MIN5

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2652]

**Comment by onetruepurple** [comment]
Weird thought: MIN4, 4 damage, on 6, roll another dice.

**Comment by TerryCavanagh** [comment]
Nah, Gardener is complicated enough I think! Made this change.

**Comment by TerryCavanagh** [comment]
It's weird how much more legible this is

![image](https://user-images.githubusercontent.com/2874150/149984438-55c0854f-8394-4f93-aaab-583a27faa4f0.png)
