### ISSUE TITLE
Rephrase Electric Shock- text

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#266]
Current: "NEEDS 6 / Do [dice] damage,"
Problem: It does +1 shock but that's not stated.
Suggested:
- "Do [dice] damage / +1 shock" (leave the "needs 6 implicit)
- "NEEDS 6 / [dice]dmg +1 shock"

**Comment by TerryCavanagh** [comment]
Thanks!

This also affects:
  - Ice Shard-
  - Pickpocket-
  - Ring of Sacrifice-

**Comment by TerryCavanagh** [comment]
![fixed](https://user-images.githubusercontent.com/2874150/41717227-e73fcd92-7550-11e8-96b9-473eb3090a09.png)

Fixed!
