### ISSUE TITLE
Sting tooltip isn't quite right

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2660]
![image](https://user-images.githubusercontent.com/2095534/150004050-4e5c4d9a-fb23-4bee-804a-a425b8856edc.png)

It doesn't apply 2 Shock - it should be more like "When you use the next _n_ equipment, inflict shock to yourself"

**Comment by TerryCavanagh** [comment]
Oh, right! I changed this in the last alpha, forgot to adjust the tooltip!
