### ISSUE TITLE
Sting doesn't seem to inflict Shock?

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2663]
![image](https://user-images.githubusercontent.com/2095534/150005434-b43a1581-843d-440e-9a0f-eb8ebd9ed120.png)

**Comment by TerryCavanagh** [comment]
Oh wow, ok! Seems this issue is deeper than I thought: https://github.com/TerryCavanagh/diceydungeons.com/issues/2661

**Comment by TerryCavanagh** [comment]
Fixed.
