### ISSUE TITLE
Gargoyle Potion doesn't work for the player, since Stunlock isn't a skill

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2669]
![image](https://user-images.githubusercontent.com/32357485/150544800-1bef364f-9815-42f5-a72a-3edf4ef21750.png)

**Comment by TerryCavanagh** [comment]
Whoops! Another case of something breaking because I'm removing things from the spreadsheets...

**Comment by TerryCavanagh** [comment]
Fixed.
