### ISSUE TITLE
Try attaching shield power to specific items

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#267]
Suggestion from @iiiaaannn: 

```
for example: i find a wooden shield and an iron shield. 
both would accept any dice, but wooden shield would stop 
growing at 4 and iron would stop growing at 8
```

I think the implications of this are neat, and could make shielding more interesting. Try it out!

**Comment by joshtriplett** [comment]
Another possibility: instead of capping the maximum shield level, what if you capped the growth rate? For instance, you can put any die in the wooden shield, but it raises shield power by die/2 rounded up.

**Comment by TerryCavanagh** [comment]
I do think this might have been an interesting direction to explore at some point, but, at this point in development, it would be a pretty devastating change. Shields aren't the runaway overpowered mechanic they used to be, so I think this change would amount to a lot more complexity, with it not being clear as to whether or not it was worthwhile. Closing.
