### ISSUE TITLE
Consider making Fury (or Re-Equip) inaccessible in Thief Reunion, or at least less common

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2674]
If you get both Pirate Hookshot/Hookshot and any Fury item in Thief Reunion + backstab, you can go infinite.

Maybe this is ok? I think it probably is. The issue is maybe that it's a little too easy to get this combo, so take a look at the numbers and see if anything needs to be changed.

**Comment by onetruepurple** [comment]
Potential options to consider:

- making Rhino Beetle's items size 2, to discourage (but not outright disable) stealing Beetle Dash
- removing Fury Spell from Deck of Wonder (at least in this episode)

But also:

- it's not an obvious combination to think of, and not one that will always be available
- the player always has the option to _not_ go for it, if they've already experienced it once
- even if, it's supposed to be the easiest episode of the final DLC

**Comment by JuniorUdale** [comment]
Alternatively, consider replacing Backstab with something different. Poison Needle was replaced with Berlin Key, presumably because there's not enough poison equipment to make a "poison build" work. I don't think there's enough reusable equipment to get a really good Backstab turn going either!
