### ISSUE TITLE
Balance issue: Baby Squid hits a little too hard for a level 2 enemy (18 damage on his best turn)

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2677]

**Comment by onetruepurple** [comment]
Suppose that he had only one Inky Juggle: fundamentally this wouldn't affect him mechanically (he only gets to re-use Baby Squid Strike once), but it would shave 3 damage off the max for a relatively more reasonable 15.

He would also need a third dice at that point, though.

**Comment by TerryCavanagh** [comment]
Have made some balance changes (thank you for the suggestion to remove one Inky Juggle!). Baby Squid is probably still a bit too powerful, but I think it's acceptable as is now.
