### ISSUE TITLE
Crash as thief while fighting skeleton (I think it was from stealing his sword)

### ISSUE THREAD

**Issue by FelixNemis** [TerryCavanagh/diceydungeons.com#269]
![screenshot from 2018-06-11 14 03 33](https://user-images.githubusercontent.com/6477924/41251716-6a3be42a-6d80-11e8-9ab9-2408f7d87b88.png)
looks like it tried to steal his two handed sword but instead tried to look up an equipment called "Two"

**Comment by FelixNemis** [comment]
Hmm my theory may not be correct, I got a the same exact crash when fighting the skeleton with the witch (same error and stack trace)

**Comment by pace212** [comment]
I also got it when fighting Skeleton+ as Thief. I took my first turn (stole Wooden Shield, put a 5 in it), Skeleton took its turn, used all its equipment, then after Skeleton ended its turn I got the same "Two" exception.

Starling.hx:648: [Starling] Context ready. Display Driver: OpenGL Vendor=WebKit Version=WebGL 2.0 (OpenGL ES 3.0 Chromium) Renderer=WebKit WebGL GLSL=WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
diceydungeons.js:91570 
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 91569
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 91402
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 91355
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 121182
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 90884
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 37155
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 649
Called from https://www.terrycavanaghgames.com/dice/8/html5/diceydungeons.js line 121182
diceydungeons.js:91575 Uncaught Error: Trying to create equipment "Two" from template, but cannot find a matching template in equipment.csv.

**Comment by TerryCavanagh** [comment]
Fixed. Thanks everyone!
