### ISSUE TITLE
There's too much Shielding in Warrior Reunion

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2696]
Couple of balance issues to deal with here, but this is the big one, I think.

You want Shielding to feel like an interesting extra factor in reroll decisions, but if you can reliably outpace the enemy attacks (which you can do with two shield items), it makes the combat fall apart.

**Comment by onetruepurple** [comment]
Tidal Blade!!!

**Comment by TerryCavanagh** [comment]
Have cut Wooden Shield from the episode, this feels better now.
