### ISSUE TITLE
Jester can't hurt you as Witch if you don't cast anything

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#270]
Solution: let them steal your spellbook

**Comment by joshtriplett** [comment]
As long as they have to use dice to cast spells from it, that seems OK. But in return, they shouldn't be able to steal spells you've cast.

**Comment by BarbzYHOOL** [comment]
I just realize I could've beat Jester by just using the +1 dmg from witch haha

**Comment by TerryCavanagh** [comment]
This one sorta fixed itself now that the witch starts with a prepared spell!
