### ISSUE TITLE
Stolen lightning rod doesn't account for your damage

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#271]
Fighting against the Wisp as a Thief, if you steal the Lightning Rod, it always shows 0 damage, even if you've taken damage since the start of the battle.

**Comment by TerryCavanagh** [comment]
Unless there's something I'm forgetting, I don't think this issue can occur in regular gameplay anymore (as the Wisp no longer has Lightning Rod). Closing!
