### ISSUE TITLE
Rethink the Warrior limit break

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2713]
Hmm. Deadlift *works*, and is appropriately powerful - but it's a mess of different things. It's fine when you're playing, but it adds a lot of mental overhead to the episode, trying to figure it out.

To be honest - just having Fury would probably work better.

**Comment by onetruepurple** [comment]
ultima is the onetrueweapon — Today at 10:47 PM
maybe have Warrior start with a lame limit break, but lean into learning new ones as the game progresses

**Comment by TerryCavanagh** [comment]
That's a good suggestion, and this seemed promising - but I've tried it already, and it didn't really work 😔

Originally you started with Barricade, working your way up through Warrior Smash, Stunlock, Fury, Berserk and finally Omnislash. In practice, this fell apart in a few different places - all the limit breaks need to feel worth learning, and it's weird if you end up having two cards at the same time and have to choose (and therefore end up with a dud card that would downgrade you). This might have been fixable, but it felt like yet another complication in an episode that already has a lot going on.

**Comment by TerryCavanagh** [comment]
Ok - in the next version, I'm just going to try out Fury in the name of simplifying the episode. Let's see how that feels, then re-evaluate after the next round.

**Comment by TerryCavanagh** [comment]
Oh, actually: I came up with a way to do this that I like after all! 🔥
