### ISSUE TITLE
Warrior Reunion crashes when selecting a workout card

### ISSUE THREAD

**Issue by cosmos-dot-semicolon** [TerryCavanagh/diceydungeons.com#2714]
**Can't quite remember the name of it, but it's the one that requires 2 dice to disable two damage deal cards. This was going right into a Madison fight.**

crashed:	2022-02-10 21:10:30
duration:	00:30:04
error:		Null Object Reference
stack:
Reunion.enddraftmode (Reunion.hx line 205)
Reflect.callMethod (C:\coding\haxe\openfl\std/cpp/_std/Reflect.hx line 55)
motion.actuators.GenericActuator.complete (motion/actuators/GenericActuator.hx line 155)
motion.actuators.SimpleActuator.update (motion/actuators/SimpleActuator.hx line 529)
motion.actuators.SimpleActuator.stage_onEnterFrame (motion/actuators/SimpleActuator.hx line 608)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

**Comment by TerryCavanagh** [comment]
Hey, thank you for the bug report!

This looks to be the same as https://github.com/TerryCavanagh/diceydungeons.com/issues/2714, so I'm going to close it, but thank you for the extra information (good to know that it doesn't just happen on Beatrice)
