### ISSUE TITLE
Bicep Curl's description is too ominous 

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2723]
The only other use of ... in the game is on Last Stand?, so understandably its appearance on Bicep Curl is a bit scary. It also kind of implies that it's going to do something more interesting that it does.

Might be best to just have the description update, and have the effect be an invisible thing

(while I'm here: might make it unrestricted too, why not)

**Comment by JuniorUdale** [comment]
The "..." is too ominous, but I don't think the effect should be invisible. It should definitely inform the user that it's going to give -1 for the next use; at the very least it should say *something!* Maybe "swap this effect" or "next dice gets -1" would be useful to see on it.
![image](https://user-images.githubusercontent.com/32357485/154130393-6d7b9ffe-4f4c-4179-af66-9cdd44957832.png)

**Comment by TerryCavanagh** [comment]
I do agree that it should say *something*, but anything I can think of feels messy or confusing, heh. Trying to keep it to two lines, when one of them is already taken up with the reuseable line is tricky...

`Swap this effect` isn't bad.

**Comment by TerryCavanagh** [comment]
I played around with this for a while, and I just can't find a new description I like... So I'm trying the plain one! Sorry, @JuniorUdale 😅 

(I have made it unrestricted, though, which makes it feel a bit nicer)
