### ISSUE TITLE
Even if manual firing doesn't make the final cut, consider keeping it in as some sort of hidden easter egg

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2724]
Assuming it wouldn't take *too* much effort trying to apply it universally.

**Comment by TerryCavanagh** [comment]
Well, I haven't deleted anything 😄 Currently, I have a bunch of stray bits and pieces like this that didn't really work out in a separate mod. Hopefully modders can make use of it at some point...

**Comment by TerryCavanagh** [comment]
Actually, have decided to keep this!

After simplifying a lot of things in the episode, decided to try adding back a few things I liked, and this was basically top of the list. It compliments the Reroll style of the episode really well, and contributes to giving it a very different feel.
