### ISSUE TITLE
Figure out the Jester Technique bug

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2728]
This narrowly missed the Reunion Alpha 5.1 cutoff, boo.

For some reason, if you win a fight as Jester, you lose all your equipment after the fight. If works fine if the revert happens after your turn if you haven't won the fight. Can't figure it out, which is a shame because this is a really cool thing...

**Comment by mrcdk** [comment]
Fixed!
