### ISSUE TITLE
player shouldn't be able to use limit break during drafting phase of draftmode

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2729]
at first i actually thought "eh not a big deal, draftmode's just for warrior reunion anyway" but seeing #2726 makes me think this deserves mentioning.
using limit break while draftmode is active could potentially break a *lot* of stuff if your limit is any more complex than just "gain 3 shield". e.g. what if one of the draftmode cards has a dice slot, and your limit break makes you roll a new dice?

**Comment by TerryCavanagh** [comment]
Sure, that should be easy enough 👍

**Comment by TerryCavanagh** [comment]
Fixed for v2.1!
