### ISSUE TITLE
Illuminate+ (upgrade) doesn't exist

### ISSUE THREAD

**Issue by BarbzYHOOL** [TerryCavanagh/diceydungeons.com#275]
I put illuminate on the upgrade slot and it was the same and did the same thing

I was expecting it to give me 3 dices instead of 2

**Comment by TerryCavanagh** [comment]
![fixed](https://user-images.githubusercontent.com/2874150/41687455-a8b05496-74df-11e8-8376-9c90a121fa5c.png)
Fixed :D

**Comment by joshtriplett** [comment]
@TerryCavanagh Should upgrades always be strictly better than the base version? Because "needs doubles" can make this *worse*, since it's usable in fewer situations.
