### ISSUE TITLE
Crunch+ is overpowered

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2752]
I can do 7 damage at the cost of two ones.

**Comment by TerryCavanagh** [comment]
Yeah, I did think this was pushing it a bit!

I'm considering making crunch do 5, without any other changes - I like that Crunch+ becomes a mini vise grip, and would like to keep that I think

**Comment by TerryCavanagh** [comment]
Made a little tweak to this, happy with it as is now.

![image](https://user-images.githubusercontent.com/2874150/170526443-c52ecc4e-941b-4035-ae3b-8a0eb5ef7fdc.png)
