### ISSUE TITLE
Add confirmation before using a burning dice

### ISSUE THREAD

**Issue by BarbzYHOOL** [TerryCavanagh/diceydungeons.com#276]
Because of some bugs, a missclick can end your life. Add a confirmation prompt before choosing a fire dice

Also add the option to disable the prompt in settings

**Comment by TerryCavanagh** [comment]
Hmm, I don't think this is a common enough problem to require coding a confirmation prompt in. (I've watched a lot of people play the game at this point, and almost never see it happen.)

Think I'm not going to do this one. But thank you for the suggestion!
