### ISSUE TITLE
Particle Accelerator didn't work in Inventor Reunion

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2760]
https://user-images.githubusercontent.com/32357485/155910457-cac7bf32-bc7c-4adb-9151-a1a23a9c5d02.mp4

**Comment by TerryCavanagh** [comment]
(I *think* this one's been fixed already, but I'm not 100% sure)

**Comment by JuniorUdale** [comment]
Looks like this one did get fixed at some point!
