### ISSUE TITLE
Pre-audit thought: there's too much Confuse in Reunion

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2764]
One recent run had me facing Crystalina (with Confusing Crystal), Drain Monster, and Kraken one after another and I spent almost every turn of all 3 fights confused.

**Comment by TerryCavanagh** [comment]
Hah. That *is* a lot to get in one run.

I dunno, I sorta felt like confuse was underused in vanilla, and I like it, so I'm using it a bit more often in Reunion. Maybe too much, I dunno? (This was against Reunion Jester, I'm guessing? That's a particularly bad case)

**Comment by TerryCavanagh** [comment]
Done a few things to mitigate this: Jester no longer encounters confuse, and Drain Monster inflict confuse a little less often.
