### ISSUE TITLE
testscenario arg does nothing

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2766]
![image](https://user-images.githubusercontent.com/11216597/158185700-3f839fbe-c271-4ab6-b6e1-0bee3d05f2f6.png)

**Comment by TerryCavanagh** [comment]
Oh, whoops - yeah, this was broken - turns out the testscenario code was only working when I literally compiled it myself. So when you try to run it from the steam version, it doesn't start.

I've fixed this in my build now, so it should work in `dlc2_alpha6`!
