### ISSUE TITLE
Skeleton's curse should require a 6 to launch

### ISSUE THREAD

**Issue by BarbzYHOOL** [TerryCavanagh/diceydungeons.com#277]
Or a minimum 5 dice.

Because it's really too hardcore. I haven't beat one skeleton in hard mode with the witch yet... and only once the wolf (and almost died ofc)

**Comment by ncrecc** [comment]
If all is well with the RNG, rolling a 6 would be equally as likely as rolling a 1.

**Comment by BarbzYHOOL** [comment]
-__-'

but if the skeleton uses a 6, then he won't use it to attack you....

**Comment by TerryCavanagh** [comment]
Skeleton has been redesigned. Closing!
