### ISSUE TITLE
Extra n counts for Firework damage

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2772]
It probably shouldn't, right?

**Comment by JuniorUdale** [comment]
It's a status, and Fireworks counts all statuses. As long as it's going to include things like Vampire and Bear Transform, this feels fine to me.

**Comment by TerryCavanagh** [comment]
Huh, yeah. It does feel a bit weird, but I think it's probably correct? Anything visually on your status bar should count I think.
