### ISSUE TITLE
Cluttered view with 20 dices (screenshot for boasting)

### ISSUE THREAD

**Issue by BarbzYHOOL** [TerryCavanagh/diceydungeons.com#278]
We can't see anything and if I missclick I will cast the wrong spell (happens all the time)

![How to be awesome](http://image.noelshack.com/fichiers/2018/24/2/1528834855-diceydungeons-very-practical.gif)

Btw I could get infinite dices if I wanted lol.

PS: omg after the win I'm left with 1 hp to fight the boss

**Comment by TerryCavanagh** [comment]
I've come to love the messiness of a good cluttered screen when this happens. It feels broken and messy in the right ways, I think. We considered various UI changes to deal with this, but I think ultimately I wanna keep it exactly as is. Closing!
