### ISSUE TITLE
v0.7 - Vampire bypassed the iron armor -2 reduction

### ISSUE THREAD

**Issue by BarbzYHOOL** [TerryCavanagh/diceydungeons.com#279]
I once beat the vampire with a crowbar build (proud of it :P) and in top of that, one of my item"iron armor" was completely useless.

Maybe it has been fixed in 0.8 but not sure so here I report.

![crowbar](http://image.noelshack.com/fichiers/2018/24/2/1528835639-diceydungeons-crowbar-build.gif)

**Comment by TerryCavanagh** [comment]
Pretty sure this is fixed! Blood Suck used to bypass shields; now it no longer does. Thanks!
