### ISSUE TITLE
You can inflict more than 1 Stun if you use Mastermind quickly

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2795]
![image](https://user-images.githubusercontent.com/32357485/161329883-64f341e3-8e16-43b4-931a-5a8d637e388e.png)

This is because Mastermind only checks if you have no equipment when it activates, and equipment doing their animation doesn't count as being in your inventory.

**Comment by TerryCavanagh** [comment]
Aha! Good catch. (This one comes up with the fixed gamepad controls almost everytime)

Very easy fix here, just don't inflict Stun it it's already inflicted, lol
