### ISSUE TITLE
Redesign the Detonator, rethink poison layouts

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#28]
Detonator being size 3 makes it basically worthless. It needs to be expensive, but not restrictive.

**Comment by YinYin-Falcon** [comment]
It also seems to move things off screen:

![image](https://user-images.githubusercontent.com/3826749/38164292-3ff77af0-3502-11e8-8d2a-54824fed5e10.png)

**Comment by TerryCavanagh** [comment]
Done!
