### ISSUE TITLE
"Must Equal 7" items becoming COUNT7 when upgraded makes certain enemies disproportionately difficult on Hard

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#280]
The biggest problem here is obviously the Dire Wolf+ using Howl practically every single turn if precautions i.e. shocking isn't taken. But as of 0.8 this also applies to Cleric+ and Chant, which is now a near total run ender (especially for the Witch).

**Comment by TerryCavanagh** [comment]
Phasing out must equal 7 equipment for now. Closing this!
