### ISSUE TITLE
Fix Game.progresstracking kludge from Halloween Special

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2805]
I made a decision for Halloween Special to meet a deadline that's causing me some issues now. (it's the cause of the "Null Object Reference" crash at the end of the alpha Reunion episodes).

At this point, other mods are using the same Halloween Special trick to e.g. have custom challenges and ending cutscenes, but that won't really work for Reunion. Try to detangle this mess, without breaking any existing behaviour, so that you can support the following features:

 - Custom ending cutscenes
 - Saving true/false variables

(Might end up just kludging this for Reunion too, which is not the end of the world. Will see how I go for time)

**Comment by TerryCavanagh** [comment]
Oh, for future reference:

The variable that's tying all this together is `Game.progresstracking`. The Null Object Reference crash is because the ending cutscene is trying to run `episodecomplete_mummy` in `ViewCutscene.playepisodeending`

**Comment by TerryCavanagh** [comment]
Ok, this is done now! Changes that are relevant to Dicey Dungeons Modding:

- progresssettings.txt has an extra parameter called "flags" which contains the multiple flags the game will save. So Reunion's progresssettings.txt file looks like this:
>reunion
nochallenges
nochallenges
flags=["cutscene_reunion_intro", "cutscene_reunion_outro"]

- EpisodeTemplate now has 2 extra columns 'Script: Get Intro Cutscene'  and 'Script: Get Outro Cutscene' which have to return a string pointing to the cutscene filename. If the scripts are empty or don't return a String the intro one will return the values from the Cutscene column and the outro one will return an empty string. It also has 2 extra functions to get the intro and outro cutscenes: EpisodeTemplate.getintrocutscene() and EpisodeTemplate.getoutrocutscene()

- Whenever a Cutscene starts playing a flag will be set starting with "cutscene_" plus the cutscene filename. Useful to check if certain cutscene has been played in the scripts.

- Exposed to both Script and Cutscene scripts the following functions: Savedata.checkflag(), Savedata.setflag(), Savedata.clearflag() and Game.getepisodesprogressfor()

- Exposed to the Cutscene scripts the following function and variable: CutsceneFunctions.playcutscenefromscript() as "playcutscene" and the variable Episodestate.activeepisode as "currentepisode"

**Comment by ncrecc** [comment]
how are you storing flags? is it possible to add a string argument for setflag?
