### ISSUE TITLE
Stolen cards and workout cards need to be cleared after quitting a run

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2806]
Because they use the same arrays internally, it can result in this sort of situation:

![image](https://user-images.githubusercontent.com/2874150/165183924-fe8973da-ee4a-4ecb-a809-e853e08b1821.png)

**Comment by TerryCavanagh** [comment]
Uh, weird, I actually can't reproduce this one. Seems like it might require quitting at a very specific point, so is maybe hard to do by accident. Still needs to be fixed, but that de-prioritises it a bit.

**Comment by mrcdk** [comment]
Fixed it! I was able to reproduce leaving the thief episode with a stolen equipment while in combat and starting the warrior episode and winning a battle. The stolen card wasn't being reset when starting a new episode

**Comment by TerryCavanagh** [comment]
Thanks!
