### ISSUE TITLE
Modding request: if a field of self.gamevar cannot be serialized, ignore the field instead of crashing

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2809]
There are a lot of instances where self.setvar() is used to hold temporary values that only matter in combat (so it doesn't matter if they get reset outside of combat), and it takes a lot of twiddling and some jank to make sure it always gets reset before any scenario where the game saves to avoid causing a crash. For the sake of modders who don't realize this, it should still print something in the console when this occurs, like "WARNING: fighter var [foo] holds an unserializable value; field will be empty upon reloading game!", just don't crash.

**Comment by ncrecc** [comment]
Could be done by setting any fields with unserializable values to empty before serialization (and making the warning message reflect that the field is now empty)

**Comment by TerryCavanagh** [comment]
Hmm - this is kind of complicated for reasons that I think have been covered pretty well on the Dicecord - a fix would involve making a lot of small changes to how the game currently handles scripts, and adding extra checks to various script hooks, and that's maybe a little too dangerous to mess with, considering what it could potentially break.

Plus, you know, a hard crash is actually good feedback; it tells you right away that the game can't handle what you're trying to do. An invisible failure will just lead to people ignoring the error messages, and probably ending up with substantially more cryptic bugs as a result.

Yeah - I guess I'm not convinced! Happy to reconsider if you wanna give me a few more concrete examples of where this might be a good idea, but as of right now I don't really think it's needed. It's a bad combination of (a) dangerous to mess with and (b) not really that beneficial if fixed.

**Comment by ncrecc** [comment]
in retrospect this isn't really much of an issue since Rules.substitutions exists and can be used like a non-saving version of self.gamevar (as long as none of the keys correspond to valid equipment names)
