### ISSUE TITLE
Some Reunion strings are missing in extrastrings.csv

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2816]
The following Reunion strings are not present in extrastrings.csv and therefore are always shown in English:

- Coin doesn't fit!
- Gold coins only!
- Silver coins only!
- Heads only!
- Tails only!
- Place a coin

If I add them to the CSV file, they are correctly picked up, so no code changes are needed.

Tested on v1.12.4 (reunion translator mode), 25-04-2022.

**Comment by TerryCavanagh** [comment]
Excellent catch, thank you! I'll add all six strings to the upcoming final strings pack.

**Comment by TerryCavanagh** [comment]
Fixed!
