### ISSUE TITLE
"Boom and bust" description shows an error when localized

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2817]
Even when using the exact same string as English in the localization, "ERROR" is shown instead of the correct variable, both in translator mode and in real battles. Seems like `<var_tempparticleacceleratorkludge:particleaccelerator>` is not being resolved properly.

Tested on v1.12.4 (reunion translator mode), 25-04-2022.

![Captura de pantalla de 2022-05-11 13-11-13](https://user-images.githubusercontent.com/285008/167836285-06e15bb1-7420-4a41-9fb5-b5d40f61e3b4.png)

**Comment by TerryCavanagh** [comment]
Aha, thank you! This happened with another complex variable too just before I sent off the translator mode.

It's not worth a "real" fix - a simple workaround is to remove the following two rows from the substitution file:

`Heads: Do [sword]<var_tempparticleacceleratorkludge:particleaccelerator> damage|Tails: +[sword]2 this turn|[gray](Reuseable)`
`Heads: Do [sword]<var_tempparticleacceleratorkludge:particleaccelerator> damage|Tails: +[sword]1 this turn|[gray](Reuseable)`

and to add both of them to the `extrastrings.csv` file. I'll include both in the upcoming final strings pack. Thanks!

**Comment by TerryCavanagh** [comment]
Fixed!
