### ISSUE TITLE
After purchasing all shop items in Reunion, Yolanda shows an empty dialogue

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2818]
After purchasing all three items, when reentering the shop, Yolanda shows an empty dialogue box.

Tested on v1.12.4 (reunion translator mode), 25-04-2022.

![DICEY yolanda empty](https://user-images.githubusercontent.com/285008/167837292-967c11ed-ce3c-472f-921d-d3504a0816c9.png)

**Comment by TerryCavanagh** [comment]
Huh! This used to happen in Vanilla. I'll dig into it, thanks :)

**Comment by mrcdk** [comment]
Thanks for the report! It should be fixed in the next build
