### ISSUE TITLE
Stunned equipment name is shown in English

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2827]
At least, this is what happens with "Market crash", but I guess it's most likely not dependant on the equipment and due to the stunned status. "Unavailable (Stunned)" is correctly shown in its translated form.

Tested on v1.12.4 (reunion translator mode), 25-04-2022

**Comment by TerryCavanagh** [comment]
Oh, thank you for the bug report! I'm just gonna edit out that picture to keep the new reunion background secret 🤫

**Comment by Ereza** [comment]
Oops, sorry about that!

**Comment by TerryCavanagh** [comment]
No worries 😅

**Comment by TerryCavanagh** [comment]
Ahah! This one was actually happening to *all* unavailable upgraded equipment, in any situation. Surprised it hasn't been reported before! Fixed now.
