### ISSUE TITLE
Some Reunion equipment becomes unusable when weakened

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2828]
I will try to illustrate this with a sequence of images.

I was fighting with the Robot against Audrey and she inflicted 1 weaken. "Bailout" ("Rescat financer") was weakened and "has no effect", which is correct, but... has no coins shown and is unusable?

![bailout_weakened_1](https://user-images.githubusercontent.com/285008/168173108-6843ad30-c463-4beb-9424-38fd1a2e0bf6.png)

On the next turn, she inflicted 2 weaken. The weakened equipment was "Bear claws" ("Urpes d'ós") and "Market crash" ("Fallida borsària"). However, "Bailout" is now in normal status and has an effect, but... has no coins shown and does not accept any type of coin. "Bear claws" has mysteriously lost its coin indicator too, and is unusable.

![bailout_weakened_2](https://user-images.githubusercontent.com/285008/168173450-080d12e1-0593-4c76-a082-c822ad0500f3.png)

On the next turn, she inflicted 3 weaken. The weakened equipment was "Bear claws", "Bailout" and "Cold hard cash" ("Diners frescos"). Now all of these three cards won't accept any coin.

![bailout_weakened_3](https://user-images.githubusercontent.com/285008/168173632-63614764-b01c-4694-a9a4-cde414ecd7da.png)

On the next turn, she inflicted 1 weaken. The weakened equipment was "Bailout", but all three previously weakened items lost their coins indicator and did not accept any coin.

![bailout_weakened_4](https://user-images.githubusercontent.com/285008/168174266-e7615a18-437e-4f6e-8f9f-42e4117840ec.png)

However, I must say that this does not always happen. I reproduced it in another play session, but in that case only "Bailout" exhibited this behavior, and "Bear claws" was weakened but correctly retained the coins indicator and correctly accepted coins. See this image:

![coinds_not_always_disappear](https://user-images.githubusercontent.com/285008/168173966-c3a5dbe2-b7de-487d-8063-b1d747fa9ffe.png)

Tested on v1.12.4 (reunion translator mode), 25-04-2022

**Comment by ncrecc** [comment]
this may have to do with when the weakened form of the combination equipment has more slots than the form it was weakened from

**Comment by TerryCavanagh** [comment]
Yeah, hmm - I thought this one was going to be fixable with a few spreadsheet tweaks - things like downgrades having different slot configurations - but it looks like it's a bit more serious than that. I'll just have to dig in and make sure combination slots work correctly with weaken.

**Comment by TerryCavanagh** [comment]
Fixed! The weirdness here is that this bug only happened if you had never used the item that was weakened. Once you applied a dice or coin, it fixed the required fields. Anyway, this is fixed now!
