### ISSUE TITLE
Bailout shows a dice silhouette before a coin is used

### ISSUE THREAD

**Issue by Ereza** [TerryCavanagh/diceydungeons.com#2829]
Maybe this is already fixed and it does not affect gameplay at all, but I guess it's a bit strange to see a square dice silhouette in coin-based equipment ("Bear claws" -"Urpes d'ós"- shows a proper coin silhouette).

![image](https://user-images.githubusercontent.com/285008/168175078-184ee458-45d9-4f57-97de-bc9a55229d8d.png)

Tested on v1.12.4 (reunion translator mode), 25-04-2022.

**Comment by TerryCavanagh** [comment]
Fixed!
