### ISSUE TITLE
Some Japanese translation errors in v1.12.2

### ISSUE THREAD

**Issue by NotaninDev** [TerryCavanagh/diceydungeons.com#2832]
- Cutscene Jester 1 typo
"ビザを食べて、" -> "ピザを食べて、"
("eat a visa and" -> "eat a pizza and")

- Cutscene Jester 1
"何百年もの間、" -> "何十年もの間、"
("Centuries (in the dungeon,)" -> "Decades (in the dungeon,)")

- Sticky Hands rule
"敵が先制する。" -> "ランダムで敵が先制する。"
("Enemies goes first." -> "Enemies goes first at random.")

- Sneezy rule
"装備品を使用するとサイコロを1つ振り直せる。" -> "装備品を使用するとランダムなサイコロを1つ振り直される。"
("By using an equipment, you can reroll a dice." -> "When you use an equipment, a random dice will be rerolled.")

- Frog rule
"敵がダンジョンのボスになる場合がある。" -> "どの敵でもダンジョンのボスになる可能性がある。"
("An enemy can potentially be the boss of the dungeon." -> "ANY enemy can potentially be the boss of the dungeon.")

- Challenges requirement (Sneezy, Magician, Dire Wolf, Vacuum, Bounty Hunter, Skelton)
"任意のキャラクターX人の「予選」をクリアする。" -> "任意のキャラクターX人の「登竜門」をクリアする。"
(The episode name for "Elimination Round" was changed from "予選" to "登竜門" a few years ago, but its name is not updated in the challenges.)

- Challenges Stereohead typo
"電技切れになること" -> "電池切れになること"
("My batteries running out")

- Title screen buttons
"追加攻撃" -> "ボーナスエピソード"
("additional attack" -> "bonus episodes")

**Comment by TerryCavanagh** [comment]
Thank you @NotaninDev! This is excellent timing, as the game's text is currently with our translator. I'll pass this message on for him to review!

**Comment by TerryCavanagh** [comment]
Thanks, @NotaninDev! These seem to be fixed in the latest version that I've got from Kakehashi Games.
