### ISSUE TITLE
Try a swap spell station

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#284]
Try a station that allows you to swap the position of two spells in the witches spellbook

(in generally I think this is too confusing to let you do whenever you want - but once or twice, sure)

**Comment by YinYin-Falcon** [comment]
Maybe rename the shops into libraries and make spell swap an item/action you can purchase.

**Comment by TerryCavanagh** [comment]
Am actually planning to just let the player rearrange the spellbook freely now, so, closing this.
