### ISSUE TITLE
Consider an enemy that can inflict the Magician rule as a status effect

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2859]
The potential for chicanery, especially for Warrior and Jester, would be high.

Would need to account for combination cards (could become countdowns, or NEEDS#, and vice versa).

**Comment by onetruepurple** [comment]
(Wild thought: call this item Ice Cream Headache and give it to Yeti)

**Comment by TerryCavanagh** [comment]
Huh! I was thinking Warlock, but... yeah, Yeti actually works great. I'm basically just going to do this, thanks 👍

**Comment by TerryCavanagh** [comment]
Ah - I made have gotten carried away here. This is a good idea, but it's a nightmare to implement at the 11th hour when too much can go wrong and deadlines are approaching. I can see from an implementation perspective that this is a couple of hours of work, at minimum.

I'll add the required strings to the upcoming final translator pack, and maybe this can sneak in before PC launch at least - but this shouldn't be a priority.

**Comment by TerryCavanagh** [comment]
Sooo, with Reunion out and widely played, it doesn't really feel worth exploring this anymore. Time to move on! I leave this as an exercise for modders!
