### ISSUE TITLE
In Inventor Reunion, new equipment was created in an already occupied slot

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2871]
There might be a duplicate of this, but making a new issue since it's fairly serious and I have an easy way to replicate it:

Testing with Kale Smoothie (A) and Kale Smoothie+ (B), both were weakened. When I scrapped Kale Smoothie+ (B), the new item occupied the position of Kale Smoothie (A). In this case, I had used Kale Smoothie (A) at least once that turn. On the next turn, Kale Smoothie (A) was gone.

**Comment by TerryCavanagh** [comment]
Ah hah! This happens because there are two copies of a thing! And it will happen with any duplicates - two Short Shorts will do the same thing.

**Comment by TerryCavanagh** [comment]
Fixed for the case of two normal things, but this still happens in the case of downgraded equipment, like the scenario described in the top post.

**Comment by TerryCavanagh** [comment]
To further guard against this, the equipment allocator script now no longer lets you get an extra copy of something you already have. That doesn't make this impossible, exactly, but it does make it extremely rare.

**Comment by TerryCavanagh** [comment]
Oh: a very relevant example of this is that it's pretty easy to find yourself with two "Empty Slots" that aren't prepared yet.

**Comment by mrcdk** [comment]
Fixed it by checking the source equipment in reusable copies. With the fix it may never fallback to checking using the equipment name and may break mods that depend on that behavior.

**Comment by TerryCavanagh** [comment]
Commit looks good to me! Merged, thank you!
