### ISSUE TITLE
Gauntlets makes Equipment? trigger twice instead of adding a copy to your hand

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2873]
https://user-images.githubusercontent.com/32357485/174215123-cbc398a7-bb6f-43ef-9684-7cfee55cda4b.mp4

I don't feel like this is intended!

**Comment by TerryCavanagh** [comment]
Fixed, thank you! The copied cards didn't reset the countdowns, so it was triggering immediately.
