### ISSUE TITLE
reunion skeleton is a bit punishing for inventor when she only has 3 dice

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2878]

**Comment by TerryCavanagh** [comment]
Oh, this issue has change from the one in my inbox!

Anyway, yes, the dice change to Inventor is intended, my hope is that it makes it a little trickier and more interesting. However: it was a fairly last minute change, so I'm interested in opinions about that - have you changed your mind about it. (If I keep the lower dice amount, I'll exclude Skeleton, that's a good call.)

**Comment by ncrecc** [comment]
i had a run where pugnacious sword popped up (the "do n*1 damage, multiplier +1 per use this turn" item) and i had whetstone+, and i tried to micromanage things so that pugnacious sword would get a bunch of uses so i could use it over and over against the boss, but then i ran into skeleton and got demolished. my build was already lackluster, though; whetstone+ and pugnacious sword took up half of my equipment and my other items weren't every good, and i would likely have died to crystalina in the fight prior to skeleton if she hadn't gotten mainly non-damaging items. an extra dice would give more leniency to let interesting synergies come to life despite bad rng or bad play, though it might also just make the episode feel like "playground mode"... worth considering here, is "playground mode" fine since it's the last episode or are the interesting synergies more fun when you earn them?

**Comment by TerryCavanagh** [comment]
Thank you, that's very good info!

Have thought it over a bit, and I think the lower dice number is working; I've removed Skeleton.
