### ISSUE TITLE
textboxes are *really* wide at times

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2881]
![image](https://user-images.githubusercontent.com/11216597/174247228-7ec21cf1-b4e1-4934-b60b-f04784944d59.png)
![image](https://user-images.githubusercontent.com/11216597/174249379-c568ca9b-870c-4273-8a7f-0cd116eaba58.png)
![image](https://user-images.githubusercontent.com/11216597/174249217-b60d0fcd-0f70-4190-930d-95c3671444f6.png)
not that much of a problem (except the credits, potentially), but it looks kind of ugly considering how the vanilla textboxes tend to be much less wide. these could use more newlines

**Comment by TerryCavanagh** [comment]
Whoops, spoilers! Didn't meant to include the enemy lines in the beta, oh well 😅

**Comment by TerryCavanagh** [comment]
You're not wrong, but not planning on changing this now
