### ISSUE TITLE
Thief's generator script that makes items appear from enemies not in the dungeon doesn't seem to work

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2883]
![image](https://user-images.githubusercontent.com/32357485/174399756-7bdb89d3-8d40-4b19-8e64-517ae88b8eff.png)

Already had Acorn Shield from floor 1 despite Dryad showing up

![image](https://user-images.githubusercontent.com/32357485/174399805-2948fb2f-da2c-4b6c-a0ee-ec28ccea0963.png)

Rocket Launch appeared in the shop despite me beating Space Marine earlier

**Comment by TerryCavanagh** [comment]
Aha, this took a minute to figure out. The `getenemylistindungeon()` function doesn't actually work when called from the start game script hook - it returns an empty list, which means the game thinks there are no enemies in the dungeon at all. Should be easy enough to fix now that I know the cause.

**Comment by TerryCavanagh** [comment]
Fixed. (I'm just running the script from Define Level Up Rewards instead, which is called after the enemies are placed.)
