### ISSUE TITLE
If you use an Odd dice in Throwing Axe, it doesn't get copied by Gauntlets

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2887]
https://user-images.githubusercontent.com/32357485/174978815-b607429b-7d2e-408e-9eb1-2d9e91dd310d.mp4

I don't really see much reason to have it do the error animation in the first place, I think it should still fly upwards on odd, but do no damage and play the same "dodged" sound effect.

**Comment by TerryCavanagh** [comment]
Fixed! (I ditched the error animation)
