### ISSUE TITLE
Karaoke Machine does more damage than it should

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#2889]
Karaoke Machine says that it starts at 2 damage and increases by 1 with every use, but when it's used the first time it deals 3 damage instead and so on. It deals 1 more damage than is stated on the card.

This also applies to other equipment using the "timesused" variable on the latest reunion test build, such as Overwhelm.

**Comment by onetruepurple** [comment]
#2860

**Comment by TerryCavanagh** [comment]
Fixed now! (Turns out there was a more general bug with the timesused variable that needed to be be addressed)
