### ISSUE TITLE
When Alchemist transforms into Singer, Karaoke Machine starts at 1 damage

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2897]
![image](https://user-images.githubusercontent.com/32357485/175835976-cb12ee58-8b61-42ac-bf3b-92bfd03a1c71.png)

**Comment by TerryCavanagh** [comment]
Good catch! This is happening because the start combat script (which sets the e.timesused variable) is not called with the transform. For Reunion, I've just kludged it so that Karaoke Machine starts with a different value when created.

Fixed.
