### ISSUE TITLE
Nest Egg shouldn't give Trust Fund if you're fighting the boss

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2898]
![image](https://user-images.githubusercontent.com/32357485/175960195-82259eab-d2e4-4329-b4ae-65d5ed73b70b.png)
Pretty big feels bad moment to have this happen. Maybe just add a clause in the Nest Egg@trustfund script that checks if you're against the boss now, and if you are, it gives one of the other items.

**Comment by TerryCavanagh** [comment]
Hmm, yeah, ok! There's something kinda funny about this situation, but Trust Fund appears so late that it's pretty plausible to get it in the last shop and have this happen.
