### ISSUE TITLE
no sound unless using headphones on ios

### ISSUE THREAD

**Issue by c1o13** [TerryCavanagh/diceydungeons.com#2899]
I can’t seem to get any sound from the ios app (music or anything) unless i connect my airpods, and then i can hear sound coming from the app as normal

**Comment by TerryCavanagh** [comment]
That's weird - I'll keep an ear out for other reports of this, but I think it might just be an iOS configuration issue on your side?

**Comment by TerryCavanagh** [comment]
Oh, also, do you have "silent mode" enabled on your phone? The game respects that setting!
