### ISSUE TITLE
Reunion: Thief doing more than one transform leads to... strange results

### ISSUE THREAD

**Issue by trollbreeder** [TerryCavanagh/diceydungeons.com#2900]
Crowbar goes brrr.
How to achieve this:
Step 1. Level up and choose crowbar as your item (do this at any point before step 4)
Step 2. Fight an enemy that can transform using a countdown item (for example, Alchemist)
Step 3. Steal one of the transform countdown items
Step 4. Fight another enemy that can transform using a countdown item (for example, Copycat)
Step 5. Use crowbar to simultaneously become both transformations at the same time

Strange things happen with the visuals upon doing this!
For example, in Reunion, i caused these equipment visual shenanigans by transforming into Cowboy (through stolen Cowboy Potion from Alchemist) and Warrior (through borrowed Imitate from Copycat) at the same time:
![image](https://user-images.githubusercontent.com/25937686/177833493-f1399d94-10b7-43bf-82b9-8d5e33ce8136.png)
It seems one transformation is prioritized above the other, so only the equipment on top is available (warrior), and the one on the bottom is fake (cowboy).
What's even stranger is what goes on with the player character!
![image](https://user-images.githubusercontent.com/25937686/177833806-04aa0137-a095-48b2-81cc-44318ed3cdd9.png)
Warrior named Cowboy, Thief named Cowboy, that sorta thing. I definitely missed some of the weird stuff that happens from this because i was having fun.

Upon winning the fight by defeating Copycat, the game crashed. At the point of winning, i was transformed into a Cowboy named Cowboy. Here's some details:
![image](https://user-images.githubusercontent.com/25937686/177834027-547089fc-06ec-4884-a13c-0a43d97125cb.png)
Crash log:
```
--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	v2.0 / 1.0 (mod API)
sess. ID:	dicey_dungeons_2022-07-07_18'51'07
started:	2022-07-07 18:51:07
--------------------------------------
crashed:	2022-07-07 19:21:51
duration:	00:30:43
error:		ERROR in callscenemethod(LevelUpScreen,update) static : Null Object Reference, stack = 
Called from elements.Fighter.showstatusbaricon (elements/Fighter.hx line 3583)
Called from elements.Fighter.showstatusbarstats (elements/Fighter.hx line 3675)
Called from displayobjects.Statusbar.draw (displayobjects/Statusbar.hx line 65)
Called from states.LevelUpScreen.update (states/LevelUpScreen.hx line 487)
Called from Reflect.callMethod (C:\coding\haxe\openfl\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 93)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 265)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 178)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 456)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)
```
I did not load any mods at all. I suspect this is possible in vanilla Finders Keepers too, but only Reunion would allow for more than one enemy to have transforming countdown equipment.

**Comment by TerryCavanagh** [comment]
This is a great bug that *hopefully* very few people will see before I have a chance to fix it 😅  Thank you for the detailed bug report, that's very helpful!

**Comment by TerryCavanagh** [comment]
Fixed!
