### ISSUE TITLE
"combat roll move was grabbing whatever dice was picked up"

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2904]
There have been at least two reports of this, both on twitter:

>... was playing the game and found a drag drop bug, it persisted until rebooting the game, but the combat roll move was grabbing whatever dice was picked up and casting as soon as I touched a dice, second one was the inventory screen didn't allow dragging items on to slots in the inventory. 

(The second bug sounds like it might be this one: https://github.com/TerryCavanagh/diceydungeons.com/issues/2903)

**Comment by mrcdk** [comment]
The issue has been found and been resolved. It will be available in the next build!

**Comment by StefanJonceski** [comment]
Feel free to close this ticket, Terry 👍
