### ISSUE TITLE
App crashes immediately - iPhone SE

### ISSUE THREAD

**Issue by hecht-era** [TerryCavanagh/diceydungeons.com#2914]
When I open the app, I see the splash screen for a split second and then it disappears back to Home Screen. IOS15.5, iPhoneSE

just downloaded about an hour ago

**Comment by TerryCavanagh** [comment]
Oh, yikes! That's not good!

Does this happen with any other apps on your phone?

**Comment by hecht-era** [comment]
Hi Terry, 

Nope! Just this one at the moment from what I can tell.

**Comment by hecht-era** [comment]
I’ll try redownloading first

**Comment by TerryCavanagh** [comment]
Ok! To be honest, crashing on startup is just something that shouldn't ever happen on a device as closed as an iPhone, so I don't really have any ideas here. A clean reinstall and restart of the device is probably the first thing to try, yep.

**Comment by hecht-era** [comment]
Tried both a reinstall and reboot. Nothing.

**Comment by TerryCavanagh** [comment]
Hmm - is there anything unusual about your phone? Do you have low storage space? Is it jailbroken?

**Comment by hecht-era** [comment]
Nope! 56/128GB free, not jailbroken

**Comment by TerryCavanagh** [comment]
Sorry I can't be more help!

This is the only report like this we've gotten, so chances are that it's *something* to do with the configuration of your phone - but I have no idea what. When Justo takes a look I might have more questions (though that'll probably be Monday).

**Comment by TerryCavanagh** [comment]
Oh, one thought - what language is your phone set to?

**Comment by hecht-era** [comment]
English (US)

**Comment by hecht-era** [comment]
Whoa holy crap. I had it set to just “English” and then went to check and set it to “English (US)” and now it works. Lol what

**Comment by TerryCavanagh** [comment]
That is super strange, but really good information that we can work from! Thanks!

**Comment by hecht-era** [comment]
No, thank you!
