### ISSUE TITLE
Picnic Basket/any other items that stash dice for next turn should be excluded for Reunion Jester

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2920]
The dice they give you next turn don't get rerolled after using an item.

https://user-images.githubusercontent.com/32357485/178240139-40b651e7-721f-4a70-8809-eb88860c1741.mp4

These items are rare and there's not many of them, but one did spawn for Aliensrock in his latest video (he didn't take it, though)

**Comment by TerryCavanagh** [comment]
Good catch, this would have broken completely. Got lucky that Aliensrock didn't have this happen on camera!

**Comment by TerryCavanagh** [comment]
Fixed.
