### ISSUE TITLE
Polish translation corrections vol. 2

### ISSUE THREAD

**Issue by Diceyop** [TerryCavanagh/diceydungeons.com#2922]
1. "Counter" status has a question mark in name in Polish (all 1-6).

![2022-07-10_17h38_51](https://user-images.githubusercontent.com/108955259/178268321-ec9dd7e9-2980-48e0-ac58-0e3881d8f168.png)

2. Mana is giving additional powers for Jester boxes? 😳
"Karton" is a cardboard box in polish. 📦 It should be corrected to "kartom".

![2022-07-10_17h32_05](https://user-images.githubusercontent.com/108955259/178269087-356715ee-9180-43d1-8cad-cb82b4be6e69.png)

3. "AWANSUJ" is incorrect type of meaning in this context, it should be "AWANS".

![2022-07-10_17h30_56](https://user-images.githubusercontent.com/108955259/178269440-06f5e8de-7c84-4edf-9b3d-ef8aefc249f3.png)

4. "Edit progress" in menu in polish is "Resetuj postępy", which means... "Reset progress".
It should be corrected to "Edytuj postęp".

![image](https://user-images.githubusercontent.com/108955259/178271459-26e09fda-6e64-4390-bd07-476beb2c930e.png)

**Comment by TerryCavanagh** [comment]
Fixed!
