### ISSUE TITLE
Reunion Copycat is named Copycat[], likely causing the name to be shortened in translations

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2925]
not sure why this is the case considering how base copycat isn't in reunion, but in theory it causes translations to use the shortened/alternate translated form of "Copycat" that fits on character icons in the bestiary page, instead of the full name, since reunion doesn't supply its own translation for "Copycat[]" and vanilla has a translation of "Copycat[]" (and all enemy names followed by []) with the note "alternate version for bestiary icon"

**Comment by TerryCavanagh** [comment]
In practice this doesn't cause an issue; none of the localisations for "Copycat[]" are different from "Copycat". (the reason for the use of the [] character here is a boring optimisation issue for consoles)
