### ISSUE TITLE
Achievements No Longer Working Xbox Series X, Downloaded Through Gamepass

### ISSUE THREAD

**Issue by AlexAWyatt** [TerryCavanagh/diceydungeons.com#2930]
Last achievement unlocked 10 days ago, none since despite getting in game challenge rewards for completing 2 and 3 elimination rounds, 2 parallel universe rounds, playing as a furry dice, and possibly others , not sure. Feel free to contact and I will share gamertag.

**Comment by AlexAWyatt** [comment]
Last achievement unlocked 10 days ago, none since despite getting in game challenge rewards for completing 2 and 3 elimination rounds, 2 parallel universe rounds, playing as a furry dice, and possibly others , not sure. Feel free to contact and I will share gamertag.

**Comment by TerryCavanagh** [comment]
We've figured this out and fixed this! The update should be live by tomorrow.
