### ISSUE TITLE
You can't unshock Rocket Launch versus Beatrice in rare scenario

### ISSUE THREAD

**Issue by StefanJonceski** [TerryCavanagh/diceydungeons.com#2931]
If Beatrice has activated Parallel Universe shock, and I'm advancing the Rocket Launcher from a 6 to a 5 if the Rocket Launcher gets shocked.

I can't unshock it with the "Unshock" button

Here's the following clip:

https://user-images.githubusercontent.com/79204909/178950516-b52bf3f5-88e5-4090-8f0e-391753ed29a7.mp4

**Comment by TerryCavanagh** [comment]
This one appears to be a touch related bug that should no longer be happening in v2.1!
