### ISSUE TITLE
Game crashes on Thief Bonus Round if you're transformed into a bear and get "The Thief" rule

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2935]
Surprised this hasn't come up before!

![Screenshot_20220717-110753](https://user-images.githubusercontent.com/2874150/179552121-5dce3050-9e56-418f-9410-10e3e09057c3.jpg)

![Screenshot_20220717-110858](https://user-images.githubusercontent.com/2874150/179552129-b589b969-4a79-491b-8172-d0c0dffd0090.jpg)

**Comment by TerryCavanagh** [comment]
Turns out it *has* come up before, sort of: https://github.com/TerryCavanagh/diceydungeons.com/issues/1331

**Comment by musicalentropy** [comment]
I was about to add that issue here since it has just happened for me on iOS :)

**Comment by TerryCavanagh** [comment]
Think I've fixed this by adding an exception to Finders Keepers and Bear overlap, but I'm entirely sure why this was crashing before, so I don't know!

**Comment by TerryCavanagh** [comment]
Ah - a little more digging, and I figured out why this was really crashing. Fixed in v2.1.

**Comment by StefanJonceski** [comment]
@TerryCavanagh 

I've managed in the new branch to acquire the Thief rule -> transfer to a Bear.
