### ISSUE TITLE
Try subclasses

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#294]
Allow selection of slight variations of starting equipment for each class - depending on guilds you may have found, equipment, etc

**Comment by onetruepurple** [comment]
Warrior: Replace the Sword with the Two Handed Sword for more viable glass cannon builds over shield builds

Thief: Replace the Lockpick with the Pea Shooter/Longbow/Dodge maybe? for more viable Crowbar builds

Inventor: Replace the Hammer with the Shovel (?)

Witch: Replace all 6 spells with the Mystery Box

**Comment by TerryCavanagh** [comment]
Done! (sort of :D )
