### ISSUE TITLE
Russian localisation issues (Reunion + a few things in the base game)

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#2942]
* Bonus Episodes screen - text bleed on the Halloween Special button
![image](https://user-images.githubusercontent.com/26709843/179739466-5a4458a4-ccb9-462a-9c54-365a3d3765f3.png)

# Reunion
## Major issues
* Ancient Terror's Haunt descriptions should be "Наложить одержимость|на [haunt]2 кубика" instead (right now it translates to "inflict 2 haunt on a dice").
![image](https://user-images.githubusercontent.com/26709843/179768668-4e431d18-c283-479f-b3bd-131daee2284f.png)
    * Same with Jack o'Lantern - should be "Наложить одержимость|на [haunt]<d6> кубика" instead of "Наложить на кубик|одержимость [haunt]<d6>"
* Broken Sword should be translated as "Нанести [sword]<d6> урона|Больше[;] если ослаблено..." (right now it basically says "Deal X damage, more if Weaken...")
![image](https://user-images.githubusercontent.com/26709843/179819096-37839190-b33f-4e92-a3da-1c037814d771.png)
* Cartwheel's second line gets overridden by the "(destroyed when used") text
![image](https://user-images.githubusercontent.com/26709843/179758399-0b548ff4-e4f6-4dbb-a3f6-b26fc6fd78a6.png)
* Enthrall description starts with a lowercase letter
![image](https://user-images.githubusercontent.com/26709843/179770454-68753969-09be-4d34-a6d9-4b2139d8ef77.png)
    * Also, Acorn Shield starts with a lowercase щ, should be Щ
* Guard Pass is wrongly translated, should be "Проход гарда" instead of "Пропуск охранника".
* Ice Cream Headache: description should be "Заменить ячейки кубиков|на [ice]2 предметах"
* Jester Technique is translated as "Навыки Шутника" and not "Навыки Шута".
* Polar Storm says "закончил", which is not gender-neutral. Should be "закончено".
* Roundhouse Kick should say "[85%]Нанести [sword]<double>[;] отключается[;]|[85%]если кубик перебрасывается"
* Rusty Sword still uses old description. Should be: "Нанести [sword]<d6>[;] удвоить[;]|если у тебя меньше|50% здоровья"
* Shoryuken is translated as "Сюрикен" (Shuriken). Should be either "Шорюкен", or "Серюкен", or "Удар дракона" (Dragon Punch).
* Spatula@coin should just say "Перевернуть монету" instead of "Подбросить и перевернуть монету" (which means "Toss and flip a coin", which could be interpreted as "toss an extra coin, and flip this coin")
* Vacuum Potion should be "Зелье Пылесоса" instead of "Вакуумное зелье".
* Wolf Puppy Scratch should be "Царапанья Волчонка" instead of "Почесывания Волчонка".
* Jester's Equipment? cards have this weird syntax where the description just repeats the item's name in accusative. Some of the the descriptions are straight up untranslated. I'd suggest changing these description lines to just "Экипировать предмет" (Equip this item).
![image](https://user-images.githubusercontent.com/26709843/179816386-3bad41a5-67a1-4780-acde-18ee28c3923d.png)
    * Some of the Equipment? status effect descriptions include the item name, for some reason, and sometimes even in untranslated form
    ![image](https://user-images.githubusercontent.com/26709843/179835005-5ff50995-87b3-4409-9d9f-b4b7abf9ec64.png)
* Luckpenny's "Лишняя монета" should be changed to "Запасная монета" to be consistent with Spare 1-6 items that say "Запасная 'единица'/'двойка'/etc."
* Pirate's last words don't really rhyme that well. Haven't come up with a better rhyme yet though.
* Rhino Beetle's last words also don't really rhyme. You could switch some words around and do: "ФРР. Ф-Е-Е. ФУ. ФО-О-О. СКОРО ТЕБЯ НАСТИГНЕТ РО-О-ОК."
* Scathach uses he/him?? Last words lv. 1 should be changed to: "В подземелье шепчут твое имя, так что я проснулась и|взялась за свое доброе копье. Пора погибнуть, дружище."
* Inventor uses and is referred to by he/him.
* Aoife's first words lv. 3 should probably say "Малявка" instead of "Малыш". Малыш is usually used when referring to a little boy, so gender-neutrality should be preserved when referring to the dice cast.
    * Magician's "кто к нам пришел" should be changed to "кто снова здесь"
    * Dryad's "дружок" in the last words should be changed to "приятель" or "дружище"
* Fireman should say "чуток разогреться" instead of "чуток размяться" to preserve the fire pun.
* Banshee's last words don't have the "Б" at the end.
* Headache tooltip name uses a space instead of an underscore
![image](https://user-images.githubusercontent.com/26709843/179831291-d737d88a-d5ea-4913-9f9f-a18468360c3f.png)
    * Also, the description is wrong and should say "На этом ходе заменить ячейки|<value> предмета(ов)."
* Crucihall tooltip name uses a space instead of an underscore
![image](https://user-images.githubusercontent.com/26709843/179836170-78714560-35ec-444f-8371-df39d80fe806.png)
* First Mover status effect is untranslated (should be "Первопроходец", "Следующая монета будет золотой")
![image](https://user-images.githubusercontent.com/26709843/179831781-c58d08a5-ff1e-44a0-bac5-25ee4ca0f695.png)
    * Costume Change name is untranslated (should be "Переодевание")
    ![image](https://user-images.githubusercontent.com/26709843/179833962-4bd2fdc6-1ddd-44fc-8cb1-53809a60c945.png)
    * Terrified ("Ужас", "Сбегаешь из битвы через <value> ходов.")
    ![image](https://user-images.githubusercontent.com/26709843/179834222-9868e4a9-8662-4503-8ca9-97478bb5bfcf.png)
    * Rose Shield name ("Щит розы")
    ![image](https://user-images.githubusercontent.com/26709843/179834270-6f3b2f3e-1b9e-4ce4-9364-116d45b2b35d.png)
    * Trust Fund name ("Трастовый фонд")
    ![image](https://user-images.githubusercontent.com/26709843/179834325-e5b53e11-8e41-463a-8af8-c9249866594d.png)
    * Burn Next Turn name
    ![image](https://user-images.githubusercontent.com/26709843/179834804-d3ff2b49-5b1a-4b64-9a97-b4ea12404a1c.png)
    * Alternate Shock status effect header is untranslated, should be "Альтернативный шок"
    ![image](https://user-images.githubusercontent.com/26709843/179833122-fef92a30-5a7e-4521-9778-bee55e368d08.png)
    * Victory Point ("Балл победы")
* Victory Point has a very uninformative description. It just says "For unlocking the Omnislash limit break"
![image](https://user-images.githubusercontent.com/26709843/179834475-336f62ff-cda3-4cd2-a0c3-90e15a9f4073.png)
Because of this comma instead of a pipe
![image](https://user-images.githubusercontent.com/26709843/179834609-949b121f-79cd-46bb-b6f9-a490310f8d79.png)
* Coinflip Freeze status effect description is wrong, should be "Превращает след. выброшенную монету в решку.", and Freeze All should be "Превращает все монеты в решки."
* Haunted status effect should be translated as "Одержимость" instead of "Одержим" to maintain gender neutrality
* Coinflip Haunted status effect description is the same as the dice one, and says "перебрасывает случайный кубик" instead of "перебрасывает случайную монету"
* Sting status description should say "наложить на себя [shock]шок" instead of "наложить на себя шок [shock]<value>"
* CAW status description should say "наложить на себя [weaken]слабость" instead of "наложить на себя слабость [weaken]<value>"
* Steinway Axe jinx name is untranslated
![image](https://user-images.githubusercontent.com/26709843/179835312-11355b12-3be5-484f-a720-936cb8768ad3.png)

## Minor issues
* Angel Ring says "Recover health [heal]2" instead of "Recover [heal]2 health", which is inconsistent with how every vanilla item is translated
![image](https://user-images.githubusercontent.com/26709843/179742036-08781aea-c4d5-4c34-9d3a-e8d5f43621c8.png)
    * Same happens in Bench Press (says "Deal damage X" instead of "Deal X damage"); Confusing Crystal, Dangerous Fumes & Faintest Sunlight ("Inflict confuse [star]" instead of "Inflict [star]confuse"); Defensive Stance, Lift Off!, Paper Armor, Pixie Flame, Poisoned Apple, Polar Storm, Ragnarock, Rest Day, Rose Shield+, Shiver, Slime Blaster, Slime Shooter+, Slime Sword, Slimepick, Slimey Roll, Slimey Spanner, Slimfliction, Sloop+, Slop, Tomatoes, Toxic Asset
    * Also happens in the Toxic status description
    ![image](https://user-images.githubusercontent.com/26709843/179832914-a587a887-7b3a-4ed0-89ee-792203f1aa9e.png)
* Bear Claws don't have a comma between the first and second lines
![image](https://user-images.githubusercontent.com/26709843/179743229-e77f0dd3-6495-4090-9159-f0c85e0c552c.png)
    * Same with Beetle Bash, Deep Freeze, Dazzler, Inky Crystal, Inky Juggle, Star Crystal, Worker Bee, Wildfire, Uppercut
* Broken Glass is currently translated as "Deal X damage for each dice rolled by the enemy", which can be interpreted as "deal X damage for each dice rolled by the enemy so far". Should probably be changed to "Нанести [sword]2 за каждый|кубик у врага".
![image](https://user-images.githubusercontent.com/26709843/179753627-905e013c-eeae-42fa-9330-9966cb9d0b8e.png)
* Burn Rate is translated *too* accurately as a finance term (Среднемесячные затраты), so it's no longer a burn joke. I'd suggest changing it to "Прогоревший банк".
    * Cold Hard Cash suffers from the same problem, being translated too accurately (Живые деньги), and not being an ice joke. Should probably be changed to "Замороженный счет".
* Chef's Kiss is translated as "Delicious!" (Объедение!), which doesn't really represent the item's effect. I think it should rather be "Вишенка на торте" (Cherry on Top).
* Dazzler is a reference to the Dazzler skill from Persona 5. It's called 目眩し in Japanese, and Google says that translates to Dizziness (which correlates to the skill inflicting a Dizzy status effect in P5), so it'd probably be more accurate to translate it as "Головокружитель". Right now it's translated as "Ослепление" (Blinding, or Dazzling), which sounds more related to the Blind status (Слепота) than Shock.
* The Contestant Technique cards are translated as "Навыки <contestant name>", which is closer to "<contestant> Skills" than "Technique". Should probably be "Техника <contestant name>" instead.
* Queen Bee: should be changed to "На след. ходе|переключиться на шок из|[quote]Параллельной вселенной[quote]  "
* Red Beard is translated as "Рыжая борода" (Ginger Beard) instead of "Красная борода"
* Tax Evasion?'s name + Dark Shadow and Garlic Bread's descriptions are untranslated (not that big of an issue because they don't appear in Reunion).
* Omnislash is not translated anywhere. It's always referred to as "Omnislash", in English, which is probably not ideal for those who *don't* know how to read and pronounce that.
* Alchemist's last words could sound more "natural" this way: "Ладно, это не сработало, но... Стой! Вернись!|У меня ещё столько новых зелий, тебе стоит посмотреть!"
    * Also, for Baby Squid: "Ну вот, теперь всё как раньше!|Бросили кубики, сразились!||Ты и другие кубики по-прежнему|одни из моих любимых врагов."
* Madison's first words lv. 2 has an extra space after "возможно" and before the comma.
* Stereohead's last words have an extra space on the last line
![image](https://user-images.githubusercontent.com/26709843/179828724-0d8f1404-f939-46a6-8bb9-61b1ba42b3ef.png)
Also, "А ты наверху ничего не слышал|о [quote]стриминге[quote]?" should be changed to "А вы с друзьями наверху ничего не слышали|о [quote]стриминге[quote]?", to maintain gender neutral language.
* Scorch needs a linebreak
![image](https://user-images.githubusercontent.com/26709843/179833351-6b88f383-b81a-4aea-a163-92e46ccd7a1a.png)
    * Also, Delay
    ![image](https://user-images.githubusercontent.com/26709843/179833444-d9ce39e8-0e0d-4022-9994-ff27fa00dc76.png)
    * Coinflip Fade
    ![image](https://user-images.githubusercontent.com/26709843/179832386-1f96bde8-a033-4fda-aa19-6779472fc3f2.png)
    * Password
    ![image](https://user-images.githubusercontent.com/26709843/179833651-ec6b9347-326a-4ecb-a90d-3203452081da.png)
    * Most of the guest item statuses (but that's also an issue in English, so I don't know if that's something that *should* be fixed in the localisation)

## Text bleed
* Boom and Bust
![image](https://user-images.githubusercontent.com/26709843/179770193-08430a49-2c53-4c4e-895b-69bce0447a67.png)
* Endurance Training
![image](https://user-images.githubusercontent.com/26709843/179770076-ebfa5b20-8d6d-4dbc-b391-8d08d8ec8465.png)
* Hostile Takeover
![image](https://user-images.githubusercontent.com/26709843/179774591-41b05d1f-051b-4246-b5ea-e235cdc95332.png)
* Pugnacious Sword
![image](https://user-images.githubusercontent.com/26709843/179797164-4b29f53f-47df-4276-8a8d-d18992a282c7.png)
* Wicker Man Potion
![image](https://user-images.githubusercontent.com/26709843/179815176-36824131-4424-4f41-b65e-f1a7a3d3419e.png)
* Witch Technique
![image](https://user-images.githubusercontent.com/26709843/179815358-6c8f4411-a2a1-4a33-a550-8c3865b3947a.png)
* Zlonk+ (could replace "шестерку" with 6)
![image](https://user-images.githubusercontent.com/26709843/179815959-343df76f-8313-4e27-bd97-510bf0bc04af.png)
* Warrior Reroll "no more uses this turn" description (could replace with "жди следующего хода" to avoid using excessive shrinking)
![Screenshot_371](https://user-images.githubusercontent.com/26709843/179839666-71884c36-e27d-47e4-a4d3-97703a6ddeb1.png)
* Workout Card description
![Screenshot_373](https://user-images.githubusercontent.com/26709843/179839840-8ce7b1a1-32be-4b40-8397-fa66a91e611a.png)
* Password panel
![Screenshot_378](https://user-images.githubusercontent.com/26709843/179840202-b957a6de-18ab-41b2-b45a-8d8063ccca01.png)
* Burn cost should be changed from "Затраты X" to "Цена X", because the text will overlap when multiple dice get burnt
![Screenshot_379](https://user-images.githubusercontent.com/26709843/179840406-d6fc10f7-2bc6-4ae4-a4c3-f16bd2be9e7a.png)
* Witch episode
![Screenshot_380](https://user-images.githubusercontent.com/26709843/179840458-6c101ba4-bdd6-45a0-b35c-bfb0d1b10784.png)

## Low priority re-translation suggestions
* Lightning Kick (Пинок молнии) could be changed to Молниеносный пинок or Громовой пинок to sound more intimidating.
* Sheer Will is translated as "Абсолютная воля" (Absolute Will). Could be "Чистая воля", but maybe that was a stylistic choice.
* Sloop and Slop could be changed to "Хлюп" and "Хлоп" respectively to be closer to the Jester card naming scheme (Boop & Bop).

# Base game
## Mistranslations
* Bear Maul should be "Медвежье растерзание" instead of "Медвежье терзание".

## Major issues
* Disco Ball? should say "если враг **выброси**т**" instead of "выброси**л**". The upgraded version doesn't have that issue
![image](https://user-images.githubusercontent.com/26709843/179768542-a78cafb5-a2a6-4ec0-80df-34e6a2e862ab.png)
* Buster Sword is translated as Buster's Sword (Buster as in, the dragon boss), instead of being a clear FF7 reference. I initially didn't bring this up because I thought it'd be too late to change a translation of such a fundamental item, but honestly, it's better late than never. I'd suggest changing it to "Бастер-меч". Ultima Weapon *could* be changed to "Оружие Ультима", but the current translation, "Окончательное оружие" (Ultimate Weapon), seems recognizable enough if you already know what Buster Sword refers to.
    * Missing Score should rather be "Недостающий счет" instead of "Пропадающий счет".
    * Premium Heart could be changed from "Золотое сердце" to "Премиум-сердце" to be closer to being a recognizable FF7 reference.
* Overwhelm should be "Сокрушение" or "Крушение" instead of "Преимущество".
* "Flee in X turns" text goes out of screen bounds a little bit
![image](https://user-images.githubusercontent.com/26709843/179838890-ac5ce1f0-c8a2-4c15-a8f5-a66d6a1773b6.png)
* The "Created by" section in the Credits should be "Создатели:" instead of "Создатель:" (because the latter is singular)
* Relaxed Mode is translated as Lazy Mode, which comes off as a bit... rude? Could be "Расслабленный режим" instead of "Ленивый режим"
* Inventor's char description should say "увлеклась" instead of "увлекся"
* I've recently learned that Jester uses they/them in English, but they're translated as he/him because the word Шут is masculine. Should that be changed?
* Yolanda's "bought everything" dialogue says "Ого, ты купил всё!", where "купил" is strictly masculine. Could be changed to "Ого, давненько у меня всё не раскупали!" (Wow, it's been a while since I've sold out *everything*), as a suggestion.

## Minor issues
* Backstab should probably say "+1 за каждое использование предмет**ов**" instead of "предмет**а**". A few people got confused as to whether it increases damage with other equipment uses, or whether it deals more for each time you use Backstab itself.
* Berlin Key should probably be changed to "Превратить случ. кубик в|<d6>[;] вернуть кубик" to make the description more clear.
![image](https://user-images.githubusercontent.com/26709843/179744316-8585d9f4-36dd-4a08-9ae2-ba221abe7855.png)

## Small nitpicks
* I don't know if it's *wrong* that Boop was translated as Be-e-ep! (Би-и-ип!), but it feels unfaithful to the original, I guess? Also, Bop is translated as Thwack (Тумак), so Boop and Bop are absolutely not related to each other in the localisation. Maybe it's a stylistic choice, or maybe I'm missing something, I don't know. I'd personally translate them as "Буп" and "Бам", or maybe even "Буп в носик" and "Бам по носу" for extra flavour.

**Comment by TerryCavanagh** [comment]
Got a few more of these, new locale files here if you're interested!

[diceydungeons_ru.zip](https://github.com/TerryCavanagh/diceydungeons.com/files/9152270/diceydungeons_ru.zip)
[reunion_ru.zip](https://github.com/TerryCavanagh/diceydungeons.com/files/9152271/reunion_ru.zip)

Here are the issues that I can't do right now:

* Bonus Episodes screen - text bleed on the Halloween Special button **(This is a bug with the levelpack selection screen that affects several languages, I'll need to make a separate issue)**
![image](https://user-images.githubusercontent.com/26709843/179739466-5a4458a4-ccb9-462a-9c54-365a3d3765f3.png)

* "Flee in X turns" text goes out of screen bounds a little bit **(Need to make time to fix this manually)**
![image](https://user-images.githubusercontent.com/26709843/179838890-ac5ce1f0-c8a2-4c15-a8f5-a66d6a1773b6.png)

* Relaxed Mode is translated as Lazy Mode, which comes off as a bit... rude? Could be "Расслабленный режим" instead of "Ленивый режим" **(This is an excellent note, but I will also need a translation for the string "В ленивом режиме у всех врагов на 25% меньше здоровья.||Ленивый режим можно включать и выключать по желанию[comma]|и он никак не сказывается на прогрессе и достижениях.")**

* Steinway Axe jinx name is untranslated **(This appears to be a bug)**
![image](https://user-images.githubusercontent.com/26709843/179835312-11355b12-3be5-484f-a720-936cb8768ad3.png)


The following issues are all things where a translator needs to tell me how to make the change:

* Inventor uses and is referred to by he/him.

* Burn Next Turn name
![image](https://user-images.githubusercontent.com/26709843/179834804-d3ff2b49-5b1a-4b64-9a97-b4ea12404a1c.png)

* Omnislash is not translated anywhere. It's always referred to as "Omnislash", in English, which is probably not ideal for those who don't know how to read and pronounce that.

* I've recently learned that Jester uses they/them in English, but they're translated as he/him because the word Шут is masculine. Should that be changed? **(Absolutely, yes, if this is possible! It seems this is not possible in some languages and I assumed that was also the case with Russian)**

**Comment by TheMysticSword** [comment]
Cool! I've checked the files, and here are a few more things that should be changed + translations for the things in your latest comment:
* Roundhouse Kick - The `<double>` part is missing because Markdown ate it, so now it doesn't tell how much damage it will deal. It should be: `[85%]Нанести [sword]<double>[;] отключается[;]|[85%]если кубик перебрасывается`
* Rusty Sword - also missing the damage symbol, should be `Нанести [sword]<d6>[;] удвоить[;]|если у тебя меньше|50% здоровья`
* Bag of Swords and Sunlight Shield now start with lowercase characters, should start with `Каждый` instead of `каждый`.
* The `A spare coin[;] always heads` line in Luckpenny should also be changed to `[85%]Запасная монета[;] всегда орел` (right now only the name of the item is fixed)
* Headache tooltip `Change the slots on <value> item(s) this turn.` is still wrong, should be `На этом ходе заменить ячейки|на предметах: <value>.`
* Burn_Next_Turn name should be `Ожог_на_след._ход`
* Broken Sword_upgraded's description should be `Нанести [sword]<d6> урона[;] еще|больше[;] если ослаблено...`
* The `Use all equipment and|dice to inflict [stun]Stun` line could be changed to `[95%]Используй все|[95%]оснащение и кубики[;] чтобы|[95%]наложить [stun]Оглушение`. Right now all of the verbs in it use infinitive, which sounds weird.
* Relaxed Mode strings:
    * Description: `В расслабленном режиме у всех врагов на 25% меньше здоровья.||Расслабленный режим можно включать и выключать по желанию[comma]|и он никак не сказывается на прогрессе и достижениях.`
    * Enabled: `Расслабленный режим включен`
    * Disabled: `Расслабленный режим выключен`
* `Edit Progress` line should be `[90%]Изменить прогресс` to avoid text bleed
    * `Reset Progress` should be `[90%]Сбросить прогресс` for the same reason
* Omnislash could be translated as `Омнислэш` for an accurate transliteration
  
I'm also working on fixing some of the Reunion dialogue, and I need to clarify a few things:
* Lady Luck says "[welcome]...to the DICEY DUNGEONS REUNION SPECIAL!" fully in English. Should that be changed to a more localised version, e.g. `...в СПЕЦВЫПУСК DICEY DUNGEONS "СНОВА ВМЕСТЕ"!`
![image](https://user-images.githubusercontent.com/26709843/180198003-eac8812b-d1db-48a0-8526-305b3ce268b1.png)
* Jester - singular they/them isn't really a historical thing in Russian (as opposed to how widely it was used in English for a long time), so some people say that "it's not grammatically correct", and that "it sounds unusual", but a lot of people are pushing for a change and incorporating it into their language. I've also seen a way of translating non-binary characters by paraphrasing sentences in a way that does not use gendered language (e.g. passive voice, impersonal passive). I could either use the former, or could mix the two and use the latter for most of the dialogue, and use the former when it's impossible to structure the sentence without gendered language.

**Comment by TheMysticSword** [comment]
I've finished changing the Jester lines, and also fixed several other dialogue text during that, hopefully didn't miss anything. Too many changes to list, so I'll just send my files.  
  
Base game:
[introductions.csv](https://github.com/TerryCavanagh/diceydungeons.com/files/9169506/introductions.csv)
[strings.csv](https://github.com/TerryCavanagh/diceydungeons.com/files/9169653/strings.csv)
[cutscenes.csv](https://github.com/TerryCavanagh/diceydungeons.com/files/9169655/cutscenes.csv)

Reunion:
[extracutscenes.csv](https://github.com/TerryCavanagh/diceydungeons.com/files/9169725/extracutscenes.csv)

**Comment by TerryCavanagh** [comment]
Thank you so much for these - everything's merged now!
