### ISSUE TITLE
If you activate Call for Backup while selecting a workout card, it causes problems

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2948]
![Dicey Dungeons Jul 22 11-29-54AM](https://user-images.githubusercontent.com/2874150/180420970-838cac6e-0795-4d26-b649-88b09feb46ab.png)

**Comment by TerryCavanagh** [comment]
At the start of the next fight, I had lost all my equipment:

![Dicey Dungeons Jul 22 11-31-40AM](https://user-images.githubusercontent.com/2874150/180421092-799a696c-395b-40d1-b028-12ce0e350a8d.png)

**Comment by Matz-42** [comment]
Should probably just prevent limit breaks from being used while selecting a work-out card, while it might not game break as much, other effects like rolling 3 extra dice could also do weird stuff.

**Comment by mrcdk** [comment]
Fixed! It won't be possible to trigger a limit break while selecting a workout card. I could not reproduce the lose of all equipment after the fix either.

**Comment by TerryCavanagh** [comment]
Fixed! I'll do some more testing to be sure, but I think this means I can quietly add the "Jester Technique" card to the Warrior Reunion episode in the next patch 😄
