### ISSUE TITLE
Upgraded cards lost after Call for Backup limit break

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2951]
![Dicey Dungeons Jul 25 12-50-24PM](https://user-images.githubusercontent.com/2874150/180771472-c02fd422-f70c-42ef-ab05-6b706f025574.png)

I had previously upgraded Crunch, but it was weakened during the fight with Marshmallow. I think what happened is that I activated the limit break while the card was weakened, and when my inventory was recreated for the Warrior, it gave me the normal version back instead of the upgraded version.

**Comment by TerryCavanagh** [comment]
(did quite a lot of additional testing after this, and this is the only issue related to Call for Backup that I could find)

**Comment by mrcdk** [comment]
This has been fixed!
