### ISSUE TITLE
Snap and Shield Bash as Jester can create infinite dice

### ISSUE THREAD

**Issue by StefanJonceski** [TerryCavanagh/diceydungeons.com#2952]
I spotted this one on the Discord channel, and here is the following clip:

https://user-images.githubusercontent.com/79204909/180780124-31457a4c-d1bc-4f0c-803d-d968229815f6.mp4

**Comment by mrcdk** [comment]
This has been fixed! If you `Discard` or `Snap!` equipment with a dice assigned to a slot it will return it back to the stack

**Comment by TerryCavanagh** [comment]
Excellent, thank you!
