### ISSUE TITLE
Reunion sorceress: hookshot+deck of wonder causes game to hang

### ISSUE THREAD

**Issue by marktengi** [TerryCavanagh/diceydungeons.com#2956]
The sorceress used hookshot and then deck of wonder. The deck of wonder was briefly replaced by another card, but then the deck of wonder card came back with a countdown of 0 and stayed there. I couldn't do anything to get the game to proceed.

Platform: switch

![2022072720343200-79B02B5BA372774567A5DE1F7B872776](https://user-images.githubusercontent.com/62948358/181586202-424efa97-a5ea-4de4-aff7-438a4934c9fa.jpg)

**Comment by TerryCavanagh** [comment]
Thanks! This one is fixed already in the upcoming patch!
