### ISSUE TITLE
[Translation] There is no word for "item" in the Japanese Backstab text.

### ISSUE THREAD

**Issue by naokiy** [TerryCavanagh/diceydungeons.com#2958]
![image](https://user-images.githubusercontent.com/6022981/182648406-04755966-a1d6-40f5-9b4b-cc0b675596d3.png)
![image](https://user-images.githubusercontent.com/6022981/182648428-2af75a13-499f-42ee-bc2e-1cc50c7a5976.png)

![image](https://user-images.githubusercontent.com/6022981/182656449-2913c1b6-a0cd-4d9f-864a-f02aae422fd5.png)
![image](https://user-images.githubusercontent.com/6022981/182656615-b23d1797-e8ab-451b-9333-32a67f8c80ce.png)

Japanese Backstab has similar text ("**使うごとに+:hocho:1**") (Add 1 on each use) to Japanese Electromagnet  ("**使うごとに+2**") .
However, the behavior is different.
Electromagnet damage is increased only when Electromagnet is used, but Backstab damage is increased when other equipment is used.
This difference cannot be read from the Japanese text.

Japanese Backstab should be "**装備を使うごとに+:hocho:1**" (Add 1 on each equipment use).

**Comment by TerryCavanagh** [comment]
Aha, thank you! That's an easy fix for the next patch!

**Comment by TerryCavanagh** [comment]
Fixed in v2.1.
