### ISSUE TITLE
Activating the Call for Backup Robot quickly at the start of the turn breaks the game mechanics

### ISSUE THREAD

**Issue by StefanJonceski** [TerryCavanagh/diceydungeons.com#2963]
This problem emerges if you activate it before the UI buttons appear, and you can't use Equipment as well after that.

Here is the following clip:

https://user-images.githubusercontent.com/79204909/182880099-8e013d4c-3fad-45ec-92c4-d56ecc94e7f9.mp4

**Comment by StefanJonceski** [comment]
Yup, it occurs in normal gameplay too.

**Comment by TerryCavanagh** [comment]
Fixed!
