### ISSUE TITLE
Crystallina uses dice suboptimally

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#2975]
I just watched Crystallina roll a six, four, four, and six, on the first turn. Used a six to unlock the first crystal weapon, which was Power Crystal. Used a four on Power Crystal, and got Re-Equip Next. Then ended turn without using the other six to unlock another crystal equipment.

**Comment by TerryCavanagh** [comment]
Ah - these kind of AI redesigns are not planned at this point in the game's life (see also https://github.com/TerryCavanagh/diceydungeons.com/issues/2974, which I just closed) - with quite a lot of work it might be possible to fix things at this level, but the game is stable and this risks breaking things and potentially even throwing off the balance.
