### ISSUE TITLE
Guild of Power has no downsides

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#302]
It offers you one extra die in exchange for one piece of equipment starting out stunned. At worst, this can stun equipment you need to use and require you to put your extra die in - resulting in the same state as if you had never obtained the guild's effect - but at best, this is free firepower. You'd have no reason not to join this guild if you see it.

All other guilds have clear downsides which cannot be negated: Guild of Sacrifice removes dice-tweaking, Guild of Assassins removes equipment stealing, Guild of Innovators sacrifices more equipment per turn, and Sorceress Guild removes control over one spell slot.

**Comment by TerryCavanagh** [comment]
Yeah, hmmm

I really like the downside for this guild - having a randomly stunned piece of equipment is fun, but I need to figure out an upside that balances it. Maybe one burning dice, I dunno!

Using weaken instead of stun is cool too - might just do both tbh!

**Comment by joshtriplett** [comment]
Weaken would work, but seems more directly counter to the stated purpose of the guild ("power").

**Comment by TerryCavanagh** [comment]
Trying a burning dice for v0.9. Thanks for the suggestions!
