### ISSUE TITLE
Data for v0.8 balance

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#303]
I've been keeping a record of my Wins/Attempts for v0.8, with notes. Perhaps it will be useful for balancing purposes?

**Warrior** hard: 1/1 (Ye Olde Shielde Builde)

**Thief** hard: 0/4
Thief is harder than it used to be. It feels like I'm getting Dagger+ later than I used to; is that true? But Thief is unplayable in v0.8 due to #269, so I'll set it aside for now and come back for v0.9.

**Inventor** hard: 1/2
Burrower is awesome. And in general I love the new elemental system!

**Witch** normal shock: 3/8 (defeated Cornelius, Crime Boss, Guardian)
Witch normal fire: 0/5
Witch normal ice: 0/2
Witch hard: 0/10

Shock seems to be the only viable choice for Witch. I'd love to play a fire witch or ice witch, but shock is just so necessary, especially if you have to face Knight.

**Comment by TerryCavanagh** [comment]
These are great, and super useful! Thank you!

**Comment by alexirpan** [comment]
I haven't been tracking my stats as much, but I found Witch the hardest out of the 4 classes to beat on Normal. Perhaps I'm doing a bad build, but it feels like I'm always a bit too low on health and damage output. The guaranteed apple shop helps, but right now it feels like it shows up 1 floor earlier than I need it to.

My Witch runs either died to a Knight that built shield faster than I could clear it, or getting Silenced every turn by one of the 4 dice / 5 dice enemies (which forced me to roll a good spellbook on the first turn on be forced to run away.)

**Comment by YinYin-Falcon** [comment]
I've gotten through with fire witch twice. Shock seems to somewhat rely on stupid AI the way I see it (Knight for example only using shield bash despite being able to just focus on building the shield).

Only ice has too little footing with too few targets weak to it and too many benefiting from 1s. Let's see if freezing highest dice first will help.

**Comment by ncrecc** [comment]
Should old (< 0.12?) "thoughts" and "balance data" issues like these be closed?
