### ISSUE TITLE
Reroll Unused Dice Doesn't Reroll Die in Warrior Tweak

### ISSUE THREAD

**Issue by KevenDenen** [TerryCavanagh/diceydungeons.com#305]
Not sure if this is intentional or not, but if you want to hold a die back from the warrior's Reroll Unused Dice feature, you can put it in the warrior's Tweak slot. It will reroll all of the other dice, but not that one. Can be used to stop a die from being rerolled.

**Comment by ncrecc** [comment]
I'd say this is intentional, as it also doesn't reroll dice being stored in equipment like Shield Grip or Two-Handed Sword.

**Comment by TerryCavanagh** [comment]
Heya,

Thanks for the bug report!

This is intentional - it was an attempt to preserve an old behaviour that people liked in early versions, where you could store dice in equipment to prevent them from being rerolled. I'm not that happy with this and might redesign tweak in a later version.
