### ISSUE TITLE
Absorb Poison Issue

### ISSUE THREAD

**Issue by ElBosque19** [TerryCavanagh/diceydungeons.com#307]
This is less of a bug than a possible "broken design" issue. I know you changed damage immunities to resistances so that a certain elemental build would stand a chance against enemies with said resistances (ex: fire build against the dragon, poison against dire wolf). However, a poison build against the Guardian boss must completely redo their equipment in order to stand a chance (ex: i did a run-through with a poison build rogue with a poison needle, lockpick, lockpick +, posion slingshot, and detonator, and I think the only way to win with that build is to poison them enough to one-shot them with the detonator, which would take forever). I don't know that this is a major issue but I thought I'd point it out.

**Comment by TerryCavanagh** [comment]
Fixed. Guardian has retired. Thanks!
