### ISSUE TITLE
Crash when stealing weakened equipment

### ISSUE THREAD

**Issue by njvrzm** [TerryCavanagh/diceydungeons.com#314]
![image](https://user-images.githubusercontent.com/19716792/41690737-cc626836-74ab-11e8-844a-60ce87b5ce5c.png)

`Uncaught Error: Trying to create equipment "Healing crystal-" from template, but cannot find a matching template in equipment.csv.`

**Comment by TerryCavanagh** [comment]
Fixed! Thank you!
