### ISSUE TITLE
Witch spells can be triggered for free

### ISSUE THREAD

**Issue by njvrzm** [TerryCavanagh/diceydungeons.com#320]
If you place one spell on top of another and they have incompatible die requirements, you can trigger the overlaid spell without losing a die. For instance, place `Magic Missile` on top of `Ember` and place an odd die on it. `Ember` will trigger but the die will not be consumed.

Similarly, you can cast a two-die spell with only one die being consumed, if you place one die on it before placing an incompatible spell on top.

I'm assuming the basic behavior of stacking spells _isn't_ a bug, but if it is, this one is probably irrelevant :)

**Comment by njvrzm** [comment]
Note that you can do this with Magic Dagger as well, giving infinite damage potential.

**Comment by TerryCavanagh** [comment]
Fixed. Thanks!
