### ISSUE TITLE
Make Knight weak to electricity

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#323]
Action code is too much of a mess right now to do this, so for v0.9, gonna make the knight weak to ice instead. But it should be electricity!

**Comment by onetruepurple** [comment]
The Knight should probably get a 6th dice then, to make electricity stunlocking less effective than it is now.

**Comment by TerryCavanagh** [comment]
Done! (Also gave her a 6th dice)
