### ISSUE TITLE
Freeze Spell+ doesn't affect mirror dice

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#326]
To reproduce in Editor:
* Thief (lots more dice, lots more HP) vs. Wizard, Hard Mode
* If you steal Hall of Mirrors, use it, then wait until Wizard uses Freeze Spell+
* If Wizard uses Hall of Mirrors and you steal Freeze Spell+, use it

It will only freeze the dice you started with, not the extra dice from Hall of Mirrors.

See how I have 15(+1) but only 15 Frozen.
![screenshot 2018-06-23 10 54 36](https://user-images.githubusercontent.com/38589027/41810907-1d215da2-76d4-11e8-8a16-4034a5747dc6.png)

It's probably worth checking any other "foo ALL dice" equipment for the same problem.

**Comment by TerryCavanagh** [comment]
Fixed! Thanks!
