### ISSUE TITLE
Guild of Greed: Item named Tazer++ instead of Tazer+

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#327]

**Comment by TerryCavanagh** [comment]
Huh! Whatever caused this, it doesn't seem to happen every time. Can't replicate. I'll investigate more later.

**Comment by pace212** [comment]
So weird. If I see it again I'll take more careful note of the context. I wish I had taken a screenshot; I assumed it was a simple typo (:

**Comment by pace212** [comment]
I haven't tried reproducing this by actually playing the game, but I think I found the bug in the code. I must have misremembered when I guessed Tazer++ came from a chest, because looking at the code, it looks like it'll only happen on level up.

When you join the guild, it eagerly sticks a + on all the LevelUpRewards:
```
states_Guildstate.join = function(g) {
	Game.player.guild = g;
	if(g == "power") {
		Game.player.dice++;
		Game.player.innate.push("shockcurse");
	} else if(g == "greed") {
		Game.player.innate.push("cursecurse");
		var _g1 = 0;
		var _g = states_LevelUpScreen.leveluprewards.length;
		while(_g1 < _g) {
			var i = _g1++;
			if(states_LevelUpScreen.leveluprewards[i].type.toLowerCase() == "equipment") {
				if(!haxegon_S.isinstring(states_LevelUpScreen.leveluprewards[i].rewardname,"+")) {
					states_LevelUpScreen.leveluprewards[i] = new elements_LevelUpReward("equipment",states_LevelUpScreen.leveluprewards[i].level,states_LevelUpScreen.leveluprewards[i].rewardname + "+",states_LevelUpScreen.leveluprewards[i].musttake);
				}
			}
		}
	}
```

...and then when you level up, it sticks another + on there:
```
states_PickupEquipment.openfromlevelup = function(_itemname) {
	states_PickupEquipment.returnscene = "levelup";
	if(Game.player.guild == "greed") {
		_itemname += "+";
	}
	states_PickupEquipment.itemname = _itemname;
	states_PickupEquipment.witchmode = false;
	if(Game.player.name == "Witch") {
		states_PickupEquipment.witchmode = true;
		states_PickupEquipment.spell = elements_Spellbook.createspell(states_PickupEquipment.itemname);
	}
	haxegon_Scene.change(states_PickupEquipment);
};
```

So I think the fix is to remove one of those two cases. 

In passing I noticed this:
```
var elements_Equipment = function(_type,_upgraded,_weakend) {
	if(_weakend == null) {
		_weakend = false;
	}
	if(_upgraded == null) {
		_upgraded = false;
	}
	this.create(_type,_upgraded);
};
```
Should that last line be: this.create(_type,_upgraded,_weakend);
?

**Comment by pace212** [comment]
Although the most robust fix would probably be to change openfromlevelup and its siblings to
```
	if(Game.player.guild == "greed") {
		if(!haxegon_S.isinstring(_itemname,"+")) {
			_itemname += "+";
		}
	}
```
because that would catch any other weird cases of ++ that may somehow crop up later

**Comment by TerryCavanagh** [comment]
Hah! That's some thorough bug hunting :D

Just adding a note that seems to supply a clue here:

![image](https://user-images.githubusercontent.com/2874150/41972019-65b65c16-7a08-11e8-8517-a27b69ecd208.png)

**Comment by TerryCavanagh** [comment]
Fixed! (I think. I'm pretty sure!)
