### ISSUE TITLE
There is no "Bear transform-"

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#332]
Uncaught Error: Trying to create equipment "Bear transform-" from template, but cannot find a matching template in equipment.csv.

edit: happened while using yoink+ on druid in the editor (and weakening them with their own card when yoink was weakened)

**Comment by pace212** [comment]
That's interesting, because I weakened Druid and he totally had Bear Transform-. It said "Do nothing" and it indeed did nothing when he used it.

Capitalizationpo? T vs. t?

**Comment by TerryCavanagh** [comment]
I think this due to bugs with Inventor Steal, which I need to look at properly soon. Thanks!

**Comment by YinYin-Falcon** [comment]
Inventor steal is fine. That was my one and only Bear run.

In this case I used a weakened yoink+, all pretty convoluted to begin with.

**Comment by TerryCavanagh** [comment]
Ah! Inventor steal and yoink are exactly the same thing, internally!

**Comment by TerryCavanagh** [comment]
I can't replicate this one - I suspect I fixed it while fixing some other inventory bugs. Closing for now, please feel free to make an new issue or reopen if you spot it again. Thank for reporting!
