### ISSUE TITLE
Yeti should be weak to fire

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#336]
Thematically, it seems like the yeti should have a fire weakness.

**Comment by TerryCavanagh** [comment]
Probably, but thanks to glass cauldron changes this time around, I had to give Yeti a Dice Gain innate, so Yeti doesn't have room for it anymore :(

Hmm. Closing this for now, but will think it over a bit more next time I do an enemy audit! Thanks!
