### ISSUE TITLE
Froze shocked spell slot as witch

### ISSUE THREAD

**Issue by Questioner42** [TerryCavanagh/diceydungeons.com#338]
I got shocked fighting a sorceress, and during the first frames of my turn (before I knew which slot had the shock effect), i pulled a six die into a Hall of Mirrors spell in the top left slot. As it turns out, that was the slot that got shocked. I think I actually got an extra die (not entirely sure), but the slot froze afterwards, displaying a half-transparent shock overlay over the normal spell, and not allowing me to interact with it. Casting a new spell in the slot still worked, though, and afterwards the game continued normally.

**Comment by TerryCavanagh** [comment]
This one is fixed now in an upcoming version!
