### ISSUE TITLE
When trying to grab overlapping dice the top-most dice isn't always the one the mouse grabs

### ISSUE THREAD

**Issue by FelixNemis** [TerryCavanagh/diceydungeons.com#339]

**Comment by joshtriplett** [comment]
I can confirm this.

One common way to end up with overlapping dice is if you have two effects that generate dice trigger at the same time. When this happens, and you go to drag the dice away, you grab a die beneath the visible one.

**Comment by TerryCavanagh** [comment]
Fixed!
