### ISSUE TITLE
Witch can lose dice if put in "cast" with no corresponding spell

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#341]
Another variation on the problem of dice falling into the wrong slot in the spellbook: if you have a blank space in the spellbook, and you drop a corresponding die into the "cast" slot, you just lose the die. Since it would have no effect, the spellbook shouldn't accept it, so that you can drop it into "Do 1 dmg" instead.

**Comment by TerryCavanagh** [comment]
Fixed!
