### ISSUE TITLE
Make sure Backstab can neverever be in the same screen as Spatula+ or Spanner+

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#344]
Spatula+ because it's reuseable, compatible with all dice, and returns another die.
Spanner+ because it's reuseable and putting 6 and another die in it gives you the same dice, which you can put in there again.

The point is that these items can be *infinitely reused* under the right circumstance. Consider that Backstab deals one damage per item usage. Infinite reusage can be converted through Backstab to *infinite damage*.

Perhaps just nerf backstab so reuseables don't apply? Or so that reuseables don't apply if they also return a die? Might be too much to fit in there.

Mainly in response to [Thief's ability to retain equipment gained from a stolen Mystery Box](https://github.com/TerryCavanagh/diceydungeons.com/issues/244#issuecomment-400520806). Not sure if Spatula or Spanner can be obtained from Mystery Box. Thief can also retain equipment taken via a stolen Yoink iirc.

**Comment by joshtriplett** [comment]
Spatula and Spanner can also be purchased and upgraded, so you can happen to find them in-game.

That said...I wonder if the *existence* of infinite-damage combos should be considered a bug, or simply a "hey, if you're both clever and get lucky with equipment sometimes you'll have that happen". As long as it isn't *common*, having an overpowered combo in the occasional game is reasonable in a roguelike.

**Comment by TerryCavanagh** [comment]
Fixed! I introduced the concept of multiuse versus reusable, and spanner and spatula are both multi use now. Thanks!
