### ISSUE TITLE
Lightning is overpowered

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#348]
Even with AI fixes planned in future, Lightning is just significantly more powerful than other status effects - Ice and Earth reduces attack power/effectiveness, fire gives extra damage, but lightning *reduces* your actual ability to use dice and equipment. It's a totally different axis.

I really like how this feels, though, so the solution might just be to make it a little less common for the player.

some interesting thoughts from pinknoodlehair on the dicecord:

>So I'm not sure this is even the right place for this but I'd like to say I think Electricity is a little OP for Witch. Electric Shock, when compared to the other two possible powers, seems to be overwhelmingly better in most scenarios and overall. When you consider one of the best other upgrades is Glass Cauldron, that makes the second best magic, Burning Light, become less desirable due to Burn and Freeze cancelling each other out. Meanwhile, Shock works with Glass Cauldron extremely well. 
>
>Additionally, Ice Shard is something I want to like but it seems to be the worst of the 3 choices. It's always capped at 5 damage at most compared to the other two that can always be at 6 meaning you will never output as much damage. The effect of turning a die into one with Freeze is situationally good for some things, but most enemies especially later on seem to actually thrive on low dice values especially one. Not to mention it simply does not work with the Burn as they cancel one another out. I don't think this skill is useless, but it's situational at best and detrimental at worst. 
>
>Meanwhile, Shock works in your favor pretty much all of the time except when the enemy has lots of dice or skills, but even then you are slowing them down and the ai seems to favor un-stunning themselves meaning that's one whole less die to worry about and crippling the enemy a lot more.
>
>So anyway, that's my opinion and I don't think any of them, even Ice Shard, is useless. I just wish Shock and Electric Shock in particular wasn't so overwhelmingly effective to the point choosing anything else feels like nerfing myself, while simultaneously shutting out another element because if you choose Fire, mixing it with Ice wont work, and vice versa.

**Comment by onetruepurple** [comment]
The easiest thing to do would be to give a dice cap on Lighting Shock, like MAX4 or even MAX3.

**Comment by TerryCavanagh** [comment]
The new AI has significantly nerfed shock, which is a good thing.

I'm going to leave this issue open for reference for now, since there are some useful thoughts here, but I consider this basically solved <3
