### ISSUE TITLE
Countdowns are getting reset when weakened

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#350]
This shouldn't happen

**Comment by TerryCavanagh** [comment]
Ditto things like electromagnet and lightning rod

**Comment by jepler** [comment]
Related: dragon boss's one-time use attacks keep reappearing when I weaken them using "bear roar"

**Comment by StefanJonceski** [comment]
@TerryCavanagh 

If you weaken enemies' Equipment with countdown they aren't resting, but vice-versa yours get a bit more countdown. Not sure if intended as a new fix.

https://user-images.githubusercontent.com/79204909/182863423-1b8901b5-8c9b-4d30-8ffe-3b0bf29854ce.mp4

**Comment by TerryCavanagh** [comment]
Ah, yep, looks like this isn't fully fixed! The player's countdown shouldn't increase in this situation. Thanks!

**Comment by TerryCavanagh** [comment]
Fixed!
