### ISSUE TITLE
Things to try with alternative cauldrons

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#352]
- Have Glass Cauldron roll a guaranteed 1 instead of a 6
 - Try a new cauldron that rolls even numbers or odd numbers
 - Make whatever Cauldron that rolls a guaranteed 6 have a player penalty - e.g. a burning six, or 1 damage to yourself, or something

**Comment by onetruepurple** [comment]
> Make whatever Cauldron that rolls a guaranteed 6 have a player penalty - e.g. a burning six, or 1 damage to yourself, or something

Roll a cursed six - the item has a 50% chance of getting cursed out when using that particular six on it.

**Comment by ncrecc** [comment]
Something like this:
![](https://media.discordapp.net/attachments/459100587296948255/459109248241106945/unknown.png)
but more cauldron-y? Could be called "low cauldron".

**Comment by ncrecc** [comment]
Glass cauldron now rolls a 1, even/odd cauldrons made it in as golden and silver cauldrons, bonus roll made it in but with the opposite effect, and high/low cauldrons are too boring. This can be closed now, though I'm interested to see whether "cauldron that always rolls a 6, but with a penalty" is still viable.

**Comment by TerryCavanagh** [comment]
Yeah, will probably need some weird cauldrons for Parallel Universe Witch :)
