### ISSUE TITLE
Fireman doesn't handle correctly frozen dice

### ISSUE THREAD

**Issue by carlito767** [TerryCavanagh/diceydungeons.com#353]
When Fireman's dice are frozen and one of previous values was even, the enemy tries to use the die with Fireball+:

![dicey dungeons fireman](https://user-images.githubusercontent.com/27714584/41997281-d1ce419e-7a57-11e8-9a1d-47d2af9f3470.gif)

**Comment by TerryCavanagh** [comment]
This is a *great* find, thank you! I think it gives some clues as to why the AI makes some decisions that make no sense - the AI phase is being triggered before the actual status changes.

**Comment by TerryCavanagh** [comment]
Fixed!
