### ISSUE TITLE
Can walk over apple

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#355]
![](https://i.frogbox.es/kj0)
From the level layout it seems like the apple is supposed to be a forced heal.
The apple was still there when I returned to the map.

**Comment by joshtriplett** [comment]
This is a feature, in that you sometimes want to wait to use the apple until later.

However, it'd be helpful to have a better visual cue that the apple is available for use but will not automatically be used by walking over it.

**Comment by TerryCavanagh** [comment]
Fixed!
