### ISSUE TITLE
Dragging a die into a just-cast spell quickly enough makes the faded version disappear

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#356]
Normally, after using a spell, it appears in the slot in faded form to remind you what you have there.

However, if you cast a spell and fill it with a die quickly enough after it arrives, it disappears entirely and doesn't leave the faded version behind.

**Comment by TerryCavanagh** [comment]
After some testing, it seems this particular cause of spell shows not appearing has been fixed, but the bug still happens for some other reasons. 😐
