### ISSUE TITLE
Silence does nothing against enemies

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#359]
Silence affects the player, but not the enemies, because they have no abilities to silence.

**Comment by TerryCavanagh** [comment]
This is a pretty major design blind spot, and I'd love to fix it for launch. Adding to High Priority.

**Comment by TerryCavanagh** [comment]
For better or worse, the solution I've gone with is to just avoid the design space completely (by excluding problematic enemies from various episodes), and that's not likely to change at this point. No longer planning to implement this.
