### ISSUE TITLE
Crash when editing a custom enemy with no enemy or non-custom enemy selected

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#361]
To reproduce; open game, go to editor, select enemy, go to custom and click "edit", the game tries to edit the [none] enemy and crashes.

Best result would be something like "you can't edit with no enemy selected!"

This also happens if you have a non-custom enemy selected, in which case it should probably create and edit a copy of the selected enemy.

**Comment by TerryCavanagh** [comment]
Custom enemies aren't in the editor anymore. Closing!
