### ISSUE TITLE
Burning/Freezing dice doesn't always work with Crime Lord

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#362]
Using Glass Cauldron twice and then Meteor the status effect should be have all dice set to 1 and burning. It appears only 1 die was frozen and no dice burned.

![dicey dungeons v0 9 1](https://user-images.githubusercontent.com/40739964/42136451-b663daca-7d29-11e8-968b-095ea003cb05.gif)

On subsequent rounds using Glass Cauldron once and Meteor, no die was frozen and only half the dice were burning:

![dicey dungeons v0 9 1-nofreeze](https://user-images.githubusercontent.com/40739964/42136571-08d38376-7d2c-11e8-94d6-35318bbda777.gif)

**Comment by ncrecc** [comment]
That's a feature, actually; all freeze/burn pairs are cancelled out, so freezing 6 dice and burning 5 dice would just leave you with one frozen die. Terry plans on removing this though -
 https://github.com/TerryCavanagh/diceydungeons.com/issues/347

**Comment by lcenine** [comment]
Ahhh..... that makes complete sense now. Thanks for the clarification!
