### ISSUE TITLE
If hard-mode enemy's equipment weakened, subsequent steal will return non-upgraded equipment

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#365]
Fighting against a Sorceress in hard mode, I used her own Hex to weaken two pieces of her equipment, which happened to include her Cauldron+. The next turn, the thief's steal turned up a Cauldron, not a Cauldron+.

**Comment by TerryCavanagh** [comment]
Duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/391, thanks!
