### ISSUE TITLE
Stereohead shouldn't be a level 1 enemy

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#366]
In hard mode, Stereohead has two Sonic Wave+s, each of which can do the full damage of any one die. That makes it entirely possible for Stereohead to do up to 12 damage per round, plus weakening two equipment. That seems wildly more powerful than any other level 1 enemy.

**Comment by TerryCavanagh** [comment]
Yeah, agreed! For v0.10.1, I've swapped the Builder with Stereohead! Thanks!
