### ISSUE TITLE
Problems if using both weaken and shock together

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#367]
>if a piece of equipment gets both weakened and shocked, when un-shocked the result is the un-weakened version. They should both work on the same equipment, so that the enemy has to unshock it and then they have the weakened version.
>
>Otherwise, for instance, if you're relying on weaken to keep you alive, shock will get you killed. For instance, if you weaken the Barbarian's "Fist" equipment, it goes from 4 damage reusable to 3 damage non-reusable. If you then have Magic Armor, you can generate just enough shield to avoid taking damage. But if you also shock the Fist, the barbarian can un-shock it and then use it normally without the weaken, and you die.

**Comment by onetruepurple** [comment]
Still valid in RC1.

**Comment by pace212** [comment]
In RC3 I shocked and weakened Dryad's Venus Fly Trap, and it got weakened but not shocked.

**Comment by onetruepurple** [comment]
Still valid in v1.4...

**Comment by TerryCavanagh** [comment]
![shocked+weaken](https://user-images.githubusercontent.com/2874150/87290181-34f35900-c545-11ea-860d-64f2ed6e4d65.gif)

I finally fixed this one for v1.9! 🎉

**Comment by pacesmith** [comment]
Yay!
