### ISSUE TITLE
Blinding dice doesn't do much to robot

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#368]
Design issue. Robot's calculate bar shows how much CPU is filled, and the current CPU usage is always the sum of all dice. If squid or whomever blinds one of your dice, you can just roll the blinded die and see how much CPU you've used to track what die it is.

**Comment by TerryCavanagh** [comment]
Thanks! This was duplicated with this newer issue https://github.com/TerryCavanagh/diceydungeons.com/issues/467, so closing this one.
