### ISSUE TITLE
Cleric still tries to silence robot

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#369]
If it has double 6s, it will try Chant instead of placing a 6 into Blinding Light. Robot can't be silenced, since that would defeat the purpose of Robot.
Although, if nobody ever tried to silence robot, it would be confusing why enemies are conveniently avoiding their silence attacks. Maybe that could be explained some level 1 enemy with silence ability who's very weak otherwise, coded such that it will try to use silence no matter what class it's against. Or enemies who can silence would have their silence cards visibly removed if they're against robot.

**Comment by TerryCavanagh** [comment]
Fixed!
