### ISSUE TITLE
New feature: gambling stations

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#37]
It's dice, after all!

Have stations where you can play various dice games to win prizes, staking your equipment on it.

If you win, maybe you get a double upgrade? If you lose, you lose the equipment.

**Comment by joshtriplett** [comment]
This would be fun, if you get to use your equipment to help you make whatever patterns you need to win.

**Comment by TerryCavanagh** [comment]
Probably too late in development to explore this now. Closing.
