### ISSUE TITLE
status effects re-apply every time you Calculate

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#374]
Freeze applies every time you Calculate, even to already-frozen dice. This has the effect of making Freeze geometrically impotent, i.e. 3 freeze only freezes 2 dice (because it freezes the first one twice), 6 freeze only freezes 3 dice, etc.

This might apply to other dice-affecting status ailments as well.

ShinyKitten07 also reported this and added: also if you click calculate again before the freeze/burn animation plays out it wont use up the status and your next dice gets burned too

**Comment by pace212** [comment]
This doesn't happen with Burn. I think it's because Freeze can freeze a 1, but Burn won't burn an already-burning dice.

**Comment by pace212** [comment]
[8:48 AM] fraZ0R: I've noticed a similar bug with robot and freeze
[8:48 AM] fraZ0R: It's almost as if robot is immune to freeze
[8:49 AM] fraZ0R: When i got 2 dice frozen from a snowman, they immediately unfroze right after freezing

**Comment by TerryCavanagh** [comment]
Fixed! Thanks :)
