### ISSUE TITLE
Weakened equipment placed at 0,0 instead of a pleasant location

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#375]
![screenshot 2018-07-06 18 28 23](https://user-images.githubusercontent.com/38589027/42403572-186588a2-8150-11e8-9e54-39dd6ff0a6d5.png)
This happens every time an enemy is weakened, at least with Robot. Haven't tried other classes yet, haven't encountered it with player equipment getting weakened yet.

**Comment by pace212** [comment]
Graydiance: Can confirm that happens to the player character's weakened item too, totally forgot to screenshot though, since it was my first run through and I was more just focused on beating the boss haha
Graydiance: I was Warrior, boss weakened my items, one of them vanished from the screen and one was at 0,0

**Comment by TerryCavanagh** [comment]
Fixed!

(omg this one took forever to track down)
