### ISSUE TITLE
Using fury with only 1 combat reroll left gives you infinite rerolls

### ISSUE THREAD

**Issue by icon315** [TerryCavanagh/diceydungeons.com#376]
When you use the combat reroll it will turn the counter to 0 then the fury will have the counter turn to -1. Once it is negative it will just keep going further down with every reroll.
https://i.imgur.com/aiZwgA2.gifv

**Comment by onetruepurple** [comment]
Fury should probably not affect Reroll at all IMO?

**Comment by TerryCavanagh** [comment]
Agreed! I made it so that fury never effects Combat Roll. Thanks!
