### ISSUE TITLE
Bear - invisible but usable spell/weapon card and dice not being consumed.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#379]
Bear against Formorian there is an invisible spell/weapon that can be activated:
https://drive.google.com/file/d/12jHLZvSvJjv1z5P8lQBsVSjvTrSROXrc/view

Against the Cleric it is there but burns 1 die:
https://drive.google.com/file/d/1MgDZjUlK-ec41Pmp2xenk-IGH_MMwWqs/view

Against the Banshee  it freezes a die:
https://drive.google.com/file/d/1DITqe8kaLMAYL4mo6FL449161pc0s6Y1/view

And against Scathach the die is not consumed:
https://drive.google.com/file/d/1s3EmzIUxzifaE-OeRU3HW_e1jmxfTsLl/view

Other strange things happened with other enemies but I think this conveys the idea well enough.
I did this in the editor as getting the bear organically can be difficult due to the druid not being an available enemy.

**Comment by ncrecc** [comment]
See also #370

**Comment by pace212** [comment]
I encountered this (or something similar) as well, with Bear on Hard vs. Skeleton, when using my leftmost Maul. The dice stayed in place after the Maul went up and did damage, and it snapped into place too far to the left.

![screenshot 2018-07-08 22 59 44](https://user-images.githubusercontent.com/38589027/42449465-c7212cca-834e-11e8-987a-889a64741093.png)

**Comment by TerryCavanagh** [comment]
Fixed! (finally!)
