### ISSUE TITLE
Using Grappling Hook on Mystery Box results in misplaced equipment

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#381]
![image](https://user-images.githubusercontent.com/162737/42418326-5cf3df7a-8252-11e8-87e6-0a7208ebfce7.png)

**Comment by onetruepurple** [comment]
Sort-of resolved?

**Comment by TerryCavanagh** [comment]
Yeah, this has been resolved for a while! Re-Equip Next and Fury no longer affect equipment that is going to transform into something else.
