### ISSUE TITLE
Dice appear to persist in Spellbook slots after use 

### ISSUE THREAD

**Issue by thesirms** [TerryCavanagh/diceydungeons.com#382]
you can still place new dice there, the old ones just don't go away until you do.

**Comment by TerryCavanagh** [comment]
Huh, I’m not sure what this ones referring to! Old dice are sticking around when you cast spells?

**Comment by thesirms** [comment]
Yes, after placing a die in one of the Spellbook slots (Cast Spell or Do 1 dmg) the die will stay there instead of quickly fade away. You can still place new dice there, it just looks like the slot is taken up. It was happening consistently but I've started a new game now and it's not happening anymore.

**Comment by TerryCavanagh** [comment]
Weird! Thanks for the bug report, I'll be on the look out!

**Comment by TerryCavanagh** [comment]
I haven't seen this one crop up this year, so I think it's fixed. Closing!
