### ISSUE TITLE
Can you escape Boomerang's backlash if you End Turn very quickly?

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#383]
I'm not quick enough to pull this off, but you might want to crank up your dev-only animation slowdown and try this:
* get xp to almost level up
* equip boomerang
* get both you and an enemy to low hp, enough that one hit will kill you both
* use boomerang and immediately end turn

There are two potential bugs here:
1. Does this allow you to avoid the boomerang backlash entirely?
2. Does the backlash still hit you, but then the level up heal saves your life? If so, is this a bug or a feature? (:

**Comment by pace212** [comment]
If this is possible to do, it might be easy to do on a touchscreen.

**Comment by njvrzm** [comment]
I don't know about the timing aspect, but if you kill your opponent with boomerang, you survive even if it knocks you down to 0 HP. In fact, I tested this with Warrior & Fury against an opponent with 20 HP when I had 3, threw a 6 die boomerang. The first backlash took me to 0 but the second attack still happened and I won.
![0hp](https://user-images.githubusercontent.com/19716792/42464626-7b3efe9e-835e-11e8-8f5f-2df9e9c7754e.png)

**Comment by gryftir** [comment]
Can confirm, you can go eat a fruit with 0 health.

**Comment by TerryCavanagh** [comment]
The surviving at 0hp thing is a still an open issue, but you can't avoid a boomerang! Closing :)
