### ISSUE TITLE
If you back out of upgrade level up reward, you should get to choose the other thing

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#387]

**Comment by AmethystAir** [comment]
Additionally, you lose the chance for an upgrade (I'm on v0.15.1). I wanted to change my equipment out before upgrading but was unable to receive the upgrade again after leaving the menu.

**Comment by extremewirehead** [comment]
v0.16.3

Backing out of an upgrade from a level up leaves you with no benefit on reward. Should have some verification ("are you sure") to avoid this as an accidentally moving through a level up without a reward.

**Comment by TerryCavanagh** [comment]
This is an easy one, and should really be fixed for launch.  Adding to high priority.

**Comment by TerryCavanagh** [comment]
Oh, this one's been done for a while, closing
