### ISSUE TITLE
Thief Hard steals weakened equipment as normal version (instead of upgraded version)

### ISSUE THREAD

**Issue by pacesmith** [TerryCavanagh/diceydungeons.com#391]
I stole Sonic Wave (not Sonic Wave+) from Stereohead on Hard.
![screenshot 2018-07-09 06 31 46](https://user-images.githubusercontent.com/38589027/42449163-afab8a96-834d-11e8-8288-76afae053bc9.png)
I did use Sonic Wave+ to weaken him on the previous turn, so maybe I stole a Sonic Wave+-?

I guess I get what I deserve if I weaken the enemy's equipment and then steal it back, but I was surprised that this could happen. It's actually kind of cool in theory, but if this were an intended feature I would have expected to steal a Sonic Wave-, not a normal Sonic Wave.

**Comment by joshtriplett** [comment]
This seems like the same bug as https://github.com/TerryCavanagh/diceydungeons.com/issues/365

**Comment by TerryCavanagh** [comment]
Fixed!
