### ISSUE TITLE
"Thief" overlaps equipment boxes after Pickpocketing

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#393]
You can't exactly see it in this screenshot, but when you have more equipment, the newline between "Thief" and "1 gold" pushes the "Thief" up and it sometimes overlaps with equipment.
![screenshot 2018-07-09 06 31 46](https://user-images.githubusercontent.com/38589027/42449763-e4c968a4-834f-11e8-98e8-3e8abea52d6e.png)

**Comment by pace212** [comment]
Here's a better example.

![the word thief overlaps the rock text](https://user-images.githubusercontent.com/38589027/50546854-4fc8db80-0bf4-11e9-8b85-bb9a67d30d10.png)

**Comment by pace212** [comment]
It happens on Thief's turn too.

![it happens on thief s turn too](https://user-images.githubusercontent.com/38589027/50546900-75a2b000-0bf5-11e9-86c1-9400d22df4d8.png)

**Comment by TerryCavanagh** [comment]
Fixed!
