### ISSUE TITLE
Weakening countdown equipment resets its counter

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#394]
Reproduce in the editor by pitting Thief against Druid on Hard.

Weakening Druid's Bear Transform+ resets its counter, because Bear Transform+ is 12 but Bear Transform- is 16. This bug might occur with all equipment whose countdown changes when weakened. I haven't tested to see if it occurs when the enemy weakens the player's countdown equipment.

**Comment by TerryCavanagh** [comment]
It's annoyingly hard to reproduce this in v0.17 - you need to enable the `Rules.upgradeenemyequipment = true;` flag. After that, fight Alchemist, and equip 4x Whisper.

**Comment by mrcdk** [comment]
This should be fixed.
