### ISSUE TITLE
New softlock bug in v0.10

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#398]
This is pretty rare, it seems, but three players have reported a soft lock bug.

Might be related to reusable equipment - Kraken is in two of the reports.

**Comment by pace212** [comment]
It might also be a bug in the cephalopod code. I encountered it with Baby Squid: as Thief on Hard, I rolled 5 4 2. I bumped the 5, duped the resulting 6, then put everything into Headbutt+: 6 6 4 2 and my End Turn button went away.

**Comment by TerryCavanagh** [comment]
![frozensnowman](https://user-images.githubusercontent.com/2874150/42514962-81c8d4d4-8452-11e8-9879-2be76f820f21.PNG)

>encountered a bug where the game simply stopped respoding rather than beginning an enemy's turn after i hit the end turn button, resulting in the screenshot below. (I'd just spent all 3 of my dice - a 1, a 3, and a 5 - on matchstick to apply 3 burn, in case this is relevant).

**Comment by TerryCavanagh** [comment]
Hmm. I can't replicate this one. I've added some diagnostics to the game to help try and track it down in future, though. If you press zero on your keyboard, the web console will track out a lot of internal game information that should help me figure out why it's getting stuck.

**Comment by TerryCavanagh** [comment]
![ssss](https://user-images.githubusercontent.com/2874150/42633298-f505f914-85d7-11e8-84fd-2d42381e755a.PNG)

**Comment by TerryCavanagh** [comment]
```
Game.hx:1402: Diagnostic info:
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Combat state:
Queuedelay: 0
Current -> wait: playerequipmentanimating [0]
playertidyup:  [0]

Character: Thief
HP: 29/29
Equipment: (6 equipped)
Dagger (ready: true, slots: [x], in animation: false)
Lockpick (ready: true, slots: [x], in animation: false)
Pickpocket (ready: true, slots: [x], in animation: false)
Crowbar (ready: true, slots: [x], in animation: false)
Pea Shooter (ready: true, slots: [x], in animation: true)
Wildcard (ready: true, slots: [in animation: false)
Thief dice: 2, assigned to slot 0 of Dagger
Thief dice: 6, assigned to slot 0 of Throwing Axe
Thief dice: 3, assigned to slot 0 of Dagger

Character: Barbarian
HP: 15/26
Equipment: (5 equipped)
Throwing Axe (ready: true, slots: [x], in animation: false)
Throwing Axe (ready: true, slots: [x], in animation: false)
Throwing Axe (ready: true, slots: [x], in animation: false)
Throwing Axe (ready: true, slots: [x], in animation: false)
Fists (ready: true, slots: [x], in animation: false)

Total Dice on board: 3, values: [2,6,3]
```

**Comment by TerryCavanagh** [comment]
So this actually still happens, but *now* the game can see it happening and time out the round, which is better than nothing. Try to fix this properly for launch!

**Comment by TerryCavanagh** [comment]
Oh, this one has been fixed for a while now. Closing!
