### ISSUE TITLE
Editor welcome screen still says "playing through all **four** classes"

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#403]
"Also, beware. This spoils THE WHOLE game. I recommend messing playing through all **four** classes first before messing with this!"

Since 0.10, there are five main classes (Robot having been added) and Bear, so the editor should either say "all five classes", "all six classes", or the more ambiguous "all of the classes" that doesn't deny or confirm the existence of Bear and won't have to be continually updated as more classes are added.

**Comment by TerryCavanagh** [comment]
Fixed!
