### ISSUE TITLE
Auroroll stacks some dice, hiding them

### ISSUE THREAD

**Issue by damorend** [TerryCavanagh/diceydungeons.com#405]
When using autoroll (Robot's limit ability), usually two dice are located in the same spot, hiding one of them. The problem is compounded because when you click on the visible die, the hidden one is selected, causing player mistakes. I encountered this issue on mobile (Safari-IOS) and desktop (Edge-Windows).

**Comment by damorend** [comment]
Related to #339

**Comment by TerryCavanagh** [comment]
Thanks for the report! Seems this is related to changes I made for v0.10.1 for Freeze All and Burn All!

**Comment by pace212** [comment]
Reproduced:
LV2 Robot vs. Druid, hard mode
calc 4, calc 5, autoroll 1 1
the two 1s are on top of each other

**Comment by pace212** [comment]
Still reproducible in v0.15

**Comment by mrcdk** [comment]
This is fixed, the dice will not overlap as long as they have space left.
