### ISSUE TITLE
A comprehensive roundup / systematization of known AI issues

### ISSUE THREAD

**Issue by damorend** [TerryCavanagh/diceydungeons.com#406]
### General	
- The AI phase seems to be triggered before the actual status changes (#353)

### Equipment priorization issues:
- Choosing to unshock an item that shouldn't be unshocked
a. Items that they can’t use because they don’t have the right dice for it (#351, #315, #240, #220)
b. Items that are identical or inferior to other, available items (#315, #240, #220) (they should be unshocked only after the other items are used, if there still are dice available)
c. Items that are uncharged, like the Knight’s Shield Bash (#315) (they should be unshocked only after they are charged, if there still are dice available)
- (Updated) Prioritizing an attack that doesn't do damage (silencing, cursing, freezing, blinding) over an attack that reduces the player's HP. It results in enemies that don't harm the player when they have less dice than expected (because some dice are locked or burned, they have to waste dice on unshocking an item, or a weakened item requires more dice than usual). The AI doesn't seem to differentiate two stages of prioritizing: first, it should evaluate if it has enough dice to use all the available items and if not, decide which items to use; then, it should prioritize which dice to allocate to each item it chose. Right now, some enemies seem to always try to first use the right die on items that require a certain number, even if that means not damaging the player during the turn. 
- (Updated) Wrongfully prioritizing weakened items (note: this applies to cases where weakened items have a less desirable effect. When weakening an item makes it harder to activate an unchanged effect, then sometimes you want to use the weakened item first, like Master Thief):
a. Choosing to use a weakened item when a normal one is available (#220)
b. Wasting dice on an item that "does nothing", like Bear Transform-, instead of using them elsewhere.
- Dealing ineffectual elemental attacks (¿should the enemy know their attack is useless?):
a. Using shocking attacks when they already shocked all your dice (#343)
b. Trying to silence robot (#369)
- (updated) Having the wrong priorities when using dice manipulation items
a. If Builder+ rolls a 6, it will put it in Bump+ instead of Shovel+ (#334)
b. Engineer combines dice before unshocking (#315)
c. Crime Lord might use a six on Hacksaw+ instead of Lockpick+
- Healing when they have full or near full HP (#315)
- (Updated) Prioritizing other actions over a more valuable countdown item:
a. The Druid should prioritize activating Bear Transform over doing damage with Quarterstaff, so he should use the smallest even die on Quarterstaff to weaken the player and the higher even dice on Bear Transform.
b. Fomorian should prioritize Earthquake over Headbutt. He should put his odd dice first on Earthquake, and use his even dice on Headbutt only if they're not enough to activate Earthquake in the same turn.
- Prioritizing other actions (like healing, silencing or dealing elemental attacks) over dealing a death blow (#315) (¿should the enemy know your health stats? You know theirs)
- Wasting time doing things that don't change the outcome, like the Engineer using Spanner to combine dice even if they already have a 6 (#235)

### Dice selection issues:
- Activating burning dice they won’t use (#272, #220)
- Not activating burning dice that can’t harm them (Vampire with 1 HP)
- Using a small die on one-use-per-battle equipment, wasting the item (#321, #220)
- Using a valuable die for an action that is indifferent to the value of the die, when there's useless or less valuable dice available. The “value” of the die depends of the enemy’s equipment; for instance, if they have max 3 items, small dice might be more valuable to them than higher numbers. A “useless” die would be one that can’t be used in any of the cards.
a. Using a valuable die for unshocking an item (#315)
b. Using a valuable die for activating an item that requires any die (or an odd/even die) for an effect whose intensity is independent of the die’s value (#239)

### Other:

- AI is unaffected by blinded dice (#335)

**Comment by TerryCavanagh** [comment]
Whoa! This is super helpful, thank you!

**Comment by damorend** [comment]
Good to know. I understand fixing all these issues would make some enemies nearly unbeatable, and require a rebalancing that might affect the whole game, so maybe it's better to keep some "dumb" actions. they could even be characterization fodder for the enemies.

**Comment by TerryCavanagh** [comment]
Thanks again for this! The new AI is now up and running, with exciting new bugs to dig into! Some of these are still happening, but for totally new reasons, so I'm closing the old AI issues and opening new issues for the new ones. Thanks!
