### ISSUE TITLE
Counterspell+ strange behavior against Crime Lord.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#409]
I'm not sure if this is due to the Innate status of Crime Lord but locking out 1's with counterspell+ is erratic. It also locks out some 3's. Maybe other dice. I'm not sure if this is an intended mechanic that isn't explained well or a bug.

https://drive.google.com/file/d/1QsWtZ0DHk_lHGEqNWYAnBmoITgPeEXdk/view

**Comment by TerryCavanagh** [comment]
Ah, this one is fixed!
