### ISSUE TITLE
Reconsider upgraded versions of Snowball and Fireball

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#419]
In hard mode enemies with these attacks suddenly get very scary!

**Comment by onetruepurple** [comment]
Probably resolved in v0.17 with the change to Snowball+, but Staff is still pretty weak when compared to its easier-to-play equivalents.

**Comment by TerryCavanagh** [comment]
Yeah, I think I wanna buff Staff a little bit, even if it's just to slightly reduce the countdown.
