### ISSUE TITLE
Buying and not equipping spells as the Witch causes them to disappear

### ISSUE THREAD

**Issue by ShiftedClock** [TerryCavanagh/diceydungeons.com#420]
How to recreate: When playing as the Witch, buy a spell from the store and choosing to "Ignore It". This causes the spell to be lost, and the gold spent on it.

In contrast, when getting new spells from Chests you can ignore the spell, and come back later to equip it. I was hoping Stores did this too, and I think it defies expectations a bit that they don't work the same way.

One solution would be to show the purchased item in the Store's inventory still, but with an "Equip" instead of "Buy" button.

(Sorry if this has been reported before, I searched for issues regarding the Witch and didn't see anything like it.)

**Comment by TerryCavanagh** [comment]
This one still happens in v1.9, unbelievably. Let's make sure it's fixed for v1.10.

**Comment by TerryCavanagh** [comment]
This one's been fixed for a little while, should have closed the issue!
