### ISSUE TITLE
Try this change to blight

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#421]
Unupgraded blight: once per combat with countdown 12
upgraded: remove the once per combat

**Comment by onetruepurple** [comment]
Strong disagree to Blight+ remaining the same as it currently is, it's probably the single most overpowered item in the game.

**Comment by ncrecc** [comment]
Maybe don't do this until Thief and his poison needle addiction is fully sorted out, since Blight right now is rather overpowered in his hands.

**Comment by TerryCavanagh** [comment]
Fairly happy with where this is right now. Closing!
