### ISSUE TITLE
Locked dice can also be Burning

### ISSUE THREAD

**Issue by ShiftedClock** [TerryCavanagh/diceydungeons.com#423]
How to recreate: Use an item that causes a random status effect, which can include Locking a die of the AI. In the same turn, use an item that burns dice. The Locked and Burning status effects overlap on the same die.

The annoying thing is that the AI can't use the Burning dice because they're Locked, reducing the effect of both abilities. I think the sensible solution is to say that Locked dice can't be Burning.

I've only caused this to happen once, because Locked is fairly uncommon to cause, and I don't always have an item that also causes Burning. So it may not happen all the time.

**Comment by TerryCavanagh** [comment]
Very good catch, gosh! It's pretty difficult to even get this combo to come up.

**Comment by svass** [comment]
I think Robot with Gae Bolg and Missile Launcher can cause it. Not sure who else.

**Comment by lcenine** [comment]
Playing against Paper Knight with Thief. Using the stolen Glue I locked all PK's  dice and burned them with the Staff of Fire. When it was Pk's turn he would always touch the burning dice... which was helpful but still odd😄

**Comment by Cody-KW** [comment]
![image](https://user-images.githubusercontent.com/75864569/101961616-b2dc8e80-3bcf-11eb-9775-fb764549c4d2.png)
Hi just to add to this it happens frequently with the Thief stealing the Rhino Beetles equipment!

**Comment by TerryCavanagh** [comment]
Fixed!
