### ISSUE TITLE
[Bug/Oversight] : Removing status at end of turn can skip some status

### ISSUE THREAD

**Issue by Liryax** [TerryCavanagh/diceydungeons.com#425]
There is currently an issue that can make status that remove at end of turn last longer due to being skipped whiled checked to be removed, the reason is that in the javascript code at line 18813 the iterator "i2" doesn't get subtracted by 1 after removing an element from "this.status", making it skip a status each time it remove one.

`while(i2 < this.status.length) {
            if(this.status[i2].remove_at_endturn) {
                if(this.status[i2].selfinflicted) {
                    this.status[i2].selfinflicted = false;
                } else {
                    this.status.splice(i2,1);
                    //Missing '--i2;' here  <=============
                }
            }
            ++i2;
        }`

**Comment by TerryCavanagh** [comment]
Fixed!
