### ISSUE TITLE
Consider making Robot silenceable, somehow

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#426]
This way, enemies whose gimmicks rely mostly on silencing wouldn't be so easy.

E.g. when robot is silenced, it automatically rolls anywhere from three to five dice at the start of the turn, as long as their sum isn't equal to or greater than the CPU limit. CPU bar would be unstunnable with two dice like any other skill card.

**Comment by TerryCavanagh** [comment]
Gonna tackle this for launch 👍

**Comment by ncrecc** [comment]
Perhaps silence calculate after any two dice have been generated, so you have the option of using those two dice and nothing else or sacrificing the two dice to potentially gain more

**Comment by TerryCavanagh** [comment]
Since launch, I've excluded enemies from Robot rounds that can silence them. I'm no longer planning to change this.
