### ISSUE TITLE
AI seems overly paranoid when avoiding burnt dice, sometimes

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#427]
Master Thief had four health, rolled a 6, but since that 6 was burnt (deals two damage on touch) it did not want to use it, even though touching the die would not have killed it and it would not be likely to survive either way.

**Comment by TerryCavanagh** [comment]
This is fixed! AI will now consider extinguishing any useful dice (so long as that's not fatal).
