### ISSUE TITLE
New Inventor Limit Break idea

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#428]
Change all your equipment cards into temporary gadget cards. When you use one, they turn back into normal equipment. You get to keep the original equipment too, so it's a free action.

**Comment by svass** [comment]
Seems like it would be very powerful if you got to use all the gadgets and your equipment, perhaps trivializing some fights.

Perhaps for one turn every equipment you use turns into a gadget as well? It's very similar to the original suggestion, but if you have 5/6 equipment and only 4 dice, this way you won't get to use all the gadgets, reducing it's power slightly in some situations.

(And would add another way the Inventor's power level scales as they reach parity between dice and equips later in the game, allowing them to use Limit Break to it's full effectiveness.)

It could be nice for the Inventor's Limit Break to feel especially powerful, however. Having options is always nice from a balancing perspective, in any case.

In general, it would be nice if the Inventor could use their gadgets more regularly, or at least with a different "rhythm" than the current system. Incorporating them into the Limit Break could satisfy that. Perhaps the Inventor could "invent" their own Limit Break?

Sorry for the long comment!

**Comment by TerryCavanagh** [comment]
Still worth considering for a DLC episode, maybe, but I'm not planning to implement this in the final version of the game anymore.
