### ISSUE TITLE
Broomstick is semantically nonsensical

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#429]
You don't actually fly anywhere.

Suggestion: Rename it to "Crystal Ball" as an adjacent of Hall of Mirrors, and then make Broomstick a Witch-only spell that works as an instant flee (for all those instances where you mess up and prepare the wrong spells).

**Comment by TerryCavanagh** [comment]
Yeah, fair point! I'll try Crystal Ball for v0.11!
