### ISSUE TITLE
Bear vs Vampire works, but doesn't give any indication that it will

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#430]
I managed to win a Bear run on Hard, but when I got to the boss floor and saw that it was the Vampire, I didn't expect it to be possible. And when I got into combat and still got the same message that the Vampire can only be killed by a wooden stake, I figured that'd be the end of the run. I went ahead just to see how far I could get, and was pleasantly surprised to find that I could still win without a wooden stake.

Please consider adjusting the messages when playing as a Bear to avoid suggesting that the player can't win.

**Comment by TerryCavanagh** [comment]
It's a bit of a cop out, but I've decided to work around this by just preventing the Vampire from appearing for the Bear. Should it somehow still happen (i.e. with modding), Maul removes the Vampire status, and the Vampire status tool tip explains that the Maul will work..

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/50739295-fc4b2480-11d5-11e9-8ea1-4f914605e2be.png)

**Comment by onetruepurple** [comment]
What if the limit break was "Do 10 unavoidable damage" instead?

**Comment by TerryCavanagh** [comment]
I think that might introduce some ambiguity that would have to be explained somewhere (does it bypass dodge? What about shields?)

(Basically, it’s hard to carefully write up rules for edge cases like this that don’t complicate the basic cases, which is what players will care about 99% of the time. And in this case, it will never even actually come up unless someone has specifically modded the game to make it happen!)
