### ISSUE TITLE
Equipment can not be weakened and shocked at the same time

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#433]
Using 0.11 right now, but maybe this has existed for all versions and I haven't noticed it. Weaken overrides shock, it seems. But is this a bug or another clever elemental-rock-paper-scissors mechanic?

**Comment by onetruepurple** [comment]
Duplicate of #367

**Comment by TerryCavanagh** [comment]
Yep! Closing.
