### ISSUE TITLE
Too many commas in the german hard mode description.

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#434]
There should be none :D

edit: is this the right place to report German translation stuff/at all or is something else/waiting for newer iterations better?

edit: yup, I may need to hold off on these until Thomas got to check for context and the like

edit: oh - these commas are in the English line as well ...

**Comment by TerryCavanagh** [comment]
This sentence is gone from the game in v0.15!
