### ISSUE TITLE
got a dice stuck on a weakened card by inserting it early - freed it up by using another on the card

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#436]
![image](https://user-images.githubusercontent.com/3826749/43702542-5d91a57e-995a-11e8-847c-50c4d2e93877.png)
![image](https://user-images.githubusercontent.com/3826749/43702556-6acc4ea6-995a-11e8-98b6-62fbde456c76.png)

desperately trying to reproduce that now - no luck so far

**Comment by TerryCavanagh** [comment]
I haven't seen this one re-occur in any recent version, so I'm gonna assume it's been fixed. Closing!
