### ISSUE TITLE
Make a distinction between physical attacks and magical/ethereal attacks

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#439]
This could clear up some things regarding some attacks being logical to be blocked by shields, and some less so - i.e. when attacked with a Claw, a shield should logically block the poison too and not just the damage; however, it would make sense for attacks like Smog Cloud or Toxic Ooze to bypass any shields.

This could be presented either as a new per-spell property, or via text: "Do [] damage, cast 2 poison on hit".

This could play nicely with some monsters, Dire Wolf in particular (who can destroy you even despite building up massive shields).

On the downside, this has the potential to make shield builds even more powerful than currently, but a rebalance has been on the horizon for some time now...

**Comment by onetruepurple** [comment]
I now think this would add too much complexity into an already robust game at this point, so closing.

**Comment by Thunder33345** [comment]
i personally somewhat agree on it, yes more complications
but more layers open for strategies
