### ISSUE TITLE
Implement a simple tutorial floor to clarify combat

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#441]
With a single tutorial enemy, who would then possess the following specifics:

- "Goes first" innate, to demonstrate to the new player that dice go into slots on the cards

- A 0 damage attack that shocks - this spells out that the player can place their dice on their cards to interact with them (if the enemy's actions didn't make that obvious) and an opportunity to "learn" it twice, by moving one dice to unshock the item, and another to attack

- Just enough health that they can be felled in one move (two max, if the player has very bad roll), to keep the tutorial section short - all the other combat dynamics are pretty self explanatory

This floor would appear only on the very first playthrough of the game.

**Comment by TerryCavanagh** [comment]
Done.
