### ISSUE TITLE
health bar and text positions get messed up if you focus a different browser tab while taking a hit

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#443]
![image](https://user-images.githubusercontent.com/3826749/43764380-9abc796e-9a2d-11e8-946e-9d797fafbad5.png)

It corrects itself on the next hit.

Rather irritating, if you end a fight that way:

![image](https://user-images.githubusercontent.com/3826749/43764519-ec5b8cf6-9a2d-11e8-81b4-903258b3c4ac.png)

**Comment by TerryCavanagh** [comment]
This is interesting! But the HTML5 version is no more, so probably not worth digging into. Closing!
