### ISSUE TITLE
Bump's effect should give an extra 1 dice

### ISSUE THREAD

**Issue by doctorpangloss** [TerryCavanagh/diceydungeons.com#446]
"right now, bump 6 gives you a 1. I'm going to change it so that you get two dice, though, a 6+1"

<img width="984" alt="screenshot 2018-08-07 13 38 16" src="https://user-images.githubusercontent.com/2229300/43803055-90620564-9a4c-11e8-8504-1d197e32afce.png">

**Comment by TerryCavanagh** [comment]
Done!
