### ISSUE TITLE
Blinded dice stick on Wooden Stake.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#451]
I've had this happen before where  blinded dice stick to the wooden stake. The blinded die cannot be moved but other dice can be loaded onto the stake behind it to bring the count down. 

![blind_vamp](https://user-images.githubusercontent.com/40739964/44052489-bf5b8a1c-9f0a-11e8-8747-3f7eeee37785.jpg)

**Comment by musicalentropy** [comment]
I got the same issue with several items with counts and blinded dies

**Comment by TerryCavanagh** [comment]
Fixed. Thanks!
