### ISSUE TITLE
Cannot cancel a Spellbook spell selection action

### ISSUE THREAD

**Issue by doctorpangloss** [TerryCavanagh/diceydungeons.com#453]
![screenshot 2018-08-31 15 20 07](https://user-images.githubusercontent.com/2229300/44938089-9c2d0900-ad31-11e8-8262-08aead6b75b4.png)

 1. Drag dice on Spellbook
 2. Observe `Select a slot`
 3. Try to "cancel" what I was doing by right clicking, nothing happens.

**Comment by TerryCavanagh** [comment]
This is now supported for v1.9!
