### ISSUE TITLE
Crowbar ignores shock

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#459]
![unknown](https://user-images.githubusercontent.com/2874150/44944620-f087c580-add1-11e8-912d-ab18ed332e09.png)

```
Crowbar ignores shock, here I can still activate the pea shooter etc without realeasing shock
```

**Comment by mrcdk** [comment]
this is fixed. Crowbar doesn't affect used, shocked or cursed equipment anymore.
