### ISSUE TITLE
Make Silence affect the Robot

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#468]
Not sure what the best solution is here yet, but it's a bit disappointing that the Robot is simply immune.

Consider disabling Jackpot?

**Comment by timeracers** [comment]
#426 is another issue with the same problem. I like his idea of making it so you can't push your luck til you remove the silence. I also agree the jackpot should also be disabled.

**Comment by TerryCavanagh** [comment]
Duplicate of https://github.com/TerryCavanagh/diceydungeons.com/issues/426, closing!
