### ISSUE TITLE
Sometimes, Maul as Bear doesn't remove the dice

### ISSUE THREAD

**Issue by doctorpangloss** [TerryCavanagh/diceydungeons.com#474]
Platform: Safari Version 11.1.2 (13605.3.8)

 1. Play Thief
 2. Join the Power Guild
 3. Encounter Alchemist
 4. Transform into bear using stolen alchemist potion
 5. Place dice on leftmost Maul
 6. Observe the dice does not fly down to the part of the canvas where I cannot click it.

<img width="1007" alt="screenshot 2018-09-02 00 12 04" src="https://user-images.githubusercontent.com/2229300/44953133-f23ea100-ae44-11e8-9c94-d835b25039de.png">

 7. Observe I can use this dice for the next Maul.

<img width="1004" alt="screenshot 2018-09-02 00 13 24" src="https://user-images.githubusercontent.com/2229300/44953135-04204400-ae45-11e8-99a4-3b0a26dc0fba.png">

When playing against the Snowman and using a frozen 1 dice in the Maul slot, the dice anchors to the right of the Maul card while it flies off screen upwards and correctly (if glitchily) removes itself. After this, the problem was not reproducible for a few times, before becoming reproducible again.

**Comment by YinYin-Falcon** [comment]
Same as #379 
The thief doesn't stop stealing even as a bear.

**Comment by TerryCavanagh** [comment]
Fixed!
