### ISSUE TITLE
The player uses 3.19GB of RAM and shows a warning in the browser

### ISSUE THREAD

**Issue by doctorpangloss** [TerryCavanagh/diceydungeons.com#475]
Platform: Safari Version 11.1.2 (13605.3.8)
<img width="399" alt="screenshot 2018-09-02 00 14 09" src="https://user-images.githubusercontent.com/2229300/44953138-23b76c80-ae45-11e8-99a9-39261e5d4023.png">

<img width="1045" alt="screenshot 2018-09-02 00 14 26" src="https://user-images.githubusercontent.com/2229300/44953140-29ad4d80-ae45-11e8-83b0-a8b03a1ac5ea.png">

This occurred during a playthrough as Thief, stealing a Bear Potion, transforming into Bear, and observing another issue (#474 ).

**Comment by TerryCavanagh** [comment]
I've just launched update v0.12.1, which drops the game's asset resolution to 1080p. Please let me know if this helps with this issue!

**Comment by TerryCavanagh** [comment]
Fixed.
