### ISSUE TITLE
Screen frozen after fight

### ISSUE THREAD

**Issue by woctezuma** [TerryCavanagh/diceydungeons.com#480]
I was playing the latest build (v0.12.1 alpha) in French as the Witch, beat one opponent, then proceeded to beat another one, then the screen was frozen after the fight. If I remember right, the music was still going on.

![frozen screen](https://i.imgur.com/j9Ba9xZ.jpg)

**Comment by TerryCavanagh** [comment]
Hey! Thanks for the bug report! (This one seems to be the same as https://github.com/TerryCavanagh/diceydungeons.com/issues/458)

Do you remember anything about what you did at the end of the fight that might help me narrow this one down? Did you throw dice? Click End Turn? Anything else?

**Comment by woctezuma** [comment]
I think I clicked on "throw dice".

**Comment by TerryCavanagh** [comment]
Ok, cool!

**Comment by woctezuma** [comment]
It might just be some connection error, because when I tried to play another game, I had a black screen, so I pressed "Ctrl+F5" in the browser to load all the assets from scratch, and everything is working fine for now.

**Comment by TerryCavanagh** [comment]
Ah, probably not - everything in the game is loaded up front, so it shouldn't care if you're offline once you're on the title screen. (It does seem like this issue is pretty rare, at least!)

**Comment by TerryCavanagh** [comment]
Fixed!
