### ISSUE TITLE
Weakening cards removes their "once per turn" restriction

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#484]
e.g. with Bully's rocks:

https://gfycat.com/DependentUnlinedAidi

**Comment by krsiehl** [comment]
There is a similar effect when you weaken Paper Knight's attack, where the weakening-over-time effect doesn't carry over to the next turn

**Comment by onetruepurple** [comment]
(duplicate of #424 )
