### ISSUE TITLE
Sometimes Short Circuit doesn't inflict a status effects

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#487]
One of the options must be broken

```
I used short circuit on the girl scout
and it didn't inflict her with a status effect
```

**Comment by TmanDaCool1** [comment]
Okay... I think I know what happened. The Girl Scout has an immunity to the freeze status effect, and Short Circuit chose to inflict the freeze status, which was blocked.

Still, maybe there should be a conditional to not inflict her with freeze?

**Comment by onetruepurple** [comment]
I've never seen this happen.

**Comment by TerryCavanagh** [comment]
The underlying issue here is that there's no feedback for when an immune enemy blocks a status effect! So I've made a new issue specifically for that (https://github.com/TerryCavanagh/diceydungeons.com/issues/1974), and am closing this one.
