### ISSUE TITLE
Try out a re-arrangable spellbook

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#491]
Some strong cases made for it on the dicecord: try it out and see how it feels

**Comment by Wowfunhappy** [comment]
Just to add on to this, a lot of the reasons raised for this are also why I reeeeally wish Witch had backpack. Not having one forces you to be super locked into a single strategy for the whole game, which discourages experimentation + (for me) increases choice paralysis.

**Comment by TerryCavanagh** [comment]
Ok, sorrrryyyy but at this point in the game's life, I'm just not willing to mess around with something like this. I concede that this might have been a good idea, but I think it's too late now.
