### ISSUE TITLE
Size 4 Equipment

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#493]
With Chant gone, the only remaining 2x2 spells are:

- Dire Wolf Howl, with 1 dice slot
- Overwhelm, with 1 slot
- ~~Earthquake, with 1 dice slot~~
- Ice Age, with 6 dice slots
- Tower Shield, with 2 dice slots on Normal and 3 on Hard
- ~~Nightmare, with 1 dice slot~~

Obviously there's no problem with fitting 1 and 2 slots on regular cards. We know from the old Hacksaw+ that 3 dice slots can fit fine on a single space card.

What I'm getting at, is that with the odd exception of Ice Age, there doesn't seem to be much purpose for size 4 equipment anymore?

Changing all size 4 equipment into size 1 or size 2 would:
- allow the player to equip them again, as per the old versions of the game
- instantly fix the "stolen size 4 equipment is partly offscreen" problem for the Thief
- make all equipment more consistent in size

**Comment by TerryCavanagh** [comment]
Thanks for making an issue for this! This is basically my plan, but I keep forgetting to do it. 👍

**Comment by onetruepurple** [comment]
List as of v0.15:

- Dire Wolf Howl
- Divine Rod
- Fire Breath
- Ice Age
- Overwhelm
- Tower Shield

**Comment by TerryCavanagh** [comment]
Finally, done!

This involved a couple of redesigns that I think are probably all improvements, and automatically fixes a couple of other open issues while we're at it.

![image](https://user-images.githubusercontent.com/2874150/50729953-db81c100-113a-11e9-8daa-68fcfa059498.png)

![image](https://user-images.githubusercontent.com/2874150/50729956-e3d9fc00-113a-11e9-99e4-82e780e5b9b6.png)

![image](https://user-images.githubusercontent.com/2874150/50729960-e8061980-113a-11e9-8eba-30e8b786c5f6.png)

![image](https://user-images.githubusercontent.com/2874150/50729963-ef2d2780-113a-11e9-9cb8-b8505053892c.png)

![image](https://user-images.githubusercontent.com/2874150/50729971-13890400-113b-11e9-80da-76016eb1969a.png) 
![image](https://user-images.githubusercontent.com/2874150/50729972-184db800-113b-11e9-90ee-ad7702463ad4.png)

![image](https://user-images.githubusercontent.com/2874150/50729979-26033d80-113b-11e9-89ce-b7bdfa42ec24.png)

![image](https://user-images.githubusercontent.com/2874150/50729981-2d2a4b80-113b-11e9-978c-bcf35f6efb41.png)

![image](https://user-images.githubusercontent.com/2874150/50729984-32879600-113b-11e9-85b1-4a2632040bcc.png)

**Comment by onetruepurple** [comment]
Good work, but I'll miss that the Divine Rod required a "666" to fire.

Could you maybe stack the three slots close together and add a "Needs 666" caption underneath? It would need to be its own unique kind of card, but it would probably work well.

**Comment by onetruepurple** [comment]
Also, seems like Tower Shield and Tower Shield+ are pretty much identical in function now?

**Comment by TerryCavanagh** [comment]
Yeah, I kinda miss it too - but nothing actually uses the Divine Rod right now, so it seemed like a low priority. Might reinvestigate that separately if I end up reintroducing it!

Tower Shield+ is a very very minor upgrade - it basically just means you can use either 1 or 2 dice on it, instead of needing two, so it makes sense for builds where you maybe just want to use a leftover dice.
