### ISSUE TITLE
Background issues in inventory. Chrome.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#506]
Might be related to #500 as it happened in Chrome.

Default behavior getting a new item is I get some button text as the background.
![ignore_it](https://user-images.githubusercontent.com/40739964/45267932-654aa780-b443-11e8-9292-2b7960baed3b.jpg)

On selecting an item I get some random text.
![random](https://user-images.githubusercontent.com/40739964/45267955-a0e57180-b443-11e8-85c8-5941e5d8a095.jpg)

On clicking the background I get a sprite map... that looks like some great pop art.
![sprites](https://user-images.githubusercontent.com/40739964/45267964-b8bcf580-b443-11e8-93ba-c4b65cebf40e.jpg)

**Comment by Doppp** [comment]
![fled](https://user-images.githubusercontent.com/627410/45917923-81256300-beb1-11e8-92b0-8cfc80eabca6.png)
![bug](https://user-images.githubusercontent.com/627410/45917926-81bdf980-beb1-11e8-994b-8e89c86ae377.png)
![bug2](https://user-images.githubusercontent.com/627410/45917924-81256300-beb1-11e8-984a-add189e40bc3.png)

**Comment by TerryCavanagh** [comment]
Never quite figured this out, but we've stopped doing HTML5 updates now, so closing the issue! Thanks!
