### ISSUE TITLE
Impossible to use any dice after the paper fighter uses too much its weapon

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#507]
I was fighting the paper fighter with the witch at some point, and then I wasn't able to use any of my dice (they don't move anymore), and I wasn't able to select next turn either. However, it was possible to throw some dices. At the previous turn, the paper fighter was using its weapon with the "-2 attack next time" and I think the current attack became null or negative, causing the issue.

**Comment by TerryCavanagh** [comment]
Fixed!
