### ISSUE TITLE
Jester versus Copycat causes crashes in some situations

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#537]
Not 100% sure why, but might be related to using Yoink when the player has exhausted their deck.

**Comment by ikdzu** [comment]
If it helps, here's my stack trace from when this happened to me.  It was definitely just after the Copycat used Yoink.

https://pastebin.com/gi8s2hmW

**Comment by onetruepurple** [comment]
Resolved in v0.16?

**Comment by TerryCavanagh** [comment]
Yep, so it is, thank you!

There are some remaining/new issues with copycat, thanks to their redesign, but I'll open new issues for those.
