### ISSUE TITLE
Using Fury on multiple use equipment reduces it by 2 instead of 1

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#538]
e.g. on a spear with 3 uses, it goes from 3 uses left to 1 use left.

(this might be a duplicate? can't find it right now though)

**Comment by YinYin-Falcon** [comment]
Sort of related to #376 and #449

You've fixed issues related to this (re/multi use + fury) plenty of times, so that's probably why it seems like a duplicate.

The most pressing issue here is, that this allows you to go into negatives and thus infinites.

**Comment by TerryCavanagh** [comment]
Fixed!
