### ISSUE TITLE
Crowbar + More Rats causes crash

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#546]
![image](https://user-images.githubusercontent.com/2874150/46434927-f49a6080-c74c-11e8-9f06-5b013ea4c9a1.png)

![image](https://user-images.githubusercontent.com/2874150/46434943-ff54f580-c74c-11e8-825c-cfb1e097bafb.png)

**Comment by onetruepurple** [comment]
Resolved in v0.16?

**Comment by TerryCavanagh** [comment]
Ah. I guess it is! Rats work differently now, so this doesn't come up. I guess a modder might run into this issue eventually, but that's not a priority for launch.
