### ISSUE TITLE
Batch files included with Crashdumper look suspicious

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#557]
People get paranoid when they see command prompts. For good reason!

![image](https://user-images.githubusercontent.com/2874150/46467052-c0fb1d00-c7c4-11e8-83f7-7354e09dd6d6.png)

Do we need these?

**Comment by mrcdk** [comment]
Those files recollect information about the computer like: CPU, GPU, memory, OS version,... That information isn't probably that important and we could remove them.

**Comment by TerryCavanagh** [comment]
Fixed.

**Comment by larsiusprime** [comment]
Done. Update crashdumper -- I added an option to turn off system data gathering, and it's now false by default.
