### ISSUE TITLE
Using Bear Charge while in Fury State causes infinite loop.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#560]
Bear was already in Fury state and for whatever reason I decided to try and repeat the next attack of Bear Charge.  I'm not sure if it also applies to Fury.  

https://drive.google.com/file/d/1b5hE4AYuut5ftQT_bnRmxnPhVEc4k6Io/view

**Comment by TerryCavanagh** [comment]
Fixed!
