### ISSUE TITLE
Font contrast of enemy level with some background colors needs adjusting.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#562]
Sometimes the background color and the font color of the enemy level have very similar saturation levels making them difficult to read. Screenshot has the fireman moused over and it's very hard to see ( lvl 3).

![font_contrast](https://user-images.githubusercontent.com/40739964/46575232-85f11900-c97f-11e8-870d-a22b34652467.jpg)

**Comment by TerryCavanagh** [comment]
Fixed.
