### ISSUE TITLE
Trading an equipped card for a card that's too large to fit in your equipped grid results in getting both cards

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#569]
At least, I'm guessing that's what it is. This was my inventory after an ultima weapon <> headbutt deal:
![](https://i.frogbox.es/l20)

**Comment by ncrecc** [comment]
(This is referring to trade deals)

**Comment by hunky-dory** [comment]
Still present in 1.0
![gif](https://giant.gfycat.com/VelvetyDopeyBarnacle.gif)
HD: https://gfycat.com/velvetydopeybarnacle

**Comment by ncrecc** [comment]
This got fixed
