### ISSUE TITLE
Jester cards that have been deleted or copied sometimes show up before the next fight.

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#573]
https://www.twitch.tv/videos/322513251?t=00h08m16s

**Comment by TerryCavanagh** [comment]
Haha, I might have underestimated finale builds a little 😅

**Comment by TerryCavanagh** [comment]
this is a very easy fix, and it looks very broken, so I'll just add it to high priority. It happens because some stuff isn't disposed of correctly.

**Comment by TerryCavanagh** [comment]
This one has been fixed for a little while!
