### ISSUE TITLE
The shopkeeper does not give grand finale+ for my dice cannon+ 

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#582]
The player just got the normal version of Grand Finale instead.

**Comment by YinYin-Falcon** [comment]
I was offered dice cannon+ for a dice cannon+.

**Comment by TerryCavanagh** [comment]
haha, yep, they shouldn't do that  😄 
https://github.com/TerryCavanagh/diceydungeons.com/issues/586

**Comment by YinYin-Falcon** [comment]
Oh yes.

I also once went back to the shop after my inventory/loadout changed, figuring they'd offer a new deal.

**Comment by TerryCavanagh** [comment]
Fixed!
