### ISSUE TITLE
Black screen on Mac build

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#591]
![screenshot_2018-10-13_at_18 59 55](https://user-images.githubusercontent.com/2874150/46916480-38922e80-cfb3-11e8-80c7-3606b1a38252.png)

```
I think the OSX version might be kaput -- I'm getting music but a totally black
screen on both an old Macbook Air and a new iMac (Interestingly I think I can
click on where a menu item might be by the sound)
EDIT: Actually not as bad as feared: the game doesn't work in windowed mode
on OSX
EDIT2: The game can be returned to windowed mode and work fine, it just
won't display anything if it starts in windowed mode
```

**Comment by TerryCavanagh** [comment]
Gif of it happening!

https://gfycat.com/KnobbyWarmAnnelid

**Comment by Wowfunhappy** [comment]
Odd, this is not happening on my 2015 Macbook Air, which is also running Mojave.

![screen shot 2018-10-29 at 11 59 24 am](https://user-images.githubusercontent.com/4484096/47662822-18956a00-db72-11e8-9030-dba7047ea4b6.png)

**Comment by TerryCavanagh** [comment]
It's a weird one - only one person has reported this, but it's happening on *both* their macs. Shrug emoji!

**Comment by mrcdk** [comment]
This is a macOS 10.14 (Mojave) bug more info and possible workaround here https://bugzilla.libsdl.org/show_bug.cgi?id=4272 

Apple deprecated OpenGL in this version of the OS so a fix from their side may not happen.

**Comment by Harrison-M** [comment]
For what it's worth, I got stuck on a black screen starting the game on Mojave, but it returned to normal after turning off dark mode.

**Comment by Wowfunhappy** [comment]
I can replicate! The bug only appears when I turn on dark mode! And then goes away when I set it back to light.

**Comment by TerryCavanagh** [comment]
Fixed!
