### ISSUE TITLE
Fourth card created by Match 3

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#592]
```this happened when I tried to match3 stumble```

![match3](https://user-images.githubusercontent.com/2874150/46916532-e43b7e80-cfb3-11e8-80cf-081972187545.png)

```
I guess the sweets just didn't get pushed back or something? I'm not sure 
if it's because I was doing things too quickly
the snap worked fwiw
```

**Comment by onetruepurple** [comment]
"Resolved" in v0.16
