### ISSUE TITLE
noclip

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#6]
![image](https://user-images.githubusercontent.com/3826749/37878969-f8b812fc-3070-11e8-9714-da53417314ee.png)

You can clip through things if you descend before arriving at the stairs.

**Comment by TerryCavanagh** [comment]
If you tap on the stairs and click "Descend" before the movement has finished, the movement continues on the next floor (and you can walk through and get stuck in walls) #71

**Comment by TerryCavanagh** [comment]
Fixed.
