### ISSUE TITLE
Jester - Dice Finale and Match 3/Snap Behavior.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#605]
Not a bug so much as an opportunity for the player to nerf/frustrate themselves.

When you have a Match 3 available and get to Dice Finale, using Match 3 then snap leaves you with (sometimes) lots of dice with nothing to do but end the turn. 

It would be better if Match 3 was prevented or an upgraded attack became available.

The player has gotten rid of their entire deck _and_ has filled their limit which might be deserving of a special attack.

**Comment by TerryCavanagh** [comment]
Fixed (snap no longer works this way!)
