### ISSUE TITLE
Pierce Spell has odd positioning

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#610]
Spanner and Pierce Spell are both two-slot 1x1 cards with one line of description. Compare:
![](https://i.frogbox.es/l38)
![](https://i.frogbox.es/l39)
Everything contained in Pierce Spell seems to be positioned as if it had two lines of description and not one.

**Comment by TerryCavanagh** [comment]
Fixed!

(This was actually a symptom of this issue - https://github.com/TerryCavanagh/diceydungeons.com/issues/1056)
