### ISSUE TITLE
Jester - Shocked Thief Card Has a Weird Name

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#611]
Shocked Thief/Magic Lockpick is called "Call For Backup Thief".

![shocked_thief](https://user-images.githubusercontent.com/40739964/47228603-a2378180-d393-11e8-8d20-6e4bd467e3d1.jpg)

**Comment by onetruepurple** [comment]
Not a bug

**Comment by lcenine** [comment]
So text that doesn't make a lot of sense and runs of the card is intended ?

**Comment by onetruepurple** [comment]
There's a Thief, serving as your backup, and the card calls for him

**Comment by ncrecc** [comment]
The card itself is just named "Thief". The shocked version shouldn't change it to "Call for Backup Thief".

**Comment by onetruepurple** [comment]
Not when you use the editor

**Comment by TerryCavanagh** [comment]
Fixed this one in v1.9!
