### ISSUE TITLE
Weakened Shield Grip+ won't accept dice.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#613]
And will often snap dice back. 

https://drive.google.com/file/d/1aGv2sB_t8QVYxwvvWNyFzxICPCNdnHIm/view

**Comment by pace212** [comment]
Reproduced in v0.15. Perhaps it's got a secret condition like "Total must equal 7" but the condition is not displayed?

![shield grip- wont accept dice](https://user-images.githubusercontent.com/38589027/50546919-dfbb5500-0bf5-11e9-951c-697610764bbb.png)

**Comment by TerryCavanagh** [comment]
Fixed - yep, this was secretly a "needs 9" slot, but wasn't displaying that info!
