### ISSUE TITLE
A flame without any animation remains on the bottom of the screen with the Jester

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#615]
The Jester can use the thief card to cut and split a random dice. If that dice is burnt, then a flame remains visible on the bottom of the screen and is not animated anymore.

**Comment by pace212** [comment]
I encountered this as well. Jester vs. Marshmallow, 2 dice burning. I selected Magic Lockpick, and when the dice went belowdecks, the fire went almost-belowdecks and stopped animating.

**Comment by TerryCavanagh** [comment]
This one's been fixed for a while! Closing.
