### ISSUE TITLE
Entering the shopkeeper's tent crashed the game

### ISSUE THREAD

**Issue by Malan-Tai** [TerryCavanagh/diceydungeons.com#616]
I was playing as Jester in 0.14. I have no idea what I did different than any of my other Jester runs, but here is the crash log.

crashed:	2018-10-22 11:50:43
duration:	00:36:35
error:		ERROR in callscenemethod(Barterstate,update) static : Null Object Reference, stack = 
Called from states.Barterstate.update (states/Barterstate.hx line 56)
Called from Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
stack:
haxegon.Scene.callscenemethod (haxegon/Scene.hx line 90)
haxegon.Scene.update (haxegon/Scene.hx line 53)
haxegon.Core.doupdate (haxegon/Core.hx line 252)
haxegon.Core.onEnterFrame (haxegon/Core.hx line 173)
starling.events.EventDispatcher.__invokeEvent (starling/events/EventDispatcher.hx line 184)
starling.events.EventDispatcher.dispatchEvent (starling/events/EventDispatcher.hx line 144)
starling.display.DisplayObject.dispatchEvent (starling/display/DisplayObject.hx line 778)
starling.display.DisplayObjectContainer.broadcastEvent (starling/display/DisplayObjectContainer.hx line 449)
starling.display.Stage.advanceTime (starling/display/Stage.hx line 108)
starling.core.Starling.advanceTime (starling/core/Starling.hx line 469)
starling.core.Starling.nextFrame (starling/core/Starling.hx line 455)
starling.core.Starling.onEnterFrame (starling/core/Starling.hx line 682)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

**Comment by onetruepurple** [comment]
#566

**Comment by TerryCavanagh** [comment]
Fixed!
