### ISSUE TITLE
Italian tester reporting for duty!

### ISSUE THREAD

**Issue by SellingSunlight** [TerryCavanagh/diceydungeons.com#618]
- In the title screen, I would translate "Quit" with "Esci", instead of leaving it in English. "Editor" has to remain "editor" because we don't have an Italian equivalent, but there's no sense in leaving untranslated words that can be translated!
![image](https://user-images.githubusercontent.com/21975245/47355407-94e70380-d6c1-11e8-8c1a-8f0ae66c402f.png)

- The "limit" bar has been translated with "limite", and it doesn't feel correct. "Limite" means "limitation". It doesn't carry the meaning of "limit break" you associate with the English word.
I'd adapt the world to something else entirely. Speciale (special)? Rabbia (rage)? Carica (charge)? Mumble.

- Fighter's ability "combat roll" has been translated with "lancio combattente" (throw fighter/fighting throw), which doesn't really mean anything.
![image](https://user-images.githubusercontent.com/21975245/47359028-e0061400-d6cb-11e8-9210-121672cece0a.png)
I'd translate it to "lancio del combattente" (fighter's throw), which feels more like the name of a special move. 

- HELLO, I AM HERE TO BE OVERTLY PEDANTIC
The UI messages switch between referring to the player in third or in second person. 
This happens in the English version as well, but it feels less noticeable because English doesn't have to conjugate verbs all the time, so it can sound more passive/impersonal.
![image](https://user-images.githubusercontent.com/21975245/47357338-ada5e800-d6c6-11e8-9de7-7e4153534192.png)
The Italian version reads as "Warrior wins! YOU found gold etc". But since _you_ are the warrior, it feels clashing.
Either translate the first part with "Hai vinto, *classname*!" (you won, "classname") to keep referring to the player, or change the second part to "trovati x oro e" to make the second more impersonal.

Other snippets here and there, like the game over screen, have the same issue.
![image](https://user-images.githubusercontent.com/21975245/47357784-07f37880-d6c8-11e8-85e3-f4fdc051a5a5.png)
"Warrior has been defeated..."

I wasn't sure about reporting this as an issue or not, because the Italian translation is a faithful translation of the English version, after all. As I said, I am just being very pedantic.

**Comment by TerryCavanagh** [comment]
Thanks for this! This type of feedback is super useful! If you play any more, please update the thread with anything else you find :)

(A lot of the time, untranslated stuff is my fault, not the translators - the translated script files are a little bit behind the current english version right now. "Quit" is a new word in the game, for example.)

**Comment by TerryCavanagh** [comment]
Have passed this on to my translator! Thank you - closing!
