### ISSUE TITLE
Game crash at the end of vampire boss.

### ISSUE THREAD

**Issue by Valkann** [TerryCavanagh/diceydungeons.com#619]
Hi, 
I had a bug at the end of the fight with the vampire, I used the stake to kill him but the game crashed.
Here is the error log.

[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/2511286/_error.txt)

**Comment by TerryCavanagh** [comment]
Oh, this was due to a missing skill for gadgetising the wooden stake. Fixed!
