### ISSUE TITLE
Crash when Warrior encountered Keymaster

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#620]
Warrior encountered the Keymaster and crashed. 

Crash log: 

--------------------------------------
filename:	diceydungeons
package:	com.terrycavanaghgames.diceydungeons
version:	0.12.1
sess. ID:	dicey_dungeons_2018-10-26_14'04'26
started:	2018-10-26 14:04:26
--------------------------------------
crashed:	2018-10-26 14:58:32
duration:	00:54:06
error:		Null Object Reference
stack:
elements.Floor.activatenode (elements/Floor.hx line 544)
elements.Floor.playerstep (elements/Floor.hx line 444)
Reflect.callMethod (C:\coding\haxe\haxe\std/cpp/_std/Reflect.hx line 55)
motion.actuators.GenericActuator.complete (motion/actuators/GenericActuator.hx line 155)
motion.actuators.SimpleActuator.update (motion/actuators/SimpleActuator.hx line 501)
motion.actuators.SimpleActuator.stage_onEnterFrame (motion/actuators/SimpleActuator.hx line 579)
openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 443)
openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1236)

**Comment by TerryCavanagh** [comment]
Fixed.
