### ISSUE TITLE
[Suggestion] Prevent Inventor from gadgetizing her last damage-dealing card

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#625]
Damage-dealing meaning anything from plain damage to status effects that can deal damage (burn, poison).
Obviously this would avoid the mistake of immediately turning your Hammer into a Jackhammer when you're new to the game. There might be a situation in that a player would _want_ to discard their last damaging card for a gadget that deals damage or a status effects, but it seems unlikely that they would have literally no other damaging cards in their inventory in that case.

**Comment by TerryCavanagh** [comment]
Not planning to do this! I think the new inventor design makes it very difficult to get into this situation anyway. Closing!
