### ISSUE TITLE
Explore ways to make inventor steal to gain enemy equipment a more deliberate thing

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#629]
There is a bug at the moment where it's possible to steal and keep enemy equipment while playing as Inventor, which can lead to some super fun layouts (and also make the character a bit easier, since it provides more equipment).

This is fun, and I want to keep it around in some form, but I want to make it feel more deliberate! So, think about some ways to implement this differently.

I think the "phrasing" of the steal gadget might help a lot here - maybe "Copy" is a more useful verb than steal, to get across the idea of permanently keeping equipment.

**Comment by ncrecc** [comment]
I think the Steal (Copy) gadget should be obtainable from more cards if it's going to be a highlighted aspect of Inventor. Maybe make it the default gadget? Or replace accelerator for "undefined" gadgets?

**Comment by TerryCavanagh** [comment]
Some interesting ideas there! Thanks, @YinYin-Falcon!

**Comment by TerryCavanagh** [comment]
Wish I'd explored some of those ideas back in 2018. Oh well 😀
