### ISSUE TITLE
Weakened Crystallize doesn't work

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#634]
It should just spawn a *temporary* weakened version of that attack.

**Comment by onetruepurple** [comment]
What if Weakened Crystallize had no effect?

It's very unlikely the player will have the ability to use Weaken 4 times in a turn. 3 is a possibility with Burrower, but the AI should know to put all the dice into the one Crystallize that's still normal, which still makes it a capable enemy in some regard.

**Comment by onetruepurple** [comment]
Resolved in RC1.
