### ISSUE TITLE
Jester softlocks with reusable gear

### ISSUE THREAD

**Issue by SomeGuyXG3** [TerryCavanagh/diceydungeons.com#64]
I had the reusable shield and when he borrowed it he used it and it never switched back to my turn.

**Comment by TerryCavanagh** [comment]
Yeah, looks like this one's a straight up crash! Thanks for the report!

**Comment by TerryCavanagh** [comment]
Ok, fixed! He's not smart enough to re-use reusable equipment yet, but at least it doesn't crash anymore
