### ISSUE TITLE
New AI: Enemies prefer to just deal damage than inflict status, which is technically correct, but less fun

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#640]
Examples:
 - Given the choice between a bark and a bite, the Wolf Puppy will always bite if it can do either or not both.
 - The Dryad will pick Magic Missile over Poison slingshot, if she can't do both.
 - Kraken will basically always use Overwhelm instead of blinding dice, as the score for using Overwhelm quickly passes out the score for inflicting 3 blind.
 - Banshee will just place a 6 in Lament instead of Silencing you.

All these moves are all technically the correct moves for the AI, but it's less fun for the player. I need some sort of system to identify a preference of equipment for enemies to deal with situations like this.

It might be tempting to fix this by reversing the score incentives on status effects and dealing damage - but that probably wouldn't work. Lament deals as much "status" as shriek does, but ALSO deals damage. And Overwhelm will eventually outscore Ink Splat unless the scores are very dramatically tweaked.

**Comment by pace212** [comment]
I suggest that enemies prefer dealing status early in the fight and dealing damage late in the fight. This is only optimal for Poison, but I think it will feel more intuitive to the player. Perhaps "% of max HP" could be an indicator of whether it's early or late in the fight.

**Comment by TerryCavanagh** [comment]
Ok, I've solved this for v0.15! There are some particular cases that aren't quite right at the moment, but the general solution is fine for this build.

(Appreciate the thoughts, by the way! Will be an ongoing process to perfect this new system!)
