### ISSUE TITLE
Rare crash bug with Bear using new AI

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#641]
I've had a single case of a Bear getting caught in a seemingly infinite loop, where it couldn't decide on a move. This has only happened once and I don't have a graph file for it. I can't reproduce it.

When it happened, I was shocking all but one of the Alchemist's potions, and she chose Bear Transform when she still had other potions left. The freeze happened on the Bear's next turn. They had a 6, 2, and a burning 5, and Maul was shocked. They used the 2 to unshock Maul, and then the game froze.

**Comment by sandman98321** [comment]
I just had the same thing happen against Super Alchemist.  Same circumstances--Alchemist transformed, ended turn.  Then Bear's turn came, he did his first attack, unfroze Maul, and then is now sitting there with a 4 that's playable refusing to play it.  I missed the dice on the first 2 rolls.  It seems more like an interaction with the Shocked dynamic somehow?

It it makes any difference, I'm in challenge...3? The one with reducing hit points.

**Comment by TerryCavanagh** [comment]
This was the Alchemist shock bug, and it was a nightmare to track down! Thankfully, it's fixed as of v1.8.
