### ISSUE TITLE
Dice lerp to the wrong location when AI use equipment that creates more equipment

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#643]
For example, cards like Bear Transform, Mystery Box, or Yoink. It's due to the new changes in combat timing.

**Comment by onetruepurple** [comment]
Still valid in v0.17 (Crystallize).

**Comment by TerryCavanagh** [comment]
This one was fixed, but then broken again in v1.9 in some situations, grr. (hence https://github.com/TerryCavanagh/diceydungeons.com/issues/1959). Gonna look into it again and hopefully fix it forever for v1.10.

**Comment by TerryCavanagh** [comment]
Ah: I'd manually added delay functions to some giveequipment equipment, but not all. I've now implemented across everything, so this should be fixed properly now.
