### ISSUE TITLE
Consider a radical redesign for Sorceress

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#644]
There's an opportunity to do something cool here to showcase the new AI. Sorceress works in her current form, but feels like a bit of a black box. Consider making her more like the player Witch, with a real spellbook that can summon equipment.

**Comment by onetruepurple** [comment]
Resolved in v0.16?

**Comment by TerryCavanagh** [comment]
Yeah. Not gonna do the mirroring the Witch thing anymore!
