### ISSUE TITLE
Wizard's "must use all dice" rule means that it unshocks equipment it doesn't need to

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#645]
In order to satisfy the new "must use all dice rule", Wizard unshocks equipment it doesn't need to, which doesn't look deliberate. It's harmless, but it looks bad.

It's a subtle problem too, because if you turn that off and fix it by giving bonus points to backfire, say, the AI will then go out of it's way to use backfire, which I don't want. Say we have a shocked Hall of Mirrors and a 1 - I would like the Wizard to use the 1 to unshock Hall of Mirrors, ideally.

**Comment by onetruepurple** [comment]
(Resolved in v0.16)
