### ISSUE TITLE
Handyman will use a spanner with a six, even though it's pointless

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#646]
I'm not quite sure why this is happening - minimising turn lengths should in theory prevent this. It's harmless, but not necessarily worth digging into.

A quick fix is to adjust the spanner script to give -1000 bonus points if either dice is a six.

**Comment by onetruepurple** [comment]
Spanner- is already two MAX3 slots. Why not make Spanner MAX5?

**Comment by TerryCavanagh** [comment]
Fixed!

(decided against adding a dice restriction to Spanner because (a) there are some interesting edge cases with null operations that I don't want to close off and (b) it looks slightly nicer not to have restrictions on equipment, where possible.)
