### ISSUE TITLE
Pea Shooter should roll over

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#647]
AI simulations expect reusable countdowns (i.e. the Pea Shooter) to "roll over" - so using a six on it would take 1 off the next countdown. This is a nice behaviour, and you should implement it!

**Comment by Wowfunhappy** [comment]
I feel like this takes away a significant layer of strategy to the countdowns?

If I have a 7 countdown, should I use a 6 die now so I only need to use a 1 later, or should I blow my 6 on something else and use 3 on the countdown, since if I have a bigger dice next turn, the extra goes to waste.

**Comment by TerryCavanagh** [comment]
Oh, I just mean reusable countdowns, not all of them! Right now, this is literally just the Pea Shooter :)

**Comment by Wowfunhappy** [comment]
Oh, that makes sense! But... isn't it odd to have it function differently for reusable equipment? I would intuitively expect countdowns to behave exactly the same whether or not they are reusable in a single turn, with the one exception that I don't have to wait until next turn to reuse.

**Comment by TerryCavanagh** [comment]
I'm not sure. With testing, I've seen people act like they definitely expect a reusable countdown to loop around, so it could be an issue of expectations because of how they currently work. Will find out when I try it - could end up reverting it if it's confusing!

**Comment by TerryCavanagh** [comment]
Nah. Closing.
