### ISSUE TITLE
Fix Rat King

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#650]
Rat King is broken due to a number of complications with how the new AI works.

**Comment by onetruepurple** [comment]
Resolved?

**Comment by TerryCavanagh** [comment]
*nearly*, I think. I've had a bit of trouble getting Rat King to work as an enemy, and the v0.17 edition feels as close as I've gotten. But it still needs a tweak, I think...

**Comment by TerryCavanagh** [comment]
(Oh, this was about technically broken, not design broken - well, will leave this open until I sort it out)

**Comment by TerryCavanagh** [comment]
Oh, this is fine now.
