### ISSUE TITLE
Cornelius could be optimised

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#651]
As soon as you get 6 or more dice, the AI starts to really struggle, and you can notice it taking time to think. Cornelius in particular could be massively optimised, because they're just trying to do a very simple thing - dump the highest values they can on Nightmare.

Create an alternate AI mode that simplifies these decisions to speed up the game.

**Comment by ncrecc** [comment]
If a simplified AI is made for Cornelius, note it will still have to take the Rock from Bully's rule into consideration

**Comment by JuniorUdale** [comment]
Ideally this would be generalized to any enemy with a single countdown item - Super Space Marine also starts to slow the game down quite a bit.

**Comment by TerryCavanagh** [comment]
We've made some fixes here for v1.11, and the AI is now much better at dealing with large numbers of dice like this! Fixed.
