### ISSUE TITLE
Robot Should be Negatively Affected by Freeze

### ISSUE THREAD

**Issue by timeracers** [TerryCavanagh/diceydungeons.com#666]
Freeze should make dice roll like normal before freezing, so that cpu is wasted.

**Comment by TerryCavanagh** [comment]
Hah! That's good - it's really harsh, but I like it :)

**Comment by TerryCavanagh** [comment]
I still sorta love this evil suggestion, but no longer planning to implement it. Getting frozen as Robot is a lot of fun, so I'd like to leave it as is.
