### ISSUE TITLE
Simplify Monster Extra HP

### ISSUE THREAD

**Issue by timeracers** [TerryCavanagh/diceydungeons.com#670]
This would simplify the job of balancing enemies by simplifying the calculation of extra hp. I think a good formula would be: EXP stars over the level of the monster.
Examples:
LVL 1 warrior + 2 stars versus LVL 2 monster: +0
LVL 2 warrior + 0 stars versus LVL 2 monster: +0
LVL 3 warrior + 0 stars versus LVL 2 monster: +8
LVL 2 warrior + 4 stars versus LVL 2 monster: +4

**Comment by TerryCavanagh** [comment]
responded on this discord:

```
Not sure I'm into this - this just seems like it makes it even harder to build an intuition for
the change I'm actually considering here is to just remove the HP increases completely, and adjust the actual monster HP by level to compensate
something like +4 for level 1 enemies, +8 for level 2, etc
```

**Comment by TerryCavanagh** [comment]
Ok, changed all the enemies hp to *not* increase after each fight. This is a very overdue simplification!

![image](https://user-images.githubusercontent.com/2874150/50045490-c5c53280-008b-11e9-8572-1fda8b7ff2a4.png)
