### ISSUE TITLE
Anvil icon on the level up screen is low resolution

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#672]
As observed here: https://i.imgur.com/FcNbnmX.jpg

**Comment by pace212** [comment]
Oh good, it wasn't just my eyes. I agree, Anvil looks like it was low-res and scaled up. It looks fine on the walking-around screen, but on the "Choose ONE additional reward" screen, the blurry-ish shading of the anvil looks out of place next to the crisp lines of SHIELD GRIP.

![big anvil looks blurry or low-res](https://user-images.githubusercontent.com/38589027/50546979-e9918800-0bf6-11e9-8301-f57a815d95b6.png)

**Comment by TerryCavanagh** [comment]
Fixed!
