### ISSUE TITLE
First usage of Overwhelm deals 0 damage

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#680]
The card description implies it starts at 1 damage and goes up every time it's used, but in this version it starts at 0 damage and only starts doing damage the second time it's used.

**Comment by pace212** [comment]
Reproduced. Looks like a dupe (or a reincarnation) of #392 way back from v0.10

**Comment by TerryCavanagh** [comment]
Fixed!
