### ISSUE TITLE
Stealing boss item "Dragon's Breath" crashes the game

### ISSUE THREAD

**Issue by ikdzu** [TerryCavanagh/diceydungeons.com#683]
Playing as Thief.
Quest was Finders Keepers.
After defeating the Dragon boss, I was given one option of (I believe it's called) "Dragon's Breath".  After choosing this, the game crashed with a null reference.

[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/2716836/_error.txt)

**Comment by TerryCavanagh** [comment]
Thanks for the bug report - fixed! (Stealing any oversized equipment was causing a crash, but I've made all equipment a reduced size now, so this can no longer happen)
