### ISSUE TITLE
Some battle sprites (e.g. dice and fire) stick around on You Win screen

### ISSUE THREAD

**Issue by pacesmith** [TerryCavanagh/diceydungeons.com#686]
If, as the enemy is about to die, you quickly pick up a dice by holding down the mouse button, when the enemy finishes dying, the dice is still visible on the You Win screen.

Similarly, if your dice are burned when you win, the top bit of the flickering flame is still visible on the You Win screen. I think it's cool but it might look like a bug to others.

**Comment by TerryCavanagh** [comment]
This one is fixed in recent versions! Closing!
