### ISSUE TITLE
Animation/performance is choppy (laggy, drops frames)

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#688]
The animation/performance is choppy in v0.15; it doesn't feel/look smooth. For example, when I'm just dragging a dice around, it drops a lot of frames. And sometimes the music pauses for a second during scene transitions. It happens almost every time on the You Win screen when You Win has almost but not quite lerped up off the screen, and sometimes when I first start fighting an enemy and my equipment is lerping onto the screen. I don't currently have any screen recording software installed, so I'm hoping someone else will report a duplicate of this so you can see what I'm talking about.

Win64 laptop i7 1920x1080 NVidia GeForce GTX 1060

**Comment by TerryCavanagh** [comment]
Thanks for creating an issue about this. We're overdue an optimisation pass!

It looks like your screen resolution is low enough that the 4K assets shouldn't have kicked in, so this is separate to https://github.com/TerryCavanagh/diceydungeons.com/issues/709.

Other related messages from dicecord:

![image](https://user-images.githubusercontent.com/2874150/50616900-66b44a00-0ee2-11e9-8856-2c0f4b0e21fc.png)

![image](https://user-images.githubusercontent.com/2874150/50616905-6caa2b00-0ee2-11e9-9f3e-d6fbf9c8eb6c.png)

![image](https://user-images.githubusercontent.com/2874150/50616917-73d13900-0ee2-11e9-8b74-2346cc19cb9d.png)

**Comment by TerryCavanagh** [comment]
It appears that the memory leak fixes have dealt with this! Closing!
