### ISSUE TITLE
You can sneak in an extra Calculate in No Going Back

### ISSUE THREAD

**Issue by pacesmith** [TerryCavanagh/diceydungeons.com#691]
If you use equipment and then quickly press Calculate, you can get an extra dice. This is often too dangerous to be worth risking, but in many cases it is free cheese. 🧀

**Comment by YinYin-Falcon** [comment]
It's pretty viable still before levelling up.

**Comment by TerryCavanagh** [comment]
Oh, this episode was removed before launch, and there's no implementation of this "No Going Back" rule in the game anymore, so I guess I can close this!
