### ISSUE TITLE
Don't prompt the player for a filename when saving a screenshot

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#692]
Just use anything like "screen0001" so long as the game doesn't forcibly suck me out of the gameloop.

**Comment by onetruepurple** [comment]
Still valid in RC1.

I feel really strongly about this, it's unusable currently. I use Alt+Print Screen every time instead.

**Comment by TerryCavanagh** [comment]
On steam this uses the built in steam api now, which I think makes it a non issue.
