### ISSUE TITLE
Vampiric Tendencies is kind of unbalanced

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#694]
It's a lot of fun, but most of the time it's cruising through the game on autopilot until the boss, where it becomes a 50:50 chance of winning - not really a quest worthy of level 3 in my opinion.

It would be a lot more balanced/challenging if the game had a rare "Life Steal on 6" kind of sword item that was then a starting item in the quest (as per #695).

**Comment by TerryCavanagh** [comment]
Yeah, agree that this one needs work! But I like the idea, and wanna try another iteration of it to see if I can fix the problems.

(think it probably needs a more in depth equipment shuffle)

**Comment by onetruepurple** [comment]
Resolved in v0.16.

**Comment by TerryCavanagh** [comment]
Thank you for the equipment idea! :)
