### ISSUE TITLE
Implement more "special action on 6" items

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#695]
Items like Hammer/Shovel/Whip/Rubber Mallet are fun, especially with the Warrior, Inventor, and Jester, so why not have some more? Such as:

- Pierce Armor on 6.
- Blind _n_ Dice on 6.
- Freeze _n_ Dice on 6.
- Life Steal on 6. Good for #694!
- Curse on 6.
- Silence on 6. Right now the effect does nothing to enemies, but it's been suggested several times that it should disable their innate abilities for the turn.
- Borrow Equipment on 6. This could be called a Fishing Rod, or something.
- Deal _n_ poison on 6.
- Megabump on 6.
- Reroll all dice on 6.

Etc!

**Comment by TerryCavanagh** [comment]
This is a very good suggestion! Gonna try adding a weapon like this to the next iteration of Vampiric Tendencies!

**Comment by onetruepurple** [comment]
As of v0.17 the game features four of the suggested items on the list, and also others. Safe to say this can be closed.
