### ISSUE TITLE
Make Confuse work on enemies as well

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#696]
Right now Confuse does nothing to enemies - but what if you extended that effect to make them pick a suboptimal result from the decision tree for a turn?

This is an extension of #695, since Rubber Mallet already exists.

**Comment by onetruepurple** [comment]
This was referring to the old Confuse effect. I've no idea how would the AI even be able to fake being Confused. Leaning towards closing this.

**Comment by onetruepurple** [comment]
Potential solution present in #1713.

**Comment by TerryCavanagh** [comment]
Yep, closing this issue as it's basically an older version of the more modern https://github.com/TerryCavanagh/diceydungeons.com/issues/1713!
