### ISSUE TITLE
Issue with flight from the loud bird and actions not causing any damage

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#698]
Flight is supposed to prevent any damage done on the loud bird, but on my last run I remarked that Thief's duplicate ability has been cancelled because of it, even if it is not a damage based action. Is it normal behaviour ? I'm not sure it happened previously on v0.14.

**Comment by TerryCavanagh** [comment]
This specific issue is fixed! Dodge still needs a bit of a rework, but there's another issue for that. Closing!
