### ISSUE TITLE
Try a weapon that does more damage with low health

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#702]
This could work *really* well with the warrior low health quest.

**Comment by TerryCavanagh** [comment]
(related: lightning rod might be interesting to throw into that quest!)

**Comment by Thunder33345** [comment]
warrior already has low max hp due to losing hp over lvup

**Comment by TerryCavanagh** [comment]
This is now the starting weapon in parallel universe!
