### ISSUE TITLE
weird german translation

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/diceydungeons.com#703]
For "Kletterhacken" the description is "Nächst Ausrüstung Ausrüstung" which I cannot make sense of

<img width="312" alt="bildschirmfoto 2019-01-01 um 04 56 14" src="https://user-images.githubusercontent.com/465632/50571656-703d9500-0db0-11e9-94d5-20413ed738c0.png">

**Comment by increpare** [comment]
What does it say in english? (is there a table anywhere with the translations?)

**Comment by increpare** [comment]
Ah, "Reuse next equipment".  Yeah, "Nächste Ausrüstung zurückholen" makes more sense to my non-native ears.  

(other question - would Enterhaken be better than Kletterhaken? :P Or just Haken? not so important tho...)

**Comment by TerryCavanagh** [comment]
Looks like this one is fixed?
