### ISSUE TITLE
working out and working out in warrior description

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#710]
![image](https://user-images.githubusercontent.com/3826749/50607231-c56cca00-0ec8-11e9-9d6b-f819fc29ce3b.png)

"I love working out [...] and working out"

I get that he's not the brightest, but this is over top isn't it?

**Comment by TerryCavanagh** [comment]
This is basically exactly what we're going for with the writing, haha. Maybe stick with it for a few more versions, see if it grows on you when there's more text in the game!

**Comment by YinYin-Falcon** [comment]
Good to know.
I'm sure it'll grow on me with more writing.

Maybe adding an ellipsis instead of a comma after the beach to really drive the point home and make certain there are no doubts about a copy paste error would help!
