### ISSUE TITLE
previewing enemy cards while one of your own is animating gets it stuck in that animation

### ISSUE THREAD

**Issue by YinYin-Falcon** [TerryCavanagh/diceydungeons.com#712]
Insert a dice into one of your cards and click preview before it gets to do anything.
![stuckcard](https://user-images.githubusercontent.com/3826749/50609973-9dce2f80-0ed1-11e9-96fb-e9f79cb7db90.gif)

**Comment by mrcdk** [comment]
This is fixed, you can't click the preview button while an action is being played.
