### ISSUE TITLE
Try starting the inventor without Scrap Metal

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#714]
Starting with Scrap Metal adds an extra layer of confusion to the inventor. Instead, try starting with 3 distinct weapons.

![image](https://user-images.githubusercontent.com/2874150/50615525-d8899500-0edc-11e9-8379-5c6ddb82a59d.png)

![image](https://user-images.githubusercontent.com/2874150/50615520-d45d7780-0edc-11e9-8df6-61b263f21e3c.png)

![image](https://user-images.githubusercontent.com/2874150/50615535-e212fd00-0edc-11e9-859e-65ce27f80737.png)

**Comment by Thunder33345** [comment]
agreed, under that scrap metal is kinda just junk anyways to begin with

and it's a wordless tutorial that dosent kill the player,
even if they dont know it removes the equipment
it's still something they can live with if they still had 2 weapon left

**Comment by TerryCavanagh** [comment]
Ok, trying something new here for v0.16. Let's see how it goes!
