### ISSUE TITLE
Reduce available equipment in Finders Keepers

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#720]
The fun of this quest is using stolen equipment, so probably best to radically reduce the amount of found equipment in the dungeon. Some player equipment is interesting and fun to mix in - counterfeit device, lockpick, crowbar, etc - but most still you find is just junk compared to what you can steal.

Finders Keepers should probably also be a late thief quest - it's only really satisfying once you're familiar with the range of available enemy equipment, and feels like a nice "reward" when you get to that point. Maybe swap it with uptick?

**Comment by onetruepurple** [comment]
I think this is in a good place now.
