### ISSUE TITLE
Change copycat to have a steal innate

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#721]
"Yoink" is a weak piece of equipment that's probably best removed from the game. Instead, give Copycat an innate that just steals all the player's equipment, and move them up to level 3.

**Comment by onetruepurple** [comment]
(Resolved in v0.16)

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/58630741-3f6a7900-82d8-11e9-91eb-74afa08f177e.png)
