### ISSUE TITLE
Steal gadget can result in a soft lock

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#732]
```
was playing inventor vs keymaster, and had a gadget that stole enemy abilities. Used it immediately as my turn began, now dice slot into abilities but dont get used, there is no "end turn" or enemy equipment buttons
```

**Comment by TerryCavanagh** [comment]
![dicey_dungeons_2019-01-19_00-16-28_en](https://user-images.githubusercontent.com/2874150/51979868-2e267280-2486-11e9-8832-f28d1671b978.png)

Another recent case

**Comment by mrcdk** [comment]
This is fixed, you can't interact with the equipment buttons while they are animating into the screen.
