### ISSUE TITLE
Graphical glitches in text rendertextures on Ubuntu

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#771]
(See the character description)

![lines](https://user-images.githubusercontent.com/2874150/50743223-1d7b3780-120d-11e9-9185-0c49f3c84bf1.png)

This used to happen on Mac, fix might be worth applying to all operating systems.

**Comment by lanxu** [comment]
Just to let you know that this happens to me on my Arch Linux installation. I am using Mesa drivers with Radeon RX 580. Thanks for supporting Linux.

**Comment by paxed** [comment]
Also happens on Debian testing with NVidia GeForce 210, using the nvidia legacy drivers

**Comment by TerryCavanagh** [comment]
Fixed in v0.17.2!
