### ISSUE TITLE
Cleared encounters repeatable with clicks after another encounter is 'bumped'

### ISSUE THREAD

**Issue by ciaphas01** [TerryCavanagh/diceydungeons.com#772]
See: https://i.imgur.com/siHDt2G.mp4

Pasting my notes from earlier; apologies for the lousy grammar, they were hurried.

clicked on encounter, clicked away enroute (near end of travel), entered combat after entering cleared-encounter node, fought that previous encounter a second time

received full rewards, no effect on originally clicked encounter

repeatable

**Comment by TerryCavanagh** [comment]
Ahh! Great, thanks for this report! I'll make sure it's fixed in v0.15.1 :)

**Comment by TerryCavanagh** [comment]
Fixed! Thanks!
