### ISSUE TITLE
Sneezy shouldn't put 1's into Pop

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#773]
Just takes more time than needed.

**Comment by TerryCavanagh** [comment]
Yeah, good point! Not sure why this is happening, to be honest - I think the score function's tendency to want to use all equipment, while normally very good, just leads to some weird behaviour like this.

**Comment by YinYin-Falcon** [comment]
Just give it a min 2.

**Comment by onetruepurple** [comment]
No, because it's a MAX4.

**Comment by YinYin-Falcon** [comment]
Oh right ... and no smart way of combining limits yet ...

**Comment by onetruepurple** [comment]
It's already an unlimited slot when upgraded, which makes him practically immune to shock on Hard, which considering the damage output on Hard makes him a much tougher enemy than he usually is on v0.15

**Comment by onetruepurple** [comment]
Reopening on account of Hard Sneezy still slotting 1's into Sneeze+.

**Comment by TerryCavanagh** [comment]
Fixed!
