### ISSUE TITLE
Should there be a 9999 cap on status effects

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#776]
Blight doubling poison got ... a little out of hand on one particular playthough.

But what should happen? A cap stops crashes, but maybe there's a better acknowledgement or something?

**Comment by YinYin-Falcon** [comment]
An achievement.

Bringing the Vampire to maximum poison is a special kind of cruelty.

**Comment by DiceWithDeath** [comment]
Ahaha, that's hilarious. And I thought 68 poison was impressive!

Does it need to be as high as 9999 - isn't 999 enough?

Agree with an achievement.
'You've been arrested for treason. Don't you know plotting to poison is an offence?' and you get slammed in jail. Secret game ending. ;)

**Comment by Thunder33345** [comment]
maybe make it 999,999 because 9,999 is as arbitrary as 999

**Comment by YinYin-Falcon** [comment]
The exact cap would be down to the graphic design, not an arbitrary number.

Another special acknowledgement could be making the Vampire flee in terror.

**Comment by TerryCavanagh** [comment]
This can technically cause a crash, so I should try to fix it even if the cap is MAXINT or whatever.

**Comment by TerryCavanagh** [comment]
Ok, done. You can't inflict more than 9999 of a status anymore! Personally I think discovering the limit will be as satisfying as crashing the game because you've exceeded MAXINT 😄
