### ISSUE TITLE
v0.15.1 Quest notes: Thief - Finders Keepers

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#778]
- Try finding less equipment in this mode - maybe even none, apart from level up rewards and starting equipment
 - Try having a *limit* on the total number of equipment steals by making the Finders Keepers card destroyed after use, and giving the player 5 or so to start with. You could offer more in shops/level up rewards.
 - Making Finders Keepers an ordinary equipment card means you'll need a replacement skillcard - or, you could just unlock all 8 equipment slots?
 - Unlucky roll is a less good fit here than for other Thief quests. What are some possible alternatives?

**Comment by TerryCavanagh** [comment]
Here's a kind of "all in" variation idea: instead of the Finders Keepers equipment, have the thief steal a random piece of equipment from the enemy every turn. For the skillcard, have a button below the stolen card that says "Keep".

**Comment by onetruepurple** [comment]
I would dislike removing Finders Keepers as a permanent skillcard and putting a limit on steals, that would just take the thieving out of the Thief.

If balance is a problem, perhaps you could disable the one-per-turn restriction of the card, but then restrict it to only picking one enemy equipment at random? So you could end up stealing more than one item, but you couldn't control which one you steal.

This quest also makes Crowbar much more useful than Poison Needle, to the point where I'd recommend changing the level up rewards in this quest.

To be fair, I think Finders Keepers is an improvement over the normal Thief gameplay that I'd be seriously thinking about making it the way Thief works, period, but that's probably a discussion outside the scope of this ticket...

**Comment by TerryCavanagh** [comment]
>To be fair, I think Finders Keepers is an improvement over the normal Thief gameplay that I'd be seriously thinking about making it the way Thief works, period, but that's probably a discussion outside the scope of this ticket...

I'm considering this! But I think having full on enemy equipment builds is better kept back a little, since it kind of spoils the mechanics a little, and playing well depends on having a good knowledge of enemy equipment. Imagine if a new player's first Thief game was this enemy equipment mode - I think it'd be pretty overwhelming!

**Comment by TerryCavanagh** [comment]
Still some issues to think about here.

**Comment by TerryCavanagh** [comment]
I'm fairly happy with how Finders Keepers works now. No longer planning to make any changes here.
