### ISSUE TITLE
v0.15.1 Quest notes: Thief - Uptick

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#781]
One of the weaker quests, probably - Countdown (for Witch) is similar, but much more interesting.

Can this quest be saved? How could it be made more interesting?

**Comment by YinYin-Falcon** [comment]
What if the uptick carries over between fights?

**Comment by TerryCavanagh** [comment]
Uptick is probably the weakest episode in the game. I have some ideas to fix it that I think will work, though. If they don't, consider a brand new episode instead.

**Comment by onetruepurple** [comment]
Resolved in RC4

**Comment by TerryCavanagh** [comment]
Yep, really happy where this landed! Closing.
