### ISSUE TITLE
v0.15.1 Quest notes: Robot - No going back

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#782]
I really like this one - it's great how making one tiny change to the core rules changes it so much. Some notes:

 - Need to change the level up rewards here - heat sink is obviously useless. Increment is still useful, though.
 - It does feel like this quest is missing something - one little twist or extra thing that could push it further.
 - I considered increasing the player's starting CPU for this quest, but having watched a number of playthroughs now, I'm not sure that's needed. The real problem to fix here is maybe figuring out to make the starting loadout fairer. Maybe replace Plasma Blaster with Auto Dagger, like with Dice for a Price?

**Comment by DiceWithDeath** [comment]
I feel this one pretty challenging already - not necessarily hard to win, but it takes some thought. Maybe a 'twist' in terms of something fun, but doesn't need to be any more complex.

Could the items that are useless for this quest be removed/made so they can't show up? You've mentioned heat sink, but there's also the one that increases the jackpot range. I suppose it's not entirely useless with Increment, but I wouldn't use two slots on that personally.

**Comment by YinYin-Falcon** [comment]
Definitely keep everything that allows getting a jackpot after disabling the counter in. Increment, range increase, all of it. I'm much more inclined to go for that when I can't use dice as they come in and error out at the end. A lot better than standard robot.

**Comment by TerryCavanagh** [comment]
Bug: you can safely use countdowns partially without losing access to the calculate button.

**Comment by TerryCavanagh** [comment]
I've gone off the episode in a big way, and I'm going to try something else for launch.
