### ISSUE TITLE
v0.15.1 Quest notes: Warrior - This'll be fine

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#783]
This works pretty well! Probably shouldn't be the second warrior quest, though, as it introduces an upgraded equipment loadout a little too early.

 - The alternate starting weapons are meant to make the initial loadout less susceptible to curse, which works, but could they be something more interesting?
 - Avoid the strong temptation to add an anti-curse piece of equipment to this quest - ultimately I think it'd just spoil it, for a similar reason as to how fuse kinda spoils Dice for a price.

**Comment by onetruepurple** [comment]
`The alternate starting weapons are meant to make the initial loadout less susceptible to curse, which works, but could they be something more interesting?`

Two Battle Axes!!

**Comment by TerryCavanagh** [comment]
Awesome :D Trying that out for v0.16.1!

**Comment by onetruepurple** [comment]
I'm doing ~40 damage by floor 4. This may or may not be a good thing.

Worth considering some changes to the skillcard and/or limit break for this one.

**Comment by TerryCavanagh** [comment]
Haha, great. Yeah, maybe with the upgraded equipment, this one would work better with some bonus applied to the enemies - even a hp bump would help. Will try some stuff out!

**Comment by TerryCavanagh** [comment]
With the changes made since v0.16, I think this is fine as warrior episode 2. The horizontal rules mean that you have to have played at least five games first, so that's fine. Closing!
