### ISSUE TITLE
Meteor- probably shouldn't be "No effect"

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#789]

**Comment by TerryCavanagh** [comment]
Fixed! (absolute zero too, while I was at it)

![image](https://user-images.githubusercontent.com/2874150/58631641-1d262a80-82db-11e9-8427-1763accb7c0e.png)

![image](https://user-images.githubusercontent.com/2874150/58631649-22837500-82db-11e9-9264-56565ac94806.png)
