### ISSUE TITLE
Fix up robot locked equipment

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#792]
Robot locked equipment is essentially hardcoded right now. Fix it up properly so I can actually create some new ones!

Specific issues:
 - [x] It's not possible to make arbitrary locked equipment
 - [x] It's not possible for it to be any colour other than red
 - [ ] Equipment with more than once dice slot (e.g. rocket launcher) doesn't show that when locked
 - [x] It might be interesting (especially for Dice for a price) to have some locked equipment with lower counts.
 - [x] Ruby Weapon: Five dice to unlock, does double damage.

**Comment by ncrecc** [comment]
Dragon's Tooth is a non-red locked equipment, and I'm not sure what "arbitrary locked equipment" refers to but modding in locked equipment is possible now if it wasn't before.

**Comment by TerryCavanagh** [comment]
Yep, most of this is fixed now! I'm going to create a new issue for the one factor of this which isn't. https://github.com/TerryCavanagh/diceydungeons.com/issues/1976
