### ISSUE TITLE
Weird softlock bug with Loud Bird

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#795]
Not sure what's going on here. Seems to be related to a broken countdown, but for an enemy where it shouldn't occur.

![tempsnip](https://user-images.githubusercontent.com/2874150/51076173-f5685a00-168c-11e9-82ee-d53219f7601c.png)

```
Squawk had somehow ended up with a value of 0, so when the AI
tried to apply a die to it, game stopped. Animations etc. continue,
but AI wont move dice or end turn
```

**Comment by DiceWithDeath** [comment]
Just had this in this game, caused by my weakening (and then Loud Bird using the weakened Squawk, dunno if that's required for it to be stuck?)

**Comment by onetruepurple** [comment]
Happened to me again in v0.16:

![image](https://user-images.githubusercontent.com/2095534/53652157-77660f80-3c48-11e9-8dbb-25c1fbef3a82.png)

Seems like as much as #494 is the culprit, this behavior seems to be exclusive to the AI trying to use Squawk.

**Comment by TerryCavanagh** [comment]
Fixed.
