### ISSUE TITLE
Audio settings are not saved between games

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#798]
Everything returns to 100% after restarting.

**Comment by larsiusprime** [comment]
Done. For now audio settings are saved when you close the audio menu, and loaded from settings right after audio channels are initialized.

**Comment by TerryCavanagh** [comment]
🎉

**Comment by ncrecc** [comment]
This seems to have been undone!

**Comment by ncrecc** [comment]
Or perhaps it just resets audio settings to default if the game crashes.
