### ISSUE TITLE
Wizard needs a new spell book

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#801]
- [ ] Backfire feels like a relic, and it's special AI rules feel like they're a kludge
 - [ ] All of the individual spells feel like they come from an earlier version of the game, in fact.
 - [ ] Maybe dodge is more fun here than shield? Or armour.

**Comment by onetruepurple** [comment]
Or: consider replacing Backfire with a NEEDS1 spell that rolls a single burning dice - this would keep some of what made Backfire funny, but also be more interesting than raw damage, and could do something funky when upgraded like roll two burning dice.

**Comment by YinYin-Falcon** [comment]
I like the idea of all six colours and replacing backfire with damaging reroll.

How about

1: freeze
2: crucible (fire is commonly 2/even)
3: heal
4: dodge (teleprort or levitation!)
5: magic armor
6: hall of mirrors

**Comment by TerryCavanagh** [comment]
Thanks for the suggestions!

Here's what I'm trying for v0.16. It amounts to a slight buff all round, and gets rid of backfire:

    1: Freeze Spell
      Do 5 damage, freeze 3 dice
    
    2: Teleport Spell
      Dodge next attack
      
    3: Earth Spell
      Do 5 damage, weaken 3 equipment
    
    4: Poison Spell
      Inflict 4 poison
        
    5: Fire Spell
      Do 5 damage, burn 3 dice
      
    6: Hall of Mirrors
      Extra dice next turn
