### ISSUE TITLE
Improve Thief level up rewards

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#809]
Thief level up rewards, particularly after the Poison Needle/Crowbar choice are really weak. Does anyone choose the Tazer? How about the Health upgrade? Make these more interesting!

**Comment by DiceWithDeath** [comment]
Don't think I've ever chosen the tazer (can't even remember what it does, heh) but I have considered choosing the health upgrade... so it's close to being worth it! Could make it 7 health to sweeten the deal? Not totally sure if it's necessary though.

**Comment by TerryCavanagh** [comment]
Ok, trying new thief level up rewards for v0.16!
