### ISSUE TITLE
Why does Bully's "Fists" say "Do 3 dmg" instead of "damage"?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#812]
No good reason, that's why! Be more consistent!

**Comment by YinYin-Falcon** [comment]
What?

I thought this is s great contrast to the single use rocks.

They'll need a max 4/5, if they do pip damage - else you might just remove the rocks.

**Comment by TerryCavanagh** [comment]
Oh, no, this is just about the consistency of the term “dmg” versus “damage”!

**Comment by YinYin-Falcon** [comment]
🤦

**Comment by TerryCavanagh** [comment]
Fixed

**Comment by muizzsiddique** [comment]
Same occurs with Hollow Crystal in 0.17.2

![Screenshot (117)](https://user-images.githubusercontent.com/23620568/58720833-27bfed00-83cb-11e9-8bed-4109257bacd2.png)
