### ISSUE TITLE
Graphical appearance of weakened cards implies that they are somehow not usable

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#815]
To one new player, they thought this meant that the cards couldn't be used.

```
hmm... the graphics to me don't imply they are usable. 
(it's the equivalent of greyed out UI buttons)
```

**Comment by onetruepurple** [comment]
This is strange, because the weakened cards still have slots and effect descriptions (even when the effect is no effect).

But maybe it's worth adding a tattered looking card graphic to weakened cards, since upgraded cards already have their own.

**Comment by TerryCavanagh** [comment]
This one's not going to change at this point. Closing.
