### ISSUE TITLE
Add a confirmation on flee attempts

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#818]
This catches a couple of people out, but the worst thing about it is that it *punishes* people for experimenting by clicking on random things, which is really bad. A simple confirmation on this would be a good addition.

**Comment by DiceWithDeath** [comment]
Yes, could there be something to confirm what's going to happen as well (the fact it's only a chance, and that you get attacked)? Something like 'Are you sure you want to try to flee? Your enemy will still have a chance to attack on your way out!'

**Comment by TerryCavanagh** [comment]
Fixed.
