### ISSUE TITLE
Kraken's main attack starts at 0 damage instead of 1

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#826]

**Comment by onetruepurple** [comment]
Can't reproduce in v0.15.1

**Comment by musicalentropy** [comment]
When the issue appeared, I was playing with the Thief and I tried to use the attack as well. That issue appeared first for me and then for the enemy. I think I was doing the quest with the dices being all the same at each turn, and the bug happened with the dices at "one".

**Comment by TerryCavanagh** [comment]
I think this is fixed!
