### ISSUE TITLE
Wizard killed itself with two "one" dices because of the freeze effect

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#827]

**Comment by onetruepurple** [comment]
Intentional

**Comment by cwhjr** [comment]
What if backfire dealt damage to player and wizard? Have it increase in damage to both every time it gets played.

**Comment by Thunder33345** [comment]
if that's done try not to make it wizards suicidal immune to freeze
wizard is immune to freeze because if it received freeze it can easily kill the player and itself

**Comment by ncrecc** [comment]
Enemies no longer kill themselves except due to a bug regarding how they evaluate thorns: #1814
Backfire has not been a regular item for a long time, and Wizard no longer gets it either. This issue can be closed.
