### ISSUE TITLE
Poison dart unbalanced compared to Claw

### ISSUE THREAD

**Issue by DiceWithDeath** [TerryCavanagh/diceydungeons.com#829]
Poison Dart: Requires precisely a 3 and deals 2 poison
Claw: Requires 1, 2 or 3 and deals x damage AND 2 poison

Both take up 1 slot. Poison dart definitely doesn't seem worth it!

Suggestion - either it could be re-usable and require 1 (maybe only does 1 poison; upgraded does 2) so has synergy with Snake Eyes, or keep as-is but do 4 poison, or change to 'requires odd' and does 3 poison (upgraded 'requires anything')?

**Comment by ncrecc** [comment]
Reusable and requiring one or odd would be early Poison Needle all over again (and would be nightmarish with hacksaw).

**Comment by Thunder33345** [comment]
yes unbalanced but i dont mind having a weapon just there for sake of begin a weaker tier of something

**Comment by TerryCavanagh** [comment]
Fixed.
