### ISSUE TITLE
Give Thief some more help early game?

### ISSUE THREAD

**Issue by DiceWithDeath** [TerryCavanagh/diceydungeons.com#832]
It's way too easy to die as Thief before hitting level 3 - the late game shouldn't be easier than the early game!

Especially when playing on hard mode, it's just RNG as to whether you get a decent weapon in your first chest(s), enough apples, etc. - you can play perfectly and still lose before even hitting level 3, about half the time in my experience (often dying at level 1).

I would suggest starting Thief off with a bandage, which would allow them to heal up a bit. Other than that, maybe manipulating the dungeon gen so they always get an apple on the first level (maybe making apples heal for more?), and they always get a 'useful' weapon off the bat - e.g. _not_ something like Pickpocket or any 'support' weapon (doubling poison, reducing countdowns...).

In particular I can't pick Crowbar as my first levelling up reward because I don't know if it'll be useful down the line, and I need a damage-dealer instead. Relates to #809 - maybe the crowbar can come later in the game, e.g. after level 2?

Thief seems strongest mid-game, and a poison build is easiest by far to pull off, which makes it the most obvious choice when levelling - leaving those level 1 rewards until later would give strength in the early game without people having to pick so early on to do a crowbar build or a poison build (and inevitably choosing poison in my experience because I don't always get enough countdown items!)

**Comment by dragonsbutalsorabbits** [comment]
I'm definitely running into this, especially on the fourth episode as the Thief. I had a much easier time as the Robot and the Jester, which are supposedly 3 and 4 star difficulties! I keep dying to Sneezy the Hedgehog rolling 6s that I can't do anything about... or the Wizard, or the Dryad... I even died to the Slime!

**Comment by TerryCavanagh** [comment]
Since launch, I've made numerous little balance changes that I think make this a non-issue now. Closing!
