### ISSUE TITLE
Kraken on hard mode too victim to RNG? (Suggestion)

### ISSUE THREAD

**Issue by DiceWithDeath** [TerryCavanagh/diceydungeons.com#833]
Kraken's 'Overwhelm+' seems a bit too... well, overwhelm-y. It seems far too victim to RNG - I had one game that was particularly bad and very little on my end could've improved it; it was just reliant upon whether Kraken rolled any doubles and therefore wasted 2 incremental 'Overwhelm's.

On hard mode, unless you either are lucky enough to shock or weaken that specific item (or lock dice), or unless he rolls doubles, he'll do guaranteed: 6 dmg, then 15, then 24. If you're unlucky enough to only go in with 21 health he'll smash you by turn 2! With him having so much health, as a class like Thief it's nearly impossible to get him down that quickly.

Some games end up being perfectly fine or even easy against him, but when it gets hard, it becomes impossible - something more balanced and a guaranteed, but minor, challenge would be much better.

I'd suggest either:
- Make it max 2 uses per turn
- Don't make it carry over its added damage across turns (I say this because, when Thief uses it without owning it, they don't get to keep their added damage - it resets! Which is particularly unfair.) But, this might be inconsistent with other similar items?
- Change Overwhelm's upgrade to something else that ultimately makes the + useless for Kraken, e.g. making it smaller

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/51685785-ff704e00-1fe6-11e9-89dc-51957e95d555.png)

**Comment by TerryCavanagh** [comment]
Nerfed Overwhelm and Overwhelm+ a bit for v0.16. Thanks for this!
