### ISSUE TITLE
Suggestion - indication of menu and options on the home screen

### ISSUE THREAD

**Issue by DiceWithDeath** [TerryCavanagh/diceydungeons.com#837]
Several people have mentioned not being able to find the volume bar.

Lots of games will show this by having, say, a flashing piece of text with a picture of an Esc key and the text 'Menu' or 'Options' or 'Press Esc for options' in the top left on the starting page; there's even a neat space for it ;)
Usually that's enough for people to realise they can press it later on, too.

**Comment by TerryCavanagh** [comment]
Fixed! Thanks!
