### ISSUE TITLE
[Minor visual complaint] Where is Waldo?

### ISSUE THREAD

**Issue by woctezuma** [TerryCavanagh/diceydungeons.com#838]
When a new map appears, I feel like it is a bit difficult to find the main character. Everything is in color and animated, so it is confusing. I believe something could show the position of the character:

- a vertical red arrow which would disappear after a few seconds,
- or a screen transition from a black screen opening as a small disk at the character location and the disk would grow bigger till the whole map is shown,
- or the tile where the character starts could be circled in red,
- etc.

![new map](https://i.imgur.com/Ezr12u4.png)

**Comment by woctezuma** [comment]
I was playing in Fullscreen, so the issue might not be there in Windowed mode.

**Comment by TerryCavanagh** [comment]
Yep, I consider the fade-in circle a fix for this. Closing!
