### ISSUE TITLE
Allowing player input before the turn is fully set up allows for too many weird things

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#840]
Such as:
- using your gadgets before Silence kicks in
- throwing your dice as the Witch before Silence kicks in
- using your limit break before Silence kicks in
- inserting dice into shocked equipment before Shock kicks in
- using weakened equipment before Weaken kicks in

The simplest way to fix all of these by disabling player input until all the cards are in place and all the effects have been applied.

**Comment by onetruepurple** [comment]
This has come under discussion again (in #beta) recently

**Comment by TerryCavanagh** [comment]
We've gone ahead and done this now in recent versions for most of all these cases, though there are still one or two cases that we don't catch (that have other issues open). So, closing this one!
