### ISSUE TITLE
Replace Combat Roll

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#841]
As per:

![image](https://user-images.githubusercontent.com/2095534/51400349-740b3e80-1b48-11e9-995c-8f86971b58d5.png)

Could be obsoleted after PAX though...

**Comment by onetruepurple** [comment]
My own suggestion would be to consider the single gadget that rerolls all dice, since I think it was the most fun from all the options that have replaced it, and the "all or nothing" aspect of it introduced an extra risk to the Warrior.

**Comment by Thunder33345** [comment]
personally i like the combat roll but looking forward if something else could be better
but it think combat roll is good enough

**Comment by TerryCavanagh** [comment]
Actually, after this PAX I think I'm gonna keep it. Trying to reintroduce the reroll gadget is tempting, but I made that change for some good reasons. Also, with new players especially, it's a pretty good gameplay loop.

Not gonna overthink it. Closing!
