### ISSUE TITLE
Champion isn't actually weak to Shock

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#844]
Oops!

**Comment by JuniorUdale** [comment]
She's weak to shock damage, but not the shock effect.

![lightning](https://user-images.githubusercontent.com/32357485/51627526-4eac7500-1f3a-11e9-9059-c6b7c4abbb7f.gif)

Here, I put 5 pips into Lightning Bolt, which dealt 10 damage but only shocked 1 of her equipment. This is consistent with other effects; the damage is doubled but the effect isn't (e.g. Matchstick vs Wicker Man only burns one of his dice, but he takes double damage from using it as it's fire damage)

**Comment by TerryCavanagh** [comment]
This could be due to a piece of equipment that's supposed to do shock damage, but actually does normal damage! Do you remember what you were using, @onetruepurple ?

**Comment by onetruepurple** [comment]
I'm sorry, I forgot Hammer doesn't actually do shock damage. Closing!
