### ISSUE TITLE
If you click the "Enemy Moves" button right after you've placed your die in an attack, but before the attack goes off, the attack doesn't happen that turn

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#846]
```
I hit the button halfway through a Fury attack and the second attack never went off. 
```

(Slightly distinct from another open issue about this)

**Comment by TerryCavanagh** [comment]
This also affects countdowns: if you view enemy moves before countdowns hit 0, they won't go off until the next turn.

**Comment by mrcdk** [comment]
This is fixed, you can't click the preview button while an action is being played.

I'll check about the countdowns issue later.
