### ISSUE TITLE
Use elemental damage types more often

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#850]
Shovel should do Weaken damage, Hammer should do shock damage, Lament should do ice damage. In general, if a piece of equipment has an element attached, it should do damage of that type to make weaknesses and strengths more important.

**Comment by onetruepurple** [comment]
Can something be strong to weaken damage though?

**Comment by TerryCavanagh** [comment]
In theory, yep!

**Comment by TerryCavanagh** [comment]
A quick look through the spreadsheet, and it looks like I made most of these changes eventually (except Lament, which I've just done now). Closing.
