### ISSUE TITLE
What is point of Clear crystal from Crystallize?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#852]
![image](https://user-images.githubusercontent.com/2874150/51643309-ed010080-1f63-11e9-94a8-fec26d8e8424.png)

**Comment by onetruepurple** [comment]
I think it's fun since it adds unpredictability to what is a lineup of enemies with entirely static loadouts, and Crystallina getting very bad luck with clear crystals has gotten me out of the trouble more than once.

**Comment by onetruepurple** [comment]
Clear Crystal was removed in v0.16, effectively resolving this.
