### ISSUE TITLE
Wording inconsistencies

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#858]
Burning Light, Electric Shock, and Ice Shard are identical aside from the dice requirements and the effect inflicted, yet all three cards have different wording:
![](https://media.discordapp.net/attachments/423894814124146689/537046335086395393/unknown.png)
Burning Light says "deal X damage" instead of "do X damage" and is missing a comma to separate the two lines, and Electric Shock says "+1 shock" instead of "shock 1 card".

Lament, Whip, Hammer, and Shovel have something similar going on:
![](https://media.discordapp.net/attachments/423894814124146689/539424699726168065/unknown.png?width=925&height=522)
Lament and Hammer both say "X if you roll 6", but Whip and Shovel just say "X on 6". Lament+ has its second line in sentence case (ala Burning Light and Ice Shard) when none of the other cards do. Lament+ and Whip+ state how many dice they effect whereas Lament and Whip does not.

**Comment by ncrecc** [comment]
Forcefield, Iron Shield, Magic Barrier, Magic Shield, Rosepetal Shield, Small Shield, Tower Shield, Wooden Shield:
"Add x shield"
Buckler, Target Shield:
"Add x to shield"
Deflect:
"Block x damage"

Acid Arrow, Claw, Liquorice, Poison Slingshot, Toxic Ooze:
"Add x poison"
Toxic Potion, Poison Cloud, Poison Needle, Poison Spell, Rat, Rosepetal Staff, Smog Cloud:
"Inflict x poison"

Air Crystal, Club, Electric Shock, Hex, Lightning Bolt:
"+x shock"
Buzzer, Catastrophe, Smog Cloud:
"Inflict x shock"
Hammer, The Storm:
"Shock" in white
Nightstick, Tazer:
"Shock" in yellow with lightning bolt:
Thunder Spell:
"Shock x equipment"

There's probably stuff going on with freeze/weaken/burn as well, and maybe even curse/blind/lock

Also, pickpocket says "steals x gold" instead of "steal x gold"

**Comment by ncrecc** [comment]
This is ultra-pedantic and low-priority, probably best saved for after launch (if done at all)

**Comment by TerryCavanagh** [comment]
I don't disagree that this is wrong and weird, but I'm localised in 20 languages now and I don't think this is worth the trouble of fixing 😅
