### ISSUE TITLE
Low health loop sometimes continues playing on new games

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#860]
I was about to die & low health was playing, exited to title screen but the low health loop kept going throughout the next playthrough

**Comment by ncrecc** [comment]
This is still around

**Comment by TerryCavanagh** [comment]
ahhh this is very messy, but I can fix it after launch :(

**Comment by ncrecc** [comment]
This can be pretty annoying, taunting even, if you leave a run due to the current turn being an obvious  deadlock

**Comment by TerryCavanagh** [comment]
This one's fixed!
