### ISSUE TITLE
Inventor's Meganudge makes ones even

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#864]
When you have a one and use the Meganudge gadget, the one becomes a "zero".
Cards that need ODD dice don't get used. When you remove the nudged dice from the ODD slot, it will still make the "tick" sound when you click on it even though it doesn't have a dice.
Cards that require EVEN dice get used because the dice value is 0.
NORMAL cards (like Hammer) don't deal damage (again, dice value is 0).

**Comment by TerryCavanagh** [comment]
Fixed.
