### ISSUE TITLE
Title Music decreases in volume after each quest

### ISSUE THREAD

**Issue by FriendlyNeighbourhoodQA** [TerryCavanagh/diceydungeons.com#870]
Currently upon completing a quest/dying/quitting from the pause menu the title music will get slightly quieter. Doing any of these actions repeatedly keeps decreasing the music to the point of being practically inaudible.
Quick repro steps: 

1. Play->Warrior->The Warrior's Welcome
2. Pause->Back to title
3. Repeat previous steps multiple times

Observe the music will decrease further in volume after each instance.

**Comment by TerryCavanagh** [comment]
Fixed!
