### ISSUE TITLE
Double Iron Shields for sale

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#886]
This should probably never happen

![unknown](https://user-images.githubusercontent.com/2874150/53565695-09d7b780-3b52-11e9-8517-606485b40f11.png)

**Comment by onetruepurple** [comment]
I don't think I've seen this recently.

**Comment by TerryCavanagh** [comment]
Yeah, I haven't seen this recently either - I think it's fixed. And even if it isn't, it really isn't that serious! Getting two Iron Shields + a Shield Bash is a completely OP build.
