### ISSUE TITLE
Weakening Sneezy causes a crash

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#887]
This one will require a v0.16.1, I think, oh well

![zrzut_ekranu_5](https://user-images.githubusercontent.com/2874150/53566613-94211b00-3b54-11e9-983e-505ff781bdf2.png)

**Comment by capnlee** [comment]
not sure if this is necessary, but adding crash log
[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/2919622/_error.txt)

**Comment by TerryCavanagh** [comment]
Fixed!
