### ISSUE TITLE
Snake Eye Charm stops working EDIT: Player-used countdowns stop working

### ISSUE THREAD

**Issue by icekonline** [TerryCavanagh/diceydungeons.com#89]
I had purchased snake eye charm from a store as thief, bringing me to six equipment slots. But for some reason, snake eye charm would only work on the first turn/the first time i used it. after that, it would not accept dice

**Comment by icekonline** [comment]
UPDATE: It seems countdowns of any kind used by the player (or thief, at least) only work for the first turn or first time they are used in a battle, as evidenced by snake eye charm, grapple hook, and first aid kit suffering from this.

**Comment by jltchiu** [comment]
Assuming this is the thread for countdown weapon bug. I experienced similar thing. I used crossbow to deliver a last hit to a mob, and starting next fight, I can't use countdown weapon anymore. The picture is at

https://media.discordapp.net/attachments/423894814124146689/431995338866425867/unknown.png?width=1076&height=608

And all the other items functions properly.

**Comment by TerryCavanagh** [comment]
Fixed!
