### ISSUE TITLE
Previewing Fire Breath+ in the editor crashes the game

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#893]
And presumably, so does fighting Hard Dragon.

**Comment by TerryCavanagh** [comment]
Ahha! Yep, that'll be this: https://github.com/TerryCavanagh/diceydungeons.com/issues/892

Thanks - should be a very easy fix for v0.16.1 👍

**Comment by TerryCavanagh** [comment]
Fixed!
