### ISSUE TITLE
Cutscene textures wrong on 4K

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#896]
The fact that I've only got one report of this is making me wonder if maybe we should just ditch 4k support for launch, tbh. It's very memory hungry, and causes issues when people enable it on non-4k screens...

![unknown](https://user-images.githubusercontent.com/2874150/53581751-140bad00-3b76-11e9-9dc2-539ca23d6f66.png)

**Comment by musicalentropy** [comment]
I have the same issue with my not 4K screen, when HD is enabled, from the start of the game

**Comment by TerryCavanagh** [comment]
Ok, fixed!
