### ISSUE TITLE
No sound at all on Windows

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#905]
The sound has always worked perfectly on all the previous alpha versions. And it still works right now on v15. But when I start v16, I hear no sound, even with volumes at maximum in the settings. I'm playing with Windows, and I use two sound interfaced if that's something which can help (internal, and another one, a RME Babyface)

**Comment by musicalentropy** [comment]
Just made a little test, I moved the main folder of the game from "c:\Téléchargements\diceydungeons" to "c:\diceydungeons" and it worked. It might be because of the special characters...

**Comment by TerryCavanagh** [comment]
Ohhh! That's fantastic, thank you for figuring this out! Yeah, it looks like a unicode thing with file paths, should be an easy fix for v0.17!

**Comment by larsiusprime** [comment]
This if fixed now in the "larsfixes" branch.
