### ISSUE TITLE
Hard Rat King doesn't behave as expected when rolling a 1

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#910]
The optimal move would be to split the 1 four times, inflicting 4 poison, and then using Breadcrumb+ four times. Instead the AI slots the 1 into Breadcrumb+ immediately.

**Comment by musicalentropy** [comment]
I got issues similar to this with the dire wolf too

**Comment by onetruepurple** [comment]
Irrelevant as of v0.17.
