### ISSUE TITLE
"lvl" text is unreadable on some backgrounds

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#919]
see attached screenshot. I can read "Loud Bird" clearly, but I can hardly see the "(lvl 5)"

**Comment by pace212** [comment]
![screenshot 2019-03-03 09 08 07](https://user-images.githubusercontent.com/38589027/53698626-3713a800-3d94-11e9-8ba6-62dd189225ad.png)

**Comment by lcenine** [comment]
Same issue as  #562

**Comment by TerryCavanagh** [comment]
Fixed.
