### ISSUE TITLE
Spare 3 spawned by the Backup Robot card doesn't always give dice

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#920]
It had to move from the third slot to the first before spawning a dice:

![image](https://user-images.githubusercontent.com/2095534/53699171-c4cbb380-3de5-11e9-9753-b2b746a2eacc.png)

**Comment by onetruepurple** [comment]
Still present in v0.17.1

**Comment by onetruepurple** [comment]
This was still present as of v1.10.

**Comment by TerryCavanagh** [comment]
Fixed in v2.1!
