### ISSUE TITLE
Jester episode 2: When all 4 cards are duplicates, Discard only discards 3

### ISSUE THREAD

**Issue by pacesmith** [TerryCavanagh/diceydungeons.com#921]
I had 4 boops and clicked Discard, and only 3 of them got discarded. They were the last 4 cards in my deck. Ah, it happened again when they were the first 4 cards in my deck, so this is probably easy to reproduce.

Presumably this would also apply to Snap.

**Comment by pace212** [comment]
![4boops](https://user-images.githubusercontent.com/38589027/53702510-9be2f880-3dbc-11e9-9d8f-8f9e213f8210.jpg)

**Comment by TerryCavanagh** [comment]
Duplicate!
