### ISSUE TITLE
When Jester steals Keymaster's Lock card, then unlocks it, it leaves an empty spot in the deck

### ISSUE THREAD

**Issue by pacesmith** [TerryCavanagh/diceydungeons.com#922]
Jester episode 4. Fight Keymaster. I get two keyblades (the ones Keymaster unlocked during the fight) and 4 locks. During the next fight, I unlock Lock 6. Afterward...

![screenshot 2019-03-03 19 06 20](https://user-images.githubusercontent.com/38589027/53708313-bc747800-3de7-11e9-8c27-ff04c2fac954.png)

...there's a hole in my deck where Lock 6 used to be. But I've still only got 2 Keyblades, not 3.

**Comment by pace212** [comment]
What? In the next fight...

![screenshot 2019-03-03 19 13 27](https://user-images.githubusercontent.com/38589027/53708456-766be400-3de8-11e9-9556-2fe783412212.png)

...Lock 6 is back! Perhaps this is just a deck display bug and not a deck contents bug.

**Comment by pace212** [comment]
Yeah, it's just invisible. The next fight, Lock 4 was invisible, and I bought a destroy and destroyed it, and it said "Lock 4 destroyed!"

**Comment by TerryCavanagh** [comment]
Fixed!
