### ISSUE TITLE
In Jester 4 (Losers Weepers), when you preview enemy moves, Delete stays on the screen

### ISSUE THREAD

**Issue by pacesmith** [TerryCavanagh/diceydungeons.com#923]
It's translucent, but it's still there, and it makes it hard to read the rightmost enemy card. Note the rightmost card in this screenshot:

![screenshot 2019-03-03 19 46 12](https://user-images.githubusercontent.com/38589027/53709413-06139180-3ded-11e9-9339-82d5bea2df1d.png)

**Comment by TerryCavanagh** [comment]
Just double checked, and this one is fixed!
