### ISSUE TITLE
Consider the bear as a real class

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#925]
There's still time to maybe develop this idea a little further, or at the very least, improve some of the rougher edges of it.

Definitely at least address the following, though:

 - [ ] The bear doesn't really have any options when it comes to dealing with low rolls, so they're very vulnerable to freeze.
 - [x] It's very important that all weakened bear cards are still effective, because otherwise the bear just can't handle weaken at all.
 - [ ] Bear has no mechanisms for uncertainty other than raw dice rolling, or any way to deal with a bad roll if it happens. Is there potentially an interesting bear skillcard that could address this? (some kind of charge, maybe?)

**Comment by TerryCavanagh** [comment]
Also, Jester bear is an interesting case that I completely forgot about! Right now, it doesn't work at all - it's just finders keepers with bear cards. But it might be kinda funny if we continued the run as a kind of Jester/Bear hybrid!

**Comment by onetruepurple** [comment]
- [ ] Implement a Backup Bear card for the Jester

**Comment by TerryCavanagh** [comment]
It looks like the level up rewards are slightly off for bear runs, too - if you use finders keepers to take the bear potion to level 3, you end up underpowered.

**Comment by hupfen** [comment]
Perhaps low rolls could feed into some status-based equipment? Either via countdown or low max. I'd imagine Lock could be a good one (Bear Trap!); no character really leans into that so far, and it's thematically fitting (hard to attack when a bear's mauled your arm off).

**Comment by Colgateinuntap** [comment]
How about change Hibernate to heal 5 - [], 7 - [] upgraded instead of []? Then freezing would make hibernate stronger and that would make sense.

**Comment by hunky-dory** [comment]
One of my favourite things about the bear is that it smashes up chests and shops because, well, it's a bear rather than some high-falutin' game strategist. I wonder if its ability could be built around a similar contempt for/indifference to the game's systems? Like a claw swipe that sends your hand of dice re-rolling across the board, activating cards with the new values and doing dice-throw damage with the rest.

**Comment by TerryCavanagh** [comment]
Yeah, I think the feel of "it's a bear" is crucial, so I'll be very careful to to add any mechanics here that feel too thinky.

One other aspect I've been wondering about: if Jester Bear is going to distinct, maybe it's also worth making Thief Bear and Inventor Bear distinct, somehow? Perhaps with different skill cards?

**Comment by ncrecc** [comment]
If all three flavors of bear will be distinct, maybe give them distinct graphics as well. For example, inventor bear could have small pupils, and thief bear could be missing an eye (in a non-gory way, of course, or just keep his eyepatch on)

**Comment by TerryCavanagh** [comment]
Note for future Terry: remember to implement Bear Booster packs for Jester

**Comment by TerryCavanagh** [comment]
This issue predates the last minute Bear Changes that I made for launch, which address almost everything here. Closing!

(Bear Booster packs for Jester are still a fun idea, but they're maybe something for a future official mod at this point)
