### ISSUE TITLE
Simplify the starting deck in Losers Weepers

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#929]
The amount of Boops and Bops quickly becomes frustrating when you have many more interesting cards to try and no quick way of discarding the duplicates.

**Comment by TerryCavanagh** [comment]
I've been thinking it might just be more fun to reduce the countdown on Delete, and make that much easier to pull off (6 instead of 12, say). In which case, thinning out your deck might actually be kind of a fun thing...

**Comment by TerryCavanagh** [comment]
Trying out a cheaper Delete in v0.16.2!

**Comment by onetruepurple** [comment]
This works very well now. Closing!
