### ISSUE TITLE
Wicker Man turn 1 and I have 0 dice?

### ISSUE THREAD

**Issue by jltchiu** [TerryCavanagh/diceydungeons.com#93]
Not sure if it's intended or not, but I started Wickerman battle with 0 dice. The picture is at https://media.discordapp.net/attachments/423894814124146689/431984301186220032/unknown.png?width=1084&height=608

Prior to this fight, I was fighting the acolyte that has the ultimate to turn enemy health to one, and I use his ult to make him one and kill with the poison tick, not sure whether this will be useful but just put it as an extra information.

**Comment by TerryCavanagh** [comment]
Fixed!

**Comment by TerryCavanagh** [comment]
Fixed!
