### ISSUE TITLE
Some monster names are aligned to the right of their space instead of left

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#938]
![image](https://user-images.githubusercontent.com/2095534/53814495-02544c00-3f60-11e9-85e3-a8f66013d79e.png)

![image](https://user-images.githubusercontent.com/2095534/53814597-29128280-3f60-11e9-9b0d-199965323392.png)

vs.

![image](https://user-images.githubusercontent.com/2095534/53814612-316abd80-3f60-11e9-952b-da02a7c36adc.png)

![image](https://user-images.githubusercontent.com/2095534/53814626-39c2f880-3f60-11e9-936b-10236ddb807f.png)

**Comment by TerryCavanagh** [comment]
This one is intended - though it does remind me that I need to fix this: https://github.com/TerryCavanagh/diceydungeons.com/issues/1978
