### ISSUE TITLE
When Backup Robot summons another Backup Robot card, that card then does nothing

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#939]
![image](https://user-images.githubusercontent.com/2095534/53814671-53fcd680-3f60-11e9-99fd-84954ad92435.png)

**Comment by TerryCavanagh** [comment]
Whoa! Ok, great, very good catch!

**Comment by hunky-dory** [comment]
This is in fact true for all back up cards summoned through backup robot

**Comment by onetruepurple** [comment]
I'm 99% positive this got fixed somewhere down the line.

**Comment by TerryCavanagh** [comment]
Me too, but I'll check before I close it!
