### ISSUE TITLE
Two weapon missing when I equip 4 weapons during a battle

### ISSUE THREAD

**Issue by jltchiu** [TerryCavanagh/diceydungeons.com#94]
My character has 4 weapon equipped. When I entered battle I only see two. The picture is at https://media.discordapp.net/attachments/423894814124146689/431992378187055104/unknown.png?width=1077&height=608

In addition to these two weapon, I also have a crystal sword and throwing axe equipped. But not showing up at all (I didn't use this is the prior turn, it's just disappeared.)

**Comment by jltchiu** [comment]
Update: The weapon do show up in the later battle (But not the immediate next one, the immediate next one I still only have 2 weapon), in about 2 battles after the 4 weapon shows up again. But I died eventually
shield is really strong, I am trying to do a no shield run and has been struggling about it.

**Comment by jltchiu** [comment]
Update: According to SomeguyXG3 in discord, seems this to be known issue for single use weapon. So if that's been tracked then this issue can be closed.

**Comment by TerryCavanagh** [comment]
I *think* this is fixed. Let me know if I'm wrong once I've uploaded the new version! Thanks!
