### ISSUE TITLE
Burning 2s and 3s hard to distinguish.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#941]
Sometimes I confuse 2s and 3s when they are burning. Mainly mistaking a 2 for a 3.  Might just be me. Any way to perhaps change the transparency? 

![burn](https://user-images.githubusercontent.com/40739964/53820316-8810d100-3f39-11e9-84fc-751d9885c708.png)

**Comment by TerryCavanagh** [comment]
Hmm, I see the issue, but unlikely to make any art changes at this point I think. Not planning to fix, sorry.
