### ISSUE TITLE
Can't play Uptick - just get a black screen

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#943]
https://drive.google.com/open?id=1lUZ5w8id0zYaGyhBd4p1wpgwM1ytdHYd

You can hear the dialogue sound, and you can advance it, but then it's just a black screen. You can bring up the options menu, but the option buttons don't do anything. (I forgot to try the sliders) It happens in both fullscreen and windowed.

**Comment by TerryCavanagh** [comment]
I think this is fixed in v0.16.3 - please let me know if that's not the case for you!

**Comment by pace212** [comment]
Confirmed fixed in v0.16.3! Thanks for the quick fix!
