### ISSUE TITLE
Tazer has a sword icon on it, but causes extra damage to Stereohead

### ISSUE THREAD

**Issue by pace212** [TerryCavanagh/diceydungeons.com#944]
Tazer has the sword icon on it, but Stereohead takes extra damage from it. It should be a different icon, right?

Also, ought Lightning Rod deal electric damage?

**Comment by onetruepurple** [comment]
+1 to Lighting Rod doing electric damage, maybe that can be a part of the upgraded version (otherwise it becomes an absolute Aoife buster).

**Comment by onetruepurple** [comment]
Resolved for Tazer and Tazer-, but not for Tazer+

**Comment by onetruepurple** [comment]
Resolved in RC
