### ISSUE TITLE
Add skip cutscene button

### ISSUE THREAD

**Issue by Manuel-K** [TerryCavanagh/diceydungeons.com#947]
And maybe an option to automatically skip cutscenes that you've seen before.

**Comment by TerryCavanagh** [comment]
Hey!

This is planned, but "cutscenes that you've seen before" worries me - is the game not saving your progress?

**Comment by Manuel-K** [comment]
I'm not sure – I've finished one game on the newest version and then I accidentally erased my progress because I thought that was the back button.

**Comment by TerryCavanagh** [comment]
Oh, I see. Ok!

**Comment by Manuel-K** [comment]
Progress saving works.

**Comment by TerryCavanagh** [comment]
Not planning to do this one anymore - it only takes a few seconds to speed click through cutscenes, and they're rare anyway.
