### ISSUE TITLE
Saved progress gets erased if you switch languages

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#948]
```
I think my progress trouble might be related to language settings
right now, if I start in english, warrior episode one is done
but if I start german, it is not
```

It seems switching languages erases progress, somehow!

**Comment by larsiusprime** [comment]
I've ruled out the possibility that this has to do with save location paths / unicode. I'm going to try to reproduce based on language switching now.

**Comment by larsiusprime** [comment]
Reproduction steps:

1) Start the game, in English
2) Select the warrior, select quest 2
3) Beat the quest (I used the teleportation cheat setting)
4) Go to the warrior screen and verify that episode 2 is marked as beaten
5) Close the game and restart
6) Select english, go to the warrior screen and verify that episode 2 is still marked as beaten (file is reading save correctly)
7) Close the game and restart
8) Choose spanish, go to the warrior screen and notice that episode 2 is marked as unbeaten
9) Close the game and restart
10) Choose english, go to the warrior screen and notice that episode 2 is marked as beaten

**Comment by larsiusprime** [comment]
I've confirmed the data is being properly loaded regardless of language. My hypothesis is that the lookup key for the data is being translated by accident, resulting in a null fetch.

**Comment by TerryCavanagh** [comment]
Seemed to be fixed in the latest versions!
