### ISSUE TITLE
Minor graphics corruption

### ISSUE THREAD

**Issue by Manuel-K** [TerryCavanagh/diceydungeons.com#949]
I'm getting some minor graphics corruption that gets worse when the game runs longer. This might cause some memory leak as well as the game seems to get sluggish if I play several runs back to back. This is on Arch Linux with Intel HD Graphics 4600, so it might be the graphics driver's fault. 

Problem occurs on 0.15.0, 0.15.1 and 0.16.2.

![dicey_20190306_164917](https://user-images.githubusercontent.com/775439/53894434-634b5500-4030-11e9-8371-94c2f84b181a.jpg)

**Comment by TerryCavanagh** [comment]
Oh, it's very interesting that this happens *when the game runs longer*. It looks like it might be the same thing as this known issue https://github.com/TerryCavanagh/diceydungeons.com/issues/771.

(appreciating the bug reports written up on github, by the way - that's very helpful!)

**Comment by Manuel-K** [comment]
Yes, that looks similar. But it isn't restricted to text on my end.

I wonder why I haven't found the other issue… something must be wrong with github's search. I've rechecked and I cannot find that issue if I search for “is:issue is:open glitch”, but it works if I search for “is:issue is:open glitches”, so that might be a deliberate change.

**Comment by Manuel-K** [comment]
Above the stars (this disappears by alt-tabbing out out and in of the game):
![dicey_20190306_173633](https://user-images.githubusercontent.com/775439/53898471-68ac9d80-4038-11e9-83c8-656801e0d5b2.jpg)

Text corruption:
![dicey_20190306_173731](https://user-images.githubusercontent.com/775439/53898473-69453400-4038-11e9-80af-65203c667e20.jpg)

Corruption under the bar:
![dicey_20190306_174237](https://user-images.githubusercontent.com/775439/53898474-69453400-4038-11e9-89a5-e55e171c2e53.jpg)

**Comment by TerryCavanagh** [comment]
This one is a rendertexture bug, which we fixed in v1.2 or thereabouts! Closing!
