### ISSUE TITLE
Selecting "Back to Title" from Intro Cutscene does weird things.

### ISSUE THREAD

**Issue by lcenine** [TerryCavanagh/diceydungeons.com#961]
During the introduction cutscene, pressing escape and selecting "Back to Title" takes you back to the title but Lady Luck's dialog continues to overlay and populate on mouse click.

![intro1](https://user-images.githubusercontent.com/40739964/54089028-bf68ee80-433a-11e9-9247-7eaf3a5cc0e0.jpg)

![intro2](https://user-images.githubusercontent.com/40739964/54089032-c68ffc80-433a-11e9-8681-6d52c17d118a.jpg)

And if you keep clicking the the game starts with strange artifacts on the dungeon map:
![artifacts](https://user-images.githubusercontent.com/40739964/54089039-e3c4cb00-433a-11e9-8620-7597caa84ab7.jpg)

**Comment by TerryCavanagh** [comment]
Fixed, the game doesn't let you quit to title during cutscenes anymore.
