### ISSUE TITLE
Consider making Dice Cannon a button like Witch's Throw Dice

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#969]
To avoid multiple dice insertion.

**Comment by onetruepurple** [comment]
Is Dice Cannon still in the game?

**Comment by TerryCavanagh** [comment]
Yep, it's one of Jester's finale card pick possibilities:

![image](https://user-images.githubusercontent.com/2874150/62840144-a8358080-bc8d-11e9-8e25-3799a5b813dc.png)

**Comment by onetruepurple** [comment]
This wouldn't work too well with the "copy and snap infinitely" tactic.
