### ISSUE TITLE
First Aid Kit won't let me drop dice on it after first use

### ISSUE THREAD

**Issue by jmickle66666666** [TerryCavanagh/diceydungeons.com#97]
I used the first aid kit in a battle (while also having stolen the fire staff that works similarly?), and now I cannot drop dice on it any more, even in subsequent battles.

**Comment by jmickle66666666** [comment]
Update: this recovered after a battle or two, but happened again, in another battle stealing a fire staff.

**Comment by TerryCavanagh** [comment]
Fixed!
