### ISSUE TITLE
Tutorial won't repeat if you die in it

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#971]
Methinks failing the tutorial should let you play it again, perhaps skipping the initial "I want to win a jetski" cutscene and any dialogue boxes the player has already seen. Maybe explicitly state "since you lost the introduction levels, we're letting you play them again!"

**Comment by onetruepurple** [comment]
Counterpoint: the tutorial should probably patch out all instances where the player can die.

**Comment by TerryCavanagh** [comment]
My feeling is that you have to try quite hard to die in the tutorial - maybe even do it deliberately. In which case, maybe it's ok that the tutorial doesn't repeat? I'm not sure, but I'll do some testing of this at PAX East and figure it out.

**Comment by Sandvich** [comment]
I crashed during the tutorial on my first play. But considering that the reset progress button is easy to find, I don't think this is an issue, personally.

**Comment by TerryCavanagh** [comment]
Fixed! Tutorial completion is now marked with a flag, and in fact I now have the opposite problem where you're forced to replay it even if you get 99% of the way through and die at the end. Hmm. I'll make a new issue.

**Comment by Sandvich** [comment]
Maybe it shouldn't be at completion, but rather at the point where the game stops teaching you new stuff?
