### ISSUE TITLE
Editor, Witch, Sonic Wave, Back to Title -> Crash

### ISSUE THREAD

**Issue by pacesmith** [TerryCavanagh/diceydungeons.com#975]
Editor, Witch, Sonic Wave, Back to Title

[_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/2974436/_error.txt)

This looks similar to #556

**Comment by TerryCavanagh** [comment]
Ok, fifth time's a charm! (This is the 5th random bug I've selected today, but the first one that's actually a bug I can fix)

**Comment by TerryCavanagh** [comment]
... except, nope, looks like this one doesn't happen anymore either 😅 Fixed! Next bug!
