### ISSUE TITLE
Think about ways to make trader choices more consistently interesting

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#976]
![image](https://user-images.githubusercontent.com/2874150/54481338-59dd9c00-482b-11e9-80ca-d61f6db12139.png)

![image](https://user-images.githubusercontent.com/2874150/54481342-5ea25000-482b-11e9-8efe-cd0e2998722a.png)

![image](https://user-images.githubusercontent.com/2874150/54481348-6530c780-482b-11e9-8128-8a9d9ef3e981.png)

![image](https://user-images.githubusercontent.com/2874150/54481350-695ce500-482b-11e9-8d82-5def0185a78d.png)

**Comment by onetruepurple** [comment]
Try to somehow apply the Jester booster pack logic here?

**Comment by TerryCavanagh** [comment]
Probably not going to do any more work on this - in v1.9 I just changed it so that Val is more likely to just trade for a completely random item, which generally offers more interesting options that the deliberate system I tried initially. Am pretty happy with where it is now.
