### ISSUE TITLE
"Flee" hitbox overrides dice hitbox

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#979]
So if you drag a dice on the flee button and let go, you can't touch it without fleeing the battle. I learned this the hard way after swinging the cursor around a bit too freely.

**Comment by lcenine** [comment]
I have done exact same thing, usually with the thief dragging multiple 1's to the reusable dagger.  Adding a confirmation to actually flee would solve it.

**Comment by ncrecc** [comment]
No longer the case.
