### ISSUE TITLE
Bump+ can be used infinitely

### ISSUE THREAD

**Issue by Nattytom501** [TerryCavanagh/diceydungeons.com#983]
If the warrior uses fury and goes past zero on bump+ with the double action, bump+ will go into a negative amount of uses and can be used infinitely. This was in the Vampiric Tendencies episode. See screenshot.
![BumpBug](https://user-images.githubusercontent.com/49027131/55154673-4f85a100-514d-11e9-8aed-0c1077689ea3.png)

**Comment by TerryCavanagh** [comment]
Fixed!
