### ISSUE TITLE
Last versions are slow on Windows

### ISSUE THREAD

**Issue by musicalentropy** [TerryCavanagh/diceydungeons.com#985]
I noticed that a few things became quite slow on my Windows 8.1 64 bits computer after the version 0.16, even in full screen, and it depends on the number of things displayed at the same time on the current screen. Some animations are lagging, sometimes it's slow to get to next attacks etc. My main computer isn't that bad (i5 4590 with 12 Gb of RAM), but I have a low cost graphics card there (Intel HD Graphics 4600)

**Comment by TerryCavanagh** [comment]
Hey! Is this one still an issue in beta? We've done some optimization since this and fixed some memory leaks, and switched to ATF textures, so I'm hoping things have improved a bit!

**Comment by musicalentropy** [comment]
I think it's still slower than before 0.16, not as much as in March, but still noticeable. For example, the whole game seems to be freezed for 2-3 seconds before any video, and occasionally a few animations are still slow or lagging on my computer unfortunately :( Are you working mainly on Windows or on mac OS ?

**Comment by TerryCavanagh** [comment]
We've done some serious optimisations in recent versions, and I believe this should no longer be a major problem. Closing!
