### ISSUE TITLE
Upgraded spell disabled by curse becomes invisible

### ISSUE THREAD

**Issue by Manuel-K** [TerryCavanagh/diceydungeons.com#989]
Observed in version 0.16.2 while playing the witch.

A spell on the upgraded lower right field disappears completely (only the empty field with borders remains) when disabled by curse for the remainder of the turn.

**Comment by TerryCavanagh** [comment]
Ah, yep, still need to fix this! This is a duplicate of a newer issue, though, so closing (https://github.com/TerryCavanagh/diceydungeons.com/issues/1973)
