### ISSUE TITLE
Should attacks that return dice be completely nullified by Dodge?

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#999]
Part of splitting #489 into two separate problems.

This currently affects:
- Cauldron
- Gold Cauldron
- Silver Cauldron
- Glass Cauldron
- Bumpblade
- Nudgeblade
- Keyblade
- Juggling Ball

**Comment by TerryCavanagh** [comment]
Fixed in v1.9!
